### PR TITLE
Migraphx improvements

### PR DESCRIPTION
**Pull request by scxiao**
**Description**: Describe your changes.
1. Add support of a few operators (Neg, GatherElements, Asymmetric Padding in AveragePool)
2. Add the checking of more scenarios where constant folding is available
3. Specify the ROCM3.3 used in the dockerfile

**Motivation and Context**
- Why is this change required? What problem does it solve?
Make MIGRAPHX EP have better support of onnx models

- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by scxiao** [comment]
> /azp run Linux CPU CI Pipeline, Linux CPU x64 NoContribops CI Pipeline, Linux GPU CI Pipeline, Linux GPU TensorRT CI Pipeline, MacOS CI Pipeline, MacOS NoContribops CI Pipeline, Windows CPU CI Pipeline, Windows GPU CI Pipeline, Windows GPU TensorRT CI Pipeline

This PR contains all the change in my previous PR #4240. It is up to you to merge that one first, then merge this one, or you can just merge this one that contains all the changes I made. Thanks

**Comment by jywu-msft** [comment]
> > /azp run Linux CPU CI Pipeline, Linux CPU x64 NoContribops CI Pipeline, Linux GPU CI Pipeline, Linux GPU TensorRT CI Pipeline, MacOS CI Pipeline, MacOS NoContribops CI Pipeline, Windows CPU CI Pipeline, Windows GPU CI Pipeline, Windows GPU TensorRT CI Pipeline
> 
> This PR contains all the change in my previous PR #4240. It is up to you to merge that one first, then merge this one, or you can just merge this one that contains all the changes I made. Thanks

aiming to merge this combined PR instead of PR #4240

**Pull request merged**
