### PR TITLE
fix handling of multiple QuantizeLinear nodes

### PR DESCRIPTION
**Pull request by saurabhkale17**
### Description
This fix addresses the issue of handling multiple QLinear nodes as outputs from the target node in OVEP. Previously, the stripping logic only supported a single Q node, leading to incorrect stripping of additional Q nodes.

### Motivation and Context
The OVEP stripping logic was limited to handling a single Q node as an output from the target node. As a result, additional Q nodes were being stripped, despite the stripping rules indicating they should be retained.

With this fix, OVEP can now properly handle multiple Q nodes according to the specified stripping rules, ensuring that the fate of each Q node is correctly determined.

### CODE REVIEW

**Comment by saurabhkale17** [comment]
@jywu-msft can you please trigger pipelines.

**Review by adrianlizarraga — APPROVED** [review]

**Comment by adrianlizarraga** [comment]
@saurabhkale17 We're trying to fix unrelated CI issues. Once those are fixed, we'll ask you to sync with the main branch before we're able to merge this PR.

**Comment by adrianlizarraga** [comment]
@saurabhkale17 Can you please sync with latest main so that the CI checks pass?

**Pull request merged**
