### PR TITLE
Add support for softmaxcrossentropy loss to MIGraphX EP (#64)

### PR DESCRIPTION
**Pull request by TedThemistokleous**
### Description

Add support for softmaxcrossentropy loss. This is already enabled on our ROCm Fork of the MIGraphX EP

### Motivation and Context

Adds support for the SoftmaxCrossEntropyLoss operator and removes the filtering of inputs here.

### CODE REVIEW

**Comment by TedThemistokleous** [comment]
@tianleiwu  Need to get this in sooner than later.

**Review by tianleiwu — APPROVED** [review]

**Pull request merged**
