### PR TITLE
fix memory profile build

### PR DESCRIPTION
**Pull request by jslhcl**
### Description

This PR is to fix the build break when onnxruntime_ENABLE_MEMORY_PROFILE is on

### Motivation and Context

This PR is to fix the build break when onnxruntime_ENABLE_MEMORY_PROFILE is on.
It fixes this issue https://github.com/microsoft/onnxruntime/issues/16124

### CODE REVIEW

**Review by snnn — APPROVED** [review]

**Comment by snnn** [comment]
You can merge it now. The DNNL pipeline failure is not related to your change.

**Comment by ivberg** [comment]
Working with @jslhcl to make sure this not only fixes the build but also provides working functionality of memory profiling. This was refactored so important to test. Original version only worked by default on GPU but had internal CPU support.

**Comment by snnn** [comment]
@jslhcl , does the problem exist in ORT 1.15.0 release?

**Pull request merged**
