### PR TITLE
Resync protobuf def

### PR DESCRIPTION
**Pull request by snnn**
Resync our private protobuf def with the upstream one.

In the next time, please do not modify these proto files directly. Please update 'onnxruntime/core/protobuf/onnx.in.proto' instead.

And, if it's possible, please do not re-format  'onnxruntime/core/protobuf/onnx.in.proto'.  Please make your change as small as possible.

### CODE REVIEW

**Comment by snnn** [comment]
```diff
--- ../../../cmake/external/onnx/onnx/onnx.in.proto	2019-01-23 14:42:23.712936922 -0800
+++ onnx.in.proto	2019-02-01 13:50:19.950650414 -0800
@@ -227,6 +227,8 @@
 
   // The parameterized graph that is evaluated to execute the model.
   optional GraphProto graph = 7;
+  // kezhan: This field is not in ONNX, and will be pushed into ONNX with good use cases in microsoft.
+  repeated FunctionProto functions = 100;
 
   // Named metadata values; keys should be distinct.
   repeated StringStringEntryProto metadata_props = 14;
@@ -239,6 +241,14 @@
   optional string value= 2;
 };
 
+message QuantInfo {
+  optional string tensor_name = 1;
+  // The keys used in the mapping below will be pre-defined in ONNX spec.
+  // For example, for linear case, “SCALE”, “ZERO_POINT” will be pre-defined as
+  // quantization parameter keys.
+  repeated StringStringEntryProto quant_parameter_tensor_names = 2;
+};
+
 // Graphs
 //
 // A graph defines the computational logic of a model and is comprised of a parameterized 
@@ -268,6 +278,12 @@
   // must be distinct. It is optional for a value to appear in value_info list.
   repeated ValueInfoProto value_info = 13;
 
+  // This field carries information to indicate the mapping among a tensor and its
+  // quantization parameter tensors. For example:
+  // A tensor “a” and its quantization parameter tensor are “scale_a” and
+  // “zero_point_a” (in linear case).
+  repeated QuantInfo quantization_annotation = 100;
+
   // DO NOT USE the following fields, they were deprecated from earlier versions.
   // repeated string input = 3;
   // repeated string output = 4;
@@ -536,3 +552,42 @@
   // This field MUST be present in this version of the IR.
   optional int64 version = 2;
 }
+
+// Operator/function status.
+enum OperatorStatus {
+    EXPERIMENTAL = 0;
+    STABLE = 1;
+}
+
+message FunctionProto {
+  // The name of the function, similar usage of op_type in OperatorProto.
+  optional string name = 1;
+  
+  // The first version of a function set which contains this function.
+  // When there's any breaking change for this function, the function set
+  // contains the function needs to bump its version, and since_version of
+  // the updated function will be changed to the updated function set version.  
+  optional int64 since_version = 2;
+
+  // This field indicates whether the syntax, semantics, or presence
+  // of this function is in an experimental or stable stage. Once an
+  // function is published as STABLE, its syntax and semantics MUST NOT
+  // change in subsequent versions of the operator set.
+  // When a function is published as EXPERIMENTAL, the syntax and semantics
+  // of the function MAY change across operator set versions.
+  // Functions "become" stable by deprecating the experimental version and
+  // introducing a new stable function with the same name.
+  optional OperatorStatus status = 3;
+
+  // The inputs and outputs of the function.
+  repeated string input = 4;
+  repeated string output = 5;
+
+  // The attributes of the function.
+  repeated string attribute= 6;
+  
+  // The nodes in the function.
+  repeated NodeProto node = 7;
+  // A human-readable documentation for this function. Markdown is allowed.
+  optional string doc_string = 8;
+}
```

**Comment by yuslepukhin** [comment]
@snnn So you decided to bring in in.proto files as well. The reason we have our own protobuf definitions is bc we have some customization. Are those customizations reflected now in in.proto files? Presumably they are now going to be used to generate the actual customized proto files.

**Comment by snnn** [comment]
> @snnn So you decided to bring in in.proto files as well. The reason we have our own protobuf definitions is bc we have some customization. Are those customizations reflected now in in.proto files? Presumably they are now going to be used to generate the actual customized proto files.

Yes. They are. I put the changes in this PR's comments.

**Comment by jignparm** [comment]
Does this file also need to be updated as well?

https://github.com/Microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.Tests/OnnxMl.cs

**Pull request merged**
