### PR TITLE
Add file mapping for windows platform.

### PR DESCRIPTION
**Pull request by caoting-dotcom**
**Description**: Add the MapFileIntoMemor function into windows/env.cc

**Motivation and Context**
MapFileIntoMemor is to map the file into memory rather than loading it. The file will only be loaded when it is actually used.
This can help reduce the memory cost. We have tested it for Fluency model inference on Win32, and see the memory cost reduction.

MapFileIntoMemor is already supported in posix/env.cc, rather than windows. Our current PR implementation is basically the same as in posix/env.cc.

### CODE REVIEW

**Comment by pranavsharma** [comment]
Do you've a test case?

**Comment by caoting-dotcom** [comment]
> Do you've a test case?

Hi Pranav, I have added the unit test. Please check.

**Review by pranavsharma — APPROVED** [review]

**Review by RandySheriffH — COMMENTED** [review]
@caoting-dotcom:
Pls fix errors/warnings reported by pipeline asap, we are working on the final round of cherry pick for release.

**Review by RandySheriffH — APPROVED** [review]

**Comment by chausner** [comment]
Interesting, but I couldn't find any documentation on `MapFileIntoMemory`. Could you explain how one one would leverage this function in practice? I didn't find any code in onnxruntime calling this function so I assume users are supposed to call it.

Can it be used to reduce the memory usage during loading of ONNX models?

**Comment by snnn** [comment]
> Interesting, but I couldn't find any documentation on `MapFileIntoMemory`. Could you explain how one one would leverage this function in practice? I didn't find any code in onnxruntime calling this function so I assume users are supposed to call it.
> 
> Can it be used to reduce the memory usage during loading of ONNX models?

See: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/framework/tensorprotoutils.cc#L567

It might need more work.  The original design was: if you had a large model, you could split the weights to an external file then use GetFileContent function to load the weights, and leverage memory mapping when possible. For example, if you have multiple processes running on the same machine with the same ML model. Then you may be able to reduce memory usage by only having one copy of the model in memory.

**Comment by caoting-dotcom** [comment]
> > Interesting, but I couldn't find any documentation on `MapFileIntoMemory`. Could you explain how one one would leverage this function in practice? I didn't find any code in onnxruntime calling this function so I assume users are supposed to call it.
> > Can it be used to reduce the memory usage during loading of ONNX models?
> 
> See: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/framework/tensorprotoutils.cc#L567
> 
> It might need more work. The original design was: if you had a large model, you could split the weights to an external file then use GetFileContent function to load the weights, and leverage memory mapping when possible. For example, if you have multiple processes running on the same machine with the same ML model. Then you may be able to reduce memory usage by only having one copy of the model in memory.

Right, this is where the function got called and the purpose is to reduce memory cost. It was only for POSIX only before. Now it is implemented for Win32.

**Pull request merged**
