### PR TITLE
add ThreadingOptions, wraps OrtThreadingOptions

### LINKED ISSUE #13710: [Feature Request] C++ api for OrtThreadingOptions
### Describe the feature request

add a c++ class ThreadingOptions, wraps OrtThreadingOptions

### Describe scenario use case

I need to use some model(Session in c++ api) using the global thread pool.
Then I need to create The Env with global thread pool.
https://github.com/microsoft/onnxruntime/blob/2d732e97292e58821afef6792d457b63fd864771/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L358-L362
But it needs the OrtThreadingOptions* as one of the paramater, which can be only created by the c api.
I'd like create a c++ class ThreadingOptions, which wraps OrtThreadingOptions.

### PR DESCRIPTION
**Pull request by we1559**
…threadpools' options of The Env.

### Description

add a c++ class ThreadingOptions, wraps OrtThreadingOptions
as I described in issue #13710 

### Motivation and Context

close #13710

### CODE REVIEW

**Comment by we1559** [comment]
@microsoft-github-policy-service agree [company=personal]

**Comment by we1559** [comment]
@microsoft-github-policy-service agree

**Review by RyanUnderhill — APPROVED** [review]
The new C++ API is going to be "experimental" for the next release so that we don't break anyone unexpectedly in the next release.

So your changes should go in.

**Comment by we1559** [comment]
@RyanUnderhill the python format test case seems not right

**Comment by RyanUnderhill** [comment]
> @RyanUnderhill the python format test case seems not right

Yeah, that should run automatically. Maybe the pr is stale, can you merge with main and push again?

**Comment by we1559** [comment]
> > @RyanUnderhill the python format test case seems not right
> 
> Yeah, that should run automatically. Maybe the pr is stale, can you merge with main and push again?

done. 
And it seems that you need to approve the test  case running.

**Comment by nmfisher** [comment]
@RyanUnderhill is this the intended usage?

```
Ort::ThreadingOptions tp_options;
_env = new Ort::Env(tp_options.release(), ORT_LOGGING_LEVEL_ERROR, "MyEnv");
```

This wasn't immediately clear from the documents (and I couldn't see any tests).

**Comment by RyanUnderhill** [comment]
@nmfisher No, you should never call .release() when passing to the APIs, this will just leak the object. Anything taking ownership will take it by rvalue reference (&&).

Also, you shouldn't use 'new Ort::Env' as this is now a pointer to a pointer. The C++ wrapped types are already 'smart pointers' though this isn't very obvious. You can do this:
```
Ort::Env _env{nullptr_t}; // Create empty pointer
_env = Ort::Env(...);

```

**Comment by nmfisher** [comment]
Great, thanks.

**Pull request merged**
