### PR TITLE
ORT 1.19.0 Release: Cherry-Pick Round 1

### PR DESCRIPTION
**Pull request by prathikr**
### Description

PRs marked for cherry-pick.

### Motivation and Context

ORT 1.19.0 Release Preparation

### CODE REVIEW

**Comment by snnn** [comment]
@yufenglee, the NeuralSpeed  job failed.

**Comment by snnn** [comment]
@prathikr , could you please also add #21551?

**Comment by liqunfu** [comment]
> @yufenglee, the NeuralSpeed job failed.

Which CI is failing with NeuralSpeed? NeuralSpeed has be disabled since 1.18.

**Comment by edgchen1** [comment]
> > @yufenglee, the NeuralSpeed job failed.
> 
> @snnn, which CI is failing with NeuralSpeed? NeuralSpeed has be disabled since 1.18.

https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1461029&view=results

**Comment by adrianlizarraga** [comment]
@prathikr Can you please also add this Intel OpenVino PR? Thanks. https://github.com/microsoft/onnxruntime/pull/21675

**Comment by chilo-ms** [comment]
@prathikr please also help cherry pick this TRT EP PR, https://github.com/microsoft/onnxruntime/pull/21643. Thanks

**Review by adrianlizarraga — APPROVED** [review]
QNN and OpenVino EP lgtm

**Review by edgchen1 — APPROVED** [review]
signing off on inclusion of #21626

**Review by fajin-corp — APPROVED** [review]

**Review by skottmckay — APPROVED** [review]

**Review by mszhanyi — APPROVED** [review]

**Pull request merged**
