### PR TITLE
Cherry-pick azure ep for nuget

### PR DESCRIPTION
**Pull request by RandySheriffH**
Cherry pick a commit that can:

1. support for openAi audio endpoints;
2. package as nuget

This is for 1.15 AzureEP RC release.

### CODE REVIEW

**Review by pranavsharma — DISMISSED** [review]

**Review by snnn — APPROVED** [review]

**Comment by snnn** [comment]
Please check why the "Zip-Nuget-Java-Nodejs Packaging Pipeline" is failing before merging. You may merge this PR if the failure was not related to your change.

**Review by snnn — CHANGES_REQUESTED** [review]
I'm not able to run the pipeline, even in the main branch with default settings. 

The "run" button is greyed out.

**Comment by RandySheriffH** [comment]
> Please check why the "Zip-Nuget-Java-Nodejs Packaging Pipeline" is failing before merging. You may merge this PR if the failure was not related to your change.


> Please check why the "Zip-Nuget-Java-Nodejs Packaging Pipeline" is failing before merging. You may merge this PR if the failure was not related to your change.

They are java stages that ought to be deselected from the build.

**Comment by RandySheriffH** [comment]
> I'm not able to run the pipeline, even in the main branch with default settings.
> 
> The "run" button is greyed out.

Here is main branch building:
https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=309488&view=results

**Comment by snnn** [comment]
Please also add the changes of PR #15958  to this PR. And run the Nuget pipeline twice: one with the default configs, another run with your Azure EP settings. Both of them should pass.

**Comment by RandySheriffH** [comment]
> Please also add the changes of PR #15958 to this PR. And run the Nuget pipeline twice: one with the default configs, another run with your Azure EP settings. Both of them should pass.

Done.

**Review by snnn — APPROVED** [review]

**Review by pranavsharma — APPROVED** [review]

**Pull request merged**
