### PR TITLE
enable build flag '--use_openmp' on MacOS

### PR DESCRIPTION
**Pull request by fs-eire**
**Description**: enable build flag '--use_openmp' on MacOS.

OpenMP never work because on MacOS it's always turned off automatically in cmake, although we use '--use_openmp' in mac CI.

https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L173-L189

For 'AppleClang' some variables (`OpenMP_*`) have to be set before calling `find_package(OpenMP)`.

A potential problem is, this fix may fail some mac users who didn't install openmp via `brew install libomp`.

### CODE REVIEW

**Comment by snnn** [comment]
Shall we do it without openmp if it is not common available? libomp is part of LLVM, it should be installed together with the compiler toolset. If you get it from brew, I worry it may have version compatibility issues.

**Comment by snnn** [comment]
What's your cmake version? The latest one should be fine.
See:
https://gitlab.kitware.com/cmake/cmake/-/issues/18520
https://gitlab.kitware.com/cmake/cmake/commit/e3cd7c1e014aa48b72d414104b9c1bd6bc03fd64

**Comment by fs-eire** [comment]
> Shall we do it without openmp if it is not common available? libomp is part of LLVM, it should be installed together with the compiler toolset. If you get it from brew, I worry it may have version compatibility issues.

In generally I agree with you. Maybe it's a good idea to remove '--use_openmp' flag in macOS packaging CI for consistency.
The problem is, it looks like the same question can be asked to Linux: it requires a `apt-get install libgomp1` on runtime and seems to have the same versioning problem as well; but on Linux openmp is ON by default.




> What's your cmake version? The latest one should be fine.
> See:
> https://gitlab.kitware.com/cmake/cmake/-/issues/18520
> https://gitlab.kitware.com/cmake/cmake/commit/e3cd7c1e014aa48b72d414104b9c1bd6bc03fd64

The latest CMake version allows `find_package(OpenMP)` to work, but it will fail later because of unable to locate 'omp.h'. [This document](https://iscinumpy.gitlab.io/post/omp-on-high-sierra/) suggest to call `target_link_libraries(sample PRIVATE OpenMP::OpenMP_CXX)` on each target; but we have a lot of targets in cmake. If we want to use global cmake flags, we still need to set them manually.

**Comment by snnn** [comment]
> In generally I agree with you. Maybe it's a good idea to remove '--use_openmp' flag in macOS packaging CI for consistency.
> The problem is, it looks like the same question can be asked to Linux: it requires a `apt-get install libgomp1` on runtime and seems to have the same versioning problem as well; but on Linux openmp is ON by default.

That's different. On Linux it is always consistent. apt-get, libgomp1 and gcc are all provided by the Linux distro, but on Mac OS X you need to get omp from brew.

**Pull request merged**
