### PR TITLE
Change "#ifdef WIN32" to "#ifdef _WIN32"

### PR DESCRIPTION
**Pull request by snnn**
### Description
`_WIN32` is a standard macro listed at https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170 . But `WIN32` is not.

### CODE REVIEW

**Comment by Craigacp** [comment]
It's wrong here as well - https://github.com/microsoft/onnxruntime/blob/main/java/src/main/native/ai_onnxruntime_OrtSession_SessionOptions.c#L321

**Review by yuslepukhin — APPROVED** [review]
:shipit:

**Review by yuslepukhin — CHANGES_REQUESTED** [review]
:clock1:

**Comment by yuslepukhin** [comment]
> #ifdef WIN32

Please, scan the code base for other occurrences.

---
Refers to: java/src/main/native/ai_onnxruntime_OrtSession_SessionOptions.c:321 in edcbcb5. [](commit_id = edcbcb5ea6189bf54b41eedffd7f7aeb1646f074, deletion_comment = True)

**Review by yuslepukhin — APPROVED** [review]
:shipit:

**Review by yufenglee — APPROVED** [review]

**Pull request merged**
