### PR TITLE
ORT 1.20.0 Release: Cherry pick round 1

### PR DESCRIPTION
**Pull request by apsonawane**
ORT 1.20.0 release preparation: Cherry pick round 1

Approved cherry pick comments

### CODE REVIEW

**Comment by edgchen1** [comment]
do you also want to take https://github.com/microsoft/onnxruntime/pull/22508 to fix the "Big Models" pipeline?

**Comment by sophies927** [comment]
> do you also want to take #22508 to fix the "Big Models" pipeline?

I think that's a good idea since I see that the big models checks have already failed a couple times - @apsonawane can you please add that one?

**Comment by snnn** [comment]
Please also include this change: #22516

**Comment by snnn** [comment]
And you may also need #22479 to get the Windows pipelines pass. Or you may need to retry and retry.

**Review by snnn — APPROVED** [review]

**Review by edgchen1 — APPROVED** [review]

**Review by adrianlizarraga — APPROVED** [review]

**Comment by snnn** [comment]
This PR has been included in the `rel-1.20.0` branch. Removing the `release:1.20.0` label.

**Pull request merged**
