### PR TITLE
Revert PR #9618 to bring our python packaging pipeline back online

### PR DESCRIPTION
**Pull request by snnn**
**Description**:
This reverts commit e11fde01797bd99d95504911546ebf567d85c795 because it makes our python packages over size.  The PR should only impact Rocm. It shouldn't change the other build configs. 

So I will revert the PR first. Welcome to try it gain.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by suffiank** [comment]
Hi @snnn the latest master build circa 11/15 has package sizes < 100 MB.
https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=182809&view=results

Are you sure it's related?

**Comment by snnn** [comment]
> Hi @snnn the latest master build circa 11/15 has package sizes < 100 MB. https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=182809&view=results
> 
> Are you sure it's related?

I saw it was still 700MB+. Please double check.

**Comment by suffiank** [comment]
@snnn You're right. I looked at the wrong set of packages. Okay let me take another look with Weixing.

**Comment by suffiank** [comment]
@snnn I have a feeling what the issue is.

Attempting with fix here:
https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=183026&view=results

And PR:
https://github.com/microsoft/onnxruntime/pull/9769

**Comment by snnn** [comment]
Appreciate it

**Pull request closed without merging**
