### PR TITLE
Reduce Linux binary size

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

Strip Linux binary. Will reduce its size by 40%.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by skottmckay** [comment]
Should our whole nuget approach be more consistent? We build Release in some places and RelWithDebInfo in others. If we're going to strip the Linux binary should we also build Release for Windows? Or should we instead build RelWithDebInfo everywhere but put the symbols in a snuget package (e.g. use objcopy + strip on linux)?

**Comment by snnn** [comment]
> Should our whole nuget approach be more consistent? We build Release in some places and RelWithDebInfo in others. If we're going to strip the Linux binary should we also build Release for Windows? Or should we instead build RelWithDebInfo everywhere but put the symbols in a snuget package (e.g. use objcopy + strip on linux)?

We always build Linux binaries in "Release" config and Windows binaries in "RelWithDebInfo". We can the later one to "Release", but it will also increase the binary size.  If you think it is ok, we can do it in another PR to address it.

Whether the build config is "Release" or "RelWithDebInfo",  when we run the "strip" command, it still helps.

**Comment by yuslepukhin** [comment]
Can we build RelWithDebInfo and ship symbols everywhere in a separate file like on windows and mac? It is also possible on Linux. This way the binary size is reduced and we can still debug.
[https://stackoverflow.com/questions/866721/how-to-generate-gcc-debug-symbol-outside-the-build-target](https://stackoverflow.com/questions/866721/how-to-generate-gcc-debug-symbol-outside-the-build-target)

**Comment by pranavsharma** [comment]
There's a script called copy_strip_binary.sh where the Mac binary is getting stripped. Would be nice to do it there so that we do it in only once place.

**Comment by pranavsharma** [comment]
Also, are you planning to ship the symbols along with the pkg in a separate file? How will users debug with symbols stripped? In the case of Windows we've the pdb file, for Mac we've the dSYM set of files. Are we going to have something equivalent for Linux?

**Comment by snnn** [comment]
> Also, are you planning to ship the symbols along with the pkg in a separate file?

@yuslepukhin  is suggesting this. I think it is good. But it will take more time.

> How will users debug with symbols stripped? 

Even without this change, currently the build also doesn't have debug info,

**Comment by snnn** [comment]
I'll close it now,  and try to provide a better solution per the suggestions above at a later time.

**Comment by yuslepukhin** [comment]
Yes, it is possible to achieve.

---
In reply to: [686172763](https://github.com/microsoft/onnxruntime/pull/5043#issuecomment-686172763) [](ancestors = 686172763)

**Pull request closed without merging**
