### PR TITLE
add path to build dir before test run

### PR DESCRIPTION
**Pull request by shahasad**
**Description**: Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by snnn** [comment]
Why it is needed?

**Comment by shahasad** [comment]
> Why it is needed?

Java test seems to fail to find the windows dependency dlls of ORT

**Comment by snnn** [comment]
> > Why it is needed?
> 
> Java test seems to fail to find the windows dependency dlls of ORT

You can run the test process like: "java -Djava.library.path=C:\workspace\TestJni xxx". I would prefer this because otherwise java will try to load the DLL from windows directories first. 

If you must set the PATH env, you may put it in tools\ci_build\github\windows\setup_env.bat.

**Comment by shahasad** [comment]
> Why it is needed?
> 
> Java test seems to fail to find the windows dependency dlls of ORT
> 
> Do you think it's good to put it in tools\ci_build\github\windows\setup_env.bat? So that we don't need to create an extra step and extra bat file.

resolved.

**Comment by shahasad** [comment]
tested windows build --
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=102504

**Pull request merged**
