### PR TITLE
oneDNN ep bf16 enabling

### PR DESCRIPTION
**Pull request by georgen117**
### Description
 This adds bfloat16 support to the oneDNN ep.

When using the oneDNN ep this enables bfloat16 support for the following ops:

Exp, Sigmoid, Tanh, Relu, MatMul, Gelu, BiasGelu, Add, Sub,
Mul, Div, Div, Sqrt, Pow, ReduceMean,  Abs, Cast, Equal, Exp,
FastGelu, FusedMatMul, Gemm, Greter, GreaterOrEqual, LeakyRelu,
Less, LessOrEqual, LRN, ReduceOps, Reshape, Squeeze, Transpose,
 and Unsqueeze.

LayerNorm with some internal casting. 
BatchNorm only enabled BFloat16 for input and output, scale and bias still need fp32 input.

Added bfloat16 unit tests for all of the operators in question. When possible we reused the already existing unit tests that were added by CUDA and ROCM eps.

In many of the unit tests an unusual pattern will be seen 

    #if defined(USE_DNNL)
    TEST(Test, bfloat16_test) {
      #if defined(USE_DNNL)
        // oneDNN ep specific code
      #endif
       //test code
    }
    #endif

Although it looks unusual this was purposely done if another ep implements bfloat16 support for that operator they will be able to enable the unit test by adding there execution provider to the first line without needing to edit inside the test.

Example: `#if defined(USE_CUDA) || defined(USE_DNNL)`  see the MatMul_float16 test in matmul_test.cc for and example of how this is useful.

Additionally two new ISA checks (AVX512_BF16 and AMX-BF16) were added to the cpuid_info code in.  This was important to detecting is bfloat16 operations are supported by the CPU.

### Motivation and Context
This expands the capabilities of the oneDNN execution provider to support models containing bfloat16 operations.

### CODE REVIEW

**Comment by georgen117** [comment]
@jywu-msft would you please run /azp run Linux DNNL CI Pipeline , this is the primary pipeline for testing the oneDNN execution provider.

**Comment by jywu-msft** [comment]
there seems to be a conflict on activation_op_test.cc now, can you help resolve? thanks.

**Comment by georgen117** [comment]
> there seems to be a conflict on activation_op_test.cc now, can you help resolve? thanks.

Yes I can.

**Comment by georgen117** [comment]
@jywu-msft I have resolved the conflict. would you please run `/azp run Linux DNNL CI Pipeline` again thanks.

**Comment by jywu-msft** [comment]
> @jywu-msft I have resolved the conflict. would you please run `/azp run Linux DNNL CI Pipeline` again thanks.

it's now showing 37 files modified and multiple conflicts. can you try closing/re-opening the PR?

**Comment by georgen117** [comment]
> > @jywu-msft I have resolved the conflict. would you please run `/azp run Linux DNNL CI Pipeline` again thanks.
> 
> it's now showing 37 files modified and multiple conflicts. can you try closing/re-opening the PR?

The 37 files modified is correct. Since we added so many bfloat16 operators we updated a lot of unit tests to test those operators for bfloat16.  Most of the merge conflicts have been coming from the unit tests.

22 - unit test files modified
2 - files updating cpuid_info to detect bfloat16 hardware
3 - files updated to expose the cpuid_info bfloat16 hardware detection to execution providers.
9 - files in the oneDNN execution provider to handle the bfloat16 changes.
1- change to a build script.
-----------------------------------
37 files changed in total.

Sorry that this is such a large commit.  The unit tests are modeled after the float32 tests which should make them simpler to review.

Part of the reason this is so large is that we could not make the PR till oneDNN version 2.7 that was pushed recently.

**Comment by georgen117** [comment]
@jywu-msft Would it aid you if I broke the code apart and made commits that added only a few operators at a time?

I avoided this initially because I wanted to make sure the work done by Ruihan-Yin was properly attributed in the code. i.e. he was marked at the author when you check the code using git blame. He is a new developer right out of university and the work he did to enable the bfloat16 ops was excellent. Unless done really carefully splitting the code into multiple commits would likely change me to the author instead. I wanted him to be properly attributed.

**Comment by georgen117** [comment]
@jywu-msft also I resolved the new merge conflicts again.  Don't know if you saw.

**Comment by jywu-msft** [comment]
> > > @jywu-msft I have resolved the conflict. would you please run `/azp run Linux DNNL CI Pipeline` again thanks.
> > 
> > 
> > it's now showing 37 files modified and multiple conflicts. can you try closing/re-opening the PR?
> 
> The 37 files modified is correct. Since we added so many bfloat16 operators we updated a lot of unit tests to test those operators for bfloat16. So far all of the merge conflicts have been coming from the unit tests. Which makes since a lot of developers modify those files.
> 
> 22 - unit test files modified 2 - files updating cpuid_info to detect bfloat16 hardware 3 - files updated to expose the cpuid_info bfloat16 hardware detection to execution providers. 9 - files in the oneDNN execution provider to handle the bfloat16 changes. 1 - change to a build script.
> 
> 37 files changed in total.
> 
> Sorry that this is such a large commit. The unit tests are modeled after the float32 tests which should make them simpler to review.
> 
> Part of the reason this is so large is that we could not make the PR till oneDNN version 2.7 that was pushed recently.

sorry for the confusion. thanks for the detailed explanation.

**Comment by georgen117** [comment]
@jywu-msft Based on the failure, I believe the CI test failure is my problem. I am investigating.

**Comment by georgen117** [comment]
> @jywu-msft Based on the failure, I believe the CI test failure is my problem. I am investigating.

Found the issue.  One of the new unittest was running on CUDA when it shouldn't have been. Sorry for the PR commit churn.

**Comment by jywu-msft** [comment]
there's a build failure on windows https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=800606&view=logs&s=61164437-1f1f-53c4-baf1-3ac6a150311c

**Comment by georgen117** [comment]
> there's a build failure on windows https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=800606&view=logs&s=61164437-1f1f-53c4-baf1-3ac6a150311c

@jywu-msft Thanks for pointing out the failure.  I am surprised I missed this when I was building and testing locally. Likely because it is warning that was treated as an error and it didn't prevent the build from completing. Unfortunately I missed the line in the log when building locally.

Could you kick of the windows CI builds to make sure there are no other errors I missed.

**Comment by georgen117** [comment]
@jywu-msft I don't know if you want to invite another reviewer since this change updates `core/common/cpuid.cc and *.h file.

I added code to find two new CPU intrinsics.  To get one of the intrinsics I also added a function to read the CPU SubLeaves values. I thought I would point out that change specifically since it effects core code.  Most of the time I only touch the execution provider and unit test code.

**Comment by yufenglee** [comment]
> @jywu-msft I don't know if you want to invite another reviewer since this change updates `core/common/cpuid.cc and *.h file.
> 
> I added code to find two new CPU intrinsics. To get one of the intrinsics I also added a function to read the CPU SubLeaves values. I thought I would point out that change specifically since it effects core code. Most of the time I only touch the execution provider and unit test code.

Add @chenfucn for the CPU extension detection change.

**Comment by georgen117** [comment]
> > @jywu-msft I don't know if you want to invite another reviewer since this change updates `core/common/cpuid.cc and *.h file.
> > I added code to find two new CPU intrinsics. To get one of the intrinsics I also added a function to read the CPU SubLeaves values. I thought I would point out that change specifically since it effects core code. Most of the time I only touch the execution provider and unit test code.
> 
> Added @chenfucn for the CPU extension detection change.

I CPU extensions change is limited to this commit if that helps at all. (2 files to review instead of 47) https://github.com/microsoft/onnxruntime/pull/13484/commits/d137ec0c469a013e42a8355b36fbeb9aa85331c0

**Comment by georgen117** [comment]
@jywu-msft I have looked over all of the failures and the are all failing in similar ways:
They all appear to be failing when trying to download the anylinux docker image.

With the exception of the `orttraining-linux-ci-pipeline` that timed out.  I looked at the log and it took almost 50 min to fetch the anylinux docker image. A process that on other builds typically only takes 2.5 min. I think the extra long time spent fetching the image just made it so the other build steps timed. out.

I am not 100% sure but I think this was a temporary network error and if you relaunched the 4 CI builds that failed they would pass.

**Review by chenfucn — APPROVED** [review]

**Review by jywu-msft — APPROVED** [review]
Thanks!

**Comment by georgen117** [comment]
@chenfucn and @jywu-msft Thanks for the work you all did to get this merged!

**Comment by jywu-msft** [comment]
> @chenfucn and @jywu-msft Thanks for the work you all did to get this merged!

you're welcome!

**Pull request merged**
