### PR TITLE
Better detection of MPI using FindMPI

### PR DESCRIPTION
**Pull request by ashari4**
**Description**: Describe your changes.

This PR updates the build system to use the `FindMPI` module to find an MPI installation on the user's machine.

**Motivation and Context**

- Why is this change required? What problem does it solve?

The build system currently assumes a hardcoded directory structure of MPI, which may be incompatible with a user's installation of MPI (e.g if the user has installed [OpenMPI via VCPKG](https://github.com/microsoft/vcpkg/tree/master/ports/openmpi)). 

- If it fixes an open issue, please link to the issue here.

#7629

### CODE REVIEW

**Comment by snnn** [comment]
LGTM.

**Comment by ashari4** [comment]
> ```
> CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
>   Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
> 
>       Reason given by package: MPI component 'Fortran' was requested, but language Fortran is not enabled.
> ```

It's probably the REQUIRED option that is causing the `orttraining-linux-gpu-ci-pipeline` to fail. It looks like MPI is not available on that pipeline's build agent;  a successful build demonstrates that MPI is not found:

https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=384644&view=logs&j=e72fb308-291e-5fb1-30c6-82c6894fdfe2&t=a1647df9-f305-55a0-8dad-8d9880cc18bf&l=398

I can try dropping the REQUIRED in `find_package(MPI)`

**Comment by ashari4** [comment]
@snnn, could you please queue up another build?

**Comment by ashari4** [comment]
I am noticing other PR builds suffering from similar errors - are these errors intermittent?

#7671 

https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=385588&view=logs&j=7636b40b-abcf-5c6b-cc48-bcd7d4ae0854&t=4f922874-195a-5571-f5f1-e2f658fa1687&l=794

#7657 
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=385248&view=logs&j=7636b40b-abcf-5c6b-cc48-bcd7d4ae0854&t=4f922874-195a-5571-f5f1-e2f658fa1687&l=800

**Comment by ashari4** [comment]
I spoke to Ethan Tao, who is the DRI this week; he suggested that I re-queue the job.

**Comment by snnn** [comment]
@ashari4 Thank you for making contributions to onnx runtime. But if you are a Microsoft employee, please open https://repos.opensource.microsoft.com/link and link your github id.  It is up to you to decide whether you want to link a GitHub account your already have, or create a new GitHub account specifically for your work at Microsoft. Your GitHub account is always yours.

**Comment by ashari4** [comment]
Thanks @snnn - I have linked my GitHub account.

**Review by snnn — APPROVED** [review]
@liqunfu Any comments?

**Comment by ashari4** [comment]
@snnn I would like to merge this today if possible since my work depends on this. Let me know if you have any objections.

**Pull request merged**
