### PR TITLE
[VitisAI] Add profiler interface for vitisai

### PR DESCRIPTION
**Pull request by tianfang-fafafa**
### Description

Add common interfaces for vitis ep profiler.

### Motivation and Context

Vitis ep can collect and record api and kernel timestamps in file when onnxruntime '-p' is enabled.

### CODE REVIEW

**Comment by tianfang-fafafa** [comment]
hi, @jywu_msft   Can you help to review this pr, please?

**Comment by xlnx-yuxiz** [comment]
Hi, @jywu-msft , could you please help review this PR for vitisai?

**Comment by tianfang-fafafa** [comment]
hi @jywu-msft ,  all checks have passed,  is it suitable for merging?

**Review by jywu-msft — APPROVED** [review]

**Comment by tianfang-fafafa** [comment]
@jywu-msft    thanks a lot

**Pull request merged**
