### PR TITLE
Update ONNX to a newer commit

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: Update ONNX to a newer commit

### CODE REVIEW

**Comment by snnn** [comment]
Can we stick to onnx1.6 until we released the 1.0?

**Comment by hariharans29** [comment]
> Can we stick to onnx1.6 until we released the 1.0?

You mean keep the onnx-tip commit as the "bump up version" commit ?

**Comment by snnn** [comment]
> > Can we stick to onnx1.6 until we released the 1.0?
> 
> You mean keep the onnx-tip commit as the "bump up version" commit ?

Yes.

**Comment by snnn** [comment]
I think we should use 553df22c67bee5f0fe6599cff60f1afc6748c635 ?

**Comment by hariharans29** [comment]
> 553df22c67bee5f0fe6599cff60f1afc6748c635

Sure

**Pull request merged**
