### PR TITLE
Cherry-pick 5378/5392 to rel-1.5.2

### PR DESCRIPTION
**Pull request by gwang-msft**
**Description**: Cherry-pick #5378 and #5392 to rel-1.5.2

### CODE REVIEW

**Comment by gwang-msft** [comment]
The reason why this contains extra changes than #5378  and #5392,
- There was a bug fixed in flatbuffers master branch (not yet in a release), https://github.com/google/flatbuffers/pull/6047, this issue will fail the ORT build for CUDA and TensorRT, since they use graph.h which will include flatbuffers.h
- In ORT 1.5.1, we are using the master branch of flatbuffers, so we are not hit with the above issue
- Before #5392, I had another change #5276, which move flatbuffers.h out of graph.h/model.h/session_state.h and use forward declaration instead, when #5392 was merged, we did not have build issue for CUDA and TensorRT
- We are hit with this build break in hte PR because we are not including #5276, so the fix is to include part of #5276, which remove flatbuffers.h from most head files and use forward declaration instead

**Comment by tianleiwu** [comment]
Not sure why "Linux OpenVINO CI Pipeline" failed. I included it into https://github.com/microsoft/onnxruntime/pull/5446, the build is fine with other cherry-picks.

**Comment by gwang-msft** [comment]
> Not sure why "Linux OpenVINO CI Pipeline" failed. I included it into #5446, the build is fine with other cherry-picks.

The issue is fixed in #5356, which is included in #5446 not here

**Review by skottmckay — APPROVED** [review]
:shipit:

**Comment by tianleiwu** [comment]
The commits have been merged to rel-1.5.2 with #5446.

**Pull request closed without merging**
