### PR TITLE
Uncomment line in OVEP that was commented out in error

### PR DESCRIPTION
**Pull request by javier-intel**
### Description
One line change to re-enable a line incorrectly commented out in an earlier commit

### Motivation and Context
Fix issue introduced with [PR 21872](https://github.com/microsoft/onnxruntime/pull/21872#discussion_r1736744441)

### CODE REVIEW

**Comment by jywu-msft** [comment]
can you fix the clang-format lint error? https://github.com/microsoft/onnxruntime/actions/runs/10692374490/job/29640776162?pr=21973 ?

**Comment by jywu-msft** [comment]
> can you fix the clang-format lint error? https://github.com/microsoft/onnxruntime/actions/runs/10692374490/job/29640776162?pr=21973 ?

@javier-intel , @preetha-intel  fyi

**Comment by javier-intel** [comment]
> > can you fix the clang-format lint error? https://github.com/microsoft/onnxruntime/actions/runs/10692374490/job/29640776162?pr=21973 ?
> 
> @javier-intel , @preetha-intel fyi

Sorry for the delay. I was made aware of a process for contributing to ORT project and had to quickly get approved. The PR was updated.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
