### PR TITLE
Check the AMX tile configuration is unchanged

### PR DESCRIPTION
**Pull request by georgen117**
Don't assume the AMX tile configuration will always remain unchanged It is possible that other code will change the AMX tile configuration.

This change will read the current tile configuration
 - if the tile is un-configured it will be configured
 - if the tile is configured but does not match the expected configuration it will be configured for the expected configuration

This resolves issues seen in unit tests when building OneDNN ep.

### CODE REVIEW

**Comment by chenfucn** [comment]
Just a minor suggestion, you may get away with comparing just a few bytes instead of the whole structure. Like:

https://github.com/oneapi-src/oneDNN/blob/ffc93854416994ae0fb91225e92b3a34dc220c1f/src/cpu/x64/gemm/amx/jit_avx512_core_amx_gemm_kern.cpp#L278

Or check out the structure of the config, and try to decide which one is worth checking:

typedef struct __tile_config
{
  uint8_t palette_id;
  uint8_t start_row;
  uint8_t reserved_0[14];
  uint16_t colsb[16];
  uint8_t rows[16];
} __tilecfg;

I guess we can ignore the reserved bytes at least :-)

**Comment by georgen117** [comment]
I updated the code so it does not check the reserved bites. I compared the generated assembly using godbolt.org and the generated assembly results in much fewer moves and comparisons (XORs in the asm).
 
Additionally in testing I inserted a high resolution timer around the init code to see if there was a clear difference. When running the code I didn't really see a clear difference between the check comparing the full tile config vs just the non-reserved parts of the tile config. The most we would expect is a difference of a few clock cycles.

**Comment by eralmual** [comment]
Just validated this PR fixes an issue when running with oneDNN ep support, we noticed when oneDNN executed a MatMul primitive using AMX then MLAS would crash with a SIGILL (illegal instruction) error when trying to run AMX code.

**Review by chenfucn — APPROVED** [review]

**Comment by georgen117** [comment]
@chenfucn I have checked out the failures. Both of them are failing for the same reason

```
======================================================================
ERROR: testGetProviders (__main__.TestInferenceSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 92, in testGetProviders
    sess = onnxrt.InferenceSession(get_name("mul_1.onnx"), providers=onnxrt.get_available_providers())
  File "D:\a\onnxruntime\onnxruntime\build\Release\Release\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\a\onnxruntime\onnxruntime\build\Release\Release\onnxruntime\capi\onnxruntime_inference_collection.py", line 431, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\onnxruntime\onnxruntime\onnxruntime\core\providers\tvm\tvm_api.cc:49 onnxruntime::tvm::TVMCompile compile != nullptr was false. Unable to retrieve 'tvm_onnx_import_and_compile'.
```

they are both failing saying they are unable to retrieve the `tvm_onnx_import_and_compile` this change should not effect this.  I can rebase this change if needed. Please let me know how you would like to procced.

**Pull request merged**
