### PR TITLE
Cherry-pick for 1.17.3

### PR DESCRIPTION
**Pull request by YUNQIUGUO**
### Description

Web prs are not included yet.

### CODE REVIEW

**Comment by YUNQIUGUO** [comment]
Had to address a couple merge conflicts so please have a look at the current changes - help make sure it's correct.

**Comment by Craigacp** [comment]
Is 1.17.3 a release for all APIs or just the web one? If it's for all APIs could we get https://github.com/microsoft/onnxruntime/pull/19942 merged in? It fixes a regression in 1.17 from 1.16 which we've hit in practice.

**Comment by YUNQIUGUO** [comment]
> Is 1.17.3 a release for all APIs or just the web one? If it's for all APIs could we get #19942 merged in? It fixes a regression in 1.17 from 1.16 which we've hit in practice.

Sure - mind clarifying what packages this change apply to?

**Comment by Craigacp** [comment]
It's a fix to the CPU provider implementation of the `SplitToSequence` operator. So it's still useful for the web API, but our use it via Python or Java.

**Comment by YUNQIUGUO** [comment]
@tianleiwu @mtavenrath looks like this pr #19889 introduces a bunch of build failures on the release branch. mind sharing is there any dependency prs that I need to take or so? https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1331111&view=logs&j=6df8fe70-7b8f-505a-8ef0-8bf93da2bac7&t=38e4b5a4-9041-5949-6670-6ace666c420b&l=5163 failure error message.

**Comment by tianleiwu** [comment]
> @tianleiwu @mtavenrath looks like this pr #19889 introduces a bunch of build failures on the release branch. mind sharing is there any dependency prs that I need to take or so? https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1331111&view=logs&j=6df8fe70-7b8f-505a-8ef0-8bf93da2bac7&t=38e4b5a4-9041-5949-6670-6ace666c420b&l=5163 failure error message.

There is no need to take dependency PRs, which might bring more changes. I added a commit to manually fix the build errors.

**Comment by YUNQIUGUO** [comment]
> > @tianleiwu @mtavenrath looks like this pr #19889 introduces a bunch of build failures on the release branch. mind sharing is there any dependency prs that I need to take or so? https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1331111&view=logs&j=6df8fe70-7b8f-505a-8ef0-8bf93da2bac7&t=38e4b5a4-9041-5949-6670-6ace666c420b&l=5163 failure error message.
> 
> There is no need to take dependency PRs, which might bring more changes. I added a commit to manually fix the build errors.

cool, thanks!

**Review by edgchen1 — DISMISSED** [review]
Inclusion of #19858 looks good.

**Review by tianleiwu — APPROVED** [review]

**Comment by YUNQIUGUO** [comment]
The cherry-pick process so far should be completed. please @microsoft/onnxruntime-es take and a look and help approve, thanks.

**Review by snnn — DISMISSED** [review]

**Review by tianleiwu — DISMISSED** [review]

**Review by kunal-vaishnavi — APPROVED** [review]

**Comment by snnn** [comment]
You need this: https://github.com/microsoft/onnxruntime/pull/20073/files

**Comment by YUNQIUGUO** [comment]
> You need this: https://github.com/microsoft/onnxruntime/pull/20073/files

thanks added the fix commit!

**Review by snnn — APPROVED** [review]

**Review by tianleiwu — APPROVED** [review]

**Pull request merged**
