### PR TITLE
update doc for Vitis-AI execution provider upgrade

### PR DESCRIPTION
**Pull request by mingyueliuh**
### Description
Documentation and Vitis AI EP synchronous upgrade

### CODE REVIEW

**Comment by mingyueliuh** [comment]
@microsoft-github-policy-service agree company="AMD"

**Review by jywu-msft — APPROVED** [review]

**Comment by quentonh** [comment]
@jywu-msft We are working on an important effort for Microsoft and are hoping that this PR can be merged today.  If you are able to assist with the merge, we would greatly appreciate it.

**Comment by quentonh** [comment]
Hi @jywu-msft and @jeffmend is it possible for you to update the aka.ms shortlink, or advise how I can request that this be updated?

**Comment by jeffmend** [comment]
@Faith ***@***.***> - you own the aka.ms/build-ort-vitisai.  Can you add me as an owner or redirect the link from
https://onnxruntime.ai/docs/build/eps.html#vitis-ai to
https://onnxruntime.ai/docs/build/eps.html#amd-vitis-ai ?
________________________________

**Comment by jeffmend** [comment]
completed 8/23

**Comment by quentonh** [comment]
@jeffmend Beautiful.  Thank-you so much!

**Pull request merged**
