### PR TITLE
[WebNN EP] Support Abs and Neg ops

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@fdwr, @guschmue, PTAL, thanks!

**Comment by fdwr** [comment]
I have Abs and Neg locally in my chromium fork. Do you need me to push them to [GitHub](https://github.com/fdwr/chromium-src-webnn-dml/tree/dml_sd) so you can verify them?

**Review by fdwr — APPROVED** [review]
Thanks Wanming.

**Comment by Honry** [comment]
> I have Abs and Neg locally in my chromium fork. Do you need me to push them to [GitHub](https://github.com/fdwr/chromium-src-webnn-dml/tree/dml_sd) so you can verify them?

No worry, I've verified them with Chromium Canary. (XNNPack backend has supported them)

**Pull request merged**
