### PR TITLE
[WebNN EP] Fixed bug in ConvTranspose

### PR DESCRIPTION
**Pull request by Honry**
The constraint of ConvTranspose was placed in wrong place.

### CODE REVIEW

**Comment by Honry** [comment]
@fdwr, @guschmue, PTAL, thanks!

**Review by guschmue — APPROVED** [review]

**Review by fdwr — APPROVED** [review]
👍 Is there a pending issue to support this in TFLite? Dilations is part of the WebNN spec for convTranspose.

**Comment by guschmue** [comment]
timely catch, thanks Wanming!

**Comment by Honry** [comment]
> Is there a pending issue to support this in TFLite? Dilations is part of the WebNN spec for convTranspose.

@fujunwei has filed corresponding issue: https://issues.chromium.org/issues/349089094

**Pull request merged**
