### PR TITLE
modify olive doc section

### PR DESCRIPTION
**Pull request by leqiao-1**
### Description
Move Olive doc into Performance section. 
Olive v2 is no longer just a profiling tool. It composes industry-leading techniques across model compression, optimization, and compilation. It's better to move into Performance section.

### CODE REVIEW

**Comment by natke** [comment]
Staged here: https://natke.github.io/onnxruntime/docs/performance/olive.html

**Comment by natke** [comment]
I have a couple of comments.

Are we calling the product Olive or ONNX Live? If ONNX Live that should be reflected in the docs?

Or could this topic be called Optimize end to end?

**Comment by leqiao-1** [comment]
> 

@EmmaNingMS Do you have any comments here?

**Comment by leqiao-1** [comment]
> I have a couple of comments.
> 
> Are we calling the product Olive or ONNX Live? If ONNX Live that should be reflected in the docs?
> 
> Or could this topic be called Optimize end to end?


@EmmaNingMS Do you have any comments here?

**Comment by EmmaNingMS** [comment]
1) It's Olive. 2) we can update it to end to end optimize with Olive. @leqiao-1

**Comment by leqiao-1** [comment]
Updated the topic. Staged here: https://leqiao-1.github.io/onnxruntime/docs/performance/olive.html

**Review by EmmaNingMS — APPROVED** [review]

**Pull request merged**
