### PR TITLE
Bugfixes: dangling pointers and python property typo

### PR DESCRIPTION
**Pull request by chenfucn**
### Description
Bug fixes

### Motivation and Context
Fixing one dangling pointer, and one python property name typo

### CODE REVIEW

**Review by snnn — APPROVED** [review]

**Review by jchen351 — APPROVED** [review]

**Comment by yufenglee** [comment]
>     )

it is not used anymore

---
Refers to: onnxruntime/python/tools/quantization/matmul_weight4_quantizer.py:246 in a2c6e14. [](commit_id = a2c6e14b1f6ef62f88d891a0dcdfb991137b503f, deletion_comment = False)

**Comment by yufenglee** [comment]
>     quant.model.save_model_to_file(output_model_path, False)

add a parameter to allow to save large model>2G

---
Refers to: onnxruntime/python/tools/quantization/matmul_weight4_quantizer.py:260 in a2c6e14. [](commit_id = a2c6e14b1f6ef62f88d891a0dcdfb991137b503f, deletion_comment = False)

**Comment by yufenglee** [comment]
>     q4dq_bin_path = args.quant_bin_path

dito

---
Refers to: onnxruntime/python/tools/quantization/matmul_weight4_quantizer.py:255 in a2c6e14. [](commit_id = a2c6e14b1f6ef62f88d891a0dcdfb991137b503f, deletion_comment = False)

**Comment by chenfucn** [comment]
> > ```
> > q4dq_bin_path = args.quant_bin_path
> > ```
> 
> dito
> 
> Refers to: onnxruntime/python/tools/quantization/matmul_weight4_quantizer.py:255 in [a2c6e14](https://github.com/microsoft/onnxruntime/commit/a2c6e14b1f6ef62f88d891a0dcdfb991137b503f). [](commit_id = [a2c6e14](https://github.com/microsoft/onnxruntime/commit/a2c6e14b1f6ef62f88d891a0dcdfb991137b503f), deletion_comment = False)

What tool are you using, it is quite cumbersome to find where in the code you are referring to.

**Comment by chenfucn** [comment]
> > ```
> > quant.model.save_model_to_file(output_model_path, False)
> > ```
> 
> add a parameter to allow to save large model>2G
> 
> Refers to: onnxruntime/python/tools/quantization/matmul_weight4_quantizer.py:260 in [a2c6e14](https://github.com/microsoft/onnxruntime/commit/a2c6e14b1f6ef62f88d891a0dcdfb991137b503f). [](commit_id = [a2c6e14](https://github.com/microsoft/onnxruntime/commit/a2c6e14b1f6ef62f88d891a0dcdfb991137b503f), deletion_comment = False)
Could you give me an example how? Thanks!

**Comment by yufenglee** [comment]
> > > ```
> > > q4dq_bin_path = args.quant_bin_path
> > > ```
> > 
> > 
> > dito
> > Refers to: onnxruntime/python/tools/quantization/matmul_weight4_quantizer.py:255 in [a2c6e14](https://github.com/microsoft/onnxruntime/commit/a2c6e14b1f6ef62f88d891a0dcdfb991137b503f). [](commit_id = [a2c6e14](https://github.com/microsoft/onnxruntime/commit/a2c6e14b1f6ef62f88d891a0dcdfb991137b503f), deletion_comment = False)
> 
> What tool are you using, it is quite cumbersome to find where in the code you are referring to. And dito to what?

I'm using Codeflow. Looks like it messes up the comments.

**Review by yufenglee — COMMENTED** [review]
it is not used anymore.

**Comment by yufenglee** [comment]
> > > > ```
> > > > q4dq_bin_path = args.quant_bin_path
> > > > ```
> > > 
> > > 
> > > dito
> > > Refers to: onnxruntime/python/tools/quantization/matmul_weight4_quantizer.py:255 in [a2c6e14](https://github.com/microsoft/onnxruntime/commit/a2c6e14b1f6ef62f88d891a0dcdfb991137b503f). [](commit_id = [a2c6e14](https://github.com/microsoft/onnxruntime/commit/a2c6e14b1f6ef62f88d891a0dcdfb991137b503f), deletion_comment = False)
> > 
> > 
> > What tool are you using, it is quite cumbersome to find where in the code you are referring to. And dito to what?
> 
> I'm using Codeflow. Looks like it messes up the comments.

Looks like it is an issue of github. It doesn't show comments on non-modified code. Mainly 3 comments:
matmul_weight4_quantizer.py, line 240 to 246: the quant_bin_path is not used anymore and same for line 255
matmul_weight4_quantizer.py, at the end of file: we need to support to save the model with external data format.

**Pull request merged**
