### PR TITLE
Reduce max gradient

### PR DESCRIPTION
**Pull request by anhnguyen7198**
**Description**: Add ReduceMax gradient implementation.

**Motivation and Context**
- Export torch.max operation to ONNX and build backward graph using ORTModule need ReduceMax gradient implementation

### CODE REVIEW

**Comment by esaliya** [comment]
@Aayush-Ankit or @souptc could you trigger the CI pipelines for this?

**Comment by Aayush-Ankit** [comment]
> @Aayush-Ankit or @souptc could you trigger the CI pipelines for this?

**Review by souptc — DISMISSED** [review]

**Review by souptc — APPROVED** [review]

**Review by souptc — APPROVED** [review]

**Comment by ytaous** [comment]
Hi, this PR is failing AMD CI - can you pls revert it to mitigate it for now?

**Pull request merged**
