### PR TITLE
[WebNN] Update usage of MLTensor to align with latest spec

### PR DESCRIPTION
**Pull request by Honry**
Remove deprecated 'numThreads' option BTW.

### CODE REVIEW

**Comment by Honry** [comment]
@fdwr, @guschmue, PTAL, thanks!

cc// @ibelem

**Review by fdwr — APPROVED** [review]
👀

**Comment by Honry** [comment]
@fdwr, thank you for your review! Comments addressed, PTAL again, thanks!

**Comment by fdwr** [comment]
> Check for broken links
> https://microsoft.github.io/Olive/features/cli.html failed: 404 No error

https://github.com/microsoft/onnxruntime/actions/runs/12133242537/job/33872573345?pr=22959

**Pull request merged**
