### PR TITLE
Remove identity insertion before every output for passthrough inputs

### PR DESCRIPTION
**Pull request by baijumeswani**
In an earlier pull request #7694, we addressed the problem of passthrough inputs by introducing an ```Identity``` node before every output. After the release of ```PyTorch``` ```1.9.0```, the exporter introduces the ```Identity``` and it is no longer needed to do so on the ```ORTModule``` end. Removing redundant code.

### CODE REVIEW

**Comment by ytaous** [comment]
1. would this change compatibel with torch 1.8?
2. should the identity_elimination.cc also updated?

**Comment by baijumeswani** [comment]
> would this change compatible with torch 1.8?

I think this change will break with torch ```1.8```. But users can use an earlier release of ```torch_ort (ORTModule)``` which is compatible with ```torch``` ```1.8```. I see that our CI pipeline is using 1.8 which is why the pipeline is failing.

> should the identity_elimination.cc also updated?
I think that code must stay because the frontend changes in #7694 is equivalent to the exporter changes in ```PyTorch```. The changes in ```identity_elimintaion.cc``` are related to preventing removal of ```Identity``` op in case of pass through inputs. Which is still valid after moving identity insertion to the exporter side.

**Review by thiagocrepaldi — COMMENTED** [review]
@natke Does our documentation keep a compatibility table between PyTorch versions and torch_ort? 

Something like

| torch_ort | torch |
|-----------|-------|
| 1.8.1     | 1.8+  |
| 1.8.2     | 1.8+  |
| 1.9       | 1.9+  |

That would be useful, even more when the newer versions start to break BC with older version, such as this PR

**Comment by SherlockNoMad** [comment]
let's keep this for a bit longer, as user might be still using torch 1.8. 
It doesn't hurt to have these extra Identity node, right? As the graph optimization will clean it up, if they are really duplicated.

**Comment by pranavsharma** [comment]
The PR title says "every output". Can this be corrected as it's misleading.

**Comment by baijumeswani** [comment]
@pranavsharma to resolve a problem with passthrough inputs, we had inserted an identity before every output in work item #7694 in ```ORTModule```. This PR removes that code that was inserting an ```Identity``` for every output.
BTW, this is different from the duplicate output work that we were discussing internally.

**Comment by pranavsharma** [comment]
> @pranavsharma to resolve a problem with passthrough inputs, we had inserted an identity before every output in work item #7694 in `ORTModule`. This PR removes that code that was inserting an `Identity` for every output.
> BTW, this is different from the duplicate output work that we were discussing internally.

thanks. yeah, i realized i'd commented on the wrong PR 👍

**Comment by baijumeswani** [comment]
> > would this change compatible with torch 1.8?
> 
> I think this change will break with torch `1.8`. But users can use an earlier release of `torch_ort (ORTModule)` which is compatible with `torch` `1.8`. I see that our CI pipeline is using 1.8 which is why the pipeline is failing.
> 
> > should the identity_elimination.cc also updated?
> 
> I think that code must stay because the frontend changes in #7694 is equivalent to the exporter changes in `PyTorch`. The changes in `identity_elimintaion.cc` are related to preventing removal of `Identity` op in case of pass through inputs. Which is still valid after moving identity insertion to the exporter side.

Just figured out, the pipeline was already set up to use ```torch 1.9.0``` (not 1.8). There was a problem in my unit test. Fixed it in the latest commit.

**Comment by baijumeswani** [comment]
keeping work done in #7694 for a little longer as suggested by @SherlockNoMad

**Pull request closed without merging**
