### PR TITLE
enable f64 for clip-11

### PR DESCRIPTION
**Pull request by ganler**
Fixes https://github.com/microsoft/onnxruntime/issues/10165

cc: @yuslepukhin @edgchen1

### CODE REVIEW

**Comment by edgchen1** [comment]
I believe this change will cause the kernel def hash for Clip 11 to change. We want to keep the hashes for kernels that exist in previous releases stable. There is a way to update the types and preserve the original hash value. More info here:
https://github.com/microsoft/onnxruntime/blob/97659495d982982a06eee6a4e3560923b988ff7e/onnxruntime/test/providers/kernel_def_hash_test.cc#L5-L51

You can also run this test and see if it prints any warning message:
https://github.com/microsoft/onnxruntime/blob/97659495d982982a06eee6a4e3560923b988ff7e/onnxruntime/test/providers/kernel_def_hash_test.cc#L158

**Comment by ganler** [comment]
@edgchen1 I tried what you said. It works and the tests run w/o warning.

image

**Comment by snnn** [comment]
So, please update OperatorKernels.md. You can find a new version in [the build log ](https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=560389&view=results)

**Comment by ganler** [comment]
Sorry. I mistook the doc change of different providers. Now fixed.

**Review by edgchen1 — APPROVED** [review]
LGTM

**Comment by skottmckay** [comment]
Is there a production use case for this change or is just that ORT didn't implement the full ONNX spec?

**Review by skottmckay — CHANGES_REQUESTED** [review]
Apologies this wasn't made clearer earlier, but we require a valid production use case to justify the maintenance and binary size cost of expanding the types supported by individual operators. 

Do you have a production use case?

**Comment by pranavsharma** [comment]
> Apologies this wasn't made clearer earlier, but we require a valid production use case to justify the maintenance and binary size cost of expanding the types supported by individual operators.
> 
> Do you have a production use case?

Yes, please provide a real production use case before adding a new type.

**Comment by ganler** [comment]
@skottmckay @pranavsharma  Sorry for the lack of declaration.

I am not using it in production as I'm only a student. Just found that ONNX supports clip-11-double in its specification and ORT also supports [clip-double](https://github.com/microsoft/onnxruntime/blob/master/docs/OperatorKernels.md) kernel (opset 12) so that I thought it is "free" to simply attach this API to an implemented [kernel](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/math/clip.cc#L87).

**Comment by pranavsharma** [comment]
> @skottmckay @pranavsharma Sorry for the lack of clarification.
> 
> I am not using it in production as I'm only a student. Just found that ONNX supports clip-11-double in its specification and ORT also supports [clip-double](https://github.com/microsoft/onnxruntime/blob/master/docs/OperatorKernels.md) kernel (opset 12) so that I thought it is "free" to simply attach this API to an implemented [kernel](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/math/clip.cc#L87).

Yeah, sorry, if this is not for production use case, better to do it in a fork.

**Comment by pranavsharma** [comment]
> > > @skottmckay @pranavsharma Sorry for the lack of clarification.
> > > I am not using it in production as I'm only a student. Just found that ONNX supports clip-11-double in its specification and ORT also supports [clip-double](https://github.com/microsoft/onnxruntime/blob/master/docs/OperatorKernels.md) kernel (opset 12) so that I thought it is "free" to simply attach this API to an implemented [kernel](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/math/clip.cc#L87).
> > 
> > 
> > Yeah, sorry, if this is not for production use case, better to do it in a fork.
> 
> I see. Thanks for letting me know. Now I understand the contribution preference of ORT community. :-)

Thanks. We should make this clear in our contribution guidelines.

**Pull request closed without merging**
