### PR TITLE
[Quant tool]: Improve symmetric quantization range update for Relu/Clip

### PR DESCRIPTION
**Pull request by f2013519**
### Description
This PR improves the range calculation for input to Relu/Clip nodes for the symmetric quantization case.

### Motivation and Context
Currently, the issue we face is that for the common scenario of conv followed by relu in the symmetric quantization config, different scales could assigned for the tensors corresponding to input & output of relu. 

The downside is that this may introduce noise due to multiple re-quant, and makes it difficult to fuse conv-relu nodes for hardware accelerators that support fused conv-relu.

Instead, it is more efficient to assign the output range of relu as the input range of relu / output range of upstream op wherever possible. This adjustment is currently only being done for the asymmetric quantization case. 

For the scenario where the upstream op has multiple consumers, this assumption could be incorrect. For this case we do not adjust the ranges.

### CODE REVIEW

**Comment by f2013519** [comment]
@yufenglee @xadupre pls. review. 

Thanks!

**Comment by f2013519** [comment]
@yufenglee Please help to review the change when able, thanks

**Review by yufenglee — APPROVED** [review]

**Comment by f2013519** [comment]
thanks @yufenglee for reviewing. it seems the ci is failing due to unrelated issue? pls. suggest next steps.

**Comment by adrianlizarraga** [comment]
> thanks @yufenglee for reviewing. it seems the ci is failing due to unrelated issue? pls. suggest next steps.

Hi @f2013519, We're working on resolving CI issues. Once we have a fix, I'll let you know so that you can sync this branch with the main branch.

**Review by adrianlizarraga — APPROVED** [review]

**Comment by adrianlizarraga** [comment]
Hi @f2013519, can you please sync with latest main so that CI checks pass? Thanks.

**Comment by f2013519** [comment]
> Hi @f2013519, can you please sync with latest main so that CI checks pass? Thanks.

Have synced, pls. check. Thanks.

**Comment by adrianlizarraga** [comment]
Thank you for your contribution @f2013519.

**Pull request merged**
