### PR TITLE
Fix Android CI build (onnx model test still broken)

### PR DESCRIPTION
**Pull request by shahasad**
**Description**: Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by daquexian** [comment]
What is the relation between this PR and https://github.com/microsoft/onnxruntime/pull/1600?

**Comment by shahasad** [comment]
@daquexian I did not notice https://github.com/microsoft/onnxruntime/pull/1600. 
Please feel free to merge relevant changes from here to (https://github.com/microsoft/onnxruntime/pull/1600). Main purpose is to get the Android CI back running.

**Comment by daquexian** [comment]
@shahasad Thanks for the clarification. In fact, I think https://github.com/microsoft/onnxruntime/pull/1600 already [gets Android CI working](https://dev.azure.com/daquexian/onnxruntime/_build/results?buildId=859), however, a [workaround](https://github.com/JDAI-CV/DNNLibrary/commit/b7073db6106dc07b6c933ae4065d19c2b498ce09) for cmake 3.15 seems break it again. I will fix it soon.

**Comment by daquexian** [comment]
I made Android CI working in #1600

**Comment by snnn** [comment]
Is this PR still needed?

**Pull request closed without merging**
