### PR TITLE
Reduce ops for DNNL ep

### PR DESCRIPTION
**Pull request by georgen117**
**Description**: Describe your changes.
This adds all of the ONNX specified Reduce ops to the DNNL execution provider
The ops added are  ReduceL1, ReduceL2, ReduceLogSum, ReduceLogSumExp, ReduceMax, ReduceMin, ReduceProd, ReduceSum, ReduceSumSquare.

This is a modification of the already existing ReduceMean code.

The code can now handle the keepdims attribute. Previous code  would only accept ReduceMean if the keepdims == 1.

Commit also contains a documentation fix for the recently commtied DNNL QAttention op. The in code documentaiton, some how had a bunch of new lines added that made reading more difficult.  The extra newlines were cleaned up.

**Motivation and Context**
- Why is this change required? What problem does it solve?
This change expands the model coverage of the DNNL execution provider. By adding all the Reduction Operators.
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by georgen117** [comment]
@jywu-msft maintainer, please remember to `run /azp run Linux DNNL CI Pipeline` since this is the main pipeline that runs the dnnl ep.

**Comment by jywu-msft** [comment]
run /azp run Linux DNNL CI Pipeline

**Review by jywu-msft — APPROVED** [review]

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
