### PR TITLE
[WebNN EP] Update WebNN unit test list

### PR DESCRIPTION
**Pull request by zesongw**
Update  WebNN  test list in suite-test-list.jsonc so all test cases are passed behind WebNN CPU backend on Chrome Stable (Although some cases may fall back to CPU EP).
Enable int64 support for WebNN in unit tests.

### CODE REVIEW

**Comment by zesongw** [comment]
@fdwr, @guschmue, PTAL, thanks!

**Review by guschmue — APPROVED** [review]

**Comment by fdwr** [comment]
I'm curious why some of these fail (since it seems these cases would be supported now);

- test_gemm_default_scalar_bias
- test_layer_normalization_4d_axis_negative_3_expanded
- test_layer_normalization_4d_axis_negative_4_expanded

Glad to see so many cases enabled.

**Comment by zesongw** [comment]
> * test_gemm_default_scalar_bias

CPU backend cannot broadcast the scalar to valid tensor in gemm.

> * test_layer_normalization_4d_axis_negative_3_expanded
> * test_layer_normalization_4d_axis_negative_4_expanded

They have `constofshape` nodes.

**Pull request merged**
