### PR TITLE
[VitisAI] Solve the problem that gsl cannot be found when compiling under linux

### PR DESCRIPTION
**Pull request by zz002**
### Description

[VitisAI] Solve the problem that gsl cannot be found when compiling under linux

### CODE REVIEW

**Comment by zz002** [comment]
Hi @jywu-msft
When you have some time, could you kindly kick off the pipeline and review the code for this PR aimed at resolving the compilation error in VitisAI on Linux? Your attention to this matter would be greatly appreciated.

**Review by jywu-msft — APPROVED** [review]

**Comment by zz002** [comment]
@jywu-msft I saw that pipyline has passed the test. Can it be merged?

**Pull request merged**
