### PR TITLE
Cherry-pick for 1.17.1 patch release

### PR DESCRIPTION
**Pull request by YUNQIUGUO**
### Description

As title.

### CODE REVIEW

**Review by PatriceVignola — APPROVED** [review]

**Comment by fs-eire** [comment]
Could you please help to cherry-pick this one: https://github.com/microsoft/onnxruntime/pull/19458

**Comment by YUNQIUGUO** [comment]
> Could you please help to cherry-pick this one: #19458

yes. this one was not merged just now so not being included. will cherry-pick it now.

**Comment by ivberg** [comment]
Mind grabbing #19397 ?

**Review by ivberg — APPROVED** [review]

**Comment by PatriceVignola** [comment]
@YUNQIUGUO When is the deadline for 1.17.1 changes? I have a blocking regression that I may have a fix for by tomorrow.

**Review by adrianlizarraga — APPROVED** [review]

**Review by petermcaughan — DISMISSED** [review]

**Comment by YUNQIUGUO** [comment]
> @YUNQIUGUO When is the deadline for 1.17.1 changes? I have a blocking regression that I may have a fix for by tomorrow.

tomorrow by EOD is fine.

**Review by snnn — DISMISSED** [review]

**Comment by YUNQIUGUO** [comment]
@PatriceVignola it's approaching the EOD. Just checking in - Is the pr ready and merged yet?

If not,I will go ahead and merge this cherry-pick pr for now. and maybe open a second round cherry-pick if necessary. I think we are waiting on another two prs too.

BTW, please share the pr link and tag with release 1.17.1 once it's ready for tracking purpose. thanks!

**Comment by PatriceVignola** [comment]
> @PatriceVignola it's approaching the EOD. Just checking in - Is the pr ready and merged yet?
> 
> If not,I will go ahead and merge this cherry-pick pr for now. and maybe open a second round cherry-pick if necessary. I think we are waiting on another two prs too.
> 
> BTW, please share the pr link and tag with release 1.17.1 once it's ready. thanks!

The PR is here: https://github.com/microsoft/onnxruntime/pull/19481

It was sporadically failing pipelines unrelated to the change and I had to restart them.

**Comment by PatriceVignola** [comment]
@YUNQIUGUO The PR has been merged into main and can be cherry-picked.

**Comment by YUNQIUGUO** [comment]
> @YUNQIUGUO The PR has been merged into main and can be cherry-picked.

Done.

**Review by baijumeswani — APPROVED** [review]

**Comment by jywu-msft** [comment]
can we please include https://github.com/microsoft/onnxruntime/pull/19499 ?

**Comment by tianleiwu** [comment]
Please add https://github.com/microsoft/onnxruntime/pull/19421

**Comment by smk2007** [comment]
Please add https://github.com/microsoft/onnxruntime/pull/19483

**Comment by smk2007** [comment]
Please add https://github.com/microsoft/onnxruntime/pull/19475. TY

**Comment by YUNQIUGUO** [comment]
so far the cherry-picks for the patch should all be ready in there. had to resolve some merge conflicts when merging #19509 please review it's still correct with what's included in this pr. thanks! cc @kunal-vaishnavi  (specifically -  two files whisper_chain.py and whisper_helper.py)

**Review by kunal-vaishnavi — DISMISSED** [review]

**Comment by fs-eire** [comment]
Seems #19274 is marked for 1.17.1 but still waiting for approval.

**Comment by YUNQIUGUO** [comment]
> Seems #19274 is marked for 1.17.1 but still waiting for approval.

thanks for mentioning this. added the commit.

**Comment by smk2007** [comment]
Please add https://github.com/microsoft/onnxruntime/pull/19574, TY!

**Review by jchen351 — APPROVED** [review]

**Review by yufenglee — APPROVED** [review]

**Comment by snnn** [comment]
This PR has been included in the `rel-1.17.1` branch. Removing the `release:1.17.1` label.

**Pull request merged**
