### PR TITLE
[VitisAI] Fix some typos in tensor_proto_new APIs

### PR DESCRIPTION
**Pull request by mingyueliuh**
### Description
Fix some typos in Vitis AI EP.

### CODE REVIEW

**Comment by mingyueliuh** [comment]
@jywu-msft This is a minor change for the typo fix. please take a look when you are avaliable. Thanks.

**Comment by mingyueliuh** [comment]
@jywu-msft  the failed pipeline (https://github.com/microsoft/onnxruntime/actions/runs/9493150687/job/26164565031?pr=21027) does not appear to be caused by this PR,   please help talk a look , thanks.

**Review by tianleiwu — APPROVED** [review]

**Comment by tianleiwu** [comment]
Suggest to add some tests to avoid similar errors in the future.

**Pull request merged**
