### PR TITLE
Register signal ops for op set 17.

### PR DESCRIPTION
**Pull request by garymm**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#11733 Register signal ops for op set 17.**
* #11734 clang-format signal_defs.cc

Also:
* de-duplicate get_scalar_value_from_tensor
* fix some bugs that caused compilation errors with the experimental
  ops. Tested with `build.sh --ms_experimental`

### CODE REVIEW

**Comment by snnn** [comment]
@smk2007 we have a special build arg, "--ms_experimental", for enabling the audio ops. Does it mean that after this change we can remove the build arg from build.py?

**Comment by smk2007** [comment]
I think we should keep it for when microsoft needs to make experimental contrib op additions that are specific to the winml package. After this change i think it should persist until we are certain that we can deprecate, and customers have moved to onnx 1.12 audio ops.

---
In reply to: [1146453095](https://github.com/microsoft/onnxruntime/pull/11733#issuecomment-1146453095) [](http://example.com/codeflow?ancestors=1146453095,1146453095)

**Comment by smk2007** [comment]
>  public:

These need to be ported over as well, like the dft and other ops. They have been added to 1.12.

---
Refers to: onnxruntime/contrib_ops/cpu/signal/window_functions.h:26 in 74dffcd. [](commit_id = 74dffcd3b5e3542902510f7fe3e8b316241bbc1a, deletion_comment = False)

**Comment by smk2007** [comment]
>  public:

Or is the intention to keep them as functions? Seems like these implementations would be faster..

---
In reply to: [1146478057](https://github.com/microsoft/onnxruntime/pull/11733#issuecomment-1146478057) [](http://example.com/codeflow?ancestors=1146478057)

---
Refers to: onnxruntime/contrib_ops/cpu/signal/window_functions.h:26 in 74dffcd. [](commit_id = 74dffcd3b5e3542902510f7fe3e8b316241bbc1a, deletion_comment = False)

**Comment by snnn** [comment]
> I think we should keep it for when microsoft needs to make experimental contrib op additions that are specific to the winml package. After this change i think it should persist until we are certain that we can deprecate, and customers have moved to onnx 1.12 audio ops.
> 

Then forever we would have the needs that someone wants an op that is in WindowsAI package but not in the macOS packages we provide.  When the customer comes to us, then what should we do?

**Comment by smk2007** [comment]
> > I think we should keep it for when microsoft needs to make experimental contrib op additions that are specific to the winml package. After this change i think it should persist until we are certain that we can deprecate, and customers have moved to onnx 1.12 audio ops.
> 
> Then forever we would have the needs that someone wants an op that is in WindowsAI package but not in the macOS packages we provide. When the customer comes to us, then what should we do?

I believe that this namespace will be useful for platform specific (and or dependent) efforts, and will allow us to react to windows customers quickly. For cases where operators should truly be x-plat, i believe we would then begin the process to upstream them to onnx like we did with these audio ops.

**Comment by snnn** [comment]
> I believe that this namespace will be useful for platform specific (and or dependent) efforts, and will allow us to react to windows customers quickly. For cases where operators should truly be x-plat, i believe we would then begin the process to upstream them to onnx like we did with these audio ops.

Then the customer will need to wait a few months. Wait ONNX having a new release, then wait ORT to pick up the release tag.  For the audio ops, it took one year. Is it ok?

**Comment by smk2007** [comment]
IIRC we dont want to add contrib ops widely, so wouldnt x-plat folks have to go through that pain anyway right?

---
In reply to: [1146482654](https://github.com/microsoft/onnxruntime/pull/11733#issuecomment-1146482654) [](http://example.com/codeflow?ancestors=1146482654,1146482654)

**Review by smk2007 — APPROVED** [review]

**Comment by garymm** [comment]
Switching to https://github.com/microsoft/onnxruntime/pull/11778, sorry for the noise.

**Pull request closed without merging**
