### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

Update CODEOWNERS, mainly because the one in master branch has invalid aliases.   People come and go in life and that's ok because nothing lasts forever.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by pranavsharma — APPROVED** [review]

**Comment by edgchen1** [comment]
Should we consider using teams instead?
https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams

**Comment by snnn** [comment]
> Should we consider using teams instead? https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams

Good suggestion!  I don't have admin privileges. You may propose it to Faith or Pranav.

**Comment by faxu** [comment]
We could create these, but does it have different read/write/access permissions or is just as FYI for code area ownership? 
If the latter, it's the same overhead as maintaining a text file. I would actually suggest moving this to the [wiki](https://github.com/microsoft/onnxruntime/wiki) so you don't need to run CI for changes.

**Comment by edgchen1** [comment]
> We could create these, but does it have different read/write/access permissions or is just as FYI for code area ownership? If the latter, it's the same overhead as maintaining a text file. I would actually suggest moving this to the [wiki](https://github.com/microsoft/onnxruntime/wiki) so you don't need to run CI for changes.

It is more than just FYI. It controls the required reviewers for owned files.
More info here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by snnn** [comment]
I think we should make good use of the OWNER file. Because in this project different developers quickly tend to specialize or have deep knowledge about certain portions of the code. We want to make sure every code change is reviewed by the right people. For example, I'm not the right people to review training related changes. I can make comments or approve such changes, but they also should get an approval from the people who know the component most.

**Pull request merged**
