### PR TITLE
[WebNN EP] Make some types clearer

### PR DESCRIPTION
**Pull request by Honry**
It's a follow-up to address comments in https://github.com/microsoft/onnxruntime/pull/16671#discussion_r1261761828 and https://github.com/microsoft/onnxruntime/pull/16671#discussion_r1261763873

### CODE REVIEW

**Comment by Honry** [comment]
@fdwr, @guschmue, PTAL, thanks!

**Review by fdwr — APPROVED** [review]
👍

**Comment by fdwr** [comment]
> An unexpected error occurred while trying to download the package.

🤷‍♂️ Rerunning.

/azp run orttraining-linux-ci-pipeline

**Pull request merged**
