### PR TITLE
[WebNN EP] Support latest WebNN softmax op

### PR DESCRIPTION
**Pull request by Honry**
Latest WebNN softmax supports N-D input and axis parameter.

### CODE REVIEW

**Comment by Honry** [comment]
This PR depends on Chromium's change at https://chromium-review.googlesource.com/c/chromium/src/+/5495877, please do not merge it until the CL is landed in Chromium.

@guschmue, @fs-eire, will we have ORT 1.18.x release? This spec change is an API breaking, we will keep both APIs (old and new) in Chromium for a while, but we still hope to cherry pick it to the `1.18.x` branch if it exists to unblock users from using `^1.18.0`.

cc/ @fdwr, @huningxin, @miaobin

**Review by guschmue — DISMISSED** [review]

**Comment by Honry** [comment]
> @guschmue, @fs-eire, will we have ORT-Web 1.18.x release? This spec change is an API breaking, we will keep both APIs (old and new) in Chromium for a while, but we still hope to cherry pick it to the `1.18.x` branch if it exists to unblock users from using `^1.18.0`.

@guschmue, @fs-eire, @fdwr, friendly ping.

**Comment by guschmue** [comment]
there will be a 1.18 patch release but include we might be past cutoff - I need to check.

**Comment by guschmue** [comment]
btw, this PR is stalled on missing docs update.

**Comment by Honry** [comment]
> there will be a 1.18 patch release but include we might be past cutoff - I need to check.

@guschmue, thanks! Chromium will not keep both APIs for long time (might be within 4 weeks), now only ort-web could help mitigate this kind of API breaking. Hopefully it's not too late.  

cc/ @huningxin

> btw, this PR is stalled on missing docs update.
@guschmue, I am going to fix it.

**Comment by guschmue** [comment]
they are waiting for some other PR so we might be able to get this one in tomorrow after it is merged.

**Comment by Honry** [comment]
> they are waiting for some other PR so we might be able to get this one in tomorrow after it is merged.

That's really cool, thank you so much!

I've fixed the doc conflict. PTAL.

**Review by guschmue — APPROVED** [review]

**Review by fdwr — COMMENTED** [review]
@honry Thank you for updating this consistently with the browser.

**Pull request merged**
