### PR TITLE
Revert "[WebNN EP] Remove NHWC preferred layout"

### PR DESCRIPTION
**Pull request by Honry**
Reverts microsoft/onnxruntime#21570

### CODE REVIEW

**Comment by Honry** [comment]
@guschmue, as we discussed in https://github.com/microsoft/onnxruntime/pull/21570#discussion_r1705179216, the original PR will introduce performance regression, we should not accept it. 

Please help review and merge this revert PR.

+ @fdwr

**Review by fdwr — APPROVED** [review]

**Pull request merged**
