### PR TITLE
Fix issues for Whisper export with beam search

### PR DESCRIPTION
**Pull request by kunal-vaishnavi**
### Description
This PR fixes an issue with calling the ORT transformer optimizer script on the custom export of Whisper with beam search. It also includes the [fix](https://github.com/microsoft/onnxruntime/pull/15616) for the GPU out-of-memory issue.

### Motivation and Context
With this PR fix, the optimizer runs as described in the [Whisper model optimization PR](https://github.com/microsoft/onnxruntime/pull/15473).

### CODE REVIEW

**Review by yufenglee — APPROVED** [review]

**Comment by kunal-vaishnavi** [comment]
Thank you for specifying the steps you followed. 
> ```
> ├── whisper-tiny_beamsearch.onnx
> ├── whisper-tiny_beamsearch.onnx.data
> ├── whisper-tiny_decoder.onnx
> ├── whisper-tiny_decoder.onnx.data
> ├── whisper-tiny_encoder_decoder_init.onnx
> └── whisper-tiny_encoder_decoder_init.onnx.data
> ```
Optimum exports Whisper as three models: encoder, decoder, and decoder with past. This custom export creates one combined model, `whisper-tiny_beamsearch.onnx`, with two subgraphs, `whisper-tiny_encoder_decoder_init.onnx` and `whisper-tiny_decoder.onnx`, that are chained together with beam search logic. The combined model can then run in ONNX Runtime directly.

> ```
> model = ORTModelForSpeechSeq2Seq.from_pretrained(
>     "whispertiny/openai",
>     use_io_binding=(device == 'cuda'),
>     provider='CPUExecutionProvider',
> ).to(device)
> ```
Optimum expects separate encoder, decoder, and decoder with past models as well as several JSON files to be located within `whispertiny/openai`. This custom export produces one combined model so it will not load in Optimum.

### Optimum + ONNX Runtime

You can export Whisper using Optimum and save the generated models.
```
from optimum.onnxruntime import ORTModelForSpeechSeq2Seq

model = ORTModelForSpeechSeq2Seq.from_pretrained('openai/whisper-tiny', from_transformers=True)
model.save_pretrained('whisper_tiny')
```

Then you can optimize and run Whisper with Optimum + ONNX Runtime by following the example in the PR linked above.

**Comment by shub-kris** [comment]
Thanks @kunal-vaishnavi , giving it a try

**Comment by shub-kris** [comment]
I am trying this, it works but have confusion regarding the `attention_mask`

```
from datasets import load_dataset
from transformers import AutoProcessor
import onnx
import onnxruntime as ort
import numpy as np
import sys
import time

model_path, model_id = "whisper-tiny_beamsearch.onnx", "openai/whisper-tiny"
ds = load_dataset("hf-internal-testing/librispeech_asr_dummy", "clean", split="validation")
# ds = ds.select([i for i in range(600)])
processor = AutoProcessor.from_pretrained(model_id)
ort_sess = ort.InferenceSession(model_path, provider="CPUExecutionProvider")

## warmup
for _ in range(10):
    inputs = processor.feature_extractor(ds[0]["audio"]["array"], return_tensors="np",
                                         sampling_rate=16000,
                                         return_attention_mask=True)
    # input_features = inputs['input_features'].cpu().numpy()
    # attention_mask = inputs['attention_mask'].cpu().numpy()
    attention_mask = np.tile(inputs['attention_mask'], (1, inputs['input_features'].shape[1], 1))
    
    outputs = ort_sess.run(None, {'input_features': inputs['input_features'], 
                              'max_length': [50],
                             'num_beams': [1],
                             'min_length': [50], 
                              'num_return_sequences': [1], 
                              'length_penalty': [1.0], 
                              'repetition_penalty': [1.0], 
                              'attention_mask': attention_mask                           
                             })


```

**Comment by kunal-vaishnavi** [comment]
> I am trying this, it works but have confusion regarding the `attention_mask`

We are planning to remove the `attention_mask` input since it is not used in Whisper. You can set any values for now until the `attention_mask` input is removed.

In your above example, you can use Hugging Face's `processor.batch_decode` method after obtaining the outputs from ORT.
```
outputs = sess.run(None, inputs)[0]

decoded = []
for b in range(batch_size):
    for r in range(num_return_sequences):
        torch_outputs = torch.from_numpy(outputs[b][r])
        decoded.append(processor.batch_decode(torch_outputs, skip_special_tokens=True)[0])

print(decoded)
```

**Comment by shub-kris** [comment]
Thanks a lot @kunal-vaishnavi for your help.

**Pull request merged**
