### PR TITLE
Enable WebAssembly SIMD build

### PR DESCRIPTION
**Pull request by chun137**
Add a build switch "--enable_wasm_simd" to enable
WebAssembly SIMD build

### CODE REVIEW

**Comment by fs-eire** [comment]
Thank you for your contribution! In order to support different browsers in onnxruntime-web, we planned to have different file names for those .wasm artifacts:

ort-wasm.wasm
ort-wasm-threaded.wasm
ort-wasm-simd.wasm
ort-wasm-simd-threaded.wasm

To do this, we need to modify SIMD build's EXPORT_NAME and target OUTPUT_NAME for wasm build in cmake file:
https://github.com/microsoft/onnxruntime/blob/master/cmake/onnxruntime_webassembly.cmake#L62-L68

**Review by hanbitmyths — CHANGES_REQUESTED** [review]
Thanks for your contribution to ONNX Runtime Web. Please, resolve a comment from fs-eire.

Also, note that we have a known issue on WebAssembly SIMD like an output mismatch. We'll investigate issues after 1.8 release.

**Comment by chun137** [comment]
@fs-eire Thanks for the review, The .wasm names were updated. I'll update wasm-factory.ts to support simd wasm with a new PR.

**Comment by hanbitmyths** [comment]
azp run orttraining-linux-ci-pipeline,orttraining-mac-ci-pipeline,orttraining-linux-gpu-ci-pipeline,centos7_cpu,Linux CPU Minimal Build E2E CI Pipeline,Linux Nuphar CI Pipeline,MacOS NoContribops CI Pipeline,Linux OpenVINO CI Pipeline,orttraining-distributed, orttraining-amd-gpu-ci-pipeline

**Review by hanbitmyths — APPROVED** [review]

**Pull request merged**
