### PR TITLE
Openvino ep ort 5.0

### PR DESCRIPTION
**Pull request by sfatimar**
### Description
The PR adds VPU support to OpenVINO Execution Provider
Bug fixes for GPU, CPU. 
Changes to OpenVINO Backend in Serialized Model API for faster First Inference Latency. 
Deprecation to HDDL-VADM and MYRIAD, removed code
Support OpenVINO 2023.0 
Dynamic Shapes Support for iGPU

### Motivation and Context
- VPU is an upcoming hardware that can provide AI Acceleration for Client Systems through OpenVINO
- If it fixes an open issue, please link to the issue here. -->

### CODE REVIEW

**Comment by sfatimar** [comment]
@jywu-msft Please review PR for support to OpenVINO 2023.0

**Comment by jywu-msft** [comment]
it says there are branch conflicts ?

"This branch has conflicts that must be resolved
 to resolve conflicts before continuing" but it's strange it doesn't list the conflicting files.

**Comment by sfatimar** [comment]
> it says there are branch conflicts ?
> 
> "This branch has conflicts that must be resolved to resolve conflicts before continuing" but it's strange it doesn't list the conflicting files.

conflicts are resolved

**Comment by jywu-msft** [comment]
> > it says there are branch conflicts ?
> > "This branch has conflicts that must be resolved to resolve conflicts before continuing" but it's strange it doesn't list the conflicting files.
> 
> conflicts are resolved

can you fix the python lint issues https://github.com/microsoft/onnxruntime/actions/runs/4766689596/jobs/8474732669?pr=15626
before i kick off the other ci's?

**Comment by MaajidKhan** [comment]
> > > it says there are branch conflicts ?
> > > "This branch has conflicts that must be resolved to resolve conflicts before continuing" but it's strange it doesn't list the conflicting files.
> > 
> > 
> > conflicts are resolved
> 
> can you fix the python lint issues https://github.com/microsoft/onnxruntime/actions/runs/4766689596/jobs/8474732669?pr=15626 before i kick off the other ci's?

Hi George. The conflicts should now be resolved. Can you trigger the pipelines now.

**Comment by jywu-msft** [comment]
can you fix the lint issues? https://github.com/microsoft/onnxruntime/actions/runs/4783837131/jobs/8514986001?pr=15626

**Comment by MaajidKhan** [comment]
> can you fix the lint issues? https://github.com/microsoft/onnxruntime/actions/runs/4783837131/jobs/8514986001?pr=15626

Added a patch using LintRunner to fix all CPP/Python code formatting issues.

**Instructions:**
https://github.com/microsoft/onnxruntime/blob/
main/docs/Coding_Conventions_and_Standards.md#linting

Verified locally in intel fork PR this time and made sure **Lint / Python format (pull_request)**  pipeline is now passing with the new fixes.
https://github.com/intel/onnxruntime/pull/294

image

Also rebased the branch to be in sync with MSFT master.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
