### PR TITLE
Fix build error about `if` being constant in Eigen and Protobuf

### PR DESCRIPTION
**Pull request by fdwr**
**Description**: A number of us repro a build failure with today's master (Ashwini, Sumit, Xiang, me...) in protobuf and Eigen. I'm unsure why the official build passes, and why it doesn't always repro (CMake version possibly? Visual Studio version differences?), but it's a silly warning treated as error anyway, in codebases that we don't own:

```
warning C4127: conditional expression is constant
error C2220: warning treated as error
protobuf/stubs/strutil.h(364,36): message: consider using 'if constexpr' statement instead
```

**Motivation and Context**
- Why is this change required? What problem does it solve? Build error
- If it fixes an open issue, please link to the issue here. NA

### CODE REVIEW

**Review by zhangxiang1993 — DISMISSED** [review]
:shipit:

**Review by snnn — CHANGES_REQUESTED** [review]
Let me take a look

**Comment by snnn** [comment]
Which cmake version do you use?

**Comment by fdwr** [comment]
> Which cmake version and VS version do you use? Could you please try the latest? Our build servers use cmake 3.20.5 and the latest VS 2019.

@snnn: I'm happy to try the *very* latest too, but even then, we should support versions that are a *little* bit older, and my versions are not even that old 🤔:

2021-05-27 MLRuntime.CMake.3.20.3
2021-06-09 Microsoft Visual Studio Professional 2019 Version 16.9.7

Btw, the Linux CI pipeline issue appears unrelated:

```
  1) E2E Tests - InferenceSession.run()
       multiple run() calls:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/onnxruntime_src/js/node/test/test-main.js)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by snnn** [comment]
Then I think the error was because: " In versions of Visual Studio before Visual Studio 2019 version 16.10, the /external options require you also set the /experimental:external compiler option." from: https://docs.microsoft.com/en-us/cpp/build/reference/external-external-headers-diagnostics?view=msvc-160

Instead of disable warning 4127, We can add "/experimental:external" to https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L501 .

But, I guess you will be required to update your VS to 16.10 soon(in a few weeks).

**Comment by fdwr** [comment]
> Instead of disable warning 4127, We can add "/experimental:external" to https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L501 .

@snnn : Sounds good - updated.

**Review by snnn — APPROVED** [review]

**Pull request merged**
