### PR TITLE
Softmax interface update

### PR DESCRIPTION
**Pull request by groenenboomj**
Remove usage of valid_items interface and remove unnecessary casts

This closes a performance gap on the ROCm EP.  The valid_items interface uses a less ideal
implementation than the interface without it's usage and the masking in the kernel makes it's
usage unnecessary. Also removes casts that were not needed and moved hipCUB to using a
templated datatype.

### CODE REVIEW

**Comment by tianleiwu** [comment]
I believe that this change will cause accuracy loss. Applying similar change to CUDA EP showing that top1_match_rate drops significantly (from 99.7% to 98.8%):
```
onnxruntime/python/tools/transformers/models/gpt2$ python convert_to_onnx.py -m distilgpt2 -p fp16 -a --use_gpu -o --output gpt2.onnx
```

**Comment by groenenboomj** [comment]
I've ran that test with different results and would be glad to replicate them.  How many samples was the drop seen over?  I have seen the output of that test give variable accuracy in the past.

In any case is the concern the casting or the removal of valid_items?

**Comment by groenenboomj** [comment]
With the last patch I rolled back the rest of the casting changes. We do lose a little performance this way but it should address the discussed concerns about the PR.

**Review by tianleiwu — APPROVED** [review]

**Review by zhangyaobit — APPROVED** [review]

**Comment by ytaous** [comment]
@groenenboomj - pls take a look at failed tests. thx

**Pull request merged**
