### PR TITLE
Remove all warnings C4800: Implicit conversion from 'int32_t/int64_t' to bool. Possible information loss

### PR DESCRIPTION
**Pull request by gineshidalgo99**
**Description**: Describe your changes.
Updated OperatorHelper.h, loop.cc, matmul.cc, reduction_ops.cc, deep_cpu_gru.cc, and rnn_helpers.cc to remove all warnings C4800: Implicit conversion from 'int32_t/int64_t' to bool. Possible information loss

**Motivation and Context**
- Why is this change required? What problem does it solve? In more strict compilers, this warning is triggered when compiling ORT from source.

### CODE REVIEW

**Comment by gineshidalgo99** [comment]
Hi @snnn, I fixed the merge conflicts caused by the latest changes in ORT master. Please, feel free to re-run the tests!

**Comment by gineshidalgo99** [comment]
I am very sorry, it seems there was some errors related to the [TensorRT and CUDA tests themselves](https://github.com/microsoft/onnxruntime/pull/9535/checks?check_run_id=4072828039).

My latest commit fixed these 2 files. Hopefully this 3rd test actually gets them all working finally

**Comment by snnn** [comment]
No worries. It's not an easy job. I'm glad I can help.

**Comment by gineshidalgo99** [comment]
It looks like this one can finally be merged? :)

**Review by snnn — APPROVED** [review]
Thank you

**Pull request merged**
