### PR TITLE
remove line "ADD model ${WORKSPACE_DIR}/model" in the amdgpu Dockerfile

### PR DESCRIPTION
**Pull request by jeffdaily**
Follow-up to #12707. docker build is broken otherwise; model dir is gone.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@baijumeswani please merge.

**Comment by jeffdaily** [comment]
@baijumeswani or @weixingzhang please merge.  This is a one line change but it currently is blocking our internal build processes.  Thank you.

**Comment by jeffdaily** [comment]
@baijumeswani or @weixingzhang, another reminder.  Thank you.

@snnn are you able to merge?  The dockerfile is trying to add a directory that does not exist.

**Review by weixingzhang — APPROVED** [review]

**Comment by jeffdaily** [comment]
Failures should have nothing to do with this change.  Can we merge?

**Pull request merged**
