### PR TITLE
Add NonMaxSuppression and RoiAlign to ROCm EP

### PR DESCRIPTION
**Pull request by jeffdaily**
Hipify and register NonMaxSuppression and RoiAlign for ROCm EP.

Requires a new preprocessor elif for the hipcc compiler in the shared cpu header non_max_suppression_helper.h, but otherwise does not modify any CUDA EP files.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@suffiank not sure why there are CUDA CI failures.  Doesn't seem related to the changes in this PR.  This PR does modify `onnxruntime/core/providers/cpu/object_detection/non_max_suppression_helper.h`, but only adds `#elif` conditions.  Transient failures?

**Comment by jeffdaily** [comment]
From the log for orttraining-linux-gpu-ci-pipeline:
```
2021-10-19T17:44:47.0708859Z 1: [ RUN      ] ModelTests/ModelTest.Run/5831
2021-10-19T17:44:47.0741415Z 1: /onnxruntime_src/onnxruntime/test/providers/cpu/model_tests.cc:696: Failure
2021-10-19T17:44:47.0742128Z 1: Expected equality of these values:
2021-10-19T17:44:47.0742675Z 1:   COMPARE_RESULT::SUCCESS
2021-10-19T17:44:47.0743938Z 1:     Which is: 4-byte object <00-00 00-00>
2021-10-19T17:44:47.0744569Z 1:   ret.first
2021-10-19T17:44:47.0745363Z 1:     Which is: 4-byte object <01-00 00-00>
2021-10-19T17:44:47.0746313Z 1: expected 1.85174 (3fed05ac), got nan (7fffffff), diff: nan, tol=0.00285174 idx=0. 20 of 120 differ
2021-10-19T17:44:47.0752020Z 1: [  FAILED  ] ModelTests/ModelTest.Run/5831, where GetParam() = "cuda_/data/onnx/onnx150/node/test_instancenorm_epsilon/model.onnx" (4 ms)
```

**Comment by suffiank** [comment]
@jeffdaily I resubmitted the failed CI. Also for any newly registered operators, can you confirm the associated unit tests ran on ROCm?

**Comment by jeffdaily** [comment]
> @jeffdaily I resubmitted the failed CI. Also for any newly registered operators, can you confirm the associated unit tests ran on ROCm?

https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=515349&view=logs&j=48b14a85-ff1a-5ca4-53fa-8ea420d27feb&t=e882c4fa-e626-5790-579a-99f25f8389cd&l=5191

All 19 out of 19 tests from NonMaxSuppressionOpTest used the new op.

https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=515349&view=logs&j=48b14a85-ff1a-5ca4-53fa-8ea420d27feb&t=e882c4fa-e626-5790-579a-99f25f8389cd&l=5236

4 out of 8 tests from RoiAlignTest used the new op.

**Pull request merged**
