### PR TITLE
[TensorRT EP] Enable a minimal CUDA EP compilation without kernels 

### PR DESCRIPTION
**Pull request by gedoensmax**
Adresses https://github.com/microsoft/onnxruntime/issues/18542.
I followed the advice given by @RyanUnderhill [here](https://github.com/microsoft/onnxruntime/pull/18731#issuecomment-1848261925) and went with a minimal CUDA EP for now.

### CODE REVIEW

**Comment by tianleiwu** [comment]
@gedoensmax,

What's the example build command line to use this? 

I tried the following but there is build error:
```
export CUDA_HOME=/usr/local/cuda-12.2
export CUDNN_HOME=/usr/lib/x86_64-linux-gnu/
export CUDACXX=/usr/local/cuda-12.2/bin/nvcc
export TRT_HOME=/usr/src/tensorrt

sh build.sh --config Release  --build_shared_lib --parallel --cuda_version 12.2 \
            --cuda_home $CUDA_HOME --cudnn_home $CUDNN_HOME --build_wheel --skip_tests \
            --use_tensorrt --tensorrt_home $TRT_HOME \
            --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF \
            --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=80 \
            --cmake_extra_defines onnxruntime_CUDA_MINIMAL=ON
```

**Comment by gedoensmax** [comment]
@tianleiwu I believe you are missing `--use_cuda` and I also use `onnxruntime_DISABLE_CONTRIB_OPS=ON`. To be honest I always build using cmake directly, but I can try tomorrow with the build script.

**Comment by gedoensmax** [comment]
Ok I could not hold back to try. I verified that this works on my end:
```
./build.sh --config Release  --build_shared_lib --parallel --cuda_version 12.2 \
            --cuda_home $CUDA_HOME --cudnn_home $CUDNN_HOME --build_wheel --skip_tests \
            --use_tensorrt --tensorrt_home $TRT_HOME \
            --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF \
            --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=89 \
            --cmake_extra_defines onnxruntime_CUDA_MINIMAL=ON \
            --cmake_extra_defines onnxruntime_DISABLE_CONTRIB_OPS=ON \
            --build_dir build_script
```

**Comment by tianleiwu** [comment]
@gedoensmax, I tried your build command, and it works before the last merge commit, but failed after the merge:
```
onnxruntime/onnxruntime/core/providers/cuda/cuda_stream_handle.cc:59:1: error: no declaration matches ‘onnxruntime::CudaStream::CudaStream(cudaStream_t, const OrtDevice&, onnxruntime::AllocatorPtr, bool, bool, cudnnHandle_t, cublasHandle_t)’
   59 | CudaStream::CudaStream(cudaStream_t stream,
      | ^~~~~~~~~~
```

**Comment by gedoensmax** [comment]
Sorry the webui (or me using it) must have messed this up.

**Review by tianleiwu — APPROVED** [review]

**Pull request merged**
