### PR TITLE
[ORT 1.17.0 Release] Cherry pick 1st round

### PR DESCRIPTION
**Pull request by YUNQIUGUO**
### Description

[ORT 1.17.0 Release] Cherry pick 1st round

PR authors please take a look, and let me know if there are any questions about the changes or approve accordingly.

### CODE REVIEW

**Comment by YUNQIUGUO** [comment]
For external prs, I requested review from the code reviewers. thanks.

**Review by yufenglee — APPROVED** [review]
LGTM for the x64 kernel

**Review by kunal-vaishnavi — DISMISSED** [review]

**Review by yf711 — APPROVED** [review]

**Review by adrianlizarraga — DISMISSED** [review]

**Review by baijumeswani — DISMISSED** [review]

**Review by snnn — APPROVED** [review]

**Review by tianleiwu — APPROVED** [review]

**Review by wejoncy — DISMISSED** [review]

**Review by fs-eire — APPROVED** [review]

**Review by wangyems — APPROVED** [review]

**Review by xadupre — APPROVED** [review]

**Review by tianleiwu — DISMISSED** [review]

**Comment by snnn** [comment]
I suggest holding off it a moment, since this PR will add a new dependency, neural-speed, to ONNX Runtime. I have some concerns to it. I've just sent an email to the author who added this component, and another email to a few PMs to discuss it.  I do not have any objection on adding the dependency, but there are some details that need to be figured out. Please give me a few days to complete the work.

**Comment by YUNQIUGUO** [comment]
> I suggest holding off it a moment, since this PR will add a new dependency, neural-speed, to ONNX Runtime. I have some concerns to it. I've just sent an email to the author who added this component, and another email to a few PMs to discuss it. I do not have any objection on adding the dependency, but there are some details that need to be figured out. Please give me a few days to complete the work.

ok, noticed.

**Review by snnn — APPROVED** [review]

**Review by pranavsharma — APPROVED** [review]

**Review by yufenglee — APPROVED** [review]

**Review by adrianlizarraga — APPROVED** [review]

**Review by yf711 — APPROVED** [review]

**Review by tianleiwu — APPROVED** [review]

**Review by kunal-vaishnavi — APPROVED** [review]

**Review by baijumeswani — APPROVED** [review]

**Review by wangyems — APPROVED** [review]

**Pull request merged**
