### PR TITLE
Add TensorRT library suffix for Windows

### PR DESCRIPTION
**Pull request by kevinch-nv**
### Description

In TensorRT 10, Windows libraries have the major version appended to them. Update build system to use correct library name on Windows and other platforms.

### CODE REVIEW

**Comment by jywu-msft** [comment]
see https://github.com/microsoft/onnxruntime/pull/20445

**Comment by kevinch-nv** [comment]
Closing in favor of https://github.com/microsoft/onnxruntime/pull/20445/files

**Pull request closed without merging**
