### PR TITLE
onnx_proto should be build as `.so` when `onnxruntime_BUILD_SHARED_LIB` is set.

### PR DESCRIPTION
**Pull request by xkszltl**
When tensorrt provider is moved to its own shared lib, static onnx-ml.pb.cc will causes duplicated `descriptor_table_onnx_2fonnx_2dml_2eproto` in both (main/provider) libs with re-registration.

### CODE REVIEW

**Comment by snnn** [comment]
We would rather take the change for ONNX upstream instead of patching it here.  The official ONNX python package should be built in the same way , otherwise this PR will cause conflict between ONNX Runtime python package and ONNX python package, which we don't want to see.

**Comment by xkszltl** [comment]
What do you mean by "build in the same way"?
`BUILD_SHARED_LIBS` is configurable in onnx repo, so it really up to the final user to decide how to set it.

Regarding "official package", I recommend dual build to ship both `.so` and `.a` together, so the decision can be made a link time of downstream.
Regarding "official python package", usually python package should not have `.a` right?

**Comment by xkszltl** [comment]
BTW if you plan to do something in onnx repo, I recommend to merge this first before you have solution ready.

**Comment by snnn** [comment]
> What do you mean by "build in the same way"?

If you think onnx_proto should be build as `.so` , then please tell **ONNX team** to do so in their official builds, not us.  ONNX is community driven, they have weekly meeting that opens to public. You may raise this issue to the ONNX community and ask their opinions.  You can join their zoom session and directly talk to them, they would be happy to listen to you. They absolutely want more people get involved. 

"build in the same way" means by your suggestion every one should dynamic link to onnx_proto instead of having a private copy inside of their own package.  If ONNX community decides to take the move, I'm happy to follow them.

**Comment by xkszltl** [comment]
> If you think onnx_proto should be build as .so , then please tell ONNX team to do so in their official builds, not us.

Aha good to get some clarity on that.
I used to think onnx and ort are handled by different teams, but keep hearing people refer to you as onnx team...

**Comment by tianleiwu** [comment]
close this for now according to comments.

**Pull request closed without merging**
