### PR TITLE
Unconditionally re-enable /W4 on Windows and fix warnings which showed up

### PR DESCRIPTION
**Pull request by mtavenrath**
### Description
I've set the compiler warning level for msvc back to /W4 for the CUDA backend to ensure better pre-commit testing and fixed the warnings in the core onnxruntime & CUDA EP which showed up after this change.

### Motivation and Context
The warning level on gcc/clang is higher than the one on MSVC when enabling the CUDA backend resulting in CI potential failures when filing a PR developed on Windows. Increase the warning level to have more overlap in warnings between MSVC and gcc/clang.

fix issue #19565

### CODE REVIEW

**Comment by mtavenrath** [comment]
When doing this change I had CUDA warnings disabled. Moving to /W4 without CUDA warnigns disabled opens a lot of new warnings, especially in CUTLASS. Closing for now until warning related issues are solved in CUTLASS:

**Comment by skottmckay** [comment]
Could we call set_msvc_c_cpp_compiler_warning_level from onnxruntime_providers_cuda.cmake to set to 3 and the start and back to 4 at the end to minimize the code compiled with /W3? maybe we could just do that around the `include(cutlass)`.

**Pull request closed without merging**
