### PR TITLE
[ROCm] add migraphx into onnxruntime-training-rocm package

### PR DESCRIPTION
**Pull request by PeixuanZuo**

### CODE REVIEW

**Comment by TedThemistokleous** [comment]
Is it possible to add also add an onnxruntime-rocm with just the ROCm EP and MIGraphX EP outside of training (focus on Inference). That would mirror the similar functionality that we see with onnxruntime-gpu packages for Nvidia solutions. ping @jeffdaily @jeffdaily-ms

**Comment by snnn** [comment]
@mszhanyi , please help review.

**Comment by PeixuanZuo** [comment]
> Is it possible to add also add an onnxruntime-rocm with just the ROCm EP and MIGraphX EP outside of training (focus on Inference)? That would mirror the similar functionality that we see with onnxruntime-gpu packages for Nvidia solutions. ping @jeffdaily @jeffdaily-ms

Currently we only maintain one training package for ROCm EP.

**Comment by TedThemistokleous** [comment]
> > Is it possible to add also add an onnxruntime-rocm with just the ROCm EP and MIGraphX EP outside of training (focus on Inference)? That would mirror the similar functionality that we see with onnxruntime-gpu packages for Nvidia solutions. ping @jeffdaily @jeffdaily-ms
> 
> Currently we only maintain one training package for ROCm EP.

I understand that, but for solely inference I don't think we need all the training infrastructure do we? The intent would be to have another build of just ROCm EP and MIGraphX EP for inference applications.

**Comment by zhangyaobit** [comment]
Can we remove the training from the name? The intention is to have the same package for both training and inference with minimal maintenance overhead. The package size increase (with training) is only marginally bigger. If there is a compelling reason for a separate inference package, we can also consider it.

**Comment by jeffdaily** [comment]
> Can we remove "training" from the package name to avoid confusion? The intention is to have the same package for both training and inference with minimal maintenance overhead. The package size increase (with training) is only marginal. If there is a compelling reason for a separate inference package, we can also consider it.

Ultimately we want parity with CUDA offerings.  When you go to https://onnxruntime.ai/getting-started, there are two main tabs "Optimize Inferencing" and "Optimize Training".  

For CUDA:
- Inferencing+Linux+Python+X64+[CUDA or TensorRT] --> `pip install onnxruntime-gpu`.  This package is hosted on pypi.  
- Training+Large Model Training+Linux+Python+CUDA 11.8+Stable --> `pip install -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT/pypi/simple/ onnxruntime-training`

For ROCM:
- Inferencing+Linux+Python+X64+[ROCM or MIGRAPHX] --> build from source
- Training+Large Model Training+Linux+Python+ROCM+Stable --> `pip install onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_stable_<rocm_version*>.html`

Ideally we would like to see package offering parity between CUDA and ROCm.  That would mean a pypi package called 'onnxruntime-rocm' that would include rocm and migraphx EPs.  It is unclear to me whether the onnxruntime-training package for CUDA includes TensorRT EP too?

In the short term I would be okay with putting migraphx into the onnxruntime-training package for rocm, but in that case we would also need to update the "Inferencing" tab to indicate we have a wheel available for both ROCM and MIGRAPHX.  Long term, we'd like package parity.

**Comment by PeixuanZuo** [comment]
> > Can we remove "training" from the package name to avoid confusion? The intention is to have the same package for both training and inference with minimal maintenance overhead. The package size increase (with training) is only marginal. If there is a compelling reason for a separate inference package, we can also consider it.
> 
> Ultimately we want parity with CUDA offerings. When you go to https://onnxruntime.ai/getting-started, there are two main tabs "Optimize Inferencing" and "Optimize Training".
> 
> For CUDA:
> 
> * Inferencing+Linux+Python+X64+[CUDA or TensorRT] --> `pip install onnxruntime-gpu`.  This package is hosted on pypi.
> * Training+Large Model Training+Linux+Python+CUDA 11.8+Stable --> `pip install -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT/pypi/simple/ onnxruntime-training`
> 
> For ROCM:
> 
> * Inferencing+Linux+Python+X64+[ROCM or MIGRAPHX] --> build from source
> * Training+Large Model Training+Linux+Python+ROCM+Stable --> `pip install onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_stable_<rocm_version*>.html`
> 
> Ideally we would like to see package offering parity between CUDA and ROCm. That would mean a pypi package called 'onnxruntime-rocm' that would include rocm and migraphx EPs. It is unclear to me whether the onnxruntime-training package for CUDA includes TensorRT EP too?
> 
> In the short term I would be okay with putting migraphx into the onnxruntime-training package for rocm, but in that case we would also need to update the "Inferencing" tab to indicate we have a wheel available for both ROCM and MIGRAPHX. Long term, we'd like package parity.

We will update the doc to indicate we both have ROCm and MIGraphX EP.

**Review by mszhanyi — APPROVED** [review]

**Comment by TedThemistokleous** [comment]
> > > Can we remove "training" from the package name to avoid confusion? The intention is to have the same package for both training and inference with minimal maintenance overhead. The package size increase (with training) is only marginal. If there is a compelling reason for a separate inference package, we can also consider it.
> > 
> > 
> > Ultimately we want parity with CUDA offerings. When you go to https://onnxruntime.ai/getting-started, there are two main tabs "Optimize Inferencing" and "Optimize Training".
> > For CUDA:
> > 
> > * Inferencing+Linux+Python+X64+[CUDA or TensorRT] --> `pip install onnxruntime-gpu`.  This package is hosted on pypi.
> > * Training+Large Model Training+Linux+Python+CUDA 11.8+Stable --> `pip install -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT/pypi/simple/ onnxruntime-training`
> > 
> > For ROCM:
> > 
> > * Inferencing+Linux+Python+X64+[ROCM or MIGRAPHX] --> build from source
> > * Training+Large Model Training+Linux+Python+ROCM+Stable --> `pip install onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_stable_<rocm_version*>.html`
> > 
> > Ideally we would like to see package offering parity between CUDA and ROCm. That would mean a pypi package called 'onnxruntime-rocm' that would include rocm and migraphx EPs. It is unclear to me whether the onnxruntime-training package for CUDA includes TensorRT EP too?
> > In the short term I would be okay with putting migraphx into the onnxruntime-training package for rocm, but in that case we would also need to update the "Inferencing" tab to indicate we have a wheel available for both ROCM and MIGRAPHX. Long term, we'd like package parity.
> 
> We will update the doc to indicate we both have ROCm and MIGraphX EP.

My apologies to the late reply. @PeixuanZuo @snnn @ytaous 

I don't think that's just what @jeffdaily  meant here. We want to have a clear 1:1 offering to what Nvidia has for the AMD ROCm flavor of packages so that a user can simply pip install onnxruntime-rocm and have the proper execution providers to perform inference through the ROCm stack. 

Currently users need to navigate build steps on how to build and deal with ROCm manually with Onnxruntime. For all intensive purposes, we're already begun internally testing and building Onnxruntime wheel files during each of our commits in CI and as part of model inference.

Would you prefer we release and host onnxruntime-rocm related inference wheels then? We're currently leveraging our existing infra for our upcoming release but would be happy to help transition the build/distribution over to Microsoft when we complete. This would also help clear up documentation once we can get things on pypi

Let me, or the other developers (@jeffdaily @groenenboomj  know what you'd like to see.

**Pull request merged**
