### PR TITLE
[js/web] FP16 Conv, ConvTranspose and MatMul

### PR DESCRIPTION
**Pull request by dakenf**
### Description
Another three ops for fp16

### CODE REVIEW

**Review by fs-eire — APPROVED** [review]
looks good to me.

@qjia7 @satyajandhyala please also help to take a look

**Review by qjia7 — APPROVED** [review]
LGTM, thanks!

**Comment by guschmue** [comment]
some lint error (partially my bad - tried to resolve some merge conflict).
Can you help resolve it ?

**Comment by dakenf** [comment]
@guschmue done

**Comment by fs-eire** [comment]
please fix the linting error

**Comment by satyajandhyala** [comment]
@dakenf I wish we knew we both are working on this separately, we could have avoided duplication? 
I have a PR open with almost same name I have been working on it more than a week.

**Review by satyajandhyala — APPROVED** [review]

**Review by guschmue — APPROVED** [review]

**Pull request merged**
