### PR TITLE
[java] Fp16 fix for android/react native

### PR DESCRIPTION
**Pull request by Craigacp**
### Description
This PR splits out the FP16 conversions into a separate package we can override in the android build with a version which works on old versions of Android.

I'm not sure the android build system changes are correct as I haven't got an android build environment configured on my workstation. @YUNQIUGUO if the CI build fails we should follow up offline to get my environment configured so I can iterate on it. 

### Motivation and Context
Fixes the CI failure after #16703.

### CODE REVIEW

**Comment by Craigacp** [comment]
One day I'll remember to run spotless after making small changes before making the commit, but it wasn't today apparently. I've pushed the spotless fixes so those test failures out of the Java side should go away and we'll hit the actual code changes.

**Comment by Craigacp** [comment]
After further consideration I split the Java code into three source roots. The shared code is in `src/main/java`, the Android specific stuff (which at the moment is just the FP16 conversions) is in `src/main/android` and the Java/JVM specific stuff is in `src/main/jvm`. I've tested the Java build and that works, and the Android build seems to be failing at a different point than the React pipeline error that we saw which I think is due to the misconfigured Android build environment I've cobbled together to test it. I'm hopeful that this will work, but it's probably worth running just the react native pipeline and one of the other ones with Java turned on first to make it easier for me to see the failures (which hopefully there won't be).

**Review by skottmckay — APPROVED** [review]

**Review by YUNQIUGUO — APPROVED** [review]
thanks for the fix!

**Pull request merged**
