### PR TITLE
tools: build: fix typo

### PR DESCRIPTION
**Pull request by clementperon**
### Description
Typo in the python build script

### CODE REVIEW

**Comment by tianleiwu** [comment]
Also here:
https://github.com/microsoft/onnxruntime/blob/8f0e896c95eedee624b6a3c375e86e1e4263a980/cmake/adjust_global_compile_flags.cmake#L324

**Comment by clementperon** [comment]
> Also here:
> 
> https://github.com/microsoft/onnxruntime/blob/8f0e896c95eedee624b6a3c375e86e1e4263a980/cmake/adjust_global_compile_flags.cmake#L324

Hi, 

Thanks I only look at CMakeLists.txt, fixed it

**Comment by clementperon** [comment]
@tianleiwu good for you ?

**Review by tianleiwu — APPROVED** [review]

**Pull request merged**
