### PR TITLE
add new types to shape op

### PR DESCRIPTION
**Pull request by RandyShuai**

### CODE REVIEW

**Comment by pranavsharma** [comment]
Is there a bug asking for all the new types you've added? We should be wary of adding new types unless required.

**Comment by RandyShuai** [comment]
Yes - https://aiinfra.visualstudio.com/Lotus/_workitems/edit/2314
requires us to add type for all new types I added there.

**Comment by RandyShuai** [comment]
with AllFixedSizeTensorTypes(), two more types - MLFloat16 and BFloat16 will be included, while the bug only require to add int8/uint32/uint64. So which approach is more advisable - add all the fixed type or add required type on demand?

**Comment by KeDengMS** [comment]
If there's no binary size increase, I'd prefer add all types per spec. Note AllFixedSizeTensorTypes() do not include string, which might be necessary for CPU provider but not CUDA provider.

---
In reply to: [456992941](https://github.com/Microsoft/onnxruntime/pull/362#issuecomment-456992941) [](ancestors = 456992941)

**Comment by pranavsharma** [comment]
Binary size is definitely a concern and as more and more ops are adding additional (sometimes unnecessary) types, it's all adding up. Please keep it to the bare minimum required.

**Comment by KeDengMS** [comment]
From the implementation of this Shape op, which only register one kernel for all types, there should be no binary size increase by adding support to more ops. If we don't fix in this PR, sooner or later we'll have to fix fp16/bfloat16 here...

---
In reply to: [457011646](https://github.com/Microsoft/onnxruntime/pull/362#issuecomment-457011646) [](ancestors = 457011646)

**Comment by RandyShuai** [comment]
With all fixed type included, size is not increasing - it stays at 4,593,664 as compared with version of only required types.

**Pull request merged**
