### PR TITLE
Revert "Introduce ordered quantization ops for the CUDA EP [1/n]

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

This reverts commit ad69aac491fc423fc71484a8c633ef444eec3105.

**Motivation and Context**
- Why is this change required? What problem does it solve?

Has multiple test failures in a daily pipeline.

https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=227166&view=logs&j=afc9dddb-edc9-5102-8103-90776efbd459&t=7872a514-5b8d-5593-45d7-5da6d3ebdbd9

- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by hariharans29** [comment]
Thanks for catching this. Is there a difference in the CUDA Runtime library versions installed on the Windows daily pipeline machines and the Linux daily pipeline machines ? It is weird that both are from the same Azure SKU (T4 cards) and the tests pass on one and fail on the other. The interesting thing is that the same tests pass locally on Windows on another CC 7.5 card.

**Comment by snnn** [comment]
The nightly pipeline uses "onnxruntime-gpu-tensorrt8-winbuild-t4", maintained by George's team.

**Comment by hariharans29** [comment]
> The nightly pipeline uses "onnxruntime-gpu-tensorrt8-winbuild-t4", maintained by George's team.

Even the non-TensorRT Windows pipeline ?

**Review by hariharans29 — APPROVED** [review]

**Comment by hariharans29** [comment]
Can we just take this for now - https://github.com/microsoft/onnxruntime/pull/12901/ instead of reverting the entire change (which has a lot more stuff in it)

**Pull request closed without merging**
