### PR TITLE
Fix logger regression

### PR DESCRIPTION
**Pull request by csteegz**
**Description**: Describe your changes.

Fixes a regression where passing a custom logger function to Ort::Environment doesn't create a default logger.

**Motivation and Context**
Any consumer of the C++ Api using a custom logging function is broken

### CODE REVIEW

**Comment by jywu-msft** [comment]
some tests pass now 
but still failures remaining in the ONNX Runtime Server CI.

**Comment by snnn** [comment]
You can ignore the centos7 test failure

**Pull request merged**
