### PR TITLE
[js/webgpu] Handle negative axis in op Split

### PR DESCRIPTION
**Pull request by gyagp**
This is to fix issue #21703, where the axis is a negative value in the model. According to the spec (https://onnx.ai/onnx/operators/onnx__Split.html), negative axis means counting dimensions from the back.

### CODE REVIEW

**Comment by gyagp** [comment]
@qjia7, @fs-eire @guschmue PTAL

**Review by qjia7 — APPROVED** [review]
LGTM, thanks.

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
