### PR TITLE
remove mkldnn from linux packages

### PR DESCRIPTION
**Pull request by RandyShuai**
remove mkldnn from linux packages

### CODE REVIEW

**Comment by raymondxyang** [comment]
LGTM.. could u also queue this branch in packaging pipeline?

**Comment by raymondxyang** [comment]
queue refs/pull/533/head

**Comment by snnn** [comment]
Then please add it back to our CI pipelines. Otherwise how can we validate the mkldnn provider code?

**Comment by jywu-msft** [comment]
right. we shouldn't remove mkldnn from CI test just because we are not publishing a release package.

**Comment by pranavsharma** [comment]
> right. we shouldn't remove mkldnn from CI test just because we are not publishing a release package.
> mkldnn provider is still in active development and future improvements may bring it back.

I would like us to reconsider this. Execution providers that are not part of the release should be built in a separate pipeline. Otherwise we're not really running our release pipelines until the release time. Our CI jobs should reflect what we're releasing. This is no different from how we've a separate job for cuda, tensor_rt and nuphar providers.

**Comment by snnn** [comment]
> I would like us to reconsider this. Execution providers that are not part of the release should be built in a separate pipeline. Otherwise we're not really running our release pipelines until the release time. Our CI jobs should reflect what we're releasing. This is no different from how we've a separate job for cuda, tensor_rt and nuphar providers.

If our pipelines won't build these code, the what's the meaning of sending a PR here and wasting 1 hour for waiting the pipelines to complete?

**Comment by pranavsharma** [comment]
> > I would like us to reconsider this. Execution providers that are not part of the release should be built in a separate pipeline. Otherwise we're not really running our release pipelines until the release time. Our CI jobs should reflect what we're releasing. This is no different from how we've a separate job for cuda, tensor_rt and nuphar providers.
> 
> If our pipelines won't build these code, the what's the meaning of sending a PR here and wasting 1 hour for waiting the pipelines to complete?

Well, in that case we should just add the specific exec provider jobs to the list of existing ones and mandate them to pass as well. That's why I said that as we're adding more exec providers, we should reconsider this. It is also a waste of time doing CI on checkins that run with configs completely different from the actual releases.

**Comment by jywu-msft** [comment]
sounds right. there should be CI pipeline for the configs we support (e.g. MKLDNN)
that way checkins don't break supported features.

CI pipeline for building the release package should reflect what's in the package.

**Pull request merged**
