### PR TITLE
Use Java 11 to build project in the codeql pipeline

### PR DESCRIPTION
**Pull request by justinchuby**
Codeql uses Java 8 by default, which is too old for the project.

Related:
https://learn.microsoft.com/en-us/java/openjdk/reasons-to-move-to-java-11
https://github.com/actions/setup-java

### CODE REVIEW

**Comment by Craigacp** [comment]
I think you probably want `distribution: 'microsoft'`, looks like that has an OpenJDK 11 build.

**Comment by justinchuby** [comment]
Looks like it works?

**Review by tianleiwu — APPROVED** [review]

**Review by snnn — APPROVED** [review]

**Comment by Craigacp** [comment]
When it gets merged I'll rebase my branch and hopefully then that'll pass.

**Comment by justinchuby** [comment]
> When it gets merged I'll rebase my branch and hopefully then that'll pass.

Could you do it now? This way we know sooner

**Pull request merged**
