### PR TITLE
[VitisAI] add vitisai ci pipeline

### PR DESCRIPTION
**Pull request by zz002**
### Description

Added VitisAI's CI pipeline

### CODE REVIEW

**Comment by zz002** [comment]
Hi @jywu-msft
I've added VitisAI's CI pipeline. Whenever you have a moment, could you please review the code and verify that the new CI setup is functioning correctly? Your feedback would be greatly appreciated!

**Comment by jywu-msft** [comment]
> Hi @jywu-msft I've added VitisAI's CI pipeline. Whenever you have a moment, could you please review the code and verify that the new CI setup is functioning correctly? Your feedback would be greatly appreciated!

Is this for your own pipeline? trying to understand where it's expected to run.

**Comment by zz002** [comment]
> > Hi @jywu-msft I've added VitisAI's CI pipeline. Whenever you have a moment, could you please review the code and verify that the new CI setup is functioning correctly? Your feedback would be greatly appreciated!
> 
> Is this for your own pipeline? trying to understand where it's expected to run.

image

I hope to add related compilation of vitisai to your pipeline

**Comment by jywu-msft** [comment]
> > > Hi @jywu-msft I've added VitisAI's CI pipeline. Whenever you have a moment, could you please review the code and verify that the new CI setup is functioning correctly? Your feedback would be greatly appreciated!
> > 
> > 
> > Is this for your own pipeline? trying to understand where it's expected to run.
> 
> image
> 
> I hope to add related compilation of vitisai to your pipeline

just to confirm. this is only for compilation? and are there any external dependencies required to successfully build? (e.g. i don't see a dockerfile checked in along with this)

**Comment by zz002** [comment]
> > > > Hi @jywu-msft I've added VitisAI's CI pipeline. Whenever you have a moment, could you please review the code and verify that the new CI setup is functioning correctly? Your feedback would be greatly appreciated!
> > > 
> > > 
> > > Is this for your own pipeline? trying to understand where it's expected to run.
> > 
> > 
> > image
> > I hope to add related compilation of vitisai to your pipeline
> 
> just to confirm. this is only for compilation? and are there any external dependencies required to successfully build? (e.g. i don't see a dockerfile checked in along with this)

Currently there are no other dependencies

**Comment by zz002** [comment]
Hi @jywu-msft ,Is there anything else I need to change?

**Comment by jywu-msft** [comment]
> Hi @jywu-msft ,Is there anything else I need to change?

there's nothing else you need to do for now. still need to discuss internally about creating the build CI pipelines on our end.

**Comment by jywu-msft** [comment]
+@snnn  fyi, let's discuss the possibility of adding CI's for VitisAI. only for builds (no tests) so it shouldn't take much time in pipelines.

**Pull request closed without merging**
