### PR TITLE
Adding DirectML to existing onnxruntime GPU Nuget Package Pipeline

### PR DESCRIPTION
**Pull request by jchen351**
### Motivation and Context
[AB#50891](https://aiinfra.visualstudio.com/6a833879-cd9b-44a4-a9de-adc2d818f13c/_workitems/edit/50891)

### CODE REVIEW

**Comment by fs-eire** [comment]
Are all GPU CIs will be merged into one in future?

**Comment by snnn** [comment]
>  I would like to know whether WebGPU CIs should be put into this CI or saperatedly.

If you are talking about pull request pipelines, please put it separately.  Jian's this PR is for adding DML EP to our existing GPU packages.  AB#50891

**Review by pranavsharma — CHANGES_REQUESTED** [review]
@snnn @jchen351 if this change is merged will the core ORT DLL have a dependency on DML? In other words, can I install this package and use it without installing a single DML dep?

**Comment by snnn** [comment]
DML EP depends on

- DirectML.dll
- dxgi.dll
- DXCore.dll
- D3D12.dll

They are usually part of Windows . We also distribute DirectML.dll in our python package.

**Comment by pranavsharma** [comment]
> DML EP depends on
> 
> * DirectML.dll
> * dxgi.dll
> * DXCore.dll
> * D3D12.dll
> 
> They are usually part of Windows . We also distribute DirectML.dll in our python package.

Let's say we ship this package. Will a user who doesn't want to use DML EP for inferencing need to install DML related deps? If you remember this was the very reason, we'd to separate CUDA EP into a separate DLL so that the core DLL doesn't have to depend on the CUDA EP deps. Are you suggesting that since the DML EP deps are present on all Windows machines, we don't need to worry separating DML EP into a separate DLL?

**Comment by snnn** [comment]
> Will a user who doesn't want to use DML EP for inferencing need to install DML related deps?

 No, they do not. All Windows 10 and Windows 11 should already have DX12.  We can ask the Windows team to get confirmed. 

> Are you suggesting that since the DML EP deps are present on all Windows machines, we don't need to worry separating DML EP into a separate DLL?

No, I am not suggesting that.  Being modular always has benefits.  If onnxruntime.dll doesn't have EP specific code, then we can build DML EP and CUDA EP separately on different hosts in parallel, then extract the EP DLLs out and put them together in a single package. It would be trivial and simple.

**Comment by oysteinkrog** [comment]
I think this would fulfill my feature request: https://github.com/microsoft/onnxruntime/issues/21615

**Comment by jchen351** [comment]
Close this PR. The feature has been implmented by https://github.com/microsoft/onnxruntime/pull/22602

**Pull request closed without merging**
