### PR TITLE
[MIGraphX EP] Add support for Gelu, BiasGelu, FastGelu operators

### PR DESCRIPTION
**Pull request by TedThemistokleous**
### Description

Adds support for different flavours of gelu already supported in MIGraphX

### Motivation and Context

Allows support for benchmark.py models to not rely on the need to specify --disable_bias_gelu --disable_gelu flags

### CODE REVIEW

**Comment by TedThemistokleous** [comment]
ping @tianleiwu simple change, allows support for models.

**Review by tianleiwu — APPROVED** [review]

**Pull request merged**
