### PR TITLE
Add reduce kernels for bigger types

### PR DESCRIPTION
**Pull request by neNasko1**
### Description
This PR adds the kernels for `double`-typed inputs for `ReduceL1`, `ReduceL2`, `ReduceLogSum` and `ReduceProd` and `int64`-typed inputs for `ReduceMean`. 

### Motivation and Context
Similarly to #15358, this follows the standard and improves the situation when reducing longer types. 

This is a needed change, as currently we handle bigger types by performing 2 `cast`-s: before and after reducing.

### CODE REVIEW

**Comment by neNasko1** [comment]
Can you take a look @baijumeswani, tagging you as you were the reviewer to the mentioned PR.

**Comment by cbourjau** [comment]
We have the use for these kernels because they come up regularly when using [ndonnx](https://github.com/Quantco/ndonnx), an ONNX-backed implementation of the [array API](https://data-apis.org/array-api/latest/index.html) standard. The array API standard defines various [reduce-operations](https://data-apis.org/array-api/draft/search.html?q=reduce) and, just like NumPy, commonly uses float64 and int64 data types. Downcasting to smaller types for these operations is inefficient and introduces subtle bugs.

**Comment by cbourjau** [comment]
@liqunfu It seems as if you have recently left your mark on this part of the code. Maybe you could give this PR a review?

**Comment by baijumeswani** [comment]
Changes look good. But is there a need for bigger types? Was using casts not a feasible solution for your use case?

cc @pranavsharma

**Comment by neNasko1** [comment]
> Changes look good. But is there a need for bigger types? Was using casts not a feasible solution for your use case?

In addition to the mentioned slow-down, casting adds imprecision which may become significant down the line. As @cbourjau also notes:

> Downcasting to smaller types for these operations is inefficient and introduces subtle bugs.

**Review by baijumeswani — APPROVED** [review]

**Pull request merged**
