### PR TITLE
Expose DirectML provider to python (conflicts resolved from #3359)

### LINKED ISSUE #3358: How to use DirectML execution provider from Python?
// Edit: seems like it has not been exposed to Python yet. Created a PR that exposes it.

I'm trying to use DirectML from python because it seems like that is the only one to support all popular GPU vendors (please correct me if I'm wrong). I built it from source (`build.bat --config RelWithDebInfo --build_wheel --parallel --use_dml --cmake_generator "Visual Studio 16 2019"`) which succeeds and I can see that it generates a wheel (`onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\dist\onnxruntime-1.2.0-cp37-cp37m-win_amd64.whl`). I installed that wheel but there is still only the CPU provider available:

```
>>> rt.get_available_providers()
['CPUExecutionProvider']
```

Am I missing something or is it not possible to use it in python as of now?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro 1903
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: '1.2.0'-03-29 15:49:23.4469416
- Python version: 3.7.3
- Visual Studio version (if applicable): 16.6.0 Preview 2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: GTX 1070 (8gb)

### PR DESCRIPTION
**Pull request by cameronmaske**
**Description**: Exposed the DirectML (DML) provider to Python.
This is based on #3359 but addresses the conflicts on that branch and include the DirectML.dll in the setup.py. 

**Motivation and Context**
Previously the DML provider was not exposed to python.
Fixes #3358

### CODE REVIEW

**Comment by faxu** [comment]
@cameronmaske looks like there are some more conflicts to resolve on this.

**Comment by hariharans29** [comment]
@cameronmaske @fdwr - does this PR look okay now ? (Resolved conflicts but making sure it makes sense)

**Comment by hariharans29** [comment]
The Windows GPU build are failing. Is it because it isn't able to locate the DirectML.dll for some reason ?

**Comment by faxu** [comment]
@cameronmaske Can you take a look at the failure issue and also resolve conflicts?

**Comment by cameronmaske** [comment]
@faxu I’m currently traveling but will try and resolve these issue when I return next week

**Comment by cameronmaske** [comment]
Is there any way to see why the build failed? Clicking [Details](https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=197847) just gives the error "Build Not Found"

**Comment by cameronmaske** [comment]
@faxu Issue should be resolved. For context, the `DirectML.dll` was not being copied over to the `/capi` directory to be included with the python wheel. I've updated the cmake files to do that now.

**Comment by cameronmaske** [comment]
@faux Reading over the test failures, I'd like some guidance from the maintainers about which route to take to address this, as the direction seems quite opinionated. 

The error occurring is...
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Memory pattern must be disabled before registering DMLExecutionProvider
```

The DML provider does not support (`enable_mem_pattern = True`)[https://microsoft.github.io/onnxruntime/python/api_summary.html#onnxruntime.SessionOptions.enable_mem_pattern] which is the default behavior. There are two approaches I can think of to address this.

My thoughts are either, 

Alter the tests to explicitly disable that option when running with the `DMLExecutionProvider`. Some special care will need to be taken for when the session options are loaded from the [model file](https://github.com/microsoft/onnxruntime/pull/2449).

or 

Change the session options to default `enable_mem_pattern` to `False` if the DMLExecutionProvider is used. This may be harder to do (I'm very new to the codebase, so guidance is appreciated if this is the route to do). 

Maybe there are different approaches, appreciate any thoughts/guidance.

**Comment by jywu-msft** [comment]
> @faux Reading over the test failures, I'd like some guidance from the maintainers about which route to take to address this, as the direction seems quite opinionated.
> 
> The error occurring is...
> 
> ```
> onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Memory pattern must be disabled before registering DMLExecutionProvider
> ```
> 
> The DML provider does not support [`enable_mem_pattern = True`](https://microsoft.github.io/onnxruntime/python/api_summary.html#onnxruntime.SessionOptions.enable_mem_pattern) which is the default behavior. There are two approaches I can think of to address this.
> 
> My thoughts are either,
> 
> Alter the tests to explicitly disable that option when running with the `DMLExecutionProvider`. Some special care will need to be taken for when the session options are loaded from the [model file](https://github.com/microsoft/onnxruntime/pull/2449).
> 
> or
> 
> Change the session options to default `enable_mem_pattern` to `False` if the DMLExecutionProvider is used. This may be harder to do (I'm very new to the codebase, so guidance is appreciated if this is the route to do).
> 
> Maybe there are different approaches, appreciate any thoughts/guidance.

Between those two options, I would lean towards the latter. enable_memory_pattern is an optimization, so if it is incompatible with DMLExecutionProvider, it seems better to make it a no-op, rather than place onus on user to know what optimizations are compatible with which provider. 
Defaulting the correct option seems also preferable to changing all the various test code to special case DMLExecutionProvider to instantiate sess_options and set enable_mem_pattern to false.
As for how to default enable_mem_pattern to false, I think we can either remove the error message (and change the setting there). or perhaps better would be to set enable_mem_pattern to false in [InferenceSession::ConstructorCommon](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/session/inference_session.cc#L166)
sometime after FinalizeSessionOptions() 
@pranavsharma , what do you think?

**Comment by cameronmaske** [comment]
@hariharans29 Many thanks for the help in getting this merged!

**Comment by Coderx7** [comment]
Just wanted to say, the DML seems not be exposed! 
building like : 
```
.\build.bat --cmake_generator "Visual Studio 16 2019" --config RelWithDebInfo --build_wheel --parallel
```
goes on successfully but the `onnxruntime.get_available_providers()` only returns `['CPUExecutionProvider']`

**Pull request merged**
