### PR TITLE
[doc] update supported coreml ep op md

### PR DESCRIPTION
**Pull request by YUNQIUGUO**
**Description**: Describe your changes.

As title.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by faxu** [comment]
Is this file manually updated and not automatically generated?

**Comment by YUNQIUGUO** [comment]
> Is this file manually updated and not automatically generated?

Um, yes. This file is updated by copy/paste from https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/android/nnapi_supported_ops.md
https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/apple/coreml_supported_ops.md 

on the master branch

**Review by faxu — APPROVED** [review]

**Comment by faxu** [comment]
> > Is this file manually updated and not automatically generated?
> 
> Um, yes. This file is updated by copy/paste from https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/android/nnapi_supported_ops.md https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/apple/coreml_supported_ops.md
> 
> on the master branch

@YUNQIUGUO @natke Is there a way to automate a PR to gh-pages anytime that file changes in master?

**Comment by natke** [comment]
> @YUNQIUGUO @natke Is there a way to automate a PR to gh-pages anytime that file changes in master?

Absolutely! We do it for other content

**Comment by faxu** [comment]
> > @YUNQIUGUO @natke Is there a way to automate a PR to gh-pages anytime that file changes in master?
> 
> Absolutely! We do it for other content

@natke can you work with @YUNQIUGUO to automate this? I'll merge this PR for now.

**Comment by YUNQIUGUO** [comment]
> > > @YUNQIUGUO @natke Is there a way to automate a PR to gh-pages anytime that file changes in master?
> > 
> > 
> > Absolutely! We do it for other content
> 
> @natke can you work with @YUNQIUGUO to automate this? I'll merge this PR for now.

yeah I can help to automate this. also could you please maybe merge https://github.com/microsoft/onnxruntime/pull/12273 this pr also? it's about the similar updates.

**Pull request merged**
