### PR TITLE
Update rocm_ep and migraphx_ep to rocm4.5.2 and fix dockerfiles to build docker images correctly

### PR DESCRIPTION
**Pull request by scxiao**
**Description**: Describe your changes.
The dockerfile for rocm ep and migraphx ep needs update to fix some build errors.

**Motivation and Context**
Fix build errors in the dockerfile related to rocm  ep and migraphx ep.

- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by weixingzhang — APPROVED** [review]

**Comment by scxiao** [comment]
@weixingzhang Looks like all builds passed, could you please merge it? Thanks!

**Pull request merged**
