### PR TITLE
[Rust] fix ORT_RUST_STRATEGY env var in rust ci

### PR DESCRIPTION
**Pull request by devigned**
### Description
Fix the env var in the Rust CI GitHub Action

### Motivation and Context

In #18346 the GH action contained a badly formatted env var. This is a follow up PR to fix that issue.

### CODE REVIEW

**Comment by snnn** [comment]
The logs has:
```
"-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro"
```
Do you know where does it from?

cl.exe has 4 such flags: [/MD](https://learn.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170), /MDd, /MT, /MTd. All source files in the same program should be compiled with the same flag from the four.  So, for a debug build, it should be /MDd, not /MD. Because STL's ABI for debug build and release build are different. If a library was built for a debug build, you cannot use it in a release build.

**Comment by snnn** [comment]
I see your build log has an error that:
```
 There is not enough space on the disk
```
It means the build machine isn't powerful enough to handle this.  We have another pool. To try that one, you may add
```
    runs-on: ["self-hosted", "1ES.Pool=onnxruntime-github-vs2022-mms"]
```
To your job settings.
Like:

https://github.com/microsoft/onnxruntime/blob/main/.github/workflows/windows.yml#L19

The machine pool was created from a different image. If the machine pool doesn't have the necessary software this rust job needs, tell me and I will create a new one.

**Comment by YUNQIUGUO** [comment]
@devigned hi, gentle ping - any follow-up on this on for fixing the Rust CI?

**Comment by devigned** [comment]
> @devigned hi, gentle ping - any follow-up on this one for fixing the Rust CI?

I promise to get back to it this week. Unfortunately, my availability comes in chunks and then gets overtaken by other priorities.

**Comment by wschin** [comment]
> > @devigned hi, gentle ping - any follow-up on this one for fixing the Rust CI?
> 
> I promise to get back to it this week. Unfortunately, my availability comes in chunks and then gets overtaken by other priorities.

Thanks a lot. May I gentle ping again? :)

**Comment by devigned** [comment]
@wschin you are too right. I forgot to close this out before I left for holiday.

I'm going to close this PR with the intent of using https://ort.pyke.io/.

I'd be delighted to help document usage via `ort`.

**Pull request closed without merging**
