### PR TITLE
[js/web] Fix typo in JSEP ConvTranspose

### PR DESCRIPTION
**Pull request by dakenf**
### Description
A typo fix in JSEP ConvTranspose. It used $12 as output shape pointer but it should be $13. As $12 holds shape size

### CODE REVIEW

**Review by satyajandhyala — APPROVED** [review]

**Comment by satyajandhyala** [comment]
@dakenf  Please pull changes from main and update the PR branch.

**Comment by dakenf** [comment]
> @dakenf Please pull changes from main and update the PR branch.

Done. But GitHub UI does not show it for some reason

**Review by guschmue — APPROVED** [review]

**Pull request merged**
