### PR TITLE
[js/webgpu] Fix scalar uniform

### PR DESCRIPTION
**Pull request by axinging**

### CODE REVIEW

**Comment by axinging** [comment]
@qjia7 @xhcao @hujiajie @gyagp PTAL

**Review by qjia7 — APPROVED** [review]
LGTM, thanks.
@fs-eire @satyajandhyala @guschmue  Please take a look, thanks.

@satyajandhyala Please check whether it can resolve the issue here https://github.com/microsoft/onnxruntime/pull/18260/files#diff-96abb2fda4b0f6b5dbda0729deedba3ea4fbefc1adf3368e2a8e0974420c658aR808

**Comment by satyajandhyala** [comment]
> LGTM, thanks. @fs-eire @satyajandhyala @guschmue Please take a look, thanks.
> 
> @satyajandhyala Please check whether it can resolve the issue here https://github.com/microsoft/onnxruntime/pull/18260/files#diff-96abb2fda4b0f6b5dbda0729deedba3ea4fbefc1adf3368e2a8e0974420c658aR808

If this change does not require the condition `rank>0` then please merge changes from master and remove that condition.

**Comment by axinging** [comment]
> > LGTM, thanks. @fs-eire @satyajandhyala @guschmue Please take a look, thanks.
> > @satyajandhyala Please check whether it can resolve the issue here https://github.com/microsoft/onnxruntime/pull/18260/files#diff-96abb2fda4b0f6b5dbda0729deedba3ea4fbefc1adf3368e2a8e0974420c658aR808
> 
> If this change does not require the condition `rank>0` then please merge changes from master and remove that condition.

Can the removal of 'rank>0' in another followup PR? Because if remove this,  this should also be changed: https://github.com/microsoft/onnxruntime/pull/18260/files#diff-ebe24f4aec1347c7c376ed1caf5a7cc071163f20d797c576bdbaa1a41f6242b8R162

**Comment by axinging** [comment]
> > LGTM, thanks. @fs-eire @satyajandhyala @guschmue Please take a look, thanks.
> > @satyajandhyala Please check whether it can resolve the issue here https://github.com/microsoft/onnxruntime/pull/18260/files#diff-96abb2fda4b0f6b5dbda0729deedba3ea4fbefc1adf3368e2a8e0974420c658aR808
> 
> If this change does not require the condition `rank>0` then please merge changes from master and remove that condition.

Done， PTAL

**Review by guschmue — APPROVED** [review]

**Pull request merged**
