### PR TITLE
OpenVINO dockerfile point to the ONNX Runtime master repo

### PR DESCRIPTION
**Pull request by manashgoswami**
**Description**: use master repo to build the openvino execution provider

**Motivation and Context**
- The Dockerfile is pointing to incorrect code repo

### CODE REVIEW

**Comment by suryasidd** [comment]
We can also get rid of the preview branch that its pointing to.  That's only for the other repo.

**Comment by jywu-msft** [comment]
can we follow the same pattern as the other Dockerfiles in the directory? make repo and branch ARGs

**Comment by suryasidd** [comment]
The issues have been addressed in a new PR. I think this one can be closed. 
https://github.com/microsoft/onnxruntime/pull/1362

**Comment by manashgoswami** [comment]
Resolved in #1362.

**Pull request closed without merging**
