### PR TITLE
OVEP options to disable CPU fallback at compile time

### PR DESCRIPTION
**Pull request by preetha-intel**
### Description
Provide user level options to control the fallback on CPU for models not supported on Intel's NPU hardware.

### Motivation and Context
- Current workflow of OVEP allows safe fallback from OV NPU to OV CPU on compilation failures. Also supports MLAS CPU fallback in presence of unsupported custom ops.
- The PR provides a build-time option to disable fallback from OV NPU to OV CPU. 
- The session Option "kOrtSessionOptionsDisableCPUEPFallback" disables OV CPU and MLAS CPU fallback.
- Also has bug fix for proto creation.

### CODE REVIEW

**Comment by jywu-msft** [comment]
please fix clang format.

**Comment by preetha-intel** [comment]
@jywu-msft  The pipeline run is successful. Can you please help with merging the PR. Thanks

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
