### PR TITLE
[js/webgpu] Fix max pool shape end with 0

### PR DESCRIPTION
**Pull request by axinging**
Bug: https://github.com/microsoft/onnxruntime/issues/21386

### CODE REVIEW

**Comment by axinging** [comment]
@qjia7 @xhcao @hujiajie @jzm-intel @gyagp PTAL

**Review by qjia7 — CHANGES_REQUESTED** [review]
If I understand correctly, the error is caused by the 2d shapes of `kernelShape`/`strides`/`dilations` while the 1d shapes are expected since it's pool1d instead of pool2d. 

Based on that, I think the right fixing should be passing the right shape to attributes in c++ side instead of modifying it in js. See code here https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/js/operators/pool.h#L29-L32, it will always generate a 2d array to `attributes.dilations`/`attributes.kernel_shape`/`attributes.strides`. To get the right attribute shapes, you can refer to conv's implementation here https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/js/operators/conv.h#L30-L45 which supports any expected shapes.

**Comment by axinging** [comment]
> If I understand correctly, the error is caused by the 2d shapes of `kernelShape`/`strides`/`dilations` while the 1d shapes are expected since it's pool1d instead of pool2d.
> 
> Based on that, I think the right fixing should be passing the right shape to attributes in c++ side instead of modifying it in js. See code here https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/js/operators/pool.h#L29-L32, it will always generate a 2d array to `attributes.dilations`/`attributes.kernel_shape`/`attributes.strides`. To get the right attribute shapes, you can refer to conv's implementation here https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/js/operators/conv.h#L30-L45 which supports any expected shapes.

Thanks @qjia7, updated.

**Review by qjia7 — APPROVED** [review]
LGTM, thanks!

@guschmue @fs-eire @satyajandhyala Please take a look, thanks.

**Comment by fs-eire** [comment]
This PR is replaced by #21559 because the build pipeline failed to trigger.

**Pull request closed without merging**
