### PR TITLE
Added support for ReduceMean on DNNL EP for CPU and GPU

### PR DESCRIPTION
**Pull request by chethanpk**
Signed-off-by: Chethan Palangotu Keshava chethan.palangotu.keshava@intel.com

Description: Added changes to support ReduceMean op using DNNL execution provider for both CPU and GPU.
As it stands, DNNL doesn't support ReduceMean with keepdims attribute value as 0, i.e. the rank of input and output has to be same.
If it detects this value for keepdims, it will revert to CPU default EP.

Motivation and Context
Increasing DNNL EP capabilities.

### CODE REVIEW

**Comment by jywu-msft** [comment]
there seems to be some test failure:
7: [ RUN      ] ModelTests/ModelTest.Run/746
7: 2021-06-01 17:20:40.7944219 [E:onnxruntime:tf_resnet_v2_50, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running DnnlCustomOp_11572902578026391795_27 node. Name:'DnnlExecutionProvider_DnnlCustomOp_11572902578026391795_27_27' Status Message: Status: 2, message: could not create a reduction descriptor
7: D:\a\_work\1\s\onnxruntime\test\providers\cpu\model_tests.cc(564): error: Value of: _tmp_status.IsOK()
7:   Actual: false
7: Expected: true
7: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running DnnlCustomOp_11572902578026391795_27 node. Name:'DnnlExecutionProvider_DnnlCustomOp_11572902578026391795_27_27' Status Message: Status: 2, message: could not create a reduction descriptor
7: [  FAILED  ] ModelTests/ModelTest.Run/746, where GetParam() = L"dnnl_..\\models\\opset11\\tf_resnet_v2_50\\model.onnx" (1201 ms)

**Comment by chethanpk** [comment]
> there seems to be some test failure:
> 7: [ RUN ] ModelTests/ModelTest.Run/746
> 7: 2021-06-01 17:20:40.7944219 [E:onnxruntime:tf_resnet_v2_50, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running DnnlCustomOp_11572902578026391795_27 node. Name:'DnnlExecutionProvider_DnnlCustomOp_11572902578026391795_27_27' Status Message: Status: 2, message: could not create a reduction descriptor
> 7: D:\a_work\1\s\onnxruntime\test\providers\cpu\model_tests.cc(564): error: Value of: _tmp_status.IsOK() 7: Actual: false 7: Expected: true 7: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running DnnlCustomOp_11572902578026391795_27 node. Name:'DnnlExecutionProvider_DnnlCustomOp_11572902578026391795_27_27' Status Message: Status: 2, message: could not create a reduction descriptor 7: [ FAILED ] ModelTests/ModelTest.Run/746, where GetParam() = L"dnnl_..\models\opset11\tf_resnet_v2_50\model.onnx" (1201 ms)

I had sent you an email regarding this too:
The model that is causing the failure is not run when we run our tests and I can’t seem to find that model elsewhere too.
I have two options here:
1)	If I can get access to that model then I can see what is causing the failure. I suspect some parameters of the operator is not supported by DNNL  or it cannot create an primitive with those parameters.
2)	If that is not possible, I can add this model to the list of exemptions here https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/onnx/main.cc and skip running that test for dnnl.

Let me know which one of these options looks feasible to you.

Additionally, the resnet50 v2 from onnx model zoo is working correctly and passing the test cases.

**Comment by chethanpk** [comment]
Hi George, can you please re-run the tests? I have sent you an email with more details.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
