### PR TITLE
[WebNN EP] Use GetVecUint32FromVecInt64 to simplify the code

### PR DESCRIPTION
**Pull request by zesongw**
- Use the function `GetVecUint32FromVecInt64` in helper.h to replace `transform`.
- Change some `int32_t` to `uint32_t`.
- Remove a useless `temp`.

### CODE REVIEW

**Comment by zesongw** [comment]
@fdwr, @guschmue, PTAL. Thanks!

**Review by guschmue — APPROVED** [review]

**Review by fdwr — APPROVED** [review]
Nice, that's cleaner. 🧼

**Pull request merged**
