### PR TITLE
VPUX config fix and dynamic_shape bug fixed.

### PR DESCRIPTION
**Pull request by sfatimar**
Dynamic shapes was not working with serialized model so we are switching to compile model method

### Motivation and Context
Dynamic shapes was not working with serialized model 
- If it fixes an open issue, please link to the issue here. -->

### CODE REVIEW

**Comment by MaajidKhan** [comment]
Hi @jywu-msft . Can you please review and merge this fix. we want it to be part of ORT 1.15 release.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
