### PR TITLE
Update CI build docker images

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

Update CI build docker images: delete ubuntu 16.04 support.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by thiagocrepaldi — APPROVED** [review]
cool

**Comment by thiagocrepaldi** [comment]
Any reason to not jump to 20.04?

**Comment by snnn** [comment]
> Any reason to not jump to 20.04?

No,  we can do that.

**Comment by snnn** [comment]
Jumping to 18.04 is easier, because we don't need to change python version. These images already use python 3.6 now.

**Comment by thiagocrepaldi** [comment]
> Jumping to 18.04 is easier, because we don't need to change python version. These images already use python 3.6 now.

That was actually an argument to jump to 20.04. We have been dragging 3.6, but we have to support up to 3.9, so it is a long list to keep up and generate packages for. Going for newer releases and dropping ancient versions would be nice :)

**Comment by snnn** [comment]
> > Jumping to 18.04 is easier, because we don't need to change python version. These images already use python 3.6 now.
> 
> That was actually an argument to jump to 20.04. We have been dragging 3.6, but we have to support up to 3.9, so it is a long list to keep up and generate packages for. Going for newer releases and dropping ancient versions would be nice :)

Agree. We should consider dropping 3.6 support. Numpy already did so, and we depend on numpy. 

If you don't mind,  can I put the python upgrade in another PR? This PR is mainly for some training pipelines and the nuphar EP. When we upgrade the python version, I guess I will also need to update some pytorch related settings. The change will be bigger.

**Comment by thiagocrepaldi** [comment]
> > > Jumping to 18.04 is easier, because we don't need to change python version. These images already use python 3.6 now.
> > 
> > 
> > That was actually an argument to jump to 20.04. We have been dragging 3.6, but we have to support up to 3.9, so it is a long list to keep up and generate packages for. Going for newer releases and dropping ancient versions would be nice :)
> 
> Agree. We should consider dropping 3.6 support. Numpy already did so, and we depend on numpy.
> 
> If you don't mind, can I put the python upgrade in another PR? This PR is mainly for some training pipelines and the nuphar EP. When we upgrade the python version, I guess I will also need to update some pytorch related settings. The change will be bigger.

Absolutely

**Review by thiagocrepaldi — APPROVED** [review]

**Pull request merged**
