### PR TITLE
[CUDA] Remove shape warnings in NHWC <> NCHW unit tests

### PR DESCRIPTION
**Pull request by gedoensmax**
### Description

There were some warning in https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1170770 e.g.
```
[ RUN      ] CudaNhwcTypedTest/1.AveragePoolNhwcPad @ /home/administrator/onnxruntime/onnxruntime/test/providers/cuda/nhwc/pool_test.cc:84
[W:onnxruntime:Default, graph.cc:108 MergeShapeInfo] Error merging shape info for output. 'Y' source:{1,16,66,66} target:{1,16,67,67}. Falling back to lenient merge.
```
These warnings where not specific to NHWC or NCHW but were just a miscalculation of output shape in some tests.

### CODE REVIEW

**Comment by gedoensmax** [comment]
@hariharans29 this should fix all warnings.

**Comment by tianleiwu** [comment]
image

**Review by hariharans29 — DISMISSED** [review]

**Comment by hariharans29** [comment]
> Linux MIGraphX CI Pipeline, orttraining-amd-gpu-ci-pipeline

Even though CUDA test files are not hipified, running the AMD pipelines in case we stumble on this PR to copy/paste the github triggers for a future CUDA PR.

**Comment by hariharans29** [comment]
@gedoensmax  , Please run lintrunner -a to fix python format in this PR as well

**Comment by gedoensmax** [comment]
Sorry this lint runner is my nemesis.

**Review by hariharans29 — APPROVED** [review]

**Comment by hariharans29** [comment]
Can you please re-base with main - I think we ned to take in this [commit](https://github.com/microsoft/onnxruntime/pull/18034/) to make the last pipeline green ?

**Review by hariharans29 — APPROVED** [review]

**Pull request merged**
