### PR TITLE
Fix model path marshalling in csharp, and re-enable the pretrained model tests

### PR DESCRIPTION
**Pull request by shahasad**
**Description**: Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by snnn** [comment]
Should the default marshaling works fine?

https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-for-strings

On Windows, we should mark it as UnmanagedType.LPWStr
On Linux, it should be UnmanagedType.LPStr

**Comment by jignparm** [comment]
Looks like the `[MarshalAs(UnmanagedType.LPStr)]` was commented out below, which is why the paths are not null-terminated. 

Can that be put back in, instead of adding `Char.MinValue`?

https://github.com/microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/NativeMethods.cs#L261

``` c#
        public delegate IntPtr /* OrtStatus* */DOrtCreateSession(
                                                IntPtr /* (OrtEnv*) */ environment,
                                                //[MarshalAs(UnmanagedType.LPStr)]string modelPath
                                                byte[] modelPath,
                                                IntPtr /* (OrtSessionOptions*) */sessopnOptions,
                                                out IntPtr /**/ session);
```

**Comment by shahasad** [comment]
> Looks like the [MarshalAs(UnmanagedType.LPStr)] was commented out below, which is why the paths are not null-terminated.
> Can that be put back in, instead of adding Char.MinValue?
> https://github.com/microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/NativeMethods.cs#L261
>         public delegate IntPtr /* OrtStatus* */DOrtCreateSession(
>                                                 IntPtr /* (OrtEnv*) */ environment,
>                                                 //[MarshalAs(UnmanagedType.LPStr)]string modelPath
>                                                 byte[] modelPath,
>                                                 IntPtr /* (OrtSessionOptions*) */sessopnOptions,
>                                                 out IntPtr /**/ session);

Thje MarshalAs was undone, because we are not passing C# string anymore, we were passing byte[] that was decoded based on OS. 

This can be achieved using MarshalAs, but you need #ifdefs to do 2 types of Marshalling for windows and linux.

**Comment by snnn** [comment]
Hi @shahasad,

Is it easy to have a #ifdef there? Does it have any drawback?

**Comment by shahasad** [comment]
> Hi @shahasad,
> Is it easy to have a #ifdef there? Does it have any drawback?

AFAIK, there is no preprocessor define for OS platfom in C#, we need to define them and pass along the build. The current change was simpler than that.

**Comment by shahasad** [comment]
Also, platform is unknown at compile time, because C# code is built for AnyCPU.

**Comment by snnn** [comment]
But the current one also have some problems:
1. We can't assume Linux uses UTF-8. UTF-8 is the most popular one, but not the only one.
2.  Maybe it's better to append the '\0' to the byte[], other than the original string.
3.  For every path names in the C API, we have to do the similar fix.

**Comment by shahasad** [comment]
> But the current one also have some problems:
> 
> We can't assume Linux uses UTF-8. UTF-8 is the most popular one, but not the only one.
> Maybe it's better to append the '\0' to the byte[], other than the original string.
> For every path names in the C API, we have to do the similar fix.  OrtCreateSession is one of the functions, I think we have at least one another?

OK, there are 2 others -- optimizedmodel file path, and profilepathprefix. Both are ORTCHAR_T* in C-api. So, I'll fox those on C#.

**Comment by skottmckay** [comment]
> > But the current one also have some problems:
> > We can't assume Linux uses UTF-8. UTF-8 is the most popular one, but not the only one.
> > Maybe it's better to append the '\0' to the byte[], other than the original string.
> > For every path names in the C API, we have to do the similar fix.  OrtCreateSession is one of the functions, I think we have at least one another?
> 
> OK, there are 2 others -- optimizedmodel file path, and profilepathprefix. Both are ORTCHAR_T* in C-api. So, I'll fox those on C#.

Would the C# library ever be used on Linux?

**Comment by shahasad** [comment]
Yes, dotnet platform is available on osx, windows and linux.

**Comment by jignparm** [comment]
>We can't assume Linux uses UTF-8. UTF-8 is the most popular one, but not the only one.

For the other Linux locales (e.g. C or POSIX), the file paths should be handled accurately using UTF-8 encoding. The code above just needs to  successfully convert file paths  in managed space (stored as UTF-16) to a single-byte representation for Linux. Linux doesn't support UTF-16 locales, so that case doe not need to be handled.

Is there another locale which might be problematic?

**Comment by snnn** [comment]
Hi @jignparm ,

For example, for Chinese, the locale could be 

zh_CN.gb18030
zh_CN.gb2312
zh_CN.gbk
zh_CN.utf8

Only one if them is utf8.

**Comment by jignparm** [comment]
The locale  values on Linux define a language  + encoding scheme. From the issue  here https://github.com/dotnet/corefx/issues/21701, it looks like  .NET Core only supports  UTF-8 encoding scheme for Chinese characters, and not the GBK or other encodings you mentioned above . The claim is that most Linux distributions are set up with everything on UTF-8, and .NET Core plans to only support those distributions.

Most likely users will need to update their locale to UTF-8 if they want to run models with Chinese names using the ORT C# API. Copying files created using GBK encoding onto another host that uses UTF-encoding will probably create a broken scenario, so the .NET recommendation is to always use UTF-8.

**Pull request merged**
