### PR TITLE
Sqnbitgemm: add loongarch64 code path

### PR DESCRIPTION
**Pull request by junchao-loongson**
### Description

Add support code for loongarch64 platform in sqnbitgemm

```
100% tests passed, 0 tests failed out of 7

Total Test time (real) = 116.99 sec
2023-12-11 10:43:21,287 build [INFO] - Build complete

```

### CODE REVIEW

**Review by yufenglee — APPROVED** [review]

**Comment by junchao-loongson** [comment]
The loongarch architecture requires this patch to compile pass. It would be perfect to receive this patch before the next ort release!

**Pull request merged**
