### PR TITLE
Add execute bit back to build.py

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

It got removed in #5778. But the Android pipeline needs it.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by skottmckay — APPROVED** [review]

**Review by gwang-msft — APPROVED** [review]

**Comment by gwang-msft** [comment]
Do you think it's better we add 'python3' in front of the current CI definition? So this won't get affected by this kind of accidental change?

- script: **_python3_** tools/ci_build/build.py --android ....

**Comment by snnn** [comment]
> Do you think it's better we add 'python3' in front of the current CI definition? So this won't get affected by this kind of accidental change?

I feel either is fine. You can decide it.

**Comment by skottmckay** [comment]
> > Do you think it's better we add 'python3' in front of the current CI definition? So this won't get affected by this kind of accidental change?
> 
> I feel either is fine. You can decide it.

Given this has happened twice recently, adding python3 is probably better long term. 

It happened to me on Windows and I didn't make any direct or intentional changes to the permissions for build.py (and given it was Windows it wasn't even obvious it had changed).

**Comment by gwang-msft** [comment]
> > > Do you think it's better we add 'python3' in front of the current CI definition? So this won't get affected by this kind of accidental change?
> > 
> > 
> > I feel either is fine. You can decide it.
> 
> Given this has happened twice recently, adding python3 is probably better long term.
> 
> It happened to me on Windows and I didn't make any direct or intentional changes to the permissions for build.py (and given it was Windows it wasn't even obvious it had changed).

This #5889 has the change to add python3 to CI command

**Pull request closed without merging**
