### PR TITLE
MIGraphX Execution Provider: Stream Synchronization

### PR DESCRIPTION
**Pull request by TedThemistokleous**
**Description**: Changes to the MIGraphx execution provider code to allow for stream synchronization on the gpu side

**Motivation and Context**
Performance boost by removing redundant host to device synchronizations 

The current implementation of the execution provider continuously calls hipDeviceSynchronize() between computations which adds overhead and an idle wait between the GPU's computations. This is noticeable during device

This change leverages new functionality that's been added to MIGraphX to allow for GPU side synchronization which avoids the need for host->device waits. 

To maintain backwards compatibility with older MIGraphX versions, the compile time define MIGRAPHX_STREAM_SYNC has been added to the API to allow for older version operate with newer builds of onnxruntime without loss of functionality to the current feature set as of (08/09/22)

### CODE REVIEW

**Comment by TedThemistokleous** [comment]
Hi @snnn, the MIGraphX side has completed our review process for the changeset for this and I just pushed up a change the other day that shouldn't break functionality between older versions of MIGraphX and Onnxruntime with changes to the EP.  

These stream sync changes shall be reflected in our 5.4 release.

Can I get another run of the above workflow CI?

Please let me know of any further feedback/questions/concerns on this change set as well.

**Comment by ytaous** [comment]
2022-10-11T10:13:47.9337923Z /onnxruntime_src/onnxruntime/core/providers/migraphx/migraphx_execution_provider.cc:1064:31: error: ‘ctx’ was not declared in this scope
2022-10-11T10:13:47.9339811Z  1064 |           auto input_tensor = ctx.GetInput(index);

**Comment by TedThemistokleous** [comment]
Force pushed after a rebase off your main branch.

**Review by ytaous — APPROVED** [review]
let it cook for one more day, I'll merge it if not other comments.

**Pull request merged**
