### PR TITLE
Add new cases for non biased mha tests

### PR DESCRIPTION
**Pull request by cloudhan**

### CODE REVIEW

**Comment by cloudhan** [comment]
@tianleiwu The two new cases cause testing failures on A100. I am not quite sure about the root cause. But is works fine on CPU EP, CUDA EP V100 and my WIP branch ROCm EP MI200.

**Comment by tianleiwu** [comment]
> @tianleiwu The two new cases cause testing failures on A100. I am not quite sure about the root cause. But is works fine on CPU EP, CUDA EP V100 and my WIP branch ROCm EP MI200.

See https://github.com/microsoft/onnxruntime/pull/13980

**Comment by cloudhan** [comment]
Skip the new tests for CUDA EP. Ready fot CI testing.

**Comment by tianleiwu** [comment]
LGTM. Do you want to merge to master instead?

**Comment by cloudhan** [comment]
@tianleiwu This is a stacked PR on top of #16075. I generally employ forward merge, that is merge 16075 first then this one. But I can do it in backward.

**Review by tianleiwu — DISMISSED** [review]

**Review by mindest — APPROVED** [review]

**Pull request merged**
