### PR TITLE
Enable Intel oneAPI DPC++/C++ compiler build

### PR DESCRIPTION
**Pull request by MKlimenko**
Last week I fixed error #16484 found when trying to build onnxruntime with the icpx compiler. Another thing I found out is that icpx uses -ffast-math flag by default. You can check it by running the compiler with -v flag like following:

```bash
# Setup the environment
. /opt/intel/oneapi/setvars.sh
# Compile any file to see all the implicit flags
icpx -v main.cpp
```

This leads to a bunch of warnings during the build like:

```bash
In file included from /mnt/f/wsl_home/onnxruntime/onnxruntime/test/providers/cpu/tensor/upsample_op_test.cc:5:
In file included from /mnt/f/wsl_home/onnxruntime/onnxruntime/test/providers/provider_test_utils.h:6:
In file included from /mnt/f/wsl_home/onnxruntime/onnxruntime/test/providers/checkers.h:10:
In file included from /mnt/f/wsl_home/onnxruntime/onnxruntime/core/util/math_cpuonly.h:68:
In file included from /mnt/f/wsl_home/onnxruntime/build/Linux/RelWithDebInfo/_deps/eigen-src/Eigen/Core:172:
/mnt/f/wsl_home/onnxruntime/build/Linux/RelWithDebInfo/_deps/eigen-src/Eigen/src/Core/MathFunctions.h:1019:12: warning: comparison with NaN always evaluates to false in fast floating point modes [-Wtautological-constant-compare]
    return isnan EIGEN_NOT_A_MACRO (x);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
		   
And some tests are failing as well, usually with infinities involved. To list a few:

```bash
# ...
1: [  FAILED  ] IsInfTest.test_isinf_float
1: [  FAILED  ] IsInfTest.test_isinf_double
1: [  FAILED  ] IsInfTest.test_isinf_positive_float
1: [  FAILED  ] IsInfTest.test_isinf_positive_double
1: [  FAILED  ] IsInfTest.test_isinf_negative_float
1: [  FAILED  ] IsInfTest.test_isinf_negative_double
1: [  FAILED  ] IsNaNOpTest.IsNaNFloat
1: [  FAILED  ] IsNaNOpTest.IsNaNDouble
# ...
```

This PR adds a quick global check for the IntelLLVM compiler, as in the way its name is reported by CMake and then, depending on the compiler driver, sets either MSVC-like or GCC-like switch to disable fast-maths.

Probably a bit cleaner solution would be to use ```target_compile_options(${TARGET} PRIVATE MEOW)``` instead of a global-wide ```set(CMAKE_CXX_FLAGS MEOW)```, but then we'd be required to add it to all the individual targets and execution providers and this will lead to a lot of code duplication.

### CODE REVIEW

**Comment by MKlimenko** [comment]
Hi @jywu-msft! Looks like CI is stuck, it can't start several jobs for some reason. Can you take a look?

**Comment by MKlimenko** [comment]
Looks like a major CI issue with Windows runner, I can see the same error messages in other pull requests

**Comment by MKlimenko** [comment]
@jywu-msft, looks like we have two issues here:
1. For some reason, `Windows_CI / Onnxruntime-TVM` runner is broken. We can see it in other PRs like [here](https://github.com/microsoft/onnxruntime/actions/runs/5697976951/job/15445329558?pr=16916) and [here](https://github.com/microsoft/onnxruntime/actions/runs/5697836763/job/15445057871?pr=16915). I have updated my branch to the main once again, but not sure if the core issue was fixed.
2. Some of the checks stall at `Expected — Waiting for status to be reported`. Could it be related to this auto-generated message (see above)?

> No commit pushedDate could be found for PR 16587 in repo microsoft/onnxruntime

**Comment by jywu-msft** [comment]
> @jywu-msft, looks like we have two issues here:
> 
> 1. For some reason, `Windows_CI / Onnxruntime-TVM` runner is broken. We can see it in other PRs like [here](https://github.com/microsoft/onnxruntime/actions/runs/5697976951/job/15445329558?pr=16916) and [here](https://github.com/microsoft/onnxruntime/actions/runs/5697836763/job/15445057871?pr=16915). I have updated my branch to the main once again, but not sure if the core issue was fixed.
> 2. Some of the checks stall at `Expected — Waiting for status to be reported`. Could it be related to this auto-generated message (see above)?
> 
> > No commit pushedDate could be found for PR 16587 in repo microsoft/onnxruntime

the TVM CI pipeline break is a known issue. it won't block this PR since it's not a required pipeline.

**Comment by MKlimenko** [comment]
@jywu-msft looks like all the important checks have passed and the failing ones have nothing to do with the PR (for example, some .jsonc formatting).
Do you want something else to be done in this PR?

**Comment by jywu-msft** [comment]
> @jywu-msft looks like all the important checks have passed and the failing ones have nothing to do with the PR (for example, some .jsonc formatting). Do you want something else to be done in this PR?

there are several failing required pipelines that probably aren't related to your change. that's why I asked you to merge the latest main branch (which may have fixes for those failures)

**Comment by MKlimenko** [comment]
@jywu-msft, no, these are the only changes required to make onnxrunitme buildable with icpx. 
Pulled the latest changes from the main, let's see if they'll fix the CI runs.

**Comment by jywu-msft** [comment]
> @jywu-msft, no, these are the only changes required to make onnxrunitme buildable with icpx. Pulled the latest changes from the main, let's see if they'll fix the CI runs.

the pipeline failure issue was fixed yesterday by https://github.com/microsoft/onnxruntime/pull/16962
which unfortunately was merged one hour after you pulled main. can you do it again to get that fix into your branch?
i'll kick off the CI's again after that. sorry for the delay. as you've notice there's some azure devops bug that prevents us from consistently kicking off CI's for external PR's, so I have to keep trying until it succeeds as a workaround.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
