### PR TITLE
Move the samples to a new repo

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

Move the samples to a new repo https://github.com/microsoft/onnxruntime-inference-examples 

**Motivation and Context**
- Why is this change required? What problem does it solve?

To organize them better and setup build pipelines for them.  

Also, it would be easier for us to manage open source usage registrations. Samples typically use 3rd party libraries much more. I don't want to mix them with the main library. Like, I don't want to put tensorflow into https://github.com/microsoft/onnxruntime/blob/master/ThirdPartyNotices.txt just because an ONNX Runtime sample uses it.  It would confuse people who just want to import the main onnxruntime library.

- If it fixes an open issue, please link to the issue here.

Related PR: https://github.com/microsoft/onnxruntime-inference-examples/pull/12

### CODE REVIEW

**Review by thiagocrepaldi — COMMENTED** [review]
I would create a folder that indicates the type of sample, such as samples/training/ortmodule/nodejs, samples/training/training/orttrainer/nodejs, samples/inference

This way we can properly set code owners without conflicts

**Comment by snnn** [comment]
> I would create a folder that indicates the type of sample, such as samples/training/ortmodule/nodejs, samples/training/training/orttrainer/nodejs, samples/inference
> 
> This way we can properly set code owners without conflicts

Training samples should go to https://github.com/microsoft/onnxruntime-training-examples. Does [this folder](https://github.com/microsoft/onnxruntime/tree/master/samples) have training samples?

**Comment by snnn** [comment]
I found one: samples/python/pytorch_transformer

**Comment by snnn** [comment]
Another one: samples/python/mnist

**Comment by snnn** [comment]
Related PR: #8335 . Sherlock is moving the training samples to training dir.

**Comment by thiagocrepaldi** [comment]
> > I would create a folder that indicates the type of sample, such as samples/training/ortmodule/nodejs, samples/training/training/orttrainer/nodejs, samples/inference
> > This way we can properly set code owners without conflicts
> 
> Training samples should go to https://github.com/microsoft/onnxruntime-training-examples. Does [this folder](https://github.com/microsoft/onnxruntime/tree/master/samples) have training samples?
> 
> In the new repo I will follow your advice and setup code owners. For example, iOS to the mobile team and c_cxx to the people under Pranav.

There are 2 for ORTTrainer pytorch forntend: python/mnist and python/pytorch_transformer. They are used for some end-to-end test

**Review by thiagocrepaldi — APPROVED** [review]
Check with quantization team about this removal. They often check in stuff to the samples folder

**Review by yufenglee — APPROVED** [review]
:shipit:

**Pull request merged**
