### PR TITLE
Update ORTSRV integration test model path

### PR DESCRIPTION
**Pull request by NonStatic2014**
**Description**: Update the build script to use pre-downloaded test models other than download mnist model every times

**Motivation and Context**
- Why is this change required? What problem does it solve?
The blob storage for test model is going to be offline. Need to switch to pre-download test model. Otherwise the test will fail due to missing model file.

- If it fixes an open issue, please link to the issue here.
N/A

### CODE REVIEW

**Comment by snnn** [comment]
Do you want it be in our next release or not?

**Comment by NonStatic2014** [comment]
> Do you want it be in our next release or not?

It would be great to apply this change everywhere, then the blob storage currently in use could be turned to not public facing.

**Comment by Klein-Hu** [comment]
All below CI builds passed, not sure why the "Check" tab has not been updated yet:

* Linux CPU CI: https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=91959&view=results
* Linux nGraph CI: https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=91960&view=results
* centos7_cpu CI: https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=91961&view=results

**Comment by pranavsharma** [comment]
> All below CI builds passed, not sure why the "Check" tab has not been updated yet:
> 
> * Linux CPU CI: https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=91959&view=results
> * Linux nGraph CI: https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=91960&view=results
> * centos7_cpu CI: https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=91961&view=results

We're aware of the issue and have reached out to the azure devops folks to investigate.

**Pull request merged**
