### PR TITLE
Enable onnx_test_runner to run the whole models dir in CI machine

### PR DESCRIPTION
**Pull request by mszhanyi**
### Description
1. If the model should be skipped, don't load it.
2. print loaded tests and skipped tests
3. add more same filters as of the onnxruntime_test_all.

### CODE REVIEW

**Comment by snnn** [comment]
`<filesystem>` is not supported in iOS build.  If you only use the file in test programs, we might be able to make it work by setting MACOSX_DEPLOYMENT_TARGET to a higher value for the test programs. You may give a try. 
If you don't want to try it, find another way.

**Comment by justinchuby** [comment]
LGTM but I may not have enough context for this PR. I would wait for @snnn. Thanks!

**Review by thiagocrepaldi — COMMENTED** [review]
There should have some comment/doc somewhere (besides the PR description) explaining how devs can skip tests, if there are naming conventions for the automatic loading etc

**Comment by mszhanyi** [comment]
> LGTM but I may not have enough context for this PR. I would wait for @snnn. Thanks!

This PR is mostly used for CI.

So far, we have 2 methods to run model tests.
one is onnxruntime_test_all, which is based on google test. Most CIs are running model tests with onnxruntime_test_all.
Another is onnx_test_runner, that model tests could be run parallelly easily.  A few CIs are using it.
We wish we could use onnx_test_runner as possible to reduce the duration of model testing.

There're already a lot of models saved in CI machine, and the latest models from onnx model zoo will be synced to the CI machines.
But some models are not supported by all EPs, so we have added some skip lists to pass the tests. 
Due to history reasons, the skip lists are different for these 2 methods.
Thus, onnx_test_runner will fail if it's used to run all models in the CI machine.
The PR is to solve this issue.

**Review by snnn — APPROVED** [review]

**Pull request merged**
