### PR TITLE
[MIGraphX EP] enable compilation and execution on Windows (#36)

### PR DESCRIPTION
**Pull request by TedThemistokleous**
* enable MIGraphX EP on Windows

* [MIGraphX EP] Fix provider options

* fix formatting

* unify the package name for both rocm and migraphx

* fix compilation after moving to rocm6.2

* make STREAM_SYNC the default

* workaround hip sdk bug on windows

* Revert rename of private var for now

---------

### Description

Adds Windows compile for the MIGraphX EP

### Motivation and Context

Allows for additional OS support for MIGraphX Execution provider.

### CODE REVIEW

**Comment by TedThemistokleous** [comment]
ping @cloudhan @PeixuanZuo Critical changes that speed up our compiles + allow for windows support for our EP

@apwojcik did some solid work here.

**Comment by phudtran** [comment]
Will this also add support for building ROCm on Windows? According to these [docs](https://onnxruntime.ai/docs/build/eps.html#amd-migraphx), `The MIGraphX execution provider for ONNX Runtime is built and tested with ROCm6.0.0` but Windows ROCm is still on version 5.7.1 which is only compatible with ONNX runtime 1.17

https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html
https://onnxruntime.ai/docs/execution-providers/ROCm-ExecutionProvider.html#requirements

**Comment by phudtran** [comment]
> > Will this also add support for building ROCm on [Windows](https://onnxruntime.ai/docs/build/eps.html#amd-rocm)? 
> 
> 
> 
> No, only MIGraphX EP. A few pieces still need to be included to have ROCm EP on Windows.
> 
> 
> 
> > According to these [docs](https://onnxruntime.ai/docs/build/eps.html#amd-migraphx), `The MIGraphX execution provider for ONNX Runtime is built and tested with ROCm6.0.0` but Windows ROCm is still on version 5.7.1 which is only compatible with ONNX runtime 1.17
> 
> > 
> 
> > https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html https://onnxruntime.ai/docs/execution-providers/ROCm-ExecutionProvider.html#requirements
> 
> 
> 
> We separated both EPs, and the MIGraphX EP is independent of this PR—it does not need to be built with the ROCm EP. Furthermore, one can use the standard compiler to build the MIGraphX EP (we use MSVC C++ on Windows). ROCm EP still requires the presence of the HIP SDK.
> 
> 
> 
> 

Thank you for the clarification! Can you tell me which AMD GPU's support MIGraphX?

**Comment by TedThemistokleous** [comment]
> Will this also add support for building ROCm on [Windows](https://onnxruntime.ai/docs/build/eps.html#amd-rocm)? According to these [docs](https://onnxruntime.ai/docs/build/eps.html#amd-migraphx), `The MIGraphX execution provider for ONNX Runtime is built and tested with ROCm6.0.0` but Windows ROCm is still on version 5.7.1 which is only compatible with ONNX runtime 1.17
> 
> https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html https://onnxruntime.ai/docs/execution-providers/ROCm-ExecutionProvider.html#requirements

We support newer ROCm 6.1.x and constantly update with every ROCm Release. I'll need to update the docs as well.

**Comment by TedThemistokleous** [comment]
> > > Will this also add support for building ROCm on [Windows](https://onnxruntime.ai/docs/build/eps.html#amd-rocm)?
> > 
> > 
> > No, only MIGraphX EP. A few pieces still need to be included to have ROCm EP on Windows.
> > > According to these [docs](https://onnxruntime.ai/docs/build/eps.html#amd-migraphx), `The MIGraphX execution provider for ONNX Runtime is built and tested with ROCm6.0.0` but Windows ROCm is still on version 5.7.1 which is only compatible with ONNX runtime 1.17
> > 
> > 
> > > 
> > 
> > 
> > > https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html https://onnxruntime.ai/docs/execution-providers/ROCm-ExecutionProvider.html#requirements
> > 
> > 
> > We separated both EPs, and the MIGraphX EP is independent of this PR—it does not need to be built with the ROCm EP. Furthermore, one can use the standard compiler to build the MIGraphX EP (we use MSVC C++ on Windows). ROCm EP still requires the presence of the HIP SDK.
> 
> Thank you for the clarification! Is there existing documentation on which GPUs support MIGraphX? Is it only Instinct GPUs?

No, Navi 2x and Navi 3x based cards are also able to run on MIGraphX as well.

See the "Supported GPUs" section here: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html

**Review by snnn — APPROVED** [review]

**Comment by snnn** [comment]
Sorry there were some issues in the build. Please recreate this PR.

**Comment by TedThemistokleous** [comment]
> Sorry there were some issues in the build. Please recreate this PR.

What's the issue here?

**Comment by cloudhan** [comment]
@TedThemistokleous 

```
2024-06-20T23:30:54.4091137Z CMake Error at onnxruntime_providers_migraphx.cmake:25 (cmake_policy):
2024-06-20T23:30:54.4092009Z   Policy "CMP0144" is not known to this version of CMake.
2024-06-20T23:30:54.4092552Z Call Stack (most recent call first):
2024-06-20T23:30:54.4092974Z   onnxruntime_providers.cmake:172 (include)
2024-06-20T23:30:54.4093371Z   CMakeLists.txt:1749 (include)
2024-06-20T23:30:54.4093598Z 
2024-06-20T23:30:54.4093724Z 
2024-06-20T23:30:54.5255585Z CMake Warning (dev) at onnxruntime_rocm_hipify.cmake:168:
2024-06-20T23:30:54.5256617Z   Syntax Warning in cmake code at column 26
2024-06-20T23:30:54.5256915Z 
2024-06-20T23:30:54.5257373Z   Argument not separated from preceding token by whitespace.
2024-06-20T23:30:54.5257887Z Call Stack (most recent call first):
2024-06-20T23:30:54.5258469Z   onnxruntime_providers_rocm.cmake:5 (include)
2024-06-20T23:30:54.5259083Z   onnxruntime_providers.cmake:184 (include)
2024-06-20T23:30:54.5259578Z   CMakeLists.txt:1749 (include)
2024-06-20T23:30:54.5260521Z This warning is for project developers.  Use -Wno-dev to suppress it.
2024-06-20T23:30:54.5260780Z 
2024-06-20T23:30:54.5261154Z CMake Warning (dev) at onnxruntime_rocm_hipify.cmake:169:
2024-06-20T23:30:54.5261587Z   Syntax Warning in cmake code at column 25
2024-06-20T23:30:54.5261788Z 
2024-06-20T23:30:54.5262119Z   Argument not separated from preceding token by whitespace.
2024-06-20T23:30:54.5262525Z Call Stack (most recent call first):
2024-06-20T23:30:54.5262926Z   onnxruntime_providers_rocm.cmake:5 (include)
2024-06-20T23:30:54.5263345Z   onnxruntime_providers.cmake:184 (include)
2024-06-20T23:30:54.5263740Z   CMakeLists.txt:1749 (include)
```

**Comment by TedThemistokleous** [comment]
> @TedThemistokleous https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1415831&view=logs&j=de55e6b9-e644-5941-5c9e-9db93f25fbbe&t=b93ed647-1ade-5719-e8ee-b4d0a50e0589
> 
> ```
> 2024-06-20T23:30:54.4091137Z CMake Error at onnxruntime_providers_migraphx.cmake:25 (cmake_policy):
> 2024-06-20T23:30:54.4092009Z   Policy "CMP0144" is not known to this version of CMake.
> 2024-06-20T23:30:54.4092552Z Call Stack (most recent call first):
> 2024-06-20T23:30:54.4092974Z   onnxruntime_providers.cmake:172 (include)
> 2024-06-20T23:30:54.4093371Z   CMakeLists.txt:1749 (include)
> 2024-06-20T23:30:54.4093598Z 
> 2024-06-20T23:30:54.4093724Z 
> 2024-06-20T23:30:54.5255585Z CMake Warning (dev) at onnxruntime_rocm_hipify.cmake:168:
> 2024-06-20T23:30:54.5256617Z   Syntax Warning in cmake code at column 26
> 2024-06-20T23:30:54.5256915Z 
> 2024-06-20T23:30:54.5257373Z   Argument not separated from preceding token by whitespace.
> 2024-06-20T23:30:54.5257887Z Call Stack (most recent call first):
> 2024-06-20T23:30:54.5258469Z   onnxruntime_providers_rocm.cmake:5 (include)
> 2024-06-20T23:30:54.5259083Z   onnxruntime_providers.cmake:184 (include)
> 2024-06-20T23:30:54.5259578Z   CMakeLists.txt:1749 (include)
> 2024-06-20T23:30:54.5260521Z This warning is for project developers.  Use -Wno-dev to suppress it.
> 2024-06-20T23:30:54.5260780Z 
> 2024-06-20T23:30:54.5261154Z CMake Warning (dev) at onnxruntime_rocm_hipify.cmake:169:
> 2024-06-20T23:30:54.5261587Z   Syntax Warning in cmake code at column 25
> 2024-06-20T23:30:54.5261788Z 
> 2024-06-20T23:30:54.5262119Z   Argument not separated from preceding token by whitespace.
> 2024-06-20T23:30:54.5262525Z Call Stack (most recent call first):
> 2024-06-20T23:30:54.5262926Z   onnxruntime_providers_rocm.cmake:5 (include)
> 2024-06-20T23:30:54.5263345Z   onnxruntime_providers.cmake:184 (include)
> 2024-06-20T23:30:54.5263740Z   CMakeLists.txt:1749 (include)
> ```

That requires the use of CMake >= 3.27.0. We've updated this on our end as it appears CMake was pinned to 3.26.4 and we assumed you were updated to the later version.  Are you saying we need to roll back CMake then?

More info here: https://cmake.org/cmake/help/latest/policy/CMP0144.html

**Pull request merged**
