### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ndalton12**
Added `--gpus` flag to TensorRT docker instructions.

**Description**: Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by thiagocrepaldi — APPROVED** [review]

**Review by snnn — APPROVED** [review]

**Comment by edgchen1** [comment]
Thanks for the PR. We will update this README as other changes are needed too. Closing this for now.
CC: @jywu-msft

**Pull request closed without merging**
