### PR TITLE
Update VERSION_NUMBER

### PR DESCRIPTION
**Pull request by snnn**
### Description

1. Update VERSION_NUMBER for preparing the upcoming release. This PR's commit will not be included in the 1.15 release branch
2. Delete package/rpm/onnxruntime.spec since it was not used in past years. 

### Motivation and Context
Preparing the release.

Fixed [AB#15311](https://aiinfra.visualstudio.com/6a833879-cd9b-44a4-a9de-adc2d818f13c/_workitems/edit/15311)

### CODE REVIEW

**Comment by fs-eire** [comment]
https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/session/onnxruntime_c_api.cc#L2749-L2755

**Comment by fs-eire** [comment]
JS part ( package.json/package-lock.json/yarn.lock ) looks good to me.

**Comment by fs-eire** [comment]
> https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/session/onnxruntime_c_api.cc#L2749-L2755

should we add code to update this into tools\python\update_version.py ?

**Comment by snnn** [comment]
> > https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/session/onnxruntime_c_api.cc#L2749-L2755
> 
> should we add code to update this into tools\python\update_version.py ?

onnxruntime_c_api.cc is a C/C++ file. It's difficult to parse.

**Review by pranavsharma — APPROVED** [review]

**Pull request merged**
