### PR TITLE
Adopt linrtunner as the linting tool - take 2

### PR DESCRIPTION
**Pull request by justinchuby**
### Description

`lintrunner` is a linter runner successfully used by pytorch, onnx and onnx-script. It provides a uniform experience running linters locally and in CI. It supports all major dev systems: Windows, Linux and MacOs. The checks are enforced by the `Python format` workflow.

This PR adopts `lintrunner` to onnxruntime and fixed ~2000 flake8 errors in Python code. `lintrunner` now runs all required python lints including `ruff`(replacing `flake8`), `black` and `isort`. Future lints like `clang-format` can be added.

Most errors are auto-fixed by `ruff` and the fixes should be considered robust. 

Lints that are more complicated to fix are applied `# noqa` for now and should be fixed in follow up PRs.

### Notable changes

1. This PR **removed some suboptimal patterns**:

	- `not xxx in` -> `xxx not in` membership checks
	- bare excepts (`except:` -> `except Exception`)
	- unused imports
	
	The follow up PR will remove:
	
	- `import *`
	- mutable values as default in function definitions (`def func(a=[])`)
	- more unused imports
	- unused local variables

2. Use `ruff` to replace `flake8`. `ruff` is much (40x) faster than flake8 and is more robust. We are using it successfully in onnx and onnx-script. It also supports auto-fixing many flake8 errors.

3. Removed the legacy flake8 ci flow and updated docs.

4. The added workflow supports SARIF code scanning reports on github, example snapshot:
	
	image

5. Removed `onnxruntime-python-checks-ci-pipeline` as redundant

### Motivation and Context

Unified linting experience in CI and local.

Replacing https://github.com/microsoft/onnxruntime/pull/14306

### CODE REVIEW

**Comment by justinchuby** [comment]
orttraining/orttraining/test/python/orttraining_test_ortmodule_api.py Need to remove evals

**Comment by justinchuby** [comment]
Also orttraining/orttraining/eager/test/ort_ops.py

**Comment by justinchuby** [comment]
I Will remove the evals in a PR then rebase this on it

**Review by mszhanyi — DISMISSED** [review]

**Comment by justinchuby** [comment]
@edgchen1 i removed the onnxruntime-python-check pipeline. Could you take a look?

**Review by edgchen1 — DISMISSED** [review]
signing off on removal of old build definition files. haven't reviewed all other files in this change.

**Review by snnn — APPROVED** [review]

**Pull request merged**
