### PR TITLE
Fix wrong per-tensor quantized weight type for matmul

### PR DESCRIPTION
**Pull request by duanshengliu**
### Description

Fix wrong per-tensor quantized weight type for matmul.

### Motivation and Context

Fix related bug as described in https://github.com/microsoft/onnxruntime/issues/21346

### CODE REVIEW

**Comment by duanshengliu** [comment]
@adrianlizarraga @xadupre Could you please help to review it?

**Comment by duanshengliu** [comment]
@snnn Could you help to run the CI and review?

**Comment by xadupre** [comment]
> @adrianlizarraga Some of the CIs failed, and I don't know how to resolve it. Is it a problem with the committed code?

The error is a C++ compilation error and your changes are python. This pipeline is green right now. I suggest updating your branch with main branch. The test should pass.

**Comment by duanshengliu** [comment]
> > @adrianlizarraga Some of the CIs failed, and I don't know how to resolve it. Is it a problem with the committed code?
> 
> The error is a C++ compilation error and your changes are python. This pipeline is green right now. I suggest updating your branch with main branch. The test should pass.

Thanks, could you run the CI again.

**Comment by duanshengliu** [comment]
@adrianlizarraga Could you review the code?

**Comment by duanshengliu** [comment]
@xadupre  Could you review the code?

**Comment by duanshengliu** [comment]
@yihonglyu Do you have time to review?

**Comment by adrianlizarraga** [comment]
@yufenglee @xadupre This PR looks good to me, but I wanted to get your input.

Currently, all MatMul inputs (regardless of whether they are initializers) are considered "activations" and use the activation quantization type. Instead, this PR makes initializer inputs use the weight quantization type, which makes sense to me.

**Review by adrianlizarraga — APPROVED** [review]

**Comment by duanshengliu** [comment]
> @yufenglee @xadupre This PR looks good to me, but I wanted to get your input.
> 
> Currently, all MatMul inputs (regardless of whether they are initializers) are considered "activations" and use the activation quantization type. Instead, this PR makes initializer inputs use the weight quantization type, which makes sense to me.

@yihonglyu @xadupre @yufenglee, PTAL

**Review by yufenglee — APPROVED** [review]

**Comment by yufenglee** [comment]
Could you please sync to the main branch to trigger the new CI pipelines?

**Comment by duanshengliu** [comment]
> Could you please sync to the main branch to trigger the new CI pipelines?

Done, could you please start CI pipelines?

**Review by adrianlizarraga — APPROVED** [review]

**Comment by duanshengliu** [comment]
@yihonglyu @adrianlizarraga, since the previous `whisper` test failed, could you please start the CI pipelines again?

**Comment by duanshengliu** [comment]
> /azp run Windows GPU CUDA CI Pipeline, Windows GPU DML CI Pipeline, Windows GPU Doc Gen CI Pipeline

@yufenglee, it seems that the `Windows GPU CUDA CI Pipeline` cannot be properly trigger consistently even if I have synced to the main branch multiple times.

**Comment by yufenglee** [comment]
> > /azp run Windows GPU CUDA CI Pipeline, Windows GPU DML CI Pipeline, Windows GPU Doc Gen CI Pipeline
> 
> @yufenglee, it seems that the `Windows GPU CUDA CI Pipeline` cannot be properly triggered consistently even if I have synced to the main branch multiple times.

I just triggered them manually. It is a pipeline issue. Following up.

**Comment by adrianlizarraga** [comment]
@duanshengliu Thank you!

**Pull request merged**
