### PR TITLE
Downgrade to C++11

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 
To support CentOS 7.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by KeDengMS** [comment]
This change seems quite intrusive and unnecessary. Could we add [instructions for CentOS users to build g++ from source](https://benjaminberhault.com//post/2018/06/22/install-gcc-on-rhel-centos-7.html) instead?

**Comment by snnn** [comment]
> This change seems unnecessarily intrusive. Could we add [instructions for CentOS users to build g++ from source](https://benjaminberhault.com//post/2018/06/22/install-gcc-on-rhel-centos-7.html) instead?

No. It won't work. The problem is far more complex than that.

**Comment by KeDengMS** [comment]
> > This change seems unnecessarily intrusive. Could we add [instructions for CentOS users to build g++ from source](https://benjaminberhault.com//post/2018/06/22/install-gcc-on-rhel-centos-7.html) instead?
> 
> No. It won't work. The problem is far more complex than that.

Could you elaborate? The downgrade from C++14 to C++11 would cause lots of changes in pending PRs, and taking away lots of good stuffs like make_shared. It would better to have good justification for this level of changes.

**Comment by snnn** [comment]
Hi @KeDengMS 

This task is customer driven.  Our PM has a long list of compatibility issues, and we found downgrade to C++11 is the only way to solve all of them.

But, it's not about to make all of the code to be C++11. If nuphar wants to stay at C++14, that's fine. 

For the technical details, we may talk offline. In short, the binaries compiled from different compilers can't be mixed together. It makes harder to integrate ORT with the other softwares. We want to make ORT more portable and popular.

**Comment by skottmckay** [comment]
Was there any consideration given to using the std::make_unique replacement from absl? https://abseil.io/tips/126

**Comment by snnn** [comment]
We don't directly depend on absl yet. If someone wants it, that's ok. But currently the most straightforward way is using new. Because that doesn't need to go through another design review.

**Comment by snnn** [comment]
And thanks for your tip, I really want to use it in the future changes.

**Comment by pranavsharma** [comment]
I was hoping that we continue to use make_unique (whether it comes from abseil or authored by us). The change would've been to only change the namespace prefix wherever make_unique is used.

**Comment by walrusmcd** [comment]
authoring our own make_unique is a solid idea.    or at least someway to hide the fact from the rest of the code that the entire coding pattern needs to suddenly change (unique_ptr, shared_ptr) .

**Comment by snnn** [comment]
If someone can port a make_unique implementation into our code, and validate it works on all these compiler versions we'll support, and make it happen in the next 1-2 weeks, I'm glad to see and use it, and really thanks. 
Otherwise, I want to finish this change as soon as possible. Because I'm in charge of the next release, this task is in the list, I don't want to delay it. I can't see any performance issue or correctness issue of not using make_unique.  Indeed compiler's make_unique implementation is rather simple:
https://github.com/llvm-mirror/libcxx/blob/master/include/memory#L2998

**Comment by KeDengMS** [comment]
> If someone can port a make_unique implementation into our code, and validate it works on all these compiler versions we'll support, and make it happen in the next 1-2 weeks, I'm glad to see and use it, and really thanks.
> Otherwise, I want to finish this change as soon as possible. Because I'm in charge of the next release, this task is in the list, I don't want to delay it. I can't see any performance issue or correctness issue of not using make_unique. Indeed compiler's make_unique implementation is rather simple:
> https://github.com/llvm-mirror/libcxx/blob/master/include/memory#L2998

I believe that  ORT should maintain a unified coding style instead of allowing both C++11 and C++14. As for my pending PR to Nuphar, I have no problem spending time to make it consistent with C++11, if we believe it is better to use std::unique_ptr<T>(new T(...)) in our code.

Given that, though I understood that there are release schedules and works in the queue, I'd still like to make sure we considered the impact of this change for all people working in ORT as a team, instead of just this PR alone. The decision we made here would not only affect Nuphar, but also for other internal/external partners who work on the same code base.

**Comment by pranavsharma** [comment]
> If someone can port a make_unique implementation into our code, and validate it works on all these compiler versions we'll support, and make it happen in the next 1-2 weeks, **I'm glad to see and use it, and really thanks.**
> 
> Otherwise, I want to finish this change as soon as possible. Because I'm in charge of the next release, this task is in the list, I don't want to delay it. I can't see any performance issue or correctness issue of not using make_unique. Indeed compiler's make_unique implementation is rather simple:
> https://github.com/llvm-mirror/libcxx/blob/master/include/memory#L2998
> When it get compiled to binary code, there shouldn't be any difference with directly calling new() in our code.
> 
> And, at last, we had a discussion of whether we should enforce using unique_ptr. The conclusion is clearly no. "There is no need to mandate on unique_ptr". Therefore, I can't see the value of enforce using make_unique, given it's not provided by the compiler and it can't bring any perf benefit.

Just FYI: our own Herb Sutter has talked about this here (question 3): https://herbsutter.com/2013/05/29/gotw-89-solution-smart-pointers/.

**Comment by snnn** [comment]
Abandon it now.

**Comment by snnn** [comment]
I had a talk with Pranav offline. He asked me a question:"Do you think make_unique is better than unique_ptr<...>(new ...)". I answered yes but now I think I was wrong. 
Below is my conclusion:
1. In C++11, No. Because there isn't it. Even if it existed, until you can make every constructor exceptional safe,  it doesn't help. 
2. In C++14, Yes
3. In C++17, No. It makes no sense.  see https://stackoverflow.com/questions/53870522/why-use-stdmake-unique-in-c17 

make_unique is added in C++14 but soon become useless in C++17. Then why do we so fascinate on it?

**Comment by snnn** [comment]
> I was hoping that we continue to use make_unique (whether it comes from abseil or authored by us). The change would've been to only change the namespace prefix wherever make_unique is used.

@pranavsharma  Did I misunderstand something? I thought you against replacing the make_unique with "operator new".

**Pull request closed without merging**
