### PR TITLE
OpenVino add build_shared_lib flag in the build command

### PR DESCRIPTION
**Pull request by sfatimar**
We were not able to build C++ samples without build_shared_lib flag in the build command. 

**Motivation and Context**
- This changes was required in dockerfiles to enable c++ sample build 
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by jywu-msft** [comment]
is it really necessary to change the dockerfiles? (which are for building python bindings/package)
the build_shared_lib option is for onnxruntime lib.
openvino ep gets built as a shared lib regardless of whether build_shared_lib option is enabled.

**Comment by sfatimar** [comment]
We have added build_shared_lib to build libonnxruntime.so as some developers found that it was easier to build C++ samples this way.

**Comment by MaajidKhan** [comment]
> is it really necessary to change the dockerfiles? (which are for building python bindings/package)
> the build_shared_lib option is for onnxruntime lib.
> openvino ep gets built as a shared lib regardless of whether build_shared_lib option is enabled.

Hello George. To build the CPP samples that are already available here **https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx**, we need the libonnxruntime.so shared lib to be linked while compiling along with two other shared libs (libonnxruntime_providers_shared.so and libonnxruntime_providers_openvino.so).

Without this libonnxruntime.so lib, when we try compiling, it doesn't get compiled with this error.
**/tmp/cctSSMOx.o: In function `__static_initialization_and_destruction_0(int, int)':
squeezenet_cpp_app.cpp:(.text+0x1c03): undefined reference to `OrtGetApiBase'
collect2: error: ld returned 1 exit status**

so, we thought of adding --build_shared_lib flag as default while compiling OpenVINO-EP, so that the developers won't have issues building CPP samples.

we added the same flag inside the docker files which are for building python bindings/package because anyways the onnxruntime dir gets deleted as part of optimization at this line
https://github.com/microsoft/onnxruntime/blob/f14c621c103e1880aa12abd5d148c98318741f5f/dockerfiles/Dockerfile.openvino#L89.   

so, if some user wants to use the same docker file to build CPP samples, all he has to do is remove this step.

**Comment by jywu-msft** [comment]
> > is it really necessary to change the dockerfiles? (which are for building python bindings/package)
> > the build_shared_lib option is for onnxruntime lib.
> > openvino ep gets built as a shared lib regardless of whether build_shared_lib option is enabled.
> 
> Hello George. To build the CPP samples that are already available here **https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx**, we need the libonnxruntime.so shared lib to be linked while compiling along with two other shared libs (libonnxruntime_providers_shared.so and libonnxruntime_providers_openvino.so).
> 
> Without this libonnxruntime.so lib, when we try compiling, it doesn't get compiled with this error.
> **/tmp/cctSSMOx.o: In function `__static_initialization_and_destruction_0(int, int)': squeezenet_cpp_app.cpp:(.text+0x1c03): undefined reference to `OrtGetApiBase' collect2: error: ld returned 1 exit status**
> 
> so, we thought of adding --build_shared_lib flag as default while compiling OpenVINO-EP, so that the developers won't have issues building CPP samples.
> 
> we added the same flag inside the docker files which are for building python bindings/package because anyways the onnxruntime dir gets deleted as part of optimization at this line
> https://github.com/microsoft/onnxruntime/blob/f14c621c103e1880aa12abd5d148c98318741f5f/dockerfiles/Dockerfile.openvino#L89
> 
> .
> so, if some user wants to use the same docker file to build CPP samples, all he has to do is remove this step.

yes, understood that the CPP sample needs the libonnxruntime.so 
On the other hand, I was questioning the usefulness of adding the build option in the dockerfile.openvino (whose main purpose is to build and install the python package). 
As you mentioned, the build directory gets deleted so the libonnxruntime.so would also get removed.

**Comment by jywu-msft** [comment]
> Azure Pipelines successfully started running 9 pipeline(s).



> > > is it really necessary to change the dockerfiles? (which are for building python bindings/package)
> > > the build_shared_lib option is for onnxruntime lib.
> > > openvino ep gets built as a shared lib regardless of whether build_shared_lib option is enabled.
> > 
> > 
> > Hello George. To build the CPP samples that are already available here **https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx**, we need the libonnxruntime.so shared lib to be linked while compiling along with two other shared libs (libonnxruntime_providers_shared.so and libonnxruntime_providers_openvino.so).
> > Without this libonnxruntime.so lib, when we try compiling, it doesn't get compiled with this error.
> > **/tmp/cctSSMOx.o: In function `__static_initialization_and_destruction_0(int, int)': squeezenet_cpp_app.cpp:(.text+0x1c03): undefined reference to `OrtGetApiBase' collect2: error: ld returned 1 exit status**
> > so, we thought of adding --build_shared_lib flag as default while compiling OpenVINO-EP, so that the developers won't have issues building CPP samples.
> > we added the same flag inside the docker files which are for building python bindings/package because anyways the onnxruntime dir gets deleted as part of optimization at this line
> > https://github.com/microsoft/onnxruntime/blob/f14c621c103e1880aa12abd5d148c98318741f5f/dockerfiles/Dockerfile.openvino#L89
> > 
> > .
> > so, if some user wants to use the same docker file to build CPP samples, all he has to do is remove this step.
> 
> yes, understood that the CPP sample needs the libonnxruntime.so
> On the other hand, I was questioning the usefulness of adding the build_shared_lib option in the dockerfile.openvino (whose main purpose is to build and install the python package).
> As you mentioned, the build directory gets deleted so the libonnxruntime.so would also get removed.

ok i missed your comment that the user would need to comment out the step which removes the build directory.
yes, i suppose that is true. you might as well add a comment about that if that is the case.
otherwise i doubt the user would know this up front.

**Comment by HectorSVC** [comment]
> > > is it really necessary to change the dockerfiles? (which are for building python bindings/package)
> > > the build_shared_lib option is for onnxruntime lib.
> > > openvino ep gets built as a shared lib regardless of whether build_shared_lib option is enabled.
> > 
> > 
> > Hello George. To build the CPP samples that are already available here **https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx**, we need the libonnxruntime.so shared lib to be linked while compiling along with two other shared libs (libonnxruntime_providers_shared.so and libonnxruntime_providers_openvino.so).
> > Without this libonnxruntime.so lib, when we try compiling, it doesn't get compiled with this error.
> > **/tmp/cctSSMOx.o: In function `__static_initialization_and_destruction_0(int, int)': squeezenet_cpp_app.cpp:(.text+0x1c03): undefined reference to `OrtGetApiBase' collect2: error: ld returned 1 exit status**
> > so, we thought of adding --build_shared_lib flag as default while compiling OpenVINO-EP, so that the developers won't have issues building CPP samples.
> > we added the same flag inside the docker files which are for building python bindings/package because anyways the onnxruntime dir gets deleted as part of optimization at this line
> > https://github.com/microsoft/onnxruntime/blob/f14c621c103e1880aa12abd5d148c98318741f5f/dockerfiles/Dockerfile.openvino#L89
> > 
> > .
> > so, if some user wants to use the same docker file to build CPP samples, all he has to do is remove this step.
> 
> yes, understood that the CPP sample needs the libonnxruntime.so
> On the other hand, I was questioning the usefulness of adding the build_shared_lib option in the dockerfile.openvino (whose main purpose is to build and install the python package).
> As you mentioned, the build directory gets deleted so the libonnxruntime.so would also get removed.

I think what they mean is that some user reuse same docker file for development, the developer will comment out the line which delete the build directory. For normal user build docker image directly from the original docker file, they won't aware of the libonnxruntime.so file since it will be deleted anyway.

**Comment by MaajidKhan** [comment]
> > > > is it really necessary to change the dockerfiles? (which are for building python bindings/package)
> > > > the build_shared_lib option is for onnxruntime lib.
> > > > openvino ep gets built as a shared lib regardless of whether build_shared_lib option is enabled.
> > > 
> > > 
> > > Hello George. To build the CPP samples that are already available here **https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx**, we need the libonnxruntime.so shared lib to be linked while compiling along with two other shared libs (libonnxruntime_providers_shared.so and libonnxruntime_providers_openvino.so).
> > > Without this libonnxruntime.so lib, when we try compiling, it doesn't get compiled with this error.
> > > **/tmp/cctSSMOx.o: In function `__static_initialization_and_destruction_0(int, int)': squeezenet_cpp_app.cpp:(.text+0x1c03): undefined reference to `OrtGetApiBase' collect2: error: ld returned 1 exit status**
> > > so, we thought of adding --build_shared_lib flag as default while compiling OpenVINO-EP, so that the developers won't have issues building CPP samples.
> > > we added the same flag inside the docker files which are for building python bindings/package because anyways the onnxruntime dir gets deleted as part of optimization at this line
> > > https://github.com/microsoft/onnxruntime/blob/f14c621c103e1880aa12abd5d148c98318741f5f/dockerfiles/Dockerfile.openvino#L89
> > > 
> > > .
> > > so, if some user wants to use the same docker file to build CPP samples, all he has to do is remove this step.
> > 
> > 
> > yes, understood that the CPP sample needs the libonnxruntime.so
> > On the other hand, I was questioning the usefulness of adding the build_shared_lib option in the dockerfile.openvino (whose main purpose is to build and install the python package).
> > As you mentioned, the build directory gets deleted so the libonnxruntime.so would also get removed.
> 
> I think what they mean is that some user reuse same docker file for development, the developer will comment out the line which delete the build directory. For normal user build docker image directly from the original docker file, they won't aware of the libonnxruntime.so file since it will be deleted anyway.

Right Hector. This is the main reason, we added the option in the docker file. so, that we don't have to explicitly tell the user every time that they need to add this flag themselves if they want to work with CPP samples.

**Review by HectorSVC — APPROVED** [review]

**Pull request merged**
