### PR TITLE
Cherry pick PRs to release branch rel-1.3.0

### PR DESCRIPTION
**Pull request by stevenlix**
**Cherry picked PRs**
Register Dropout(12) as inference op, https://github.com/microsoft/onnxruntime/pull/3859
Re-enable Dropout(12) ONNX tests, https://github.com/microsoft/onnxruntime/pull/3833
Bump ONNX version, https://github.com/microsoft/onnxruntime/pull/3888
Huggingface optimization, https://github.com/microsoft/onnxruntime/pull/3850
MLAS update, https://github.com/microsoft/onnxruntime/pull/3846
More types for murmurhash, https://github.com/microsoft/onnxruntime/pull/3827
Fix C# log APIs, https://github.com/microsoft/onnxruntime/pull/3840
Teams team model, https://github.com/microsoft/onnxruntime/pull/3868
Use MlasComputeSoftmax in traditional ML ops, https://github.com/microsoft/onnxruntime/pull/3892
Added aarch64 build pipeline, https://github.com/microsoft/onnxruntime/pull/3841
Update TensorRT dynamic shape profile when input shape changed during runtime, https://github.com/microsoft/onnxruntime/pull/3904
fix dnnl ep build break on Linux, https://github.com/microsoft/onnxruntime/pull/3874
fix dnnl ep shared lib python packaging, https://github.com/microsoft/onnxruntime/pull/3875
Load provider shared libraries relative to core runtime executable, https://github.com/microsoft/onnxruntime/pull/3884
use LOAD_WITH_ALTERED_SEARCH_PATH for LoadLibraryExA, https://github.com/microsoft/onnxruntime/pull/3908
Merge DML Execution Provider updates, https://github.com/microsoft/onnxruntime/pull/3885
MLAS: tune softmax kernels for partial vectors, https://github.com/microsoft/onnxruntime/pull/3906

### CODE REVIEW

**Comment by skottmckay** [comment]
Can you add this as well please? https://github.com/microsoft/onnxruntime/pull/3906

**Comment by skottmckay** [comment]
Were any manual edits required or are they all clean merges of the cherry picked commits?

**Comment by codemzs** [comment]
> Were any manual edits required or are they all clean merges of the cherry picked commits? 

@skottmckay I’m hoping only git cherry-pick commit-id was used. I plan on reviewing this PR this morning to ensure my changes are cherry picked correctly, however if @stevenlix has made any manual edits then it would be good to know them.

**Comment by codemzs** [comment]
@stevenlix Why was #3888 manually broken into two part? I see you have created an “updated onnx” commit out of it and then the rest is the original commit.

**Comment by stevenlix** [comment]
@codemzs, when I created my branch (from master branch, but reset to release branch) , the onnx submodule has been updated from @8e9c7d5 to @0c070ab, so I pushed it to remote. I didn't manually edit anything. Then I cherry picked #3888 and other PRs.

**Comment by stevenlix** [comment]
@codemzs, @liuziyue, @pranavsharma, @wangyems, @skottmckay, @prabhat00155, @stevenlix, @jywu-msft, @RyanUnderhill, @tracysh, could you please help double check if your PR is picked up correctly.

**Comment by stevenlix** [comment]
We recreated the release branch from master because there are still many PRs coming in for cherry pick. So this PR is closed.

**Pull request closed without merging**
