### PR TITLE
Create suggestions to autofix files

### PR DESCRIPTION
**Pull request by justinchuby**

### CODE REVIEW

**Review by snnn — APPROVED** [review]

**Review by snnn — APPROVED** [review]

**Comment by skottmckay** [comment]
Would be great to see in action. Could this PR have a temporary dummy change that triggers the auto correct suggestion?

**Comment by justinchuby** [comment]
Currently there are two issues with this workflow: https://github.com/parkerbxyz/suggest-changes/issues/36 and https://github.com/parkerbxyz/suggest-changes/issues/37. I am waiting for a response from the repo maintainer

**Comment by justinchuby** [comment]
@snnn could you reapprove? Thanks!

**Review by snnn — APPROVED** [review]
Thanks

**Pull request merged**
