### PR TITLE
[js/webgpu] Optimize conv1d by conv2d

### PR DESCRIPTION
**Pull request by qjia7**
### Description

Optimize conv1d to go to the conv2d path to utilize the conv2d's optimization path.

See whisper-tiny-encoder model becomes 158.66 ms from 532.28 ms. Conv goes to Conv2DMatMul(8 ms) instead of GroupedConv(382 ms).

Old profiling result:
Kernel | Time (ms) | Percentage (%)
-- | -- | --
Conv\|GroupedConv | 382.99 | 71.95
MatMul | 126.16 | 23.70
Softmax | 7.01 | 1.32
Transpose | 4.59 | 0.86
Add | 4.39 | 0.82
Mul | 2.36 | 0.44
Div | 1.44 | 0.27
ReduceMean\|ReduceMeanShared | 1.25 | 0.23
Erf | 0.85 | 0.16
Sub | 0.72 | 0.14
Pow | 0.46 | 0.09
Sqrt | 0.07 | 0.01
Sum | 532.28 |  

New profiling result with this PR:

Kernel | Time (ms) | Percentage (%)
-- | -- | --
MatMul | 127.07 | 80.09
Conv\|Conv2DMatMul | 8.00 | 5.04
Softmax | 6.95 | 4.38
Transpose | 4.65 | 2.93
Add | 4.26 | 2.68
Mul | 2.56 | 1.61
Div | 1.51 | 0.95
ReduceMean\|ReduceMeanShared | 1.31 | 0.83
Erf | 0.85 | 0.54
Sub | 0.79 | 0.50
Pow | 0.46 | 0.29
Conv\|Transpose | 0.26 | 0.17
Sqrt | 0.00 | 0.00
Sum | 158.66 |

### CODE REVIEW

**Comment by qjia7** [comment]
@guschmue @fs-eire @satyajandhyala Please take a look, thanks.

**Comment by qjia7** [comment]
run web CI

**Review by guschmue — DISMISSED** [review]

**Comment by qjia7** [comment]
@guschmue @fs-eire Please review and help trigger the bots again. Thanks.

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
