### PR TITLE
updating python docs to 1.7

### PR DESCRIPTION
**Pull request by oliviajain**
**Description**: Updating python docs to 1.7

### CODE REVIEW

**Comment by xadupre** [comment]
I don't think file python/html/.nojekyll is needed. I think the documentation files were moved from python to python/html. Is it expected?

**Comment by oliviajain** [comment]
> I don't think file python/html/.nojekyll is needed. I think the documentation files were moved from python to python/html. Is it expected?

I copied all the files from onnxruntime/build/docs/html to onnxruntime/python. Should I remove the .nojekyll file? It must have been generated by the script.

**Comment by sdpython** [comment]
> I copied all the files from onnxruntime/build/docs/html to onnxruntime/python. Should I remove the .nojekyll file? It must have been generated by the script.

Yes. If it was not there, let's not add it. This empty file is used by github.io but there should be already one in the parent folder.

**Comment by oliviajain** [comment]
> > I copied all the files from onnxruntime/build/docs/html to onnxruntime/python. Should I remove the .nojekyll file? It must have been generated by the script.
> 
> Yes. If it was not there, let's not add it. This empty file is used by github.io but there should be already one in the parent folder.

Should be fixed now.

**Comment by xadupre** [comment]
I still see folder html. It is like all the python documentation was moved in a new subfolder but if the current website does not reference the new location, the website won't be updated. In the current branch, https://github.com/microsoft/onnxruntime/tree/gh-pages/python, folder html does not exist. Unless you want to archive the previous documentation, it would better to keep the same location.

**Review by xadupre — APPROVED** [review]

**Pull request merged**
