### PR TITLE
[WebNN EP] Change some support status for XNNPack backend

### PR DESCRIPTION
**Pull request by Honry**
WebNN XNNPack backend doesn't really support `pow` and `reduceSum`, and will support `sqrt` very soon.

### CODE REVIEW

**Comment by Honry** [comment]
@fdwr, @guschmue, PTAL, thanks!

**Review by fdwr — APPROVED** [review]

**Comment by skottmckay** [comment]
Out of interest what's the relationship between WebNN and XNNPACK?

**Comment by Honry** [comment]
> Out of interest what's the relationship between WebNN and XNNPACK?

WebNN CPU device implementation in Chromium is based on XNNPack, and GPU device is based on DirectML. :)

**Pull request merged**
