### PR TITLE
cherry picked commits for rel-1.8.1

### PR DESCRIPTION
**Pull request by harshithapv**
The following 15 commits as of 06/16/2021 are cherry-picked in this PR for rel-1.8.1.
Reduce Kernel Optimization  component:training-core release:1.8.1
#8067 by iK1D was merged 8 hours ago
• Approved 

fix PATH addition in windows  release:1.8.1
#8043 by iperov was merged 23 hours ago
• Approved

[js/react_native] Use a mobile ORT instead of a full ORT  release:1.8.1
#8042 by hanbitmyths was merged 23 hours ago
• Approved

Fix Memory Leak from DlpackToOrtValue  component:training-core release:1.8.1
#8029 by iK1D was merged 6 days ago
• Approved
 
Make logic in InsertCastTransformer around forcing a node to fp32 more precise.  release:1.8.1
#8018 by skottmckay was merged 6 days ago
• Approved

Save module output for backward if needed  component:ortmodule release:1.8.1
#8010 by SherlockNoMad was merged 6 days ago
• Approved 

Zip Windows GPU Package missing CUDA provider files  release:1.8.1
#8002 by RyanUnderhill was merged 7 days ago
• Approved

add missing provider_options.h in packages  release:1.8.1
#7995 by jywu-msft was merged 8 days ago
• Approved

Update DirectML EP changes from DmlDev as of 2021-06-07  release:1.8.1
#7987 by sumitsays was merged 5 days ago
• Approved

Update CMakeLists.txt for openvino EP  release:1.8.1
#7980 by snnn was merged 9 days ago
• Approved

Override ORTModule named_modules to support extra arg  component:ortmodule component:training-frontend release:1.8.1
#7954 by baijumeswani was merged 8 days ago
• Approved

Cache initializers to avoid iterating over them on every forward  component:ortmodule component:training-frontend release:1.8 release:1.8.1
#7905 by baijumeswani was merged 14 days ago
• Approved

Add SoftmaxCrossEntropyLossInternal to Support Dynamic ignore_index Input   ( conflicts with https://github.com/microsoft/onnxruntime/pull/7937 and auto grad PR https://github.com/microsoft/onnxruntime/pull/7513 )
component:ortmodule component:training-core release:1.8.1
#7899 by iK1D was merged 8 days ago
• Approved

Change CMAKE_CUDA_STANDARD to C++17 for Windows GPU build  release:1.8.1
#7883 by snnn was merged 15 days ago
• Approved 

ATenOp Enhancement  component:training-core release:1.8.1  (had conflicts with autograd PR - https://github.com/microsoft/onnxruntime/pull/7513)
#7725 by iK1D was merged 9 days ago
• Approved

### CODE REVIEW

**Review by faxu — APPROVED** [review]

**Review by pranavsharma — APPROVED** [review]
I see a few training PRs that wouldn't qualify to be in a patch release. But I'll let the training team make that call.

**Comment by snnn** [comment]
We also need this: https://github.com/microsoft/onnxruntime/pull/8066

**Comment by snnn** [comment]
This time, please help us manually check if every GPU package has 

1. libonnxruntime_providers_cuda.so
2. libonnxruntime_providers_shared.so
3. onnxruntime_providers_shared.dll
4. onnxruntime_providers_cuda.dll

**Review by iK1D — APPROVED** [review]

**Comment by pranavsharma** [comment]
> This time, please help us manually check if every GPU package has
> 
> 1. libonnxruntime_providers_cuda.so
> 2. libonnxruntime_providers_shared.so
> 3. onnxruntime_providers_shared.dll
> 4. onnxruntime_providers_cuda.dll

@RyanUnderhill can you please help ensure this is the case? thanks!

**Review by thiagocrepaldi — APPROVED** [review]
FE looks good

**Comment by harshithapv** [comment]
> We also need this: #8066

We will pick this in the next round.

**Comment by RyanUnderhill** [comment]
> > This time, please help us manually check if every GPU package has
> > 
> > 1. libonnxruntime_providers_cuda.so
> > 2. libonnxruntime_providers_shared.so
> > 3. onnxruntime_providers_shared.dll
> > 4. onnxruntime_providers_cuda.dll
> 
> @RyanUnderhill can you please help ensure this is the case? thanks!

Sure thing, should I run the packaging pipelines on this change or on the 1.8.1 branch?

**Pull request merged**
