### PR TITLE
[java] Adds a CUDA test

### PR DESCRIPTION
**Pull request by Craigacp**
**Description**: Passes through the USE_CUDA flag to the gradle test runner, and adds a simple test to check that the CUDA provider can be enabled and used for inference in the Java API.

Other providers will need similar hooks passed through if they need to be tested by the CI.

### CODE REVIEW

**Comment by pranavsharma** [comment]
Also update win-gpu-ci-pipeline.yml file to pass --build_java as a build option.

**Comment by Craigacp** [comment]
I think I've done that now.

**Comment by Craigacp** [comment]
Ooops, the pipelines failed because I left a line in the wrong place which turned on CUDA for the JNI bindings. I pushed a change which will fix the macos pipeline break, and hopefully some of the others. It looks like at least one of the other failures was due to the disk being out of space, which probably isn't to do with this PR?

**Comment by yuslepukhin** [comment]
Looks good to me. We just need to unblock training pipelines somehow, otherwise I;d have to re-submit again.

**Comment by Craigacp** [comment]
Is there something I should do? I don't think I've touched anything near the training bits.

**Comment by pranavsharma** [comment]
I started the training pipelines manually. Let's wait for sometime.

**Comment by Craigacp** [comment]
Seems like everything passed.

**Pull request merged**
