### PR TITLE
Support two stages onnx GPT-2 conversion

### PR DESCRIPTION
**Pull request by tianleiwu**
### Description

Add support of ONNX conversion of GPT-2 for two stages:
* Stage 1 is the initial stage that has empty past state. 
* Stage 2 has non-empty past state and sequence_length is 1.

Add a parameter --stage to specify such stage. For stage 1, we will enable mask_index for Attention so that we can use fused attention in CUDA.

Other changes:
(1) use int32 inputs as default (otherwise, there is error in inference)
(2) update gpt2_parity to include SkipLayerNormalization (see https://github.com/microsoft/onnxruntime/pull/13988) and EmbedLayerNormalization
(3) get all environment variables that might impact GPT-2 latency in benchmark_gpt2

### Motivation and Context

To test fused attention for GPT-2 model for https://github.com/microsoft/onnxruntime/pull/13953.

### CODE REVIEW

**Comment by hariharans29** [comment]
Just to understand - does this generate the equivalent of the `init_decoder` `decoder` for BeamSearch/GreedySearch for the stand-alone GPT2 use-case ? So, the user will have to inference both model based on whether it is thr first decoding run or otherwise ?

**Comment by tianleiwu** [comment]
> Just to understand - does this generate the equivalent of the `init_decoder` `decoder` for BeamSearch/GreedySearch for the stand-alone GPT2 use-case ? So, the user will have to inference both model based on whether it is the first decoding run or otherwise ?

This PR is designed for BeamSearch/GreedySearch. I will update convert_generation.py later to take advantage of this change.

**Review by yufenglee — DISMISSED** [review]
:shipit:

**Review by yufenglee — APPROVED** [review]
:shipit:

**Pull request merged**
