### PR TITLE
Cjian/1.13 cherry pick round 2

### PR DESCRIPTION
**Pull request by jchen351**
### Description

This is the round 2 of cherry-pick into 1.13

### CODE REVIEW

**Review by baijumeswani — DISMISSED** [review]

**Review by edgchen1 — DISMISSED** [review]
signing off on changes from #13187

**Review by yufenglee — APPROVED** [review]

**Review by skottmckay — DISMISSED** [review]
Signing off on inclusion of #13091

**Review by skottmckay — DISMISSED** [review]
Signing off for inclusion of #13140

**Review by snnn — APPROVED** [review]

**Comment by fs-eire** [comment]
signing off for:
- fix XNNPACK on WebAssembly SIMD
- Add "--parallel" to the build flags of WASM pipeline
- [js/web] add 'xnnpack' to EP list

**Review by snnn — APPROVED** [review]

**Comment by jywu-msft** [comment]
signing off on cherry pick of https://github.com/microsoft/onnxruntime/pull/13122

**Review by baijumeswani — APPROVED** [review]

**Pull request merged**
