### PR TITLE
[WebNN EP] Support rest Reduction ops for TFLite backend

### PR DESCRIPTION
**Pull request by Honry**
- reduceLogSum, reduceLogSumExp and reduceSumSquare have been landed in https://chromium-review.googlesource.com/c/chromium/src/+/5575815
-  reduceL1 and reduceL2 have been landed in https://chromium-review.googlesource.com/c/chromium/src/+/5606091

### CODE REVIEW

**Review by guschmue — APPROVED** [review]

**Comment by Honry** [comment]
> can you merge with main?

@guschmue, done.

**Review by fdwr — APPROVED** [review]

**Pull request merged**
