### PR TITLE
Always build with XNNPACK EP in iOS CI build.

### PR DESCRIPTION
**Pull request by edgchen1**
### Description

Always build with XNNPACK EP in iOS CI build.

### Motivation and Context

Catch errors before code gets checked in.

### CODE REVIEW

**Comment by edgchen1** [comment]
there was a comment about not running this for every build:
https://github.com/microsoft/onnxruntime/pull/13461#discussion_r1006364783

but xnnpack will be in the iOS full build package:
https://github.com/microsoft/onnxruntime/blob/65201e47bf58ce5bbc8389a83082f69ee1ea50b3/tools/ci_build/github/apple/default_full_ios_framework_build_settings.json#L20

and we did run into a case where some breaking changes got merged. those could have been caught by a PR build.

**Review by snnn — DISMISSED** [review]
If you plan to add Xnnpack to every iOS package, it looks good.

**Comment by wejoncy** [comment]
Can we combine 'use_coreml' and 'use_xnnpack' together in one build?

**Comment by edgchen1** [comment]
> Can we combine 'use_coreml' and 'use_xnnpack' together in one build over insufficient mahines?

trying this out.

**Comment by edgchen1** [comment]
> > Can we combine 'use_coreml' and 'use_xnnpack' together in one build over insufficient mahines?
> 
> trying this out.

looks like that works.
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=825842&view=results

@wejoncy thanks for the suggestion.

**Review by snnn — APPROVED** [review]

**Pull request merged**
