### PR TITLE
More LayoutNormalization opset 17 changes

### PR DESCRIPTION
**Pull request by skottmckay**
### Description
Add CUDA kernel.
Support double in CPU kernel and only write Mean and InvStdDev values if the optional outputs exist.

### Motivation and Context
Complete opset 17 support for LayoutNormalization

### CODE REVIEW

**Comment by skottmckay** [comment]
Looks like this requires the rocm EP to have matching updates. Is there doco on the process to generate those?

**Comment by ytaous** [comment]
This is what I got so far, I wonder some changes is breaking amd_hipify.py. Let me check ...

c++filt _ZN11onnxruntime7contrib4rocm21BuildKernelCreateInfoINS1_76kRocmExecutionProvider_LayerNormalization_kOnnxDomain_ver1_float_float_floatEEENS_16KernelCreateInfoEv
onnxruntime::KernelCreateInfo onnxruntime::contrib::rocm::BuildKernelCreateInfo<onnxruntime::contrib::rocm::kRocmExecutionProvider_LayerNormalization_kOnnxDomain_ver1_float_float_float>()


---
In reply to: [1256026142](https://github.com/microsoft/onnxruntime/pull/13066#issuecomment-1256026142) [](http://example.com/codeflow?ancestors=1256026142,1256026142)

**Comment by skottmckay** [comment]
The kernel create info for the contrib kernel should move to having an end version in the symbol - something like 'ver_1_16' instead of just 'ver_1'. 

---
In reply to: [1256629136](https://github.com/microsoft/onnxruntime/pull/13066#issuecomment-1256629136) [](http://example.com/codeflow?ancestors=1256629136,1256026142)

**Comment by ytaous** [comment]
so maybe this is the reason: in ./onnxruntime/contrib_ops/rocm/rocm_contrib_kernels.cc those layer norm ones (5 of them) should also updated the same way like cuda contrib kernels.

class ONNX_OPERATOR_TYPED_KERNEL_CLASS_NAME(kRocmExecutionProvider, kOnnxDomain, 1, float_float_float, LayerNormalization);

I am still trying to set up a build env locally to verify ... but you can try it and see ... 

---
In reply to: [1256667891](https://github.com/microsoft/onnxruntime/pull/13066#issuecomment-1256667891) [](http://example.com/codeflow?ancestors=1256667891,1256026142)

**Review by yufenglee — APPROVED** [review]
:shipit:

**Review by ytaous — APPROVED** [review]

**Comment by ytaous** [comment]
AMD broken since this PR - https://github.com/microsoft/onnxruntime/pull/12949

**Comment by ytaous** [comment]
https://github.com/microsoft/onnxruntime/pull/13082 - FYI

**Pull request merged**
