### PR TITLE
[js/webgpu] disable GroupedConvVectorize path

### PR DESCRIPTION
**Pull request by qjia7**
Disable createGroupedConvVectorizeProgramInfo path due to bots failures on below two cases:
[webgpu]Conv - conv - vectorize group - B
[webgpu]Conv - conv - vectorize group - D

### CODE REVIEW

**Comment by qjia7** [comment]
@fs-eire @guschmue @satyajandhyala Please take a look, thanks.

**Review by fs-eire — APPROVED** [review]

**Review by guschmue — APPROVED** [review]

**Pull request merged**
