### PR TITLE
squeeze and unsqueeze operators for the dnnl execution provider

### PR DESCRIPTION
**Pull request by georgen117**
**Description**: 
This adds two additional operators to the dnnl execution provider
- Squeeze
- Unsqueeze

**Motivation and Context**
- Why is this change required? What problem does it solve?
    - This expands the op coverage for the dnnl execution provider for OnnxRuntime
    - Expanding op coverage enables building larger subgraphs inside the dnnl ep resulting in less memory copies when running 
       models using the dnnl ep.

- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by georgen117** [comment]
@jywu-msft maintainer please remember to run `/azp run Linux DNNL CI Pipeline` since this is the main pipeline that runs the dnnl ep.

**Comment by georgen117** [comment]
Investigating the build failure right now.

**Comment by georgen117** [comment]
@jywu-msft I have addressed the issue. Would you please run `/azp run Linux DNNL CI Pipeline` again?

**Comment by jywu-msft** [comment]
> @jywu-msft I have addressed the issue. Would you please run `/azp run Linux DNNL CI Pipeline` again?

yup. it's running.

**Comment by georgen117** [comment]
@jywu-msft thanks for running that again I think it is ready for the other builds to run. :)

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
