### PR TITLE
misc: Fix comment in op_node_proto_helper

### PR DESCRIPTION
**Pull request by hariharans29**
Fix confusing comment wherein the meaning is not correctly conveyed

### CODE REVIEW

**Comment by snnn** [comment]
Wait, the comment wasn't wrong.

**Comment by snnn** [comment]
What I want to express is:
If the ONNX spec provides a default value for it, then don't call these functions.

**Comment by hariharans29** [comment]
I see. 

But which function do we use in case the onnx spec provides default value ? Should we use GetAttr() and if Status is not Ok, we fallback to the onnx spec provided value ? Then what is the guideline for using GetAttrOrDefault()?

**Comment by snnn** [comment]
Like:
```
ORT_ENFORCE(info.GetAttr<float>("mean", &mean_).IsOK());
```

**Pull request merged**
