### PR TITLE
Replace float_t with float

### PR DESCRIPTION
**Pull request by MKlimenko**
A couple of places in onnxruntime used `float_t` data type alias as an alternative to `float`. However, this is not entirely correct, since `float_t` is an implementation-defined type alias, which may be `float`, `double`, `long double` or some other implementation-defined data type, depending on the state of the internal `FLT_EVAL_METHOD` macro: https://en.cppreference.com/w/c/numeric/math/float_t

On most major platforms and compilers (clang, GCC, MSVC) this is only a cosmetic change and will not lead to any changes. However, icpx compiler (and legacy icc) tends to substitute `float_t` with `long double`, resulting in a linker error (unresolved reference) to the base onnx library, that only contains the `ParseData` function for `float` and `double` as in [here](https://github.com/onnx/onnx/blob/9264e093676f40a48aee819b8013ef285e3d4fc5/onnx/defs/tensor_proto_util.cc#L133-L134).

Overall, this PR cleans up the implementation-defined behaviour and enables building onnxruntime with icpx.

### CODE REVIEW

**Comment by MKlimenko** [comment]
@microsoft-github-policy-service agree

**Review by edgchen1 — APPROVED** [review]
thanks for the fix!

**Comment by MKlimenko** [comment]
@edgchen1, looks like all of the tests passed apart from the web-related ones, which failed because of the formatting. Fixed it in the touched *.mm files, can I ask you to re-run the CI, please?

**Comment by MKlimenko** [comment]
@edgchen1, sorry to ping you again, noticed that the main branch is out-of-date, so I merged the main into my branch. Don't know if you have some kind of merge trains, but probably not, should we restart the CI once again?

**Comment by edgchen1** [comment]
no problem, I can start them again

**Comment by MKlimenko** [comment]
@edgchen1 apart from one [cancelled](https://github.com/microsoft/onnxruntime/actions/runs/5384287239/jobs/9772165156?pr=16484) task everything has passed. What would be the best course of action right now? Should we restart this specific test or repeat it after pulling the latest changes from the main branch?

**Review by edgchen1 — APPROVED** [review]

**Comment by edgchen1** [comment]
@MKlimenko thanks for your contribution!

**Pull request merged**
