### PR TITLE
Optimize BinaryElementWise and BiasGeluGrad kernels for AMD

### PR DESCRIPTION
**Pull request by hubertlu-tw**
**Description:**
Optimized _BinaryElementWise, _BinaryElementWiseRhsPerChannelBatchN, and BiasGeluGradDxKernel for AMD GPUs.

**Motivation and Context**

- Why is this change required? What problem does it solve?

The 4% runtime difference is observed in TNLRv4 on MI100 vs. V100. The cause of discrepancy is from the following three kernels: `_BinaryElementWise`, `_BinaryElementWiseRhsPerChannelBatchN`, and `BiasGeluGradDxKernel`. Given by the reproducer, we are able to see the performance improvement in terms of original sub-optimal kernels by 15.94%, 19.28%, and 27.97%, respectively.

### CODE REVIEW

**Comment by hubertlu-tw** [comment]
@weixingzhang Please review. Thanks.

**Review by weixingzhang — APPROVED** [review]

**Pull request merged**
