### PR TITLE
Add compatibility with Protobuf 3.12

### PR DESCRIPTION
**Pull request by yan12125**
**Description**: Describe your changes.

In Protobuf 3.12, classes generated from protobuf files are declared as
`final`, so use those classes as members rather than base classes.

Ref: https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0

> Mark generated classes as final; inheriting from protos is strongly discouraged.

**Motivation and Context**

Follow-up of https://github.com/microsoft/onnxruntime/pull/4230#issuecomment-643800089

### CODE REVIEW

**Comment by snnn** [comment]
Hi @yan12125 , we had some problems in our build system. Could you please update your branch with the latest master? I believe it will solve the errors.

**Comment by yan12125** [comment]
Thanks for the hint! I've rebased this patch on top of the current master (0d9db2b28d7ca72865405d7fbe47c6221f01d4ab).

**Comment by yan12125** [comment]
Great, all pipelines are green! :100:

**Comment by snnn** [comment]
Thank you!

**Comment by yan12125** [comment]
Glad to help :D

**Pull request merged**
