### PR TITLE
Fix  release version suffix for RC builds (#15865)

### PR DESCRIPTION
**Pull request by natke**
Cherry pick nuget RC version changes from main

(cherry picked from commit 36c9ae0f58cec8e6f09eaab88041c693592e2d0b)

### CODE REVIEW

**Comment by snnn** [comment]
Does this one depend on PR #15839 ? Does that one also need be cherry-picked?

**Comment by natke** [comment]
> Does this one depend on PR #15839 ? Does that one also need be cherry-picked?

That is a good question. I think this PR will standalone, as the ReleaseVersionSuffix should have been set everywhere that it is used but let me check.

**Comment by natke** [comment]
I have manually added in the default (rather than cherry pick the other PR). I don't think we need this default because the variable should be explicitly set everywhere it is used, but I am adding it to be safe in all cases.

**Comment by natke** [comment]
This needs one more review right? And there is an android pipeline failing due to a cmake version mismatch

**Comment by snnn** [comment]
>  And there is an android pipeline failing due to a cmake version mismatch 

Yes. It will be fixed by another cherry-pick from me. Now you can ignore it.

**Review by pranavsharma — APPROVED** [review]

**Pull request merged**
