### PR TITLE
[WebNN EP] Update Op Softmax for readability

### PR DESCRIPTION
**Pull request by zesongw**
### Description

Improve readability by fixing misplaced comments and utilizing std::rotate.

### Motivation and Context

Resolve some comments in https://github.com/microsoft/onnxruntime/pull/17714

### CODE REVIEW

**Comment by zesongw** [comment]
@fdwr, @guschmue, PTAL, thanks!

**Review by guschmue — APPROVED** [review]

**Review by fdwr — APPROVED** [review]
Thanks Zesong.

**Pull request merged**
