### PR TITLE
Support building ARM64EC onnxruntime.dll

### PR DESCRIPTION
**Pull request by mcfi**
Add support for building onnxruntime.dll as ARM64EC, to support x64 applications emulated on ARM64.

### CODE REVIEW

**Comment by snnn** [comment]
Does nuget have a special runtime identifier for ARM64EC? How this build config will be released?

**Comment by mcfi** [comment]
Hi Changming, I don't understand your questions, could you please elaborate (e.g., what NuGet packages you are referring to)?

**Comment by tracysh** [comment]
The MLAS related changes look good.

**Comment by snnn** [comment]
See:  https://github.com/dotnet/corefx/blob/release/3.1/pkg/Microsoft.NETCore.Platforms/runtime.json 

Does the file have an entry for ARM64EC? Should we put the ARM64EC onnxruntime.dll in https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/ ?

**Comment by mcfi** [comment]
It'll be good to have that ARM64EC entry, but right now, the ARM64EC dll can only be built with an internal Windows SDK, and it has 2 test failures we still don't fully root-caused. I would say we can add the ARM64EC entry later in a separate PR.

**Comment by snnn** [comment]
I will schedule the builds and merge this PR.

**Review by snnn — APPROVED** [review]

**Pull request merged**
