### PR TITLE
[ORT 1.18.0 Release] Cherry pick 2nd round

### PR DESCRIPTION
**Pull request by yihonglyu**
Kindly request the authors of the PRs to review the changes. If you have any questions, please let me know. If everything looks good, please approve the changes.

### CODE REVIEW

**Comment by Craigacp** [comment]
#20549 LGTM.

**Comment by mszhanyi** [comment]
@yihonglyu I suggest to merge https://github.com/microsoft/onnxruntime/pull/20618 ASAP. Because we'll disable SAS soon, then rel-1.18.x will not pass CI and packaging pipelines. cc @snnn

**Review by jywu-msft — APPROVED** [review]

**Review by yufenglee — APPROVED** [review]

**Review by edgchen1 — APPROVED** [review]
signing off on #20608

**Review by liqunfu — APPROVED** [review]

**Review by chilo-ms — APPROVED** [review]

**Review by maggie1059 — APPROVED** [review]

**Review by kunal-vaishnavi — APPROVED** [review]

**Review by pengwa — APPROVED** [review]

**Review by tianleiwu — APPROVED** [review]

**Review by snnn — APPROVED** [review]

**Pull request merged**
