### PR TITLE
[vitisai] Fix build failure introduced by #20920

### PR DESCRIPTION
**Pull request by zz002**
### Description

Fix build failure introduced by #20920

### CODE REVIEW

**Comment by zz002** [comment]
Hi @jywu-msft , I fixed the vitisai build failure introduced by #20920.

**Comment by snnn** [comment]
There is a conflict. Please help resolve it. @zz002

**Comment by zz002** [comment]
> There is a conflict. Please help resolve it. @zz002

done

**Review by snnn — APPROVED** [review]
Thank you!

**Pull request merged**
