### PR TITLE
Add debugging tools for intermediate outputs

### PR DESCRIPTION
**Pull request by PatriceVignola**
This adds debugging tools for intermediate outputs when specific build flavors are specified (so it doesn't affect the final product at all). This allows us to easily figure out which nodes are producing NaN or INF numbers, and which float16 nodes are producing outputs that are too different from their expected "perfect precision" outputs.

### CODE REVIEW

**Comment by tianleiwu** [comment]
If you want to see NAN and INF Numbers, try this: https://github.com/microsoft/onnxruntime/pull/15761.
It will also print Min and Max so that you know whether some numbers are very close to the limit of FP16 data type.

**Comment by PatriceVignola** [comment]
> If you want to see NAN and INF Numbers, try this: #15761. It will print Inf, Nan, Zero, SubNormal, Min and Max so that you know whether some numbers are very close to the limit of FP16 data type.

Oh, I was not aware of this. Your branch doesn't print non-cpu EP nodes though, does it? The change that I'm proposing automatically downloads the data of each tensor to the CPU to figure out whether it produces NaN/INF. It also has an option to run each node with fp32 vs fp16 and look at the result, which can help figure out issues where an fp16 accumulator is used instead of fp32.

**Comment by tianleiwu** [comment]
> Oh, I was not aware of this. Your branch doesn't print non-cpu EP nodes though, does it? The change that I'm proposing automatically downloads the data of each tensor to the CPU to figure out whether it produces NaN/INF. It also has an option to run each node with fp32 vs fp16 and look at the result, which can help figure out issues where an fp16 accumulator is used instead of fp32.

The node input/output dumping supports non-cpu EP since data transfer to CPU is done automatically. Normally, I just dump node input/outputs for one fp32 model and the corresponding fp16 model, then look at the dumped data side-by-side. That could help identify root cause of NaN quickly.

I understand that having an option to run node with fp32 vs fp16 could help. There is another tool [auto mixed precision converter](https://github.com/microsoft/onnxconverter-common/blob/8c81a0e7ea2381d0fc98f13a247d17f3eaa9ec25/onnxconverter_common/auto_mixed_precision.py#L70-L72) with similar idea: it generates graph with a node in fp16, then compare to the baseline graph in fp32, and validate the node output difference. I think that approach is less invasive since it does not need build a custom onnxruntime so it could work with official release package. However, it only checks one node so it cannot track error accumulation among multiple nodes. 

Note that debugging code is not built in pipeline so it might be out of maintenance later.

**Comment by fdwr** [comment]
@PatriceVignola Moot now? 🤔 Abandon it?

**Pull request closed without merging**
