### PR TITLE
First round of fixes.

### PR DESCRIPTION
**Pull request by jchen351**
### Description
First round of fixes for C4244 error.

### CODE REVIEW

**Review by snnn — COMMENTED** [review]
Please consider using gsl::narrow or gsl::narrow_cast when possible.

**Review by snnn — APPROVED** [review]

**Comment by edgchen1** [comment]
> Please consider using gsl::narrow or gsl::narrow_cast when possible. The reason is stated in https://learn.microsoft.com/en-us/cpp/code-quality/c26472?view=msvc-170 . Though we haven't enforced the rule, but I think they provided good reasons.

From that link: "gsl::narrow_cast clearly states that conversion can lose data and it's acceptable."

Looks like many of the changes are adding gsl::narrow_cast. For those cases, is it indeed acceptable for the conversions to lose data?

**Comment by snnn** [comment]
[jchen351](https://github.com/jchen351) has 1000+ such warnings to fix(or suppress). He can't make the judgement for every place he is changing, Also, the code he is changing was written before he joined this team, he doesn't know much details.  So right now we focus on identifying these places that need fixes. He will insert gsl::narrow_cast there. Then who knows the code better can make further improvements. "gsl::narrow_cast" is easily searchable.

**Comment by snnn** [comment]
Or, were you suggesting using gsl::narrow instead?

**Comment by edgchen1** [comment]
gsl::narrow seems like a safer change.

I understand that a lot of this code existed before. But compiler warnings are also a good way to identify the places that need fixing. I think they should be suppressed only when there is actually nothing to fix.

**Pull request merged**
