### PR TITLE
[js/webgpu] Prefer adapter.info to adapter.requestAdapterInfo

### PR DESCRIPTION
**Pull request by gyagp**
WebGPU is deprecating async adapter.requestAdapterInfo, and replacing it with sync adapter.info.
Spec change: https://github.com/gpuweb/gpuweb/pull/4662

### CODE REVIEW

**Comment by gyagp** [comment]
@guschmue @fs-eire @satyajandhyala PTAL

**Review by guschmue — APPROVED** [review]

**Comment by guschmue** [comment]
lint step complains:

npm error `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

**Comment by gyagp** [comment]
> lint step complains:
> 
> npm error `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

Thanks for the info! The issue was caused by old npm (version 9.2.0). After upgrading the latest nodejs, now I have npm with version 10.8.1 and it looks like the changes to package-lock.json are more reasonable.

**Comment by gyagp** [comment]
run web CI

**Review by fs-eire — APPROVED** [review]

**Comment by gyagp** [comment]
@guschmue I'm still seeing 2 failures, and I don't think they're related to my changes. Any thoughts?

**Pull request merged**
