### PR TITLE
Disable streams for the DML EP

### PR DESCRIPTION
**Pull request by PatriceVignola**
There's currently a bug  in the allocation planner when reusing buffers and more than one streams are used that make it possible (although rarely) to reach a reference count of 0 for a buffer that is still being used. Since DML doesn't benefit from multiple streams, disabling it is the safest option for now.

This is a high priority issue that we need to fix for 1.17.1 since it breaks stable diffusion. Identifying the perfect fix and fixing the underlying issue would be too risky for a patch release, especially given the limited time that we have.

https://github.com/microsoft/onnxruntime/issues/19480

### CODE REVIEW

**Review by snnn — APPROVED** [review]

**Comment by PatriceVignola** [comment]
@snnn I keep getting `CUDA failure 100: no CUDA-capable device is detected ; GPU=0 ; hostname=12a729cd64de ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider_info.cc ; line=138 ; expr=cudaGetDeviceCount(&num_devices);` on the Linux build.

**Review by fdwr — COMMENTED** [review]
Thank you Pat for restoring SD.

**Pull request merged**
