### PR TITLE
[js/webgpu] Replace array with string in transpose perm

### PR DESCRIPTION
**Pull request by axinging**
Perf test data(100000 times)
Array: 12.599999997764826ms
String: 1.6000000014901161ms

Perf test case:

```
const permFunctionBodyArray = (rank: number, input: string): string => {
  const reverseFunc = [];
  reverseFunc.push(`fn perm(i: int) -> int {
    var a: int};`);
  for (let i = 0; i < rank; ++i) {
    reverseFunc.push(input);
  }
  reverseFunc.push('return a;}');
  return reverseFunc.join('\n');
};

const permFunctionBodyString = (rank: number, input: string): string => {
  let reverseFunc= `fn perm(i: int}) -> int {
    var a: int;`;
  for (let i = 0; i < rank; ++i) {
    reverseFunc+=input;
  }
  reverseFunc+='return a;}';
  return reverseFunc;//.join('\n');
};
const count = 100000;
let start, end
console.time('array');
start = performance.now();
for(let i =0 ; i < count; i ++) {
    permFunctionBodyArray(3, 'input');
}
end = performance.now();
console.timeEnd('array');
console.log("Array: "+ (end-start));

console.time('string');
start = performance.now();
for(let i =0 ; i < count; i ++) {
    permFunctionBodyString(3, 'input');
}
end = performance.now();
console.log("String: " +(end-start));
console.timeEnd('string');
```

### CODE REVIEW

**Comment by axinging** [comment]
@qjia7 @xhcao @hujiajie @jzm-intel @gyagp PTAL

**Comment by jzm-intel** [comment]
It seems the overhead comes from `Array.join`. 
Using a polyfill such as 
``` typescript
const joinPolyfill = (array: string[], seperator: string = ',') => {
  let result = array[0];
  for (let i = 1; i < array.length; i++) {
    result += seperator + array[i];
  }
  return result;
}
```
instead of `Array.join` can improve the performance, but still take longer time (~3x) than the `string += string` version.

That is a little confusing, once upon a time the opposite conclusion is considered true, e.g. https://stackoverflow.com/questions/2781686/javascript-string-concatenation-slow-performance-array-join

**Comment by jzm-intel** [comment]
And the perf diff would be much smaller if the added string is not the same `input` each time (which is the exact case), for example
``` typescript
const permFunctionBodyArray = (rank: number, input: string): string => {
  const reverseFunc = [];
  reverseFunc.push(`fn perm(i: int) -> int {
    var a: int;`);
  for (let i = 0; i < rank; ++i) {
    reverseFunc.push(`${input} #${i}`);
  }
  reverseFunc.push('return a;}');
  return reverseFunc.join('');
};

const permFunctionBodyString = (rank: number, input: string): string => {
  let reverseFunc = `fn perm(i: int}) -> int {
    var a: int;`;
  for (let i = 0; i < rank; ++i) {
    reverseFunc += `${input} #${i}`;
  }
  reverseFunc += 'return a;}';
  return reverseFunc;//.join('');
};

const joinPolyfill = (array: string[], seperator: string = ',') => {
  let result = array[0];
  for (let i = 1; i < array.length; i++) {
    result += seperator + array[i];
  }
  return result;
}

const permFunctionBodyArrayPF = (rank: number, input: string): string => {
  const reverseFunc = [];
  reverseFunc.push(`fn perm(i: int) -> int {
    var a: int;`);
  for (let i = 0; i < rank; ++i) {
    reverseFunc.push(`${input} #${i}`);
  }
  reverseFunc.push('return a;}');
  return joinPolyfill(reverseFunc, '');
};

const count = 10000000;

const doTest = (name: string, func: (rank: number, input: string) => string) => {
  let start, end
  console.time(name);
  start = performance.now();
  for (let i = 0; i < count; i++) {
    func(3, 'input');
  }
  end = performance.now();
  console.timeEnd(name);
  console.log(`${name}: ` + (end - start));
}

const cases = {
  permFunctionBodyArray,
  permFunctionBodyString,
  permFunctionBodyArrayPF,
} as const;

Object.entries(cases).forEach((entry) => {
  doTest(entry[0], entry[1]);
})
```
I get
```
permFunctionBodyArray: 1809.490966796875 ms
permFunctionBodyString: 1350.786865234375 ms
permFunctionBodyArrayPF: 1526.43505859375 ms
```

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
