### PR TITLE
update nuget icon

### PR DESCRIPTION
**Pull request by mszhanyi**
**Description**: Update nuget icon from url to local file

**Motivation and Context**
[The 'PackageIconUrl'/'iconUrl' element is deprecated](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5048)

### CODE REVIEW

**Comment by mszhanyi** [comment]
looks good now.
https://int.nugettest.org/packages?q=onnxruntime

**Review by snnn — APPROVED** [review]
Thank you!

**Comment by mszhanyi** [comment]
The document looks incorrect for vsproj
`The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl`
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5048

We have to only use PackageIcon in vsproj.
verified locally
image

**Comment by mszhanyi** [comment]
No iconurl warning any more
image

And versions match
image

**Review by snnn — APPROVED** [review]

**Pull request merged**
