### PR TITLE
Reduce operator

### PR DESCRIPTION
**Pull request by adityagoel4512**
### Description
Operators `ReduceL1`, `ReduceL2`, `ReduceLogSum`, `ReduceLogSumExp` and `ReduceSumSquare` do not have `Int64` support. This has been available in the ONNX specification since opset 1. This has cropped up in our data feature engineering where we can often have long types being reduced. 

### Motivation and Context
Closes https://github.com/microsoft/onnxruntime/issues/15357.

### CODE REVIEW

**Comment by baijumeswani** [comment]
@adityagoel4512 would you please update [docs/OperatorKernels.md](https://github.com/microsoft/onnxruntime/blob/main/docs/OperatorKernels.md) to reflect your changes?

This is resulting in a build failure.

**Comment by adityagoel4512** [comment]
> @adityagoel4512 would you please update [docs/OperatorKernels.md](https://github.com/microsoft/onnxruntime/blob/main/docs/OperatorKernels.md) to reflect your changes?
> 
> This is resulting in a build failure.

Ah, yes of course. I'm trying to build wheels so I can use the `--gen_doc` flag in the build script but I'm getting an error on a `numpy` include. I don't need to build `numpy` from source do I?

On running `./build.sh --build_wheel` I get the following error:

Screenshot 2023-04-05 at 01 02 28

I'm not super experienced with cmake yet so any help would be appreciated!

**Comment by baijumeswani** [comment]
you don't need to build numpy from source. But you need numpy installed in your python env to build ort.

**Comment by adityagoel4512** [comment]
> you don't need to build numpy from source. But you need numpy installed in your python env to build ort python wheel.

Thanks, just trying to run with `--gen_doc` now and having install `onnxruntime` from the `whl` and get 

`from onnxruntime.capi.onnxruntime_pybind11_state import schemadef  # noqa: F401
ImportError: cannot import name 'schemadef' from 'onnxruntime.capi.onnxruntime_pybind11_state'`

Is this an issue with how I built the wheel?

**Comment by baijumeswani** [comment]
make sure your local onnxruntime folder does not clash with the python sys path onnxruntime package.

**Comment by baijumeswani** [comment]
It maybe something else. let me check.

**Comment by baijumeswani** [comment]
You probably need to build ort with the flag `--gen_doc` to enable `onnxruntime_PYBIND_EXPORT_OPSCHEMA`.

**Comment by adityagoel4512** [comment]
> You probably need to build ort with the flag `--gen_doc` to enable `onnxruntime_PYBIND_EXPORT_OPSCHEMA`.

Should be good to go now - there seems to be a small edit to the title coming from `gen_opkernel_doc.py`, not sure if I should leave it in or remove it?

**Review by baijumeswani — APPROVED** [review]

**Comment by baijumeswani** [comment]
Thanks for your contribution.

**Comment by fdwr** [comment]
For `ReduceLogSum` and `ReduceLogSumExp`, which are inherently non-integer, I suspect integer support in the type list was a copy-paste typo. Do you know any real-world models that actually use integers with these operators?

**Pull request merged**
