### PR TITLE
🐛 Bugfix win del file err

### PR DESCRIPTION
**Pull request by trajepl**
### Description

Fix for this issue which raise the error of FileNotAccessd in windows when the context of TemporaryDirectory finished.
https://github.com/microsoft/onnxruntime/issues/17627

### Motivation and Context

https://github.com/microsoft/onnxruntime/issues/17627

### CODE REVIEW

**Review by baijumeswani — COMMENTED** [review]
Looks good to me. cc @yufenglee for approval

**Review by yufenglee — APPROVED** [review]

**Comment by snnn** [comment]
Cherry-picked to the 1.16.1 patch release

**Pull request merged**
