### PR TITLE
bump ORT version to 1.8.1

### PR DESCRIPTION
**Pull request by harshithapv**
bump ORT version to 1.8.1

### CODE REVIEW

**Comment by snnn** [comment]
Please cherry-pick this commit: 38ca0f48398f10b6eae745988c7a1ebd276bbba5

**Comment by snnn** [comment]
The orttraining-distributed training pipeline issue is due to # 8022

**Comment by baijumeswani** [comment]
The ```orttraining-distributed``` pipeline not getting triggered is not  because of #8022  but instead because of it being a required pipeline for all merges into ```rel-*``` branch. I will reach out to @SherlockNoMad to see if he can help me with this.

**Comment by baijumeswani** [comment]
@snnn the pipeline has been marked as non-required even for ```rel-*``` branches and does not show up in the list anymore (@SherlockNoMad helped with this).

**Review by snnn — APPROVED** [review]
Thanks.

**Review by pranavsharma — APPROVED** [review]

**Pull request merged**
