### PR TITLE
Adding python3.12 support to ORT

### PR DESCRIPTION
**Pull request by jchen351**
### Description
Adding python3.12 support to ORT

### CODE REVIEW

**Comment by TDClarke** [comment]
Will this close issue https://github.com/microsoft/onnxruntime/issues/18793 ?

**Comment by snnn** [comment]
@jchen351 , the new python version needs a newer numpy version.

**Comment by snnn** [comment]
Please run the "Python packaging pipeline" to verify your change.

**Comment by snnn** [comment]
Please resolve the conflict.

**Review by snnn — APPROVED** [review]

**Pull request merged**
