### PR TITLE
Learned that ONNX Server has been deprecated

### PR DESCRIPTION
**Pull request by asamadiya**
Making it clear in the documentation to proactively inform users.

**Description**: Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by pranavsharma** [comment]
Is the note at the top of the file (first line of this file) not sufficient?

**Comment by asamadiya** [comment]
The note says "ONNX Runtime Server is still in beta state and may not be ready for production environments". Beta is different from deprecation. Deprecation means there won't be investment in this solution going forward. That's not clear at all from the current documentation.

**Review by pranavsharma — APPROVED** [review]

**Pull request merged**
