### PR TITLE
Fix perf test executable.

### PR DESCRIPTION
**Pull request by pranavsharma**
Fix perf test executable that broke due to removal of certain C APIs.

### CODE REVIEW

**Comment by snnn** [comment]
Is it possible to avoid duplicating these code another time?

**Comment by pranavsharma** [comment]
Yes, agree that this is not ideal. I tried to avoid duplication. But realized it’ll take significant time to rearrange the setup. Besides, the files weren’t fully duplicated; I followed some of the ort server examples.

**Comment by pranavsharma** [comment]
> Is it possible to avoid duplicating these code another time?

fixed.

**Comment by pranavsharma** [comment]
@snn can this be merged?

**Pull request merged**
