### PR TITLE
[AIX]test failure fix using gtest-1.15.0 for AIX

### PR DESCRIPTION
**Pull request by ranjitshs**
### Description
Local CI setup for AIX reported tests failure after the gtest 1.15.0 upgrade.

### Motivation and Context
Below tests failure is observed after gtest upgrade.

The following tests FAILED:
	  1 - onnxruntime_test_all (ILLEGAL)
	  7 - onnxruntime_logging_apis_test (Subprocess aborted)

To fix this, I am enabling pthread support under gtest. This was disabled with previous version of gtest for some reason.
Now by enabling this, above tests are getting passed with gtest 1.15.0.

### CODE REVIEW

**Comment by ranjitshs** [comment]
@snnn 
As mentioned in https://github.com/microsoft/onnxruntime/pull/21410 , this PR contains the AIX test failure fix with gtest 1.15.0.
Please trigger the relevant CI pipeline and  let me know if I need to create a corresponding issue.

@tianleiwu FYI.

**Comment by ranjitshs** [comment]
@snnn @tianleiwu 
if no comments on this PR, can it get merge ?  Please merge it.

**Review by tianleiwu — APPROVED** [review]

**Pull request merged**
