### PR TITLE
Ovep develop 1.21

### PR DESCRIPTION
**Pull request by preetha-intel**
### Description
OVEP development changes for ORT 1.21 Release

### Motivation and Context
Has critical bug fixes
Support for concurrency execution of models is enabled
Support for OV 2024.5
Memory optimizations for NPU platform

### CODE REVIEW

**Comment by sfatimar** [comment]
@adrianlizarraga @jywu-msft Please review

**Comment by jywu-msft** [comment]
please fix lintrunner error https://github.com/microsoft/onnxruntime/actions/runs/11822465741/job/32940502475?pr=22824

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
