### PR TITLE
Delete torchtext and transformers because they have an LGPL dependency

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

torchtext depends on chardet, which is licensed under LGPL, and I think nobody can change the license. see: https://github.com/chardet/chardet/issues/36

Because GPL and LGPL work transitively, we will be required to release our product under a license that is compatible with the LGPL, which will be a lot of work. So I'll delete torchext and the code uses it for now.  Please feel free to add them back after the license issue is resolved. 

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by kit1980** [comment]
I'm really not sure about this.
From LGPL text: 'A program that contains no derivative of any portion of the Library, but is designed to work with the Library by being compiled or linked with it, is called a "work that uses the Library". Such a work, in isolation, is not a derivative work of the Library, and therefore falls outside the scope of this License.'
After reading that, I don't think using LGPL-ed 'chardet' requires the program to fall under LGPL.
That's basically the difference between GPL and LGPL: you can use LGPL-ed library even with a proprietary program.

And ORT doesn't use 'chardet' directly, only via other libraries. Are you saying HuggingFace transformers must be licensed under LGPL because they use a LGPL-ed library?

**Comment by kit1980** [comment]
Moreover, at the top of https://github.com/microsoft/onnxruntime/blob/master/ThirdPartyNotices.txt:

> Notwithstanding any other terms, you may reverse engineer this software to the
> extent required to debug changes to any libraries licensed under the GNU Lesser
> General Public License.

Which assumes that LGPL libraries can be used.

**Comment by snnn** [comment]
> I'm really not sure about this.
> From LGPL text: 'A program that contains no derivative of any portion of the Library, but is designed to work with the Library by being compiled or linked with it, is called a "work that uses the Library". Such a work, in isolation, is not a derivative work of the Library, and therefore falls outside the scope of this License.'
> After reading that, I don't think using LGPL-ed 'chardet' requires the program to fall under LGPL.
> That's basically the difference between GPL and LGPL: you can use LGPL-ed library even with a proprietary program.
> 
> And ORT doesn't use 'chardet' directly, only via other libraries. Are you saying HuggingFace transformers must be licensed under LGPL because they use a LGPL-ed library?

LGPL was designed for C/C++ programs, to make an exempt for dynamic linking.  Many of the words do not quite make sense for python. Anyway, it need go through legal review, and it will be a long process.  Please feel free to add the code back when the review is completed. 

Google has a similar policy: https://opensource.google/docs/thirdparty/licenses/#LinkingRequirements

**Comment by snnn** [comment]
> Moreover, at the top of https://github.com/microsoft/onnxruntime/blob/master/ThirdPartyNotices.txt:
> 
> Which assumes that LGPL libraries can be used.

Yes, they can, after you get the approval from an executive and the lawyers.  We are totally open to LGPL.

**Pull request closed without merging**
