### PR TITLE
[AMX] Update assembler check

### PR DESCRIPTION
**Pull request by georgen117**
A recent commit added an assembler check if the ASM dialect was ATT

This unfortunately broke the AMX build for systems that don't have the ASM-ATT dialect.

This change assumes if the CMAKE_ASM-ATT_COMPILER_ID is not found and the CMAKE_ASM_COMPILER_ID is "GNU" based on all the other already passed checks AMX is supported by the compiler and assembler.

### Motivation and Context
On my build system the recent change to add the ASM-ATT version check disabled AMX code from the build.

### CODE REVIEW

**Comment by georgen117** [comment]
This is a response to this PR: https://github.com/microsoft/onnxruntime/pull/15055

**Comment by georgen117** [comment]
related to: https://github.com/microsoft/onnxruntime/issues/14945

Side note the computer I have building AMX code on `as --version` returns `GNU assembler (GNU Binutils for Ubuntu) 2.38` which is lower than the `2.4` talked about in the issue.

**Comment by wejoncy** [comment]
> related to: #14945
> 
> Side note the computer I have building AMX code on `as --version` returns `GNU assembler (GNU Binutils for Ubuntu) 2.38` which is lower than the `2.4` talked about in the issue.

Hi @georgen117 Thanks for this commit.

With this changes, I get the same errors as before.
```
/usr/lib/gcc/x86_64-linux-gnu/11/include/amxtileintrin.h: Assembler messages:
/usr/lib/gcc/x86_64-linux-gnu/11/include/amxtileintrin.h:42: Error: no such instruction: `ldtilecfg (%rax)'
onnxruntime/onnxruntime/core/mlas/lib/qgemm_kernel_amx.cpp:645: Error: no such instruction: `tileloadd (%r10,%r11,1),%tmm0'
```
So I am assuming there must be something missed for these AMX instructions. Could you compile it successfully using as-2.38?

**Comment by georgen117** [comment]
> So I am assuming there must be something missed for these AMX instructions. Could you compile it successfully using as-2.38?

Yes I have been able to compile the code successfully.

On my system:
`CMAKE_ASM_COMPILER_ID = “GNU”` # note the lack of -ATT in the variable name
`CMAKE_ASM_COMPILER = “/usr/bin/cc”` #note the lack of -ATT in the variable name and it does not return `as`

I am using the code on a 4th gen Xeon system. I am able to build and run the AMX code in question.

**Comment by wejoncy** [comment]
> Yes I have been able to compile the code successfully.
> 
> On my system: `CMAKE_ASM_COMPILER_ID = “GNU”` # note the lack of -ATT in the variable name `CMAKE_ASM_COMPILER = “/usr/bin/cc”` #note the lack of -ATT in the variable name and it does not return `as`
> 
> I am using the code on a 4th gen Xeon system. I am able to build and run the AMX code in question.

Do you think what's the reason of building failure in different environment?

I think it's inrelevant to the hardware which will throw me a runtime-error.

My env is:
- Ubuntu 20.04
- GCC 11
- as 2.38
- CPU i9-10900X (no amx support)

**Comment by georgen117** [comment]
> Do you think what's the reason of building failure in different environment?

It is unclear to me the reason for the failure. If you have GCC 11 you should be able to build the AMX code.

> My env is:
> 
> * Ubuntu 20.04
> * GCC 11
> * as 2.38
> * CPU i9-10900X (no amx support)
> * CMAKE_ASM_COMPILER_ID=GNU
> * CMAKE_ASM_COMPILER=/usr/bin/cc----->/usr/bin/gcc-11

My env is:
- Ubuntu 22.04
- GCC 11.3.0
- as GNU assembler 2.38
- CMAKE_ASM_COMPILER_ID=GNU
-  CMAKE_ASM_COMPILER=/usr/bin/cc----->/usr/bin/gcc-11
- CPU Intel Xeon Platinum 8480+ (Gen 4 Xeon with AMX support)

> Do you use another compiler like icc?

I am using GCC compiler. I don't have icc installed on the computer in question.

**Comment by wejoncy** [comment]
> 

I got the root cause finally. I have an older gun-as in my system (as 2.34) which is called by default. I can build it successfully with as-2.38 or later.

Could you please update the "assemble check version" to 2.38 and use `CMAKE_ASM_COMPILER_ID` instead?

`CMAKE_ASM-ATT_COMPILER_ID` and `CMAKE_ASM-ATT_COMPILER` might not be proper here.

**Comment by georgen117** [comment]
> > 
> 
> I got the root cause finally. I have an older gun-as in my system (as 2.34) which is called by default. I can build it successfully with as-2.38 or later.
> 
> Could you please update the "assemble check version" to 2.38 and use `CMAKE_ASM_COMPILER_ID` instead?
> 
> `CMAKE_ASM-ATT_COMPILER_ID` and `CMAKE_ASM-ATT_COMPILER` might not be proper here, I think it could be safely deleted.

I am happy to update it. 

Since `CMAKE_ASM_COMPILER=/usr/bin/cc----->/usr/bin/gcc-11` Would it be reasonable to assume the assembly command is `as`.  I personally don't know how to get the `as --version` from the `/usr/bin/cc` command.

**Comment by georgen117** [comment]
@wejoncy  I have update the check.  It no longer uses `CMAKE_ASM-ATT_COMPILER_ID` instead `CMAKE_ASM_COMPILER_ID` is used.  As I stated above I am directly calling `as --version`.  The regex should now check 2.38 or later.

**Review by wejoncy — APPROVED** [review]

**Comment by wejoncy** [comment]
azp run Linux QNN CI Pipeline, Windows ARM64 QNN CI Pipeline

**Comment by georgen117** [comment]
@wejoncy I have checked the failures for Linux_CI and Windows_CI.

both have what looks like the same error.

```
D:\a\onnxruntime\onnxruntime\onnxruntime\core\optimizer\graph_transformer_utils.cc(213,67): error C2065: 'cpu_ep': undeclared identifier [D:\a\onnxruntime\onnxruntime\build\Release\onnxruntime_optimizer.vcxproj]
D:\a\onnxruntime\onnxruntime\onnxruntime\core\optimizer\graph_transformer_utils.cc(213,19): error C2672: 'absl::lts_20220623::InlinedVector<std::unique_ptr<onnxruntime::GraphTransformer,std::default_delete<onnxruntime::GraphTransformer>>,6,std::allocator<T>>::emplace_back': no matching overloaded function found [D:\a\onnxruntime\onnxruntime\build\Release\onnxruntime_optimizer.vcxproj]
```
Are any other builds failing due to this error?  It is unrelated to this code change.

I would be happy to rebase the code it the error has already been fixed and was just not part of my PR.

**Comment by wejoncy** [comment]
> @wejoncy I have checked the failures for Linux_CI and Windows_CI.
> 
> both have what looks like the same error.
> 
> ```
> D:\a\onnxruntime\onnxruntime\onnxruntime\core\optimizer\graph_transformer_utils.cc(213,67): error C2065: 'cpu_ep': undeclared identifier [D:\a\onnxruntime\onnxruntime\build\Release\onnxruntime_optimizer.vcxproj]
> D:\a\onnxruntime\onnxruntime\onnxruntime\core\optimizer\graph_transformer_utils.cc(213,19): error C2672: 'absl::lts_20220623::InlinedVector<std::unique_ptr<onnxruntime::GraphTransformer,std::default_delete<onnxruntime::GraphTransformer>>,6,std::allocator<T>>::emplace_back': no matching overloaded function found [D:\a\onnxruntime\onnxruntime\build\Release\onnxruntime_optimizer.vcxproj]
> ```
> 
> Are any other builds failing due to this error? It is unrelated to this code change.
> 
> I would be happy to rebase the code if the error has already been fixed and just happened to be caught by my PR.

Don't worry. It's been fixed.

**Comment by georgen117** [comment]
> Don't worry. It's been fixed.

@wejoncy Do you want me to rebase the code so it contains the fix or will you override the CI build failures?

**Pull request merged**
