### PR TITLE
Unique operator with double

### PR DESCRIPTION
**Pull request by adityagoel4512**
### Description
The [ONNX standard](https://github.com/onnx/onnx/blob/main/docs/Operators.md#type-constraints-181) permits the `Unique` operator to have `double` input tensor element type, however this was not supported in onnxruntime. This PR enables this kernel.

### Motivation and Context
The lack of support for `float64` forces users currently to cast to `float32` instead. This loss of precision can be severely problematic in feature engineering pipelines downstream of the `Unique` operator. It would be good to prevent this by updating ORT to reflect the standard and support `double` input tensors.

### CODE REVIEW

**Comment by baijumeswani** [comment]
[adityagoel4512](https://github.com/adityagoel4512) you will need to merge main and push again so that all pipelines can run successfully.

**Comment by adityagoel4512** [comment]
@baijumeswani done, thanks for picking this up.

**Comment by baijumeswani** [comment]
Some pipelines are refusing to run with error: `refs/heads/adityagoel4512:double_unique_operator. GitHub reported the error, "No commit found for SHA: refs/heads/adityagoel4512:double_unique_operator"`

Closing an reopening the PR.

**Review by baijumeswani — APPROVED** [review]

**Comment by baijumeswani** [comment]
Thanks for your contribution. :)

**Pull request merged**
