### PR TITLE
Expose DirectML provider to Python

### PR DESCRIPTION
**Pull request by RobinKa**
**Description**: Exposed the DirectML (DML) provider to Python.

**Motivation and Context**
Previously the DML provider was not exposed to python.

Fixes https://github.com/microsoft/onnxruntime/issues/3358

### CODE REVIEW

**Comment by pranavsharma** [comment]
@RobinKa can you resolve the conflicts? We're planning to do a release soon and it'll be nice to get this as part of the release. Thanks!

**Comment by RobinKa** [comment]
When I try to check any of the builds I just get "Build not found" (for example [this one](https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=127302)).

**Comment by pranavsharma** [comment]
> When I try to check any of the builds I just get "Build not found" (for example [this one](https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=127302)).
> 
> // Edit: oh sorry you mean merge conflicts, I'll take a look.

Once you resolve the conflicts we can trigger the build.

**Comment by RobinKa** [comment]
Alright I resolved the conflicts. There are still some tests failing for me (but they also fail on the upstream master).

**Comment by faxu** [comment]
@RobinKa can you address conflicts?

**Comment by cameronmaske** [comment]
@faxu I'm attempted to resolve these conflicts on a separate PR #4630

**Comment by hariharans29** [comment]
Closing as this is a dupe of #4630

**Pull request closed without merging**
