### PR TITLE
Download protoc.exe from nuget when cross-compiling

### PR DESCRIPTION
**Pull request by snnn**
### Description
1. The protoc package on nuget.org contains binaries for Windows_x86/Windows_x64/Linux_x86/Linux_x64/MacOS_x64, which can cover most use cases. Though it doesn't have binaries for AMR64, they are only needed when we cross-compile for Intel CPUs on ARM CPUs. It is rare. When you have such a need, you always can build protoc from source by yourself and pass it to build.py as "--path_to_protoc_exe".  Or if you have security concerns that you don't want to use prebuilt binaries from outside, you can do the same thing.

2. Remove GoogleTestAdapter related thing. That part of code is out of maintain.
### Motivation and Context
Because I deleted the cmake/external/protobuf folder in PR #15190.

### CODE REVIEW

**Comment by mszhanyi** [comment]
Will it be moved into windows image?

**Comment by snnn** [comment]
> Will it be moved into windows image?

I think it is not needed. The nuget file is relatively small. Downloading it does not take much time. And downloading from nuget is easier to maintain and update.

**Review by jchen351 — DISMISSED** [review]
lgtm

**Review by jchen351 — APPROVED** [review]
LGTM

**Pull request merged**
