### PR TITLE
[WebNN EP] Update triangular_op_builder.cc

### PR DESCRIPTION
**Pull request by peishenyan**
As a follow-up of https://github.com/microsoft/onnxruntime/pull/20730

### CODE REVIEW

**Comment by peishenyan** [comment]
Thanks for the suggestions of @fdwr 
I polish the existing code in `triangular_op_builder.cc`
PTAL @Honry @guschmue @fdwr

**Review by fdwr — APPROVED** [review]
👍

**Comment by peishenyan** [comment]
Hi @fdwr , it looks like some checks are stuck? Is there anything I can do?

**Comment by fdwr** [comment]
Thanks Peishen. Merging.

**Pull request merged**
