### PR TITLE
Add FP16 support for Whisper model

### PR DESCRIPTION
**Pull request by stevenlix**
Current ORT can only run inference for Whisper FP32 model. This PR adds FP16 support.

### CODE REVIEW

**Comment by tianleiwu** [comment]
Add a test case?

**Comment by stevenlix** [comment]
ContribOperators.md also needs to be updated since FP16 is added in contrib_defs.cc . Is there a specific command to run gen_contrib_doc.py?

**Comment by tianleiwu** [comment]
> ContribOperators.md also needs to be updated since FP16 is added in contrib_defs.cc . Is there a specific command to run gen_contrib_doc.py?

You can download ContribOperators.md from kernelDocumentation build pipeline (see the failed pipeline) published artifacts.

**Comment by yufenglee** [comment]
> ContribOperators.md also needs to be updated since FP16 is added in contrib_defs.cc . Is there a specific command to run gen_contrib_doc.py?

Windows GPU CI pipeline generates and unloads them as artifacts. You can download the updated version there:
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=952726&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by stevenlix** [comment]
> Sure. We may merge this PR first so people can run Wisper FP16 mode. I will add a test case with HF testing model in a separate PR.

**Comment by stevenlix** [comment]
> Add a test case with hf-internal-testing/tiny-random-WhisperForConditionalGeneration model?

Sure. We may merge this PR first so people can run Wisper FP16 mode. I will add a test case with HF testing model in a separate PR.

**Review by yufenglee — APPROVED** [review]

**Review by tianleiwu — APPROVED** [review]

**Pull request merged**
