### PR TITLE
[AIX] build fix for using system install protobuf/onnx

### PR DESCRIPTION
**Pull request by ranjitshs**
### Description
Fixing merge issue occurred in https://github.com/microsoft/onnxruntime/pull/22272 

### Motivation and Context
To build onnxruntime using system installed protobuf/onnx.

### CODE REVIEW

**Comment by ranjitshs** [comment]
@snnn  @tianleiwu 
Small fix in this PR. Please review and trigger CI workflows

**Review by tianleiwu — APPROVED** [review]

**Comment by ranjitshs** [comment]
Thanks @tianleiwu for merging this

**Pull request merged**
