### PR TITLE
Suppress Level 3 (c4996) compile warning for CUDA

### PR DESCRIPTION
**Pull request by mc-nv**
### Description
Suppress Level 3 compile warnings for CUDA

### Motivation and Context
CUDA 12.2.1 trowing error on compilation. 
https://github.com/microsoft/onnxruntime/issues/16942

### CODE REVIEW

**Comment by snnn** [comment]
You can add it to line 930 as:
```
        target_compile_options(${target_name} PRIVATE "$<$<COMPILE_LANGUAGE:CUDA>:SHELL:--compiler-options /wd4996>")
```
Then it will only impact nvcc.  The problem you are fixing is more like a nvcc bug.

**Comment by snnn** [comment]
If we disable this warning for all the build, when the original problem is fixed, we need to fix this warning for all the EPs (clean up the code), and very likely nobody can take the job.

**Comment by mc-nv** [comment]
> If we disable this warning for all the build, when the original problem is fixed, we need to fix this warning for all the EPs (clean up the code), and very likely nobody can take the job.

> You can add it to line 930 as:
> 
> ```
>         target_compile_options(${target_name} PRIVATE "$<$<COMPILE_LANGUAGE:CUDA>:SHELL:--compiler-options /wd4996>")
> ```
> 
> Then it will only impact nvcc. The problem you are fixing is more like a nvcc bug.


I have tied to do it in way you propose but get it failed: 
```
C:\workspace\build\Release>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvcc.exe"  --use-local-env -ccbin "C:\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu    
  -IC:\workspace\onnxruntime\include\onnxruntime -IC:\workspace\onnxruntime\include\onnxruntime\core\session -I"C:\workspace\build\Release\_deps\pytorch_cpuinfo-src\include" -IC:\workspace\bu 
  ild\Release -IC:\workspace\onnxruntime\onnxruntime -I"C:\workspace\build\Release\_deps\abseil_cpp-src" -I"C:\workspace\build\Release\_deps\safeint-src" -I"C:\workspace\build\Release\_deps\g 
  sl-src\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include" -I"C:\workspace\build\Release\_deps\onnx-src" -I"C:\workspace\build\Release\_deps\onnx-build" -I"C:\work 
  space\build\Release\_deps\protobuf-src\src" -I"C:\workspace\build\Release\_deps\flatbuffers-src\include" -I"C:\workspace\build\Release\_deps\cutlass-src\include" -I"C:\workspace\build\Relea 
  se\_deps\cutlass-src\examples" -I"C:\workspace\build\Release\_deps\eigen-src" -I\TensorRT\include -I"C:\workspace\build\Release\_deps\mp11-src\include" -I"C:\Program Files\NVIDIA GPU Comput 
  ing Toolkit\CUDA\v12.2\include"     --keep-dir x64\Release  -maxrregcount=0   --machine 64 --compile -cudart shared --expt-relaxed-constexpr --Werror default-stream-launch -Xcudafe --diag_s 
  uppress=bad_friend_decl -Xcudafe --diag_suppress=unsigned_compare_with_zero -Xcudafe --diag_suppress=expr_has_no_effect -include algorithm -std=c++17 --generate-code=arch=compute_60,code=[c 
  ompute_60,sm_60] --generate-code=arch=compute_61,code=[compute_61,sm_61] --generate-code=arch=compute_70,code=[compute_70,sm_70] --generate-code=arch=compute_75,code=[compute_75,sm_75] --ge 
  nerate-code=arch=compute_80,code=[compute_80,sm_80] --generate-code=arch=compute_86,code=[compute_86,sm_86] --generate-code=arch=compute_90,code=[compute_90,sm_90] --diag-suppress 554 /wd42 
  51 /wd4201 /wd5054 /w15038 --threads 0 -Werror all-warnings -Xcompiler="/EHsc -Ob2 /utf-8 /sdl /experimental:external /external:W0 /external:templates- /external:IC:/workspace/onnxruntime/c 
  make /external:IC:/workspace/build/Release /wd4996 /wd4996 /wd4996 /wd4996 /guard:cf /wd4251 /wd4201 /wd5054 /w15038 /wd4834 /wd4127"   -D_WINDOWS -DNDEBUG -DCPUINFO_SUPPORTED_PLATFORM=1 -D 
  EIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DUSE_CUDA=1 -DUSE_FLASH_ATTENTION=1 -DUSE_TENSORRT=1 -DONNX_NAMESPACE= 
  onnx -DONNX_ML=1 -DWIN32_LEAN_AND_MEAN -DORT_ENABLE_STREAM -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STR 
  ONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000000 -D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING=1 -D"CMAKE_INTDIR=\"Release\""  
  -Donnxruntime_providers_cuda_EXPORTS -D_WINDLL -D_MBCS -DWIN32 -D_WINDOWS -DEIGEN_HAS_C99_MATH -DCPUINFO_SUPPORTED -DNDEBUG -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_USE_THREADS -DPLATFORM_WIN 
  DOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DUSE_CUDA=1 -DUSE_FLASH_ATTENTION=1 -DUSE_TENSORRT=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DWIN32_LEAN_AN 
  D_MEAN -DORT_ENABLE_STREAM -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMIL 
  Y=100 -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000000 -D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING=1 -D"CMAKE_INTDIR=\"Release\"" -Donnxruntime_providers_cuda_EXP 
  ORTS -Xcompiler "/EHsc /W3 /nologo /O2 /FS   /MD /GR" -Xcompiler "/Fdonnxruntime_providers_cuda.dir\Release\vc142.pdb" -o onnxruntime_providers_cuda.dir\Release\image_scaler_impl.obj "C:\wo 
  rkspace\onnxruntime\onnxruntime\contrib_ops\cuda\tensor\image_scaler_impl.cu"
  nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
C:\BuildTools\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 12.2.targets(799,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvcc.exe"  --us 
e-local-env -ccbin "C:\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -IC:\workspace\onnxruntime\include\onnxruntime -IC:\workspace\onnxruntime\include\onnxruntime\core\session 
 -I"C:\workspace\build\Release\_deps\pytorch_cpuinfo-src\include" -IC:\workspace\build\Release -IC:\workspace\onnxruntime\onnxruntime -I"C:\workspace\build\Release\_deps\abseil_cpp-src" -I"C: 
\workspace\build\Release\_deps\safeint-src" -I"C:\workspace\build\Release\_deps\gsl-src\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include" -I"C:\workspace\build\Rel 
ease\_deps\onnx-src" -I"C:\workspace\build\Release\_deps\onnx-build" -I"C:\workspace\build\Release\_deps\protobuf-src\src" -I"C:\workspace\build\Release\_deps\flatbuffers-src\include" -I"C:\w 
orkspace\build\Release\_deps\cutlass-src\include" -I"C:\workspace\build\Release\_deps\cutlass-src\examples" -I"C:\workspace\build\Release\_deps\eigen-src" -I\TensorRT\include -I"C:\workspace\ 
build\Release\_deps\mp11-src\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include"     --keep-dir x64\Release  -maxrregcount=0   --machine 64 --compile -cudart shared  
--expt-relaxed-constexpr --Werror default-stream-launch -Xcudafe --diag_suppress=bad_friend_decl -Xcudafe --diag_suppress=unsigned_compare_with_zero -Xcudafe --diag_suppress=expr_has_no_effec 
t -include algorithm -std=c++17 --generate-code=arch=compute_60,code=[compute_60,sm_60] --generate-code=arch=compute_61,code=[compute_61,sm_61] --generate-code=arch=compute_70,code=[compute_7 
0,sm_70] --generate-code=arch=compute_75,code=[compute_75,sm_75] --generate-code=arch=compute_80,code=[compute_80,sm_80] --generate-code=arch=compute_86,code=[compute_86,sm_86] --generate-cod 
e=arch=compute_90,code=[compute_90,sm_90] --diag-suppress 554 /wd4251 /wd4201 /wd5054 /w15038 --threads 0 -Werror all-warnings -Xcompiler="/EHsc -Ob2 /utf-8 /sdl /experimental:external /exter 
nal:W0 /external:templates- /external:IC:/workspace/onnxruntime/cmake /external:IC:/workspace/build/Release /wd4996 /wd4996 /wd4996 /wd4996 /guard:cf /wd4251 /wd4201 /wd5054 /w15038 /wd4834 / 
wd4127"   -D_WINDOWS -DNDEBUG -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DUSE_CUDA 
=1 -DUSE_FLASH_ATTENTION=1 -DUSE_TENSORRT=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DWIN32_LEAN_AND_MEAN -DORT_ENABLE_STREAM -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES  
-DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000000 -D_SILENCE_EXPERIMENTAL_FILES 
YSTEM_DEPRECATION_WARNING=1 -D"CMAKE_INTDIR=\"Release\"" -Donnxruntime_providers_cuda_EXPORTS -D_WINDLL -D_MBCS -DWIN32 -D_WINDOWS -DEIGEN_HAS_C99_MATH -DCPUINFO_SUPPORTED -DNDEBUG -DCPUINFO_ 
SUPPORTED_PLATFORM=1 -DEIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DUSE_CUDA=1 -DUSE_FLASH_ATTENTION=1 -DUSE_TENSORR 
T=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DWIN32_LEAN_AND_MEAN -DORT_ENABLE_STREAM -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11 
_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000000 -D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING=1 -D"CMAKE_INT 
DIR=\"Release\"" -Donnxruntime_providers_cuda_EXPORTS -Xcompiler "/EHsc /W3 /nologo /O2 /FS   /MD /GR" -Xcompiler "/Fdonnxruntime_providers_cuda.dir\Release\vc142.pdb" -o onnxruntime_provider 
s_cuda.dir\Release\image_scaler_impl.obj "C:\workspace\onnxruntime\onnxruntime\contrib_ops\cuda\tensor\image_scaler_impl.cu"" exited with code 1. [C:\workspace\build\Release\onnxruntime_provi 
ders_cuda.vcxproj]
```

**Comment by snnn** [comment]
Let me try it.

**Comment by jywu-msft** [comment]
> Let me try it.

@snnn any updates?

**Comment by mc-nv** [comment]
My progress is in partial here. 
I had confirmed that the suppress flag in this PR is suitable for `1.15.1` version. 

But I'm still unable to build against `main` branch as I'm facing issue with installing some packages using `vcpkg` I may have some progress by end of week.

**Comment by mc-nv** [comment]
I was able to build against `main` branch using `CUDA 12.2.1` 
```
.\build.bat --cmake_generator "Visual Studio 17 2022" --config Release --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=60;61;70;75;80;86;90" --skip_submodule_sync --build_shared_lib --parallel --build --build_dir /workspace/build --use_cuda --cuda_version "12.2" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" --use_tensorrt --tensorrt_home "/tensorrt" --update
```
But only with flag given in current PR.

**Comment by snnn** [comment]
I'm working on it.

**Comment by snnn** [comment]
Here is the command after adding "/wd4996"

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\extras\visual_studio_integration\MSBuildExtensions\CUDA 12.2.targets(799,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvcc.exe"  --use-local-env -ccbin "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64" -x cu   -IC:\src\onnxruntime\include\onnxruntime -IC:\src\onnxruntime\include\onnxruntime\core\session -I"C:\src\onnxruntime\c\Debug\_deps\pytorch_cpuinfo-src\include" -IC:\src\onnxruntime\c\Debug -IC:\src\onnxruntime\onnxruntime -I"C:\src\onnxruntime\c\Debug\_deps\abseil_cpp-src" -I"C:\src\onnxruntime\c\Debug\_deps\safeint-src" -I"C:\src\onnxruntime\c\Debug\_deps\gsl-src\include" -I"C:\src\onnxruntime\c\Debug\_deps\onnx-src" -I"C:\src\onnxruntime\c\Debug\_deps\onnx-build" -I"C:\src\onnxruntime\c\Debug\_deps\protobuf-src\src" -I"C:\src\onnxruntime\c\Debug\_deps\flatbuffers-src\include" -I"C:\src\onnxruntime\c\Debug\_deps\cutlass-src\include" -I"C:\src\onnxruntime\c\Debug\_deps\cutlass-src\examples" -I"C:\src\onnxruntime\c\Debug\_deps\eigen-src" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include" -I"C:\src\onnxruntime\c\Debug\_deps\mp11-src\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\include"     --keep-dir x64\Debug  -maxrregcount=0   --machine 64 --compile -cudart shared -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_90,code=sm_90 --expt-relaxed-constexpr --Werror default-stream-launch -Xcudafe --diag_suppress=bad_friend_decl -Xcudafe --diag_suppress=unsigned_compare_with_zero -Xcudafe --diag_suppress=expr_has_no_effect -std=c++17 -Xcudafe --diag_suppress=conversion_function_not_usable --threads 1 -Werror all-warnings -Xcompiler="/EHsc -Ob0 -Zi /wd4996 /utf-8 /sdl /experimental:external /external:W0 /external:templates- /external:IC:/src/onnxruntime/cmake /external:IC:/src/onnxruntime/c/Debug /wd4251 /wd4201 /wd5054 /w15038 /guard:cf /Qspectre /wd4251 /wd4201 /wd5054 /w15038 /wd4834 /wd4127" -g  -D_WINDOWS -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DONNXRUNTIME_ENABLE_MEMLEAK_CHECK -DUSE_CUDA=1 -DUSE_FLASH_ATTENTION=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DONNX_USE_LITE_PROTO=1 -D__ONNX_NO_DOC_STRINGS -DWIN32_LEAN_AND_MEAN -DORT_ENABLE_STREAM -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000000 -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -DWIN32 -D_WINDOWS -DEIGEN_HAS_C99_MATH -DCPUINFO_SUPPORTED -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DONNXRUNTIME_ENABLE_MEMLEAK_CHECK -DUSE_CUDA=1 -DUSE_FLASH_ATTENTION=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DONNX_USE_LITE_PROTO=1 -D__ONNX_NO_DOC_STRINGS -DWIN32_LEAN_AND_MEAN -DORT_ENABLE_STREAM -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=0x0A000000 -D"CMAKE_INTDIR=\"Debug\"" -Xcompiler "/EHsc /W3 /nologo /Od /FS /Zi /RTC1 /MDd /GR" -Xcompiler "/Fdonnxruntime_providers_cuda_obj.dir\Debug\onnxruntime_providers_cuda_obj.pdb" -o onnxruntime_providers_cuda_obj.dir\Debug\cuda_utils.obj "C:\src\onnxruntime\onnxruntime\core\providers\cuda\cuda_utils.cu""

You are right . It doesn't work.

**Comment by snnn** [comment]
Can you try this change:

https://github.com/microsoft/onnxruntime/compare/snnn/cuda_build?expand=1

**Comment by mc-nv** [comment]
> Can you try this change:
> 
> https://github.com/microsoft/onnxruntime/compare/snnn/cuda_build?expand=1

trying...

**Comment by mc-nv** [comment]
I had failed on my machine using `--parallel` flag due to reaching heap size... 
```
C:\> Get-WmiObject Win32_Processor | Select-Object Name, LastModifiedDate, NumberOfCores, NumberOfLogicalProcessors

Name                                        LastModifiedDate NumberOfCores NumberOfLogicalProcessors
----                                        ---------------- ------------- -------------------------
Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz                             10                        20
C:\>  systeminfo | findstr /i Total
Total Physical Memory:     65,189 MB
```
Compiling without that flag for now.

**Comment by snnn** [comment]
I use Microsoft Devbox to do my work. https://learn.microsoft.com/en-us/azure/dev-box/overview-what-is-microsoft-dev-box  . The one I'm using also has 64GB memory. I don't see cl.exe or nvcc.exe runs out of memory. Maybe that was just a bad luck. Hope it will pass in your this try.

**Comment by mc-nv** [comment]
I was able to build with `DISABLE_CUSPARSE_DEPRECATED` flag. 
https://github.com/microsoft/onnxruntime/issues/16942#issuecomment-1663030837

**Pull request closed without merging**
