### PR TITLE
Add binary comparators to the OneDNN (dnnl) execution provider

### PR DESCRIPTION
**Pull request by georgen117**
**Description**: 
Add "Equal", "Greater", "GreaterOrEqual", "Less", and "LessOrEqual" operators for the DNNL execution provider

**Motivation and Context**
- Why is this change required? What problem does it solve?
Helps expand the ONNX Operators covered by the DNN exeuciton provider.
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by georgen117** [comment]
@jywu-msft maintainer please run `/azp run Linux DNNL CI Pipeline` since this is the primary pipeline for testing the OneDNN execution provider.

**Comment by jywu-msft** [comment]
it looks like the MacOS CI failure will be fixed by https://github.com/microsoft/onnxruntime/pull/11682
you'll need to update master branch when that commit gets merged.
sorry for the inconvenience.

**Comment by georgen117** [comment]
> it looks like the MacOS CI failure will be fixed by #11682 you'll need to update master branch when that commit gets merged. sorry for the inconvenience.

Thanks for the heads up.  It looks like #11682 has merged.  I rebased the code this morning and did a few fast sanity checks.  If you could restart the CI builds.  Thanks @jywu-msft.

**Comment by georgen117** [comment]
@jywu-msft it appears like the `Linux CPU CI pipeline` and `Linux DNNL CI Pipeline` both failed due to running out of space. The `Linux GPU TensorRC CI Pipeline` is it a little unclear to me why that failed.  I looks like it made it through almost the full build then failed with no obvious error.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
