### PR TITLE
Remove C/CObj flag when building C++ code

### PR DESCRIPTION
**Pull request by wschin**
Address #9763. A few indents are changed by auto-formating.

### CODE REVIEW

**Comment by garymm** [comment]
Thanks!
See my comment on the bug. If this issue doesn't exist in Python 3.7, let's ignore it.

**Comment by wschin** [comment]
> Thanks! See my comment on the bug. If this issue doesn't exist in Python 3.7, let's ignore it.

This still exists in `3.7` (my environment).

**Review by garymm — APPROVED** [review]
Thanks!

**Comment by garymm** [comment]
@wschin would be nice to see this if you have time to merge it.

**Comment by baijumeswani** [comment]
Closing as stale. Please reopen if still relevant.

**Pull request closed without merging**
