### PR TITLE
Fix reshape fusion

### PR DESCRIPTION
**Pull request by MaximKalininMS**
**Description**: Fix reshape fusion.

**Motivation and Context**
https://github.com/microsoft/onnxruntime/pull/3554 introduced a bug:
initializers can now come before Shape->Gather->Unsqueeze chains; if
those initializers have more than 1 element, expected dimensions in the
chains are now incorrect.

### CODE REVIEW

**Comment by skottmckay** [comment]
>     if (optimizer_utils::AppendTensorFromInitializer(graph, *(concat.InputDefs()[i]), shape_value)) {

It would be good to use graph_utils::IsConstantInitializer here instead of hoping something doesn't get overridden. 

---
Refers to: onnxruntime/core/optimizer/reshape_fusion.cc:97 in 5a65933. [](commit_id = 5a659338be431884b3e18c02b172dd204f4294c9, deletion_comment = False)

**Comment by MaximKalininMS** [comment]
@skottmckay @tianleiwu I didn't try or intend to fix all pre-existing issues. I suggest to complete this PR first, and then I can try to address long-standing bugs.

**Comment by skottmckay** [comment]
> @skottmckay @tianleiwu I didn't try or intend to fix all pre-existing issues. I suggest to complete this PR first, and then I can try to address long-standing bugs.

Sure. There's a different issue with the fusion that Tianlei is looking at so perhaps they can be handled as part of that PR.

**Comment by MaximKalininMS** [comment]
That issue is also pre-existing but seems easy enough to fix here.
Regarding your comment, is this what you have in mind?
```
if (graph_utils::IsConstantInitializer(graph, concat.InputDefs()[i]->Name()) &&
      optimizer_utils::AppendTensorFromInitializer(graph, *(concat.InputDefs()[i]), shape_value)) {
```

**Comment by skottmckay** [comment]
> That issue is also pre-existing but seems easy enough to fix here.
> Regarding your comment, is this what you have in mind?
> 
> ```
> if (graph_utils::IsConstantInitializer(graph, concat.InputDefs()[i]->Name()) &&
>       optimizer_utils::AppendTensorFromInitializer(graph, *(concat.InputDefs()[i]), shape_value)) {
> ```

Yep.

**Comment by tianleiwu** [comment]
> @skottmckay @tianleiwu I didn't try or intend to fix all pre-existing issues. I suggest to complete this PR first, and then I can try to address long-standing bugs.

No problem. I could send another PR. 

Note that the long-standing bug does not trigger normally. After expanding reshape fusion coverage, it is easy to trigger now. For example, we encountered a case that reshapes to 2D, it does not trigger before you change since old logic only applies to 3D or 4D only.

**Comment by MaximKalininMS** [comment]
OK, let me add test cases and update this PR.

**Comment by MaximKalininMS** [comment]
@skottmckay @tianleiwu I updated the branch with the fixes for the two issues. Would you like me to send another PR?

**Pull request closed without merging**
