### PR TITLE
use version instead of version-dev for ROCM

### PR DESCRIPTION
**Pull request by TedThemistokleous**
### Description

Use version instead of version-dev

### CODE REVIEW

**Comment by tianleiwu** [comment]
@cloudhan @PeixuanZuo please also take a look at https://github.com/microsoft/onnxruntime/pull/17667.

**Comment by TedThemistokleous** [comment]
> @cloudhan @PeixuanZuo please also take a look at #17667.

Also urgent and related: https://github.com/microsoft/onnxruntime-inference-examples/pull/395

**Review by cloudhan — APPROVED** [review]

**Pull request merged**
