### PR TITLE
[ROCm] add gfx1100 and gfx1101 to CMAKE_HIP_ARCHITECTURES

### PR DESCRIPTION
**Pull request by jeffdaily**
### Description
Support additional AMD GPU architectures.

### Motivation and Context
AMD announced expanding support for additional GPUs.

https://community.amd.com/t5/rocm/new-rocm-5-6-release-brings-enhancements-and-optimizations-for/ba-p/614745

This PR is how we will deliver that expanded support to onnxruntime.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@cloudhan,@PeixuanZuo please trigger CI pipelines.  Since CI resources only have gfx908 or gfx90a GPUs, this will be a build-only test for the other gfx targets.

Thanks.

**Review by cloudhan — APPROVED** [review]

**Pull request merged**
