### PR TITLE
Second round cherry-pick to rel-1.9.0

### PR DESCRIPTION
**Pull request by wangyems**
**Description**: Describe your changes.
Includes the below PRs
image

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by fs-eire — APPROVED** [review]
LGTM for ort-web related commits

**Comment by snnn** [comment]
Could you please help me get #9049 in?

**Comment by wangyems** [comment]
> Could you please help me get #9049 in? Sorry it comes late.

added

**Review by fs-eire — APPROVED** [review]

**Review by pranavsharma — APPROVED** [review]

**Review by liqunfu — APPROVED** [review]

**Pull request merged**
