### PR TITLE
[js/webgpu] fix two errors of attention operator

### PR DESCRIPTION
**Pull request by xhcao**

### CODE REVIEW

**Comment by xhcao** [comment]
When I run stable-diffusion-2-1 model, there are two errors in attention softmax program.
1. the number of `scale` cannot be directly upload to f16 uniform buffer.
2. currently, the softmax program does not handle the normalized dispatch group values, so if the sequence length is over 65535, the result is not correct for this program.

**Comment by xhcao** [comment]
@qjia7 @fs-eire PTAL

**Review by qjia7 — APPROVED** [review]
LGTM, thanks.

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
