### PR TITLE
Support arm64e arch for osx

### PR DESCRIPTION
**Pull request by aud-ktw**
**Description**: Describe your changes.
- Added arm64e to choices variable in build.py file
- Added if-elseif statement for arm64e in onnxruntime_mlas.cmake file.

**Motivation and Context**
- Why is this change required? What problem does it solve?
Xcode supports arm64e from version 10.1,[ Xcode 10.1 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-10_1-release-notes?preferredLanguage=occ)

- If it fixes an open issue, please link to the issue here.
https://github.com/microsoft/onnxruntime/issues/7727

### CODE REVIEW

**Review by snnn — APPROVED** [review]
LGTM.

**Comment by snnn** [comment]
Thank you!

**Comment by aud-ktw** [comment]
Thank you :)

**Pull request merged**
