### PR TITLE
[MIGraphX EP] Ensure we support all inputs for MatMulInteger and ConvInteger.

### PR DESCRIPTION
**Pull request by TedThemistokleous**
… to int8 for now

Allow for models with biases/full input and only check for int8 support in EP

### Description

Allows for all inputs for MatMulInteger and ConvInteger to be supported for prequantized models

### Motivation and Context

Fixes issues when using prequantized models that contain weight biases

### CODE REVIEW

**Comment by TedThemistokleous** [comment]
Ping @cloudhand @tianleiwu @PeixuanZuo  @ytaous  Need CI run on this

**Comment by TedThemistokleous** [comment]
@Cloudhan Azure won't allow me to run failed jobs and it appears to be a java issue. I haven't touched anything with Java for this PR so unsure why that stage would fail

**Comment by TedThemistokleous** [comment]
@Cloudhan  Please let me know if there's anything else

**Comment by TedThemistokleous** [comment]
Is tthere anything more on this? The lint failures are refencing cuda code to which I didn't touch

**Comment by tianleiwu** [comment]
Please run `lintrunner -a` to fix python format. That's a pipeline required to pass.

**Comment by TedThemistokleous** [comment]
I've run it twice with no avail. The changes refereced CUDA. I've merged main it before pushing again.

**Comment by tianleiwu** [comment]
> I've run it twice with no avail. 

After merging main, you might need run lintrunner installation again just in case some packages used in lintrunner is changed in main.
```
pip install requirements-lintrunner.txt
pip install lintrunner
lintrunner init
lintrunner -a
```

**Comment by TedThemistokleous** [comment]
Done.

**Review by tianleiwu — APPROVED** [review]

**Pull request merged**
