### PR TITLE
[TVM EP] fix issue #12625 for TVM EP

### PR DESCRIPTION
**Pull request by vvchernov**
**Description**:
Update conditions in SessionState::SetupAllocators()
This is particular pacth which does not solve general problem for all EPs (see #12625) only for TVM EP

**Motivation and Context**
Customized TVM EP Allocator is overwritten by default Allocator from CPU EP on high-level which leads to problem with memory allocation.

### CODE REVIEW

**Comment by vvchernov** [comment]
Hello @xadupre, @yuslepukhin! Could you review the PR?

**Comment by yuslepukhin** [comment]
>                     auto iter = allocators_.find(memory_info);

I think the allocator name is provider specifically to create customized allocators so they can be distinguished in the associated containers. [https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/framework/ortmemoryinfo.h#L9](https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/framework/ortmemoryinfo.h#L9)

However, our custom comparator does not take name into account. [https://cs.github.com/microsoft/onnxruntime/blob/018fba9b7463664e14e4038b10545a4eb6037516/onnxruntime/core/framework/session_state.h#L426](https://cs.github.com/microsoft/onnxruntime/blob/018fba9b7463664e14e4038b10545a4eb6037516/onnxruntime/core/framework/session_state.h#L426)

Said that, this code should not use operator[], rather insert() so it can detect duplicates and raise an error as appropriate. @skottmckay 

---
Refers to: onnxruntime/core/framework/session_state.cc:40 in d74faef. [](commit_id = d74faef4b5102e38e17a8fee4c37b964ef45bfc2, deletion_comment = False)

**Comment by vvchernov** [comment]
Hello @yuslepukhin! Thanks for your comment. There are two problems: 1. during search of map (`allocators_`) the keys (`OrtMemoryInfo`) are not fully compared, looks like names are skipped. 2. Which allocator will be inserted to the map depends on order of pass of providers. In my case CPU EP is met earlier than TVM EP.
I will be glad if it is solved not so rude as in my patch.

**Comment by skottmckay** [comment]
>                     auto iter = allocators_.find(memory_info);

The name isn't included as an allocator is really device specific rather than EP specific. When name was included we ended up with multiple allocators for the same device, each with their own arena, which causes a lot of wasted memory usage.

It sounds like your issue is that your want to control the alignment though, which doesn't necessarily require a new allocator. Hacking in a special case for TVM here isn't really a good solution either way. 

2 options come to mind. There are probably more.

1) Add the ability to configure the alignment

2) Pass the AllocatorManager used [here](https://github.com/microsoft/onnxruntime/blob/0c6037b5abe571fc43a55ef7a9d2f846820fbe5d/onnxruntime/core/session/inference_session.cc#L1236-L1250) through to session state finalization and use the final list of allocators there, as the allocator manager has the notion of allowing an EP to replace an allocator for the device. That would need more thought though as the semantics may not be clear enough.

---
In reply to: [1218331827](https://github.com/microsoft/onnxruntime/pull/12627#issuecomment-1218331827) [](http://example.com/codeflow?ancestors=1218331827,1218331827)

---
Refers to: onnxruntime/core/framework/session_state.cc:40 in d74faef. [](commit_id = d74faef4b5102e38e17a8fee4c37b964ef45bfc2, deletion_comment = False)

**Comment by vvchernov** [comment]
Hello @skottmckay! I think the second way is really complicated and it requires many changes that potentially leads to new problems. The first one seemed better, but without going into possible technical problems, a few general questions arise. In my case I should adjust alignment for CPU EP when I work with TVM EP that looks strange and non client-oriented interface. If alignment is configured for all allocators it can lead to the same problem for the part of them inside EP API. If alignment is configured for each allocators separatly but we choose only one how it influence on behaviour of other EPs. Recently default alignment was 256 and looks like it solved all problems, now it depends on mlas library method. What is if specified allocator is complicated enough and has several alignments inside?
I implemented [new idea](https://github.com/microsoft/onnxruntime/pull/12702) which is close to your first one, could you see it?

**Comment by pranavsharma** [comment]
Please give us a few days. We need to think through the ramifications of any design. How urgent is this for you? A few ideas that come to mind are (1) revert to reverse iteration change in SetupAllocators (2) SetupAllocators should special case only for cuda/tensorrt since only cuda deals with per-thread allocators (no other EP allocator needs to be per-thread). I'm leaning towards #2 since it won't affect other EPs. Need to think through this though.

**Comment by vvchernov** [comment]
Hello @pranavsharma! Thanks you for quick responce. I have time but not so much. Of course, if you have good idea for solution on high-level it will be better to implement it. Unfortunately I'm not familiar enough with allocator problems related to cuda and can not help to resolve it, but I tried to solve my issue in maximally general way.

**Comment by vvchernov** [comment]
@pranavsharma see also the [PR](https://github.com/microsoft/onnxruntime/pull/12702) where the better idea is implemented I think this PR will be closed as result.

**Comment by vvchernov** [comment]
Hello @pranavsharma, @skottmckay! Any news about allocator issue?

**Comment by pranavsharma** [comment]
> Hello @pranavsharma, @skottmckay! Any news about allocator issue?

I did look at your PR. Priority doesn't belong to OrtMemoryInfo. OrtMemoryInfo describes a memory location and has nothing to do with how allocators should be registered/prioritized. At this point I'm leaning towards option 2 in my earlier comment. We'll discuss it and get back next week (we're currently inundated with other higher priority asks).

**Comment by vvchernov** [comment]
> > Hello @pranavsharma, @skottmckay! Any news about allocator issue?
> 
> I did look at your PR. Priority doesn't belong to OrtMemoryInfo. OrtMemoryInfo describes a memory location and has nothing to do with how allocators should be registered/prioritized. At this point I'm leaning towards option 2 in my earlier comment. We'll discuss it and get back next week (we're currently inundated with other higher priority asks).

Thank you for quick response. I will wait for new approach. A little bit about priority, the main is idea of allocator prioritization, the level can be kept by IAllocator instead of OrtMemoryInfo, it does not matter

**Comment by pranavsharma** [comment]
@vvchernov - We'll be reverting the reverse setup of allocators. You'll see a PR from us soon.

**Comment by vvchernov** [comment]
There's no need for this PR since @pranavsharma reverted https://github.com/microsoft/onnxruntime/pull/11700 the allocator setup. See https://github.com/microsoft/onnxruntime/pull/12954. It's already merged to the main branch.

**Pull request closed without merging**
