### PR TITLE
Remove all C/C++ samples from our C# dir

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

First, we have a new repo for the samples. All the samples should go there: https://github.com/microsoft/onnxruntime-inference-examples . And in the last team meeting we have decided to delete the C_Api_Sample.cpp because it is kind of out of maintain and it is not well written. For example, it doesn't check error status and ignores all possible errors.

Second, some other samples(like the InferenceTestCapi.cpp) apparently won't compile since the ORT 1.0 release. At that time we refactored the C API but these samples were not updated. So I will just delete them.

TODO: Add https://github.com/microsoft/onnxruntime-inference-examples to our packaging pipelines. We can use the samples there to validate our newly built packages. But I won't be able to address this concern this PR or this month. 

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by pranavsharma — APPROVED** [review]
Have these already been moved to the other repo?

**Comment by snnn** [comment]
> Have these already been moved to the other repo?

The last time we decided to remove them, instead of keeping them and improving them.

**Comment by shp776** [comment]
Using the C_API you've provided,
(https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2)
The onnx transformation model of the above link was successful to load. It was also confirmed that input tensor and output tensor values at pytorch match.

I am going to convert input text to input tensor value and use output tensor value to generate text. I wonder if there's any problem with my project at this point in time when you guys deleted your C_API because it is not well written and has error, as you said.

**Comment by snnn** [comment]
The C API  has no problem. The samples are out of maintain. Welcome to use the C API.

**Comment by snnn** [comment]
There is a better sample: https://github.com/microsoft/onnxruntime-inference-examples/blob/main/c_cxx/fns_candy_style_transfer/fns_candy_style_transfer.c

**Comment by shp776** [comment]
Thank you for your quick feedback. 

My final goal of the project is to load the gpt-2 onnx model using onnx runtime's C/C++ API and write the C/C++ code to generate text using output tensor values. The example you suggested above seems to be C_API related to image processing. I want to know if there is a link to the text generation code or source related to natural language processing using the output tensor value.

**Comment by snnn** [comment]
Sorry we don't. Welcome to contribute your samples to https://github.com/microsoft/onnxruntime-inference-examples/ or https://github.com/onnx/models

**Pull request merged**
