### PR TITLE
[VitisAI] Remove shape infer from bridge ort

### PR DESCRIPTION
**Pull request by mingyueliuh**
### Description
Vitis AI EP's custom op are completely self contained within Vitis AI EP implementation (rather than needing to add static functions in provider_bridge).

### CODE REVIEW

**Comment by mingyueliuh** [comment]
@jywu-msft please take a look when you are available. Thanks.

**Comment by jywu-msft** [comment]
> @jywu-msft please take a look when you are available. Thanks.

looks like there is a merge conflict?

**Comment by mingyueliuh** [comment]
> > @jywu-msft please take a look when you are available. Thanks.
> 
> looks like there is a merge conflict?

Thanks @jywu-msft  ,  has been fixed  conflict and rebase to main branch.

**Comment by jywu-msft** [comment]
looks like merging https://github.com/microsoft/onnxruntime/pull/21688 causes a conflict for this PR

**Comment by mingyueliuh** [comment]
> looks like merging #21688 causes a conflict for this PR

hi @jywu-msft , fixed conflict and rebased onto main branch, please take a look , Thanks.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
