### PR TITLE
Fix a bug in fusion_embedlayer.py

### PR DESCRIPTION
**Pull request by wangyems**
**Description**: Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.
https://github.com/microsoft/onnxruntime/issues/10003

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
This fix the graph optimization works for the model used in the code attached to the linked issue (#10003), but crash for a real distilbert model.

To reproduce, in the code attached to the linked issue (#10003), if you replace:

```python
# ...
hub_model = "cardiffnlp/twitter-roberta-base-sentiment"  # because it has lots of downloads, quite classic
# ...
```
by 

```python
# ...
hub_model = "distilbert-base-uncased"
# ...
```

It raises the following Exception (which I think is related to the same PR):
```log
Traceback (most recent call last):
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-6f2b0fce3f29>", line 2, in <module>
    optimized_model: BertOnnxModel = optimizer.optimize_model(
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/optimizer.py", line 230, in optimize_model
    optimizer = optimize_by_fusion(model, model_type, num_heads, hidden_size, optimization_options)
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/optimizer.py", line 141, in optimize_by_fusion
    optimizer.optimize(optimization_options)
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/onnx_model_bert.py", line 322, in optimize
    self.fuse_attention()
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/onnx_model_bert.py", line 54, in fuse_attention
    self.attention_fusion.apply()
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_base.py", line 43, in apply
    self.fuse(node, input_name_to_nodes, output_name_to_node)
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_attention.py", line 455, in fuse
    new_node = self.create_attention_node(mask_index, matmul_q, matmul_k, matmul_v, add_q, add_k, add_v,
  File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_attention.py", line 172, in create_attention_node
    assert num_heads > 0
AssertionError
```

**Comment by wangyems** [comment]
> @wangyems thank you a lot for your work. This PR fixes the graph optimization when used with a Roberta model (like in the code attached to the linked issue #10003), but still crash for a real distilbert model.
> 
> To reproduce the crash, in the code attached to the linked issue (#10003), if you replace:
> 
> ```python
> # ...
> hub_model = "cardiffnlp/twitter-roberta-base-sentiment"  # because it has lots of downloads, quite classic
> # ...
> ```
> 
> by
> 
> ```python
> # ...
> hub_model = "distilbert-base-uncased"
> # ...
> ```
> 
> It raises the following Exception (which I think is related to the same PR):
> 
> ```
> Traceback (most recent call last):
>   File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-8-6f2b0fce3f29>", line 2, in <module>
>     optimized_model: BertOnnxModel = optimizer.optimize_model(
>   File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/optimizer.py", line 230, in optimize_model
>     optimizer = optimize_by_fusion(model, model_type, num_heads, hidden_size, optimization_options)
>   File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/optimizer.py", line 141, in optimize_by_fusion
>     optimizer.optimize(optimization_options)
>   File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/onnx_model_bert.py", line 322, in optimize
>     self.fuse_attention()
>   File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/onnx_model_bert.py", line 54, in fuse_attention
>     self.attention_fusion.apply()
>   File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_base.py", line 43, in apply
>     self.fuse(node, input_name_to_nodes, output_name_to_node)
>   File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_attention.py", line 455, in fuse
>     new_node = self.create_attention_node(mask_index, matmul_q, matmul_k, matmul_v, add_q, add_k, add_v,
>   File "/home/geantvert/.local/share/virtualenvs/fast_transformer/lib/python3.9/site-packages/onnxruntime/transformers/fusion_attention.py", line 172, in create_attention_node
>     assert num_heads > 0
> AssertionError
> ```

@pommedeterresautee Thanks for reporting the issue! The root cause of the assertion error is that the reshape fusion failed to match the pattern in this model and so the num_heads cannot be auto-detected by a function in attention fusion. 
Short term solution(hardcode the num_heads):
image

we will update the fusion logic for this particular model and provide instructive error message in attention fusion.

**Review by tianleiwu — APPROVED** [review]
It might be better to add some comment about the new pattern and maybe also a test case.

**Comment by wangyems** [comment]
> It might be better to add some comment about the new pattern and maybe also a test case.

Sure, will include in separate PR

**Pull request merged**
