### PR TITLE
Add two new blogs that were posted this week to the news section and C# GPU tutorial

### PR DESCRIPTION
**Pull request by cassiebreviu**
### Description
Add new blogs to news and C# GPU configuration on windows tutorial.

https://cassiebreviu.github.io/onnxruntime/news.html
https://cassiebreviu.github.io/onnxruntime/docs/tutorials/csharp/csharp-gpu.html
https://cassiebreviu.github.io/onnxruntime/docs/execution-providers/CUDA-ExecutionProvider.html

### CODE REVIEW

**Comment by faxu** [comment]
@MaanavD has an open PR that replaces some of the images with transparent backgrounds. Can you make sure the images for the new blogs follow that criteria?

**Comment by cassiebreviu** [comment]
> @MaanavD has an open PR that replaces some of the images with transparent backgrounds. Can you make sure the images for the new blogs follow that criteria?

You mean make the background transparent in photoshop for the blog images? Not sure exactly what transparency you are looking for. Please advise. Thanks!

**Comment by faxu** [comment]
https://github.com/microsoft/onnxruntime/pull/14430/commits/74ec274b7055f4f73fb1231e610a2d1ab0759046

**Comment by natke** [comment]
> > @MaanavD has an open PR that replaces some of the images with transparent backgrounds. Can you make sure the images for the new blogs follow that criteria?
> 
> @faxu You mean make the background transparent in photoshop for the blog images? Not sure exactly what transparency you are looking for. Please advise. Thanks!

AFAIK the images are pulled from the blogs themselves. We can probably ask for a revision to the cloudblogs one but would need to reach out to HF for the other one. Perhaps we should add this to the blog publication checklist

**Comment by MaanavD** [comment]
> AFAIK the images are pulled from the blogs themselves. We can probably ask for a revision to the cloudblogs one but would need to reach out to HF for the other one. Perhaps we should add this to the blog publication checklist

Actually, false. They are saved within the repository. My pr makes changes for most of the images!

**Comment by natke** [comment]
> > AFAIK the images are pulled from the blogs themselves. We can probably ask for a revision to the cloudblogs one but would need to reach out to HF for the other one. Perhaps we should add this to the blog publication checklist
> 
> Actually, false. They are saved within the repository. My pr makes changes for most of the images!

Yes, I just realized that myself. Would you be able to add the transparency to these two images too please?

**Comment by natke** [comment]
@maanavD kindly added the transparency to the images. We also swapped out the OV EP one for an image from the blog with less detail. Thanks @MaanavD 🥇

**Review by natke — APPROVED** [review]

**Pull request merged**
