### PR TITLE
[C#] Address the concern of append EP throw

### PR DESCRIPTION
**Pull request by cloudhan**
Minor refactor

### CODE REVIEW

**Review by yuslepukhin — COMMENTED** [review]
LGTM

**Review by yuslepukhin — DISMISSED** [review]

**Review by yuslepukhin — APPROVED** [review]
:shipit:

**Comment by skottmckay** [comment]
What's the concern? It wasn't mentioned in the PR description or comments in the code. With C# being a managed language won't it call Dispose on `options` anyway?

**Comment by cloudhan** [comment]
@skottmckay https://github.com/microsoft/onnxruntime/pull/15540#discussion_r1195513038 See this.

**Pull request merged**
