### PR TITLE
add noexcept to `InitApi()` and `GetApi()`

### PR DESCRIPTION
**Pull request by diablodale**
### Description

* add noexcept to `InitApi()` and `GetApi()`

### Motivation and Context

* fixes microsoft/onnxruntime#12581

### CODE REVIEW

**Comment by diablodale** [comment]
Maintainers, 15 checks seem to be hung or forever paused. Can we resolve these CI blocks?

**Comment by diablodale** [comment]
@yufenglee can you or a maintainer look into why 15 CI job/checks are forever hung or lost?

**Comment by ytaous** [comment]
> Maintainers, 15 checks seem to be hung or forever paused. Can we resolve these CI blocks?

it's not hung, someone needs to kick it off for you

**Comment by ytaous** [comment]
@fs-eire - can u pls take a look? thx

**Review by RyanUnderhill — APPROVED** [review]

**Comment by ytaous** [comment]
pls fix lint/python format, thx

**Review by RyanUnderhill — APPROVED** [review]

**Comment by ytaous** [comment]
the lint/python format is acting weird

**Comment by diablodale** [comment]
@RyanUnderhill introduced a commit that I don't think is in alignment with onnxruntime general approach.
I suggest his commit be removed; to be reverted to my original PR.
I'm happy to rebase on to main myself and force-push.

Reference https://github.com/microsoft/onnxruntime/blob/77b455b969db15d911cd6de5009f3a30fb42c531/include/onnxruntime/core/session/onnxruntime_c_api.h#L111 where the macro I use `NO_EXCEPTION` is used to handle several permutations of exception support in compilers/platforms. I believe it is important to use this macro like used in other places in the onnxruntime codebase.

**Comment by RyanUnderhill** [comment]
I used 'noexcept' to be consistent with the rest of the file. NO_EXCEPTION isn't used anywhere in the C++ headers currently.

The C header had to use the macro for C compatibility, but our C++ header requires C++11 or later, so 'noexcept' is safe.

**Comment by ytaous** [comment]
pls rebase your code to pick the fix for lint/python - https://github.com/microsoft/onnxruntime/pull/13869#issuecomment-1412019726

**Comment by fs-eire** [comment]
I triggered a re-run for the web CI pipeline.

**Comment by ytaous** [comment]
> I triggered a re-run for the web CI pipeline.

I think the PR needs Peng's fix from main branch to pass the lint/python format check

**Comment by diablodale** [comment]
I've force pushed the changes requested for `noexcept` and rebase to `main` which includes a lint/python fix.
Several caveats...

Windows TensorRT EP fails to build. Unknow the reason but whatever the cause it is widespread. I removed TensorRT from my local Windows build+test. Examples...

```
C:\repos-nobackup\onnxruntime\build\Windows\Debug\_deps\onnx_tensorrt-src\onnx2trt.hpp(52,18): message : see declaratio
n of 'onnx2trt::IImporterContext::registerLayer' (compiling source file C:\repos-nobackup\onnxruntime\build\Windows\Deb
ug\_deps\onnx_tensorrt-src\builtin_op_importers.cpp) [C:\repos-nobackup\onnxruntime\build\Windows\Debug\_deps\onnx_tens
orrt-build\nvonnxparser_static.vcxproj]
C:\repos-nobackup\onnxruntime\build\Windows\Debug\_deps\onnx_tensorrt-src\builtin_op_importers.cpp(3144,15): error C203
9: 'BoundingBoxFormat': is not a member of 'nvinfer1' [C:\repos-nobackup\onnxruntime\build\Windows\Debug\_deps\onnx_ten
sorrt-build\nvonnxparser_static.vcxproj]
C:\repos-nobackup\TensorRT-8.4.1.5\include\NvInferPluginUtils.h(25): message : see declaration of 'nvinfer1' [C:\repos-
nobackup\onnxruntime\build\Windows\Debug\_deps\onnx_tensorrt-build\nvonnxparser_static.vcxproj]
C:\repos-nobackup\onnxruntime\build\Windows\Debug\_deps\onnx_tensorrt-src\builtin_op_importers.cpp(3144,33): error C206
5: 'BoundingBoxFormat': undeclared identifier [C:\repos-nobackup\onnxruntime\build\Windows\Debug\_deps\onnx_tensorrt-bu
ild\nvonnxparser_static.vcxproj]
```

`main` is broken and does not pass all tests. I can't see the build logs since Azure pipelines requires a login. Therefore, I suspect this PR will also not pass since it was rebased on to `main`. My local Windows build+test (cpu, dml, cuda) builds. And it passes most tests. The final report showing failures is...

```
86% tests passed, 1 tests failed out of 7

Total Test time (real) = 139.89 sec

The following tests FAILED:
          1 - onnxruntime_test_all (Failed)
Errors while running CTest
```

```
1: 2023-02-06 19:56:47.3058430 [W:onnxruntime:Default, graph.cc:108 onnxruntime::MergeShapeInfo] Error merging shape info for output. 'shape_output' source:{2} target:{1,2}. Falling back to lenient merge.
1: Assertion failed: information.tensorTypeNames.size() == information.supportedTensorDataTypes.size(), file C:\repos-nobackup\onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\Operators\OperatorRegistration.cpp, line 782
1/7 Test #1: onnxruntime_test_all ....................***Failed  118.54 sec
```

**Comment by diablodale** [comment]
CI is failing due to download errors `urllib.error.HTTPError: HTTP Error 403: Forbidden` for example
```
Start downloading model zfnet512 from https://s3.amazonaws.com/download.onnx/models/opset_10/zfnet512.tar.gz
Failed to prepare data for model zfnet512: HTTP Error 403: Forbidden
3 times tried
```

**Comment by ytaous** [comment]
pls sync with main branch to pick this fix - https://github.com/microsoft/onnxruntime/pull/14606

**Comment by diablodale** [comment]
`main` continues to be broken. There is no commit in all of February into `main` that has passed CI.
Me merging yet again a broken `main` into this PR will be broken.
This is not sustainable.

**Comment by fs-eire** [comment]
> `main` continues to be broken. There is no commit in all of February into `main` that has passed CI. Me merging yet again a broken `main` into this PR will be broken. This is not sustainable.

I understand the frustration. The CI pipeline should be more stable.

**Comment by diablodale** [comment]
I've merged `main` again. Local test continues to fail. Force-pushing.

```
86% tests passed, 1 tests failed out of 7

Total Test time (real) = 886.44 sec

The following tests FAILED:
          1 - onnxruntime_test_all (Exit code 0xc0000409
)
Errors while running CTest
Output from these tests are in: C:/repos-nobackup/onnxruntime/build/Windows/Debug/Testing/Temporary/LastTest.log
```

In that lasttest.log I see one line with the substring "FAILED"
```
[----------] 7 tests from SkipLayerNormTest
[ RUN      ] SkipLayerNormTest.SkipLayerNormNullInput
[       OK ] SkipLayerNormTest.SkipLayerNormNullInput (277 ms)
[ RUN      ] SkipLayerNormTest.SkipLayerNormBatch1
[       OK ] SkipLayerNormTest.SkipLayerNormBatch1 (302 ms)
[ RUN      ] SkipLayerNormTest.SkipLayerNormBatch1_Float16
[       OK ] SkipLayerNormTest.SkipLayerNormBatch1_Float16 (363 ms)
[ RUN      ] SkipLayerNormTest.SkipLayerNormBatch1_Float16_vec
C:\repos-nobackup\onnxruntime\onnxruntime\test\providers\provider_test_utils.cc(355): error: The difference between f_expected[i] and f_output[i] is 0.015625, which exceeds threshold, where
f_expected[i] evaluates to 11.59375,
f_output[i] evaluates to 11.609375, and
threshold evaluates to 0.004999999888241291.
i:33, provider_type: DmlExecutionProvider
[  FAILED  ] SkipLayerNormTest.SkipLayerNormBatch1_Float16_vec (280 ms)
[ RUN      ] SkipLayerNormTest.SkipLayerNormBatch1_NoBeta
[       OK ] SkipLayerNormTest.SkipLayerNormBatch1_NoBeta (277 ms)
[ RUN      ] SkipLayerNormTest.SkipLayerNormBatch2
[       OK ] SkipLayerNormTest.SkipLayerNormBatch2 (278 ms)
[ RUN      ] SkipLayerNormTest.SkipLayerNormBatch2_Bias
[       OK ] SkipLayerNormTest.SkipLayerNormBatch2_Bias (305 ms)
[----------] 7 tests from SkipLayerNormTest (2085 ms total)
```

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
