### PR TITLE
Fix an issue that the Transpose Optimizer inserts more Transpose nodes

### PR DESCRIPTION
**Pull request by HectorSVC**
Fix an issue that the Transpose Optimizer inserts more Transpose nodes which introduce more cost.

### Description
It happens to a QDQ model which has layout sensitive op GlobalAveragePool.
------------Transpose(nothing to do with channel last or channel first transformation)
-----Q----------Q
-----DQ--------DQ
------- \ ----------/
---------Concat
------------Q
------------DQ
--------- / ----- \\
-----MatMul--Slice

After Transpose Optimizer:
----Q------------
Transpose---Q
----DQ------DQ
----- \ ------ /
------Concat
-------- Q
------- DQ
------ /---- \\
Transpose -- Slice->Q->Transpose->DQ
-MatMul---------

1. It inserts more Transpose nodes around Concat. The existing Transpose node on right side of Concat input gets removed. It inserts a Transpose node on anther Concat input. It inserts Transpose nodes on Concat output and duplicate it at the consumer side. 
It inserts 2 more Transpose nodes comparing to the original model. It could introduce even more if Concat has more inputs without Transpose.
This pattern repeats more than 10 places in the model. It has big impact for the efficiency.
2. It moves Transpose to wrong places which breaks QDQ node group for MatMul.
    It moves Transpose to the place between DQ->MatMul which breaks the QDQ node group for MatMul.

Root cause:
Transpose Optimizer introduces more Transpose nodes to the graph.
1. Transpose Optimizer does it correctly before Layout Transformer applied. It calculate the cost to see whether it is worth to do some optimization for the Transpose nodes around the given node.
2. After Layout Transformer applied, more Transpose (NCHW->NHWC, NHWC->NCHW) nodes introduced. The problem is after Layout Transformer applied. Transpose Optimizer does 2nd round optimization without any cost evaluation.

Fix:
The 2nd round Transpose Optimizer should focus on the inserted new Transpose nodes which relate to channel first/last transformation.
This fix is limit the 2nd round to exclude Transpose which are nothing to do with channel first/last transformation. It unblocks the model we have.
It could still happen if the existing Transpose nodes on Concat input is relate to channel first/last transformation. It still requires further investigation and fix.

### Motivation and Context
1. As an optimizer, it shouldn't introduce more cost (inserting more Transpose nodes) to the model.
2. It should move Transpose node to correct place, shouldn't break existing QDQ node groups

### CODE REVIEW

**Comment by skottmckay** [comment]
Can you add a unit test please so it's easier to step through what the changes mean for transpose optimization and to test out edge cases?

**Comment by HectorSVC** [comment]
> Can you add a unit test please so it's easier to step through what the changes mean for transpose optimization and to test out edge cases?

It's a little bit complicate since it requires 2 rounds of graph partition, Layout transformer and Transpose optimizer. Let me see what I can do.

**Comment by HectorSVC** [comment]
made PR https://github.com/microsoft/onnxruntime/pull/14616

**Comment by skottmckay** [comment]
Whether more or less nodes are inserted is highly dependent on the model from my testing. I've considered a lot of different approaches and have one that might work. 

https://github.com/microsoft/onnxruntime/compare/skottmckay/POC_Abstract_out_Transpose_Optimizer_cost_check

I didn't like how much ORT specific logic was bleeding into transpose_optimizer.cc which is meant to be as generic as possible. A lot of that was around hacking the cost check, so instead of having hacks or disabling the cost check I changed the setup so the cost check implementation was provided by the context (which abstracts out any ORT specific logic), and split out the existing logic into:
- the default cost check
  - the original calculations based on the node inputs/outputs 
  - no ORT specific logic 
- the default ORT cost check
  - includes a couple of special cases that have been added lately that are specific to the ORT kernel implementations
- the post-layout transform cost check
  - takes the reverse approach to this PR and instead forces the push of only the NCHW/NHWC Transpose nodes and falls back to the cost check for all others
    - this is hopefully more refined that disabling the cost check and ignoring the non-NCHW/NHWC Transpose nodes

**Comment by HectorSVC** [comment]
> Whether more or less nodes are inserted is highly dependent on the model from my testing. I've considered a lot of different approaches and have one that might work.
> 
> https://github.com/microsoft/onnxruntime/compare/skottmckay/POC_Abstract_out_Transpose_Optimizer_cost_check
> 
> I didn't like how much ORT specific logic was bleeding into transpose_optimizer.cc which is meant to be as generic as possible. A lot of that was around hacking the cost check, so instead of having hacks or disabling the cost check I changed the setup so the cost check implementation was provided by the context (which abstracts out any ORT specific logic), and split out the existing logic into:
> 
> * the default cost check
>   
>   * the original calculations based on the node inputs/outputs
>   * no ORT specific logic
> * the default ORT cost check
>   
>   * includes a couple of special cases that have been added lately that are specific to the ORT kernel implementations
> * the post-layout transform cost check
>   
>   * takes the reverse approach to this PR and instead forces the push of only the NCHW/NHWC Transpose nodes and falls back to the cost check for all others
>     
>     * this is hopefully more refined that disabling the cost check and ignoring the non-NCHW/NHWC Transpose nodes

That's a good idea which makes it clean and clearer. I'll close my PR and wait for yours. Thanks Scott.

**Pull request closed without merging**
