### PR TITLE
Add sympy=1.1.1 to Linux docker image

### PR DESCRIPTION
**Pull request by snnn**
**Description**:
Add sympy=1.1.1 to Linux docker image
**Motivation and Context**

- Why is this change required? What problem does it solve?
For #5162 
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by KeDengMS** [comment]
Thanks, do you also want to pick up the change in install_dep.sh? It no longer needs to install sympy there.

**Comment by snnn** [comment]
> Thanks, do you also want to pick up the change in install_dep.sh? It no longer needs to install sympy there.

No, thanks. :-) This is file is in a different folder.

**Comment by KeDengMS** [comment]
But would the install_dep.sh script change affect the checksum of generated docker image?

---
In reply to: [692940853](https://github.com/microsoft/onnxruntime/pull/5177#issuecomment-692940853) [](ancestors = 692940853)

**Review by KeDengMS — APPROVED** [review]
:shipit:

**Pull request merged**
