### PR TITLE
Remove suspend handler to support Windows 8.1 in WinML Nuget

### PR DESCRIPTION
**Pull request by ryanlai2**
Suspend handler feature brings in LoadLibraryW which isn't supported in Windows 8.1

Also linking with the cppwinrt in NuGet brings in LoadLibraryW

### CODE REVIEW

**Comment by snnn** [comment]
LoadLibraryW isn't in Windows 8.1?  But why [https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw) says it supports Windows xp?

**Comment by smk2007** [comment]
> LoadLibraryW isn't in Windows 8.1? But why https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw says it supports Windows xp?

LoadLibraryW is in 8.1, but it isnt part of an apiset. So applications built for UWP shouldnt use it.

**Comment by smk2007** [comment]
I would prefer you not remove the functoinality to use the latest cppwinrt functionality.

To remove the call into LoadLibraryW, instead we should implement:
WINRT_IMPL_LoadLibraryW() and have that forward to LoadLibraryExW.

That will short circuit the call to LoadLibraryW which is implemented with /alternatename that maps it to LoadLibraryW

**Comment by snnn** [comment]
Off topic: is it ok to use LoadLibraryExW  and LoadLibraryW in
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/platform/windows/env.cc ?

**Comment by tiagoshibata** [comment]
@snnn : the apiset for 8.1 is at https://github.com/MicrosoftDocs/win32/blob/adcc2e2cf0329f73eb5d5ecafc17c88bc0bfb02f/desktop-src/apiindex/windows-81-api-sets.md , LoadLibraryExW is available

**Comment by tiagoshibata** [comment]
The apiset available in different versions of Windows and the universal apiset don't map directly to the desktop apiset; it's available on Desktop, but not in the apiset DLLs unfortunately.

**Comment by ryanlai2** [comment]
Abandoning in favor of this PR : https://github.com/microsoft/onnxruntime/pull/8065

**Pull request closed without merging**
