### PR TITLE
remove unused function in OpenVINO

### PR DESCRIPTION
**Pull request by jslhcl**
### Description

Remove unused functions in OpenVINO EP

### Motivation and Context

Remove unused functions in OpenVINO EP

### CODE REVIEW

**Comment by jywu-msft** [comment]
@sfatimar can you confirm this is ok?

**Comment by sspintel** [comment]
Hi @jywu-msft 

We'd like to keep these functions around, they might be required at a later time.

**Comment by jywu-msft** [comment]
> Hi @jywu-msft
> 
> We'd like to keep these functions around, they might be required at a later time.

okay. thanks for confirming we shouldn't remove them.

**Comment by jywu-msft** [comment]
closing this PR as these functions shouldn't be removed per Intel.

**Pull request closed without merging**
