### PR TITLE
Add ConvTranspose2D to WebGL backend

### LINKED ISSUE #9257: TypeError: cannot resolve operator 'ConvTranspose' with opsets: ai.onnx v11
**Describe the bug**
I ported a pytorch model over to ONNX. Im able to load the model it in python but when trying to load it via onnxruntime-web (React) v1.9.0 I get the error:

>  TypeError: cannot resolve operator 'ConvTranspose' with opsets: ai.onnx v11

loading as: 

> import * as ort from 'onnxruntime-web';
> import model_path from './latest_net_G.onnx'
> const session = await ort.InferenceSession.create(model_path);

Please assist. Thanks!

### PR DESCRIPTION
**Pull request by 101arrowz**
**Description**: Adds support for the ConvTranspose operator to the WebGL backend. Like Conv, this currently only supports two-dimensional ConvTranspose.

**Motivation and Context**
- I'm trying to get [Wav2Lip](https://github.com/Rudrabha/Wav2Lip) working with GPU acceleration in web browsers, and ConvTranspose is used in various spots so it's needed to run that model.
- Fixes #9257

I cannot guarantee how well this works - I have verified that it works for Wav2Lip but was unable to set up the unit testing infrastructure, so I couldn't write any tests. However, as far as I can tell, all the options work consistently with PyTorch's implementation (within ~0.001% tolerance).

### CODE REVIEW

**Comment by fs-eire** [comment]
Thanks very much @101arrowz for the contribution!

I will take some time to review the change in a few days. Besides, the following is a list of TODO items including updates to tests and docs:

- update suite-test-list.jsonc to include existing onnx test cases: ( [under section "webgl"/"node"](https://github.com/microsoft/onnxruntime/blob/8cd02508c84ddaf62ec0b619fe2f86bbe453c67a/js/web/test/suite-test-list.jsonc#L9) )
  - test_convtranspose
  - test_convtranspose_pad
  - test_convtranspose_pads
  - test_convtranspose_output_shape
  - test_convtranspose_kernel_shape
  - test_convtranspose_dilations

  If your current code does not support some of the test cases so far, it is fine. We can just add the passing tests and leave a comment for the failing cases

- [optional] add your custom op test for ConvTranspose
  - take a look at any file under [js/web/test/data/ops](https://github.com/microsoft/onnxruntime/tree/8cd02508c84ddaf62ec0b619fe2f86bbe453c67a/js/web/test/data/ops)
  - create a new file convtranspose.jsonc with a few test cases
  - add convtranspose.jsonc into suite-test-list.jsonc [under section "webgl"/"ops"](https://github.com/microsoft/onnxruntime/blob/8cd02508c84ddaf62ec0b619fe2f86bbe453c67a/js/web/test/suite-test-list.jsonc#L232) 

- update docs
  - in js/web/, run `npm run build:doc`. This should generate updates to file /js/web/docs/operators.md

**Comment by 101arrowz** [comment]
I ran the doc update script and added the test cases to the JSON config. As I mentioned I was unable to get the test harness set up in my environment, so maybe you could approve this PR with CI so I can find any issues?

**Comment by fs-eire** [comment]
Please fix the linter errors. you can run `npm run lint` under <ORT_ROOT>/js/ locally.

**Comment by 101arrowz** [comment]
Fixed lint and hopefully fixed the output shape bug.

**Comment by 101arrowz** [comment]
Turns out `test_convtranspose_output_shape` is broken in opset v8. The test case was fixed by [this PR](https://github.com/onnx/onnx/pull/1437) but we'd have to rewrite Git history to fix it now.

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
