### PR TITLE
Improve speed in combining per-channel data

### PR DESCRIPTION
**Pull request by duanshengliu**
### Description

Improve speed in combining `per-channel` data for using a single `np.concatenate` instead of multiple `np.concatenates` within a for loop.

### Motivation and Context

Fix the issue https://github.com/microsoft/onnxruntime/issues/21562

### CODE REVIEW

**Comment by duanshengliu** [comment]
@yihonglyu @xadupre @adrianlizarraga @yufenglee        PTAL

**Review by yufenglee — APPROVED** [review]

**Comment by yufenglee** [comment]
Hi @duanshengliu, you need to sign the license/cla to move forward.

**Comment by duanshengliu** [comment]
> Hi @duanshengliu, you need to sign the license/cla to move forward.

Hi @yufenglee, I have updated the signature and the `license/cla check` has passed now. Could you please run CI again? Thanks.

**Comment by duanshengliu** [comment]
> Hi @duanshengliu, you need to sign the license/cla to move forward.

Hi @yufenglee, I have updated the signature and the license/cla check has passed now. Could you please run CI again? Thanks.

**Comment by yufenglee** [comment]
could you please sync to the main branch? Looks like Windows GPU CUDA CI Pipeline is not in your branch.

**Comment by duanshengliu** [comment]
Hi @yufenglee, could you please review it again?  By the way, please take a look at https://github.com/microsoft/onnxruntime/pull/21347#issuecomment-2258661085

**Review by yufenglee — APPROVED** [review]

**Pull request merged**
