### PR TITLE
Bump up onnx

### PR DESCRIPTION
**Pull request by raymondxyang**
* Bump up onnx
* Update the onnx related dev-notes

### CODE REVIEW

**Comment by raymondxyang** [comment]
@askhade Let's talk offline for this issue.

**Comment by raymondxyang** [comment]
That fix should be separated right?

**Comment by pranavsharma** [comment]
> That fix should be separated right?

We'll have to update the onnx commit again after Ashwini's fix is in. Better to do it once.

**Comment by raymondxyang** [comment]
Synced with @askhade she will directly bump the onnx to include the latest fix. I'll close this PR first.

**Pull request closed without merging**
