### PR TITLE
pin ort-ext to 81e7799c69044c745239202085eb0a98f102937b

### PR DESCRIPTION
**Pull request by guschmue**
pin onnxruntime-extension to 81e7799c69044c745239202085eb0a98f102937b in preparation to in enable extension in wasm build.

### CODE REVIEW

**Review by wenbingl — DISMISSED** [review]

**Comment by wenbingl** [comment]
I saw the sentecepiece flag here is still OFF
https://github.com/microsoft/onnxruntime/blob/8943d623a4f3e85b629761dd560b2a7971d7b885/cmake/external/extensions.cmake#L12

**Comment by guschmue** [comment]
Yes, going to turn this on for wasm in the next PR once this one is merged.

**Review by snnn — CHANGES_REQUESTED** [review]
See: https://github.com/microsoft/onnxruntime/tree/main/cgmanifests#how-to-generate

Please regenerate the json file.

**Comment by pranavsharma** [comment]
Side note: Why should ORT depend on extensions? Seems weird.

**Comment by guschmue** [comment]
I'm a little confused. This PR only updates onnxruntime-extensions to a newer version. 
I do not think anybody depends on it unless you build with --use-extensions. 
It is not in https://github.com/microsoft/onnxruntime/blob/main/cmake/deps.txt.
Do I need to update deps.txt in this PR?

Next PR would be to build ort-web (same for mobile I think) with onnxruntime-extensions (we need some tokenizers) and it needs to be statically linked. So yes, there would be a dependency to onnxruntime-extensions and I don't see a way of avoiding that.

**Comment by snnn** [comment]
> I'm a little confused. This PR only updates onnxruntime-extensions to a newer version. I do not think anybody depends on it unless you build with --use-extensions. It is not in deps.txt or cgmanifest.json. Do I need to update it in this PR?
> 
> Next PR would be to build ort-web (same for mobile I think) with onnxruntime-extensions (we need some tokenizers) and it needs to be statically linked. So yes, there would be a dependency to onnxruntime-extensions and I don't see a way of avoiding that.

I will write an email to you to explain it.

**Comment by guschmue** [comment]
Updated cgmanifest.json per instruction. Resulted in a bunch of changes to cgmanifest.json, none related to this PR as far I can tell.

**Review by pranavsharma — APPROVED** [review]

**Review by snnn — APPROVED** [review]

**Comment by guschmue** [comment]
sorry, cgmanifest changed - needed to resolve some conficts

**Review by snnn — APPROVED** [review]

**Review by pranavsharma — APPROVED** [review]

**Pull request merged**
