### PR TITLE
Fix a few more signed/unsigned warnings in test code.

### PR DESCRIPTION
**Pull request by skottmckay**
**Description**: 
Fix some comparisons that result in a warning on x86.

**Motivation and Context**
Fix warnings.

### CODE REVIEW

**Review by tracysh — APPROVED** [review]
Fixes the build break I was seeing on x86.

**Review by snnn — APPROVED** [review]

**Comment by snnn** [comment]
I wonder why these warnings were not caught by our CI? Who disabled these warning, python, WinML, or something else?

**Comment by skottmckay** [comment]
> I wonder why these warnings were not caught by our CI? Who disabled these warnings, python, WinML, or something else?

Not sure. They cause the Zip Packaging Pipeline build to fail. Couldn't see anything explicitly disabling them in our cmake setup that was relevant to this build.

**Comment by skottmckay** [comment]
> > I wonder why these warnings were not caught by our CI? Who disabled these warnings, python, WinML, or something else?
> 
> Not sure. They cause the Zip Packaging Pipeline build to fail. Couldn't see anything explicitly disabling them in our cmake setup that was relevant to this build.

Something is disabling warnings as errors in that build. Warning level is 4 and 4389 isn't disabled, so the warning is generated, but doesn't break the build.
`/W4 /WX-`

**Pull request merged**
