### PR TITLE
Regain performance by caching initializer names in ORTModule

### PR DESCRIPTION
**Pull request by baijumeswani**
Every call to ```self._graph_info.initializer_names``` or ```self._graph_info.initializer_names_to_train``` resulted in a ```O(n)``` lookup time. Although these two were ```Python sets```, their lookup time was linear. This was happening most likely because on every reference, pybind made a fresh copy of the ```C++ unordered_set``` to a ```Python set```.

While we research ways to optimize this, this pull request fixes the perf regression that #7631 introduced by caching the set of initalizer names on the frontend.

This pull request also adds more unit tests for testing the support for unused model parameters.

### CODE REVIEW

**Review by thiagocrepaldi — APPROVED** [review]
LGTM
I am assuming you ran Ravi's script which benchmarks all scenarios

**Comment by baijumeswani** [comment]
> LGTM
> I am assuming you ran Ravi's script which benchmarks all scenarios

I ran Ravi's script for one of the models and it looked good. I am assuming this will generalize to other models as well.

**Review by mrry — APPROVED** [review]

**Comment by mrry** [comment]
Thanks for figuring out the problem Baiju! I would not have expected that property access to be causing a set construction every time :).

We should definitely merge this as-is, but one possibility for fixing the TODO is to investigate the trick @codemzs used to avoid copying STL structures (vectors in this case) across the Python/C++ boundary:

https://github.com/microsoft/onnxruntime/blob/7bb3f243ff7de673e042ad3f4860539731a3ecb8/orttraining/orttraining/python/orttraining_pybind_state.cc#L19

**Comment by ytaous** [comment]
do u know what's perf gain by % with Ravi's?

---
In reply to: [840811250](https://github.com/microsoft/onnxruntime/pull/7685#issuecomment-840811250) [](http://example.com/codeflow?ancestors=840811250,840811250)

**Comment by baijumeswani** [comment]
@ytaous no additional gain. Just back to where we were before pull request #7631 caused the regression.

**Pull request merged**
