### PR TITLE
[js/webgpu] Choose best wasm backend

### PR DESCRIPTION
**Pull request by gyagp**
WebGPU Android in Chrome is still behind flag "--enable-unsafe-apis". Even without this flag, navigator.gpu is available, but navigator.gpu.requestAdapter() would fail. This PR checks the availability of WebGPU and choose the best wasm backend.

### CODE REVIEW

**Comment by gyagp** [comment]
@qjia7 @guschmue @satyajandhyala @fs-eire Please review this change, thanks!

**Comment by gyagp** [comment]
Sorry, I just found even if we select the correct backend, WebGPU will get initialized later on unconditionally. I need more time to investigate this and please do not review now.

**Comment by qjia7** [comment]
> Sorry, I just found even if we select the correct backend, WebGPU will get initialized later on unconditionally. I need more time to investigate this and please do not review now.

Please check whether it's related with https://github.com/microsoft/onnxruntime/blob/main/js/web/lib/wasm/wasm-core-impl.ts#L55-L61C4. Maybe we should check whether the current backend is `webgpu` instead of checking `BUILD_DEFS.DISABLE_WEBGPU`.

**Comment by fs-eire** [comment]
close this as an alternative change (#18715) is merged

**Pull request closed without merging**
