### PR TITLE
Helper for compiling EP to generate deterministic unique ids for use in MetaDef names

### PR DESCRIPTION
**Pull request by skottmckay**
**Description**: 
Create a helper for generating unique ids that can be used by an EP that creates compiled nodes and needs ids to be deterministic for a model when used in multiple sessions.

Added to IExecutionProvider as this can potentially be used by all compiling EPs and is more robust than a simplistic counter (although EP implementer is free to choose either approach).

**Motivation and Context**
Multiple instances of time being spent investigating issues, especially involving graphs with subgraphs, involving MetaDef name uniqueness. Providing a default way to generate a good id will avoid that in future.

### CODE REVIEW

**Review by stevenlix — COMMENTED** [review]
@skottmckay I tried the changes in TRT EP and it works well. Just thinking, is it possible to hash more data, such as model's meta data (including opset version etc), ORT version and possibly GPU info into the model_hash? In this way TRT engine cache  can also use model_hash to differentiate different version of engines because the engine is model version and SW/HW platform dependent.

**Comment by jywu-msft** [comment]
> @skottmckay I tried the changes in TRT EP and it works well. Just thinking, is it possible to hash more data, such as model's meta data (including opset version etc), ORT version and possibly GPU info into the model_hash? In this way TRT engine cache can also use model_hash to differentiate different version of engines because the engine is model version and SW/HW platform dependent.

it should only hash components that are EP agnostic.  ORT version/model metadata may be good candidates.  but not GPU info/hardware specific info. (EP's can implement their own specific hashing, using the EP-independent component as a base)

**Comment by skottmckay** [comment]
> @skottmckay Scott McKay FTE I tried the changes in TRT EP and it works well. Just thinking, is it possible to hash more data, such as model's meta data (including opset version etc), ORT version and possibly GPU info into the model_hash? In this way TRT engine cache can also use model_hash to differentiate different version of engines because the engine is model version and SW/HW platform dependent.

Is there a use case where multiple versions of ORT would be running and sharing a TRT cache?

The EP is free to include more things than just a model hash and unique id when creating the MetaData.name value. If you have a caching scenario where the cache is shared across multiple ORT instances with different versions, or things like the GPU info is relevant, the EP would know best what extra info it needs to include to handle that when creating MetaData.name.

**Comment by skottmckay** [comment]
> @skottmckay Scott McKay FTE I tried the changes in TRT EP and it works well. Just thinking, is it possible to hash more data, such as model's meta data (including opset version etc), ORT version and possibly GPU info into the model_hash? In this way TRT engine cache can also use model_hash to differentiate different version of engines because the engine is model version and SW/HW platform dependent.

Is there a use case where multiple versions of ORT would be running and sharing a TRT cache?

The EP is free to include more things than just a model hash and unique id when creating the MetaData.name value. If you have a caching scenario where the cache is shared across multiple ORT instances with different versions, or things like the GPU info is relevant, the EP would know best what extra info it needs to include to handle that when creating MetaData.name.

**Comment by stevenlix** [comment]
In some scenario users will want to load cached TRT engine to save engine creation time. The cached engine could be copied to different environment by user where the engine is not compatible due to SW/HW changes. In this case if engine name includes those SW/HW info, TRT EP will know environment changed by the name and new engine will be created. SW changes include ORT version, TRT version, opset version etc and HW changes include GPU type etc.
I agree this is more like EP specific and would be better to add in the EP.

**Review by stevenlix — APPROVED** [review]

**Pull request merged**
