### PR TITLE
Remove ref struct return usage

### PR DESCRIPTION
**Pull request by tommcdon**
### Description
Removes ref struct return usage on netstandard 2.0 builds.

### Motivation and Context
Unblocks .NET native compilation

### CODE REVIEW

**Comment by tianleiwu** [comment]
@tommcdon 

Windows GPU CI Pipeline failed.
Checking D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\NativeMethods.shared.cs
Line 313 is missing UnmanagedFunctionPointer attribute:
	#if NETSTANDARD2_0
	public delegate IntPtr DOrtGetApi(UInt32 version);
Line 315 is missing UnmanagedFunctionPointer attribute:
	#else
	public delegate ref OrtApi DOrtGetApi(UInt32 version);
Checking D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\Training\NativeTrainingMethods.shared.cs
Line 58 is missing UnmanagedFunctionPointer attribute:
	#if NETSTANDARD2_0
	public delegate IntPtr DOrtGetApi(UInt32 version);
Line 60 is missing UnmanagedFunctionPointer attribute:
	#else
	public delegate ref OrtApi DOrtGetApi(UInt32 version);
Traceback (most recent call last):
  File "tools\ValidateNativeDelegateAttributes.py", line 62, in <module>
    main()
  File "tools\ValidateNativeDelegateAttributes.py", line 58, in main
    raise ValueError(f"{errors} errors were found. Please check output for specifics.")
ValueError: 4 errors were found. Please check output for specifics.

**Comment by tommcdon** [comment]
> @tommcdon
> 
> Windows GPU CI Pipeline failed. Checking D:\a_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\NativeMethods.shared.cs Line 313 is missing UnmanagedFunctionPointer attribute: #if NETSTANDARD2_0 public delegate IntPtr DOrtGetApi(UInt32 version); Line 315 is missing UnmanagedFunctionPointer attribute: #else public delegate ref OrtApi DOrtGetApi(UInt32 version); Checking D:\a_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\Training\NativeTrainingMethods.shared.cs Line 58 is missing UnmanagedFunctionPointer attribute: #if NETSTANDARD2_0 public delegate IntPtr DOrtGetApi(UInt32 version); Line 60 is missing UnmanagedFunctionPointer attribute: #else public delegate ref OrtApi DOrtGetApi(UInt32 version); Traceback (most recent call last): File "tools\ValidateNativeDelegateAttributes.py", line 62, in main() File "tools\ValidateNativeDelegateAttributes.py", line 58, in main raise ValueError(f"{errors} errors were found. Please check output for specifics.") ValueError: 4 errors were found. Please check output for specifics.

It seems this was a bug in the validation script.  I worked around it by duplicating the attribute definition inside of the ifdef's

**Comment by tommcdon** [comment]
@tianleiwu would you mind kicking off validation against the latest changes?

**Comment by tommcdon** [comment]
I've resolved the merge conflict.

**Review by tianleiwu — APPROVED** [review]

**Pull request merged**
