### PR TITLE
Support 'Bilinear' mode for 2D inputs in Resize and Upsample kernels 

### LINKED ISSUE #1641: Resize operator fails with 2D tensors
**Describe the bug**
The Resize operator fails with the following simple 2D test case.

    {
      "op_type": "Resize",
      "mode": "linear",
      "X": [[1, 1],
            [1, 1]],
      "scales": [2, 2],
      "Y": [[1, 1, 1, 1],
            [1, 1, 1, 1],
            [1, 1, 1, 1],
            [1, 1, 1, 1]],
      "T": "float32"
    },

Apparently one has to wrap the 2D tensor inside a 4D tensor with dummy 1's to get it to work, even though the two cases are equivalent o_O. (The error message is also confusing because it says it only handles 4D when it doesn't actually handle quadrilinear interpolation.)

**Urgency**
Vibranium preferred.

**System information**
- OS Platform and Distribution: Windows 10 Vibranium
- ONNX Runtime installed from: source 
- ONNX Runtime version: engine/lotus (v0.1.4-709-gbf6f19c6)
- Python version: NA
- Visual Studio version (if applicable): Visual Studio 2017
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: AMD Radeon, 32GB

**To Reproduce**
Run the attached model.

    HRESULT=0x80004005 message=Exception during initialization: S:\WindowsAI\engine\lotus\onnxruntime\core/providers/cpu/tensor/upsample.h:75
     onnxruntime::UpsampleBase::ScalesValidation scales.size() == 4 was false. Upsample: linear mode upsample only support bilinear with 4 dimension.

**Expected behavior**
I understand ORT's Resize only handling 2D for now (rather than full 3D or 4D which DML supports), but the validation code should just treat the squeezed dimensions all the same: [1,1,m,n], [1,m,n], [m,n], [m,n,1,1]. *assuming the corresponding scales would yield in nop's.

**Additional context**
Found while testing WindowsAI DML GPU vs CPU paths.

    ir_version: 3
    producer_name: "OnnxConformanceTest"
    graph {
      node {
        input: "X"
        input: "scales"
        output: "Y"
        op_type: "Resize"
        attribute {
          name: "mode"
          s: "linear"
          type: STRING
        }
        domain: ""
      }
      initializer {
        dims: 2
        dims: 2
        data_type: FLOAT
        name: "X"
        raw_data: "\000\000\200?\000\000\000@\000\000@@\000\000\200@"
      }
      initializer {
        dims: 2
        data_type: FLOAT
        float_data: 2
        float_data: 2
        name: "scales"
      }
      input {
        name: "X"
        type {
          tensor_type {
            elem_type: FLOAT
            shape {
              dim {
                dim_value: 2
              }
              dim {
                dim_value: 2
              }
            }
          }
        }
      }
      input {
        name: "scales"
        type {
          tensor_type {
            elem_type: FLOAT
            shape {
              dim {
                dim_value: 2
              }
            }
          }
        }
      }
      output {
        name: "Y"
        type {
          tensor_type {
            elem_type: FLOAT
            shape {
              dim {
                dim_value: 4
              }
              dim {
                dim_value: 4
              }
            }
          }
        }
      }
    }
    opset_import {
      version: 7
    }
    opset_import {
      version: 10
    }

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: 

1) 'Bilinear' mode needs to support 2D input tensors in Upsample/Resize. Currently we support bilinear mode for 4D tensors (NCHW) where the outermost 2 scales are 1.0 (no ops) essentially boiling it down to a 'bilinear' case from a 'quadrilinear' case. 

2) Fix error messages along the way

3) Extend support to the CUDA Resize and Upsample kernels too

**Motivation and Context**
Resolve #1641

### CODE REVIEW

**Comment by hariharans29** [comment]
CC: @fdwr

**Comment by hariharans29** [comment]
Cc: @scottmckay @snnn for review comments

**Comment by snnn** [comment]
Will it also solve #1719?

**Comment by hariharans29** [comment]
> Will it also solve #1719?

No it has nothing to do with #1719. It resolves #1641. #1719 seems strange as it is a vanilla use-case of Resize malfunctioning. Need to investigate #1719 further.

**Comment by hariharans29** [comment]
CC: @HectorSVC / @duli2012 for the CUDA kernels. - It should be very straight-forward to review as they are just adaptation of the exisiting 4-D "bilinear" case adpated for the 2-D "bilinear" case.

**Pull request merged**
