### PR TITLE
add Dockerfile.rocm4.1.pytorch

### PR DESCRIPTION
**Pull request by jeffdaily**
Adds Dockerfile.rocm4.1.pytorch.  Largely a copy of the previous Dockerfile.rocm4.0.pytorch, but adds `pip3 install --upgrade setuptools` to fix an issue when installing the python module `seqeval` because it requires `setuptools>=45`.

### CODE REVIEW

**Review by jessebenson — APPROVED** [review]

**Comment by weixingzhang** [comment]
Thanks for contribution! Just triggered CI pipeline.

**Pull request merged**
