### PR TITLE
Upgrade emsdk from 3.1.59 to 3.1.62

### PR DESCRIPTION
**Pull request by satyajandhyala**
### Description
Upgrade EM SDK to 3.1.63.

### Motivation and Context
The changes are required to clear wasm64 errors.

### CODE REVIEW

**Review by snnn — APPROVED** [review]

**Comment by fs-eire** [comment]
Thank you for the update but please hold it a little bit as we observed a feature regression in 3.1.63.

See https://github.com/emscripten-core/emscripten/pull/22165#issuecomment-2240768044

**Comment by satyajandhyala** [comment]
> Thank you for the update but please hold it a little bit as we observed a feature regression in 3.1.63.
> 
> See [emscripten-core/emscripten#22165 (comment)](https://github.com/emscripten-core/emscripten/pull/22165#issuecomment-2240768044)

Applied suggested fix.

**Review by snnn — APPROVED** [review]

**Comment by satyajandhyala** [comment]
Upgrade to 3.1.62 instead of 3.1.63

**Comment by fs-eire** [comment]
also file `.gitmodules` in root need to be updated.

**Review by fs-eire — DISMISSED** [review]

**Review by snnn — DISMISSED** [review]

**Review by guschmue — APPROVED** [review]

**Review by pranavsharma — APPROVED** [review]

**Review by fs-eire — APPROVED** [review]

**Review by baijumeswani — APPROVED** [review]

**Pull request merged**
