### PR TITLE
undo hipify of __half to rocblas_half

### PR DESCRIPTION
**Pull request by TedThemistokleous**
### Description

Originally from @jeffdaily . Need this change to hipify script otherwise onnxruntime mainline won't properly build with our upcoming 6.0

### Motivation and Context

Fixes build issue seen with newer ROCm releases

### CODE REVIEW

**Comment by TedThemistokleous** [comment]
ping @PeixuanZuo @cloudhan @ytaous

**Review by cloudhan — APPROVED** [review]

**Pull request merged**
