### PR TITLE
[PowerPC] Type casting the output operand of vec_xst.

### PR DESCRIPTION
**Pull request by BODAPATIMAHESH**
This fix resolves the build error “error: invalid parameter combination for AltiVec intrinsic ‘__builtin_vec_vsx_st’” which is coming up with the commit  dea425e7c140a7216727421c434a1c5.

### CODE REVIEW

**Comment by BODAPATIMAHESH** [comment]
@yufenglee  requesting review

**Comment by BODAPATIMAHESH** [comment]
could you review this @yufenglee

**Comment by BODAPATIMAHESH** [comment]
@snnn  requesting review

**Review by yufenglee — APPROVED** [review]

**Pull request merged**
