### PR TITLE
[js/webgpu] Add FusedConv clip test case

### PR DESCRIPTION
**Pull request by axinging**
Bug: https://github.com/microsoft/onnxruntime/issues/18899

### CODE REVIEW

**Comment by axinging** [comment]
@qjia7 @xhcao @hujiajie @gyagp PTAL

**Review by qjia7 — APPROVED** [review]
LGTM, thanks!

@fs-eire @guschmue @satyajandhyala Please take a look, thanks.

**Review by guschmue — APPROVED** [review]

**Pull request merged**
