### PR TITLE
[OpenVINO-EP] Upgrade version info to 2020.3 in docs

### PR DESCRIPTION
**Pull request by smkarlap**
**Description**: Upgraded recommended OpenVINO version to 2020.3 in text and links in documentation.

**Motivation and Context**
- Document the latest supported version of OpenVINO toolkit.

### CODE REVIEW

**Comment by jywu-msft** [comment]
can you merge latest master? that should address the training CI failure.

**Comment by smkarlap** [comment]
> can you merge latest master? that should address the training CI failure.

Done

**Comment by jywu-msft** [comment]
sorry looks like there's a merge conflict on BUILD.md

**Comment by smkarlap** [comment]
> looks like there's a merge conflict on BUILD.md due to the other OpenVINO VAD-M PR after that was merged.

Resolved now

**Pull request merged**
