### PR TITLE
Fixes to get stable diffusion benchmark running

### PR DESCRIPTION
**Pull request by TedThemistokleous**
### Description

Added changes to MIGraphX EP to suppoert stable diffusion

1. Added parameterized input dimensions to not trigger a precompile to set input parameters in the EP 
2.  Removed input checking for Resize operator in EP as MIGraphX already performs these checks
3. Add support to benchmark script to use the MIGraphX execution provider
4. Add support for an odd valued batch size (3) that was seen on other benchmarks we were performing comparison on.

### Motivation and Context

These changes are required to get stable diffusion mdoels to run on MIGraphX through the EP. Without these changes we see the following incorrect behavior.

1. Resize operators are pushed onto the CPU EP instead of MIGraphX, causing a significant slowdown during runs
2. Precompile operations incorrectly parse input_ids parameter for our text model, with a 1, which breaks during MIGraphX Compile of onnx. This in turn throws an error and stops any setup before inference.
3. Selecting the correct EP in the benchmark script which was previously missing the MIGraphX option
5. Suppressed an error we keep seeing with pthread_set_affinity - this is a quality of life change when using the MIGraphX EP 

This was testing with the benchmark.py script using stable diffusion v2 located in

onnxruntime/onnxruntime/python/tools/transformers/models/stable_diffusion/

### CODE REVIEW

**Comment by TedThemistokleous** [comment]
@Cloudhan @PeixuanZuo  this is for stable diffusion. Running last set of benchmarks on our end before I'll put these changes through the ringer. 

Please let me know if you have any questions for this changeset

**Comment by TedThemistokleous** [comment]
Ready to go. Updated changes and retested this today. Please let me know if you require any additional changes

**Review by cloudhan — CHANGES_REQUESTED** [review]
What is the purpose of this change? If this does not break (aka, not a fix as in PR title), then could you please seperate it into a new PR and justify the change there?

**Comment by TedThemistokleous** [comment]
> What is the purpose of this change? If this does not break (aka, not a fix as in PR title), then could you please seperate it into a new PR and justify the change there?

This is a fix. Previous EP wasn't able to even process stable diffusion correctly using the benchmark.py script. Without these changes to the EP MIGraphX fails to allocate and compile nodes correctly before running an incorrect exectuion.

**Comment by cloudhan** [comment]
cc @yuslepukhin FYI for the affinity change.

**Comment by cloudhan** [comment]
@TedThemistokleous Please reformat to proceed.

Also, FYI, we have some benchmark perf number for MI100 and MI250x here https://github.com/microsoft/onnxruntime/blob/e139ae238bbce6772be76fcb7ea13fb402adc483/onnxruntime/python/tools/transformers/models/stable_diffusion/README.md#results-of-mi250x-1-gcd-ubuntu-2004 for sd 1.5

The sd 2.0 is roughly 1.8s in similiar setting, but the torch 2.0 ROCm produces black images, so we haven't include the result.

It should be trivially reproducible by using https://github.com/cloudhan/onnxruntime-rocm-stable-diffusion

**Comment by TedThemistokleous** [comment]
> @TedThemistokleous Please reformat to proceed.
> 
> Also, FYI, we have some benchmark perf number for MI100 and MI250x here https://github.com/microsoft/onnxruntime/blob/e139ae238bbce6772be76fcb7ea13fb402adc483/onnxruntime/python/tools/transformers/models/stable_diffusion/README.md#results-of-mi250x-1-gcd-ubuntu-2004 for sd 1.5
> 
> The sd 2.0 is roughly 1.8s in similiar setting, but the torch 2.0 ROCm produces black images, so we haven't include the result.
> 
> It should be trivially reproducible by using https://github.com/cloudhan/onnxruntime-rocm-stable-diffusion

Can you make this an issue and tag me in it as well as @groenenboomj ? 

I can send  you the images generated with this update for the MIGraphX run. 
Is this previous result going to hold up this PR?

**Review by cloudhan — APPROVED** [review]

**Pull request merged**
