### PR TITLE
Update abseil to a release tag and register neural_speed

### PR DESCRIPTION
**Pull request by snnn**
### Description
Update abseil to a release tag and register neural_speed to CG.

### Motivation and Context
Now we are using a non-relesed version of abseil. Using a tag is better.

### CODE REVIEW

**Comment by pranavsharma** [comment]
Where is neural speed used? Can you write it in the PR desc?

**Comment by edgchen1** [comment]
> Where is neural speed used? Can you write it in the PR desc?

It's a dependency added by this PR:
https://github.com/microsoft/onnxruntime/pull/19016

The library is used in the x64 MatMulNBits implementation.

**Comment by snnn** [comment]
Neural speed is an open source library that was introduced in PR #19016 . The PR was made by Intel, and there was some left job for compliance stuffs. I told them they can merged the PR first and I would take care of the remaining compliance things. That's what this PR is doing.  
So, in fact this PR doesn't introduce new dependencies to ORT. The PR is to finish some registration work.

**Comment by snnn** [comment]
Later on I will also create a PR to update https://github.com/microsoft/onnxruntime/blob/main/ThirdPartyNotices.txt .

**Comment by pranavsharma** [comment]
> Later on I will also create a PR to update https://github.com/microsoft/onnxruntime/blob/main/ThirdPartyNotices.txt .

Any reason we need a separate PR for ThirdPartyNotices? It'll be nice to have a single PR that shows all the files that need to be updated to incorporate a new 3P dep. This way it can be used as a reference PR to add new deps.

**Comment by snnn** [comment]
The procedure is: first we should register any new dependency to CG. Then CG will use the information to go through some internal review. During the process I will also need to provide some information. Then after the review is done, we update the ThirdPartyNotices.txt.  You may think the internal process is to ensure the text that is adding to ThirdPartyNotices.txt is accurate.

**Review by pranavsharma — APPROVED** [review]

**Review by jchen351 — APPROVED** [review]

**Comment by snnn** [comment]
This PR has been cherry-picked into the `rel-1.17.0` branch in PR #19243. Removing the `release:1.17.0` label.

**Pull request merged**
