### PR TITLE
Lochi/refactor yolov3 quantization

### PR DESCRIPTION
**Pull request by chilo-ms**
**Description**: 
Refactor the code.
Move implementations of Yolov3's data reader, preprocessing and evaluation to model specific example under E2E_example_model folder.
**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by jywu-msft** [comment]
Thanks! Hope you can add some more documentation for this example in a future PR.

**Review by jywu-msft — DISMISSED** [review]

**Comment by yufenglee** [comment]
I moved the example to https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization/E2E_example_model/object_detection/trt/yolov3

**Comment by chilo-ms** [comment]
> I moved the example to https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization/E2E_example_model/object_detection/trt/yolov3. Please refactor the code based on that.


I've moved the code to the folder as well.

**Comment by chilo-ms** [comment]
> Thanks! Hope you can add some more documentation for this example in a future PR.

I will update the document along with entropy algorithm on future PR.

**Review by yufenglee — APPROVED** [review]

**Pull request merged**
