### PR TITLE
Use forward_inference to speed up convolutions with MKLDNN

### PR DESCRIPTION
**Pull request by mika-fischer**

### CODE REVIEW

**Comment by snnn** [comment]
Do you know any model can be benefited from this change?

**Comment by mika-fischer** [comment]
> Is there any model can be benefited from this change? Do you have any perf number on that model?

Yes, there were some improvements with our models. I'll post some numbers tomorrow.

**Comment by snnn** [comment]
> > Is there any model can be benefited from this change? Do you have any perf number on that model?
> 
> Yes, there were some improvements with our models. I'll post some numbers tomorrow.

Is it observable in ONNX model zoo models?

**Comment by mika-fischer** [comment]
I can't seem to demonstrate a consistent improvement. In any case it does not make a large difference.

But do note that in all other cases `forward_inference` is already used in onnxruntime and the mkl-dnn documentations says this (mkldnn_forward == mkldnn_forward_training):
```
    /** Forward data propagation (training mode). In this mode primitives
     * perform computations necessary for subsequent backward propagation. */
    mkldnn_forward_training = 64,
    /** Forward data propagation (inference mode). In this mode primitives
     * perform only computations that are necessary for inference and omit
     * computations that are necessary only for backward propagation. */
    mkldnn_forward_inference = 96,
```

So it seems this change is appropriate in any case.

I just stumbled on this, because I'm trying to figure out why mxnet is faster than onnxruntime even thought both use MKLDNN and MKLML and this was one of the differences I noticed.

**Comment by jywu-msft** [comment]
thanks for the contribution. yes, it makes sense in this case to just add this change since it should be forward_inference instead of forward.

re: mkldnn vs mxnet mkldnn perf, we already know that mkldnn implementation in onnxruntime is currently sub-optimal, due to excessive memory reorders between desired mkldnn memory format and onnxruntime format . you can confirm if this is the case by setting MKLDNN_VERBOSE env variable to 1 to enable mkldnn tracing and run your test comparison again.

we are working on improving the performance in this area and hoping to make updates in the near future.

> I can't seem to demonstrate a consistent improvement. In any case it does not make a large difference.
> But do note that in all other cases forward_inference is already used in onnxruntime and the mkl-dnn documentations says this (mkldnn_forward == mkldnn_forward_training):
>     /** Forward data propagation (training mode). In this mode primitives
>      * perform computations necessary for subsequent backward propagation. */
>     mkldnn_forward_training = 64,
>     /** Forward data propagation (inference mode). In this mode primitives
>      * perform only computations that are necessary for inference and omit
>      * computations that are necessary only for backward propagation. */
>     mkldnn_forward_inference = 96,
> 
> So it seems this change is appropriate in any case.
> I just stumbled on this, because I'm trying to figure out why mxnet is faster than onnxruntime even thought both use MKLDNN and MKLML and this was one of the differences I noticed.

**Pull request merged**
