### PR TITLE
Re-enable PEP8 check in Win CI build 

### PR DESCRIPTION
**Pull request by skottmckay**
**Description**: 
PEP8 check via flake8 was enabled in the static analysis build that is currently disabled so checks are not running. Add to Win-CPU build.
Fix build.py to be compliant again.
Add prefix to flake8 output so it's (hopefully) easier to identify the errors in build output.

**Motivation and Context**
Re-enable checks.

### CODE REVIEW

**Comment by jywu-msft** [comment]
would it actually make more sense to enable this on Linux CI build rather than Windows CPU CI?
Windows CPU CI has so many sub-task builds that if you have a flake8 error, you just wasted a bunch of build slots. 
Can we run flake8 before building C++ to fail faster?

**Comment by skottmckay** [comment]
> would it actually make more sense to enable this on Linux CI build rather than Windows CPU CI?
> Windows CPU CI has so many sub-task builds that if you have a flake8 error, you just wasted a bunch of build slots.
> Can we run flake8 before building C++ to fail faster?

It runs right at the start of the build, so will fail that build fast. Problem is the Windows CI build has a lot of builds that run in parallel, and one failing doesn't stop the others. Not sure if it could be setup so a failure terminates any other running build. 

I looked at the Linux CI but there did seem to be any equivalent to the Windows build where a bunch of pip packages were installed. Is there a good place to add the pip install of flake8 in the Linux CI setup?

**Comment by skottmckay** [comment]
> > would it actually make more sense to enable this on Linux CI build rather than Windows CPU CI?
> > Windows CPU CI has so many sub-task builds that if you have a flake8 error, you just wasted a bunch of build slots.
> > Can we run flake8 before building C++ to fail faster?
> 
> It runs right at the start of the build, so will fail that build fast. Problem is the Windows CI build has a lot of builds that run in parallel, and one failing doesn't stop the others. Not sure if it could be setup so a failure terminates any other running build.
> 
> I looked at the Linux CI but there did seem to be any equivalent to the Windows build where a bunch of pip packages were installed. Is there a good place to add the pip install of flake8 in the Linux CI setup?

Maybe the better thing would be to install it for all the sub-task builds in the Windows CPU CI so they all fail fast. Whether it's on a Linux or Windows build doesn't matter too much does it? If it fails you can't checkin.

**Comment by snnn** [comment]
> I looked at the Linux CI but there did seem to be any equivalent to the Windows build where a bunch of pip packages were installed. Is there a good place to add the pip install of flake8 in the Linux CI setup?

Try this:
https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/scripts/requirements.txt

**Comment by jywu-msft** [comment]
> > > would it actually make more sense to enable this on Linux CI build rather than Windows CPU CI?
> > > Windows CPU CI has so many sub-task builds that if you have a flake8 error, you just wasted a bunch of build slots.
> > > Can we run flake8 before building C++ to fail faster?
> > 
> > 
> > It runs right at the start of the build, so will fail that build fast. Problem is the Windows CI build has a lot of builds that run in parallel, and one failing doesn't stop the others. Not sure if it could be setup so a failure terminates any other running build.
> > I looked at the Linux CI but there did seem to be any equivalent to the Windows build where a bunch of pip packages were installed. Is there a good place to add the pip install of flake8 in the Linux CI setup?
> 
> Maybe the better thing would be to install it for all the sub-task builds in the Windows CPU CI so they all fail fast. Whether it's on a Linux or Windows build doesn't matter too much does it? If it fails you can't checkin.

Ok. If it can fail fast I'm fine with it. I just didn't want it to occupy a lot of agent slots and waste build cycles in the failure path. I've observed that for past failing builds.

**Comment by skottmckay** [comment]
> > I looked at the Linux CI but there did seem to be any equivalent to the Windows build where a bunch of pip packages were installed. Is there a good place to add the pip install of flake8 in the Linux CI setup?
> 
> Try this:
> https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/scripts/requirements.txt

Not sure that's installed early enough. Needs to be available when the makefiles are created. I could add an install of python3-flake8 to the apt-get packages if we really want Linux builds to run this test as well.

**Comment by yuslepukhin** [comment]
This is now blocking since flake is enabled in the master but the fix is not. Let's either check this in or revert the flake introduction.

**Pull request merged**
