### PR TITLE
Delay load dxcore in winml model tests

### PR DESCRIPTION
**Pull request by ryanlai2**
This fixes the Windows CI build.

### CODE REVIEW

**Review by snnn — APPROVED** [review]

**Comment by snnn** [comment]
Thank you!!!!!

**Comment by snnn** [comment]
One more question, About OS version, there are three things:

1. The OS running the build and test. We are using RS5
2. The Windows SDK version (controlled by CMAKE_SYSTEM_VERSION env variable),  could be Windows 10 RS5, 19H1, or something else. Even newer than the first one
3. The Windows version we target to. (controlled by WINVER). We set WINVER to 0x0601 to support Windows 7 and newer.

If the whole system works as expected as the above, then we shouldn't hit the DLL missing error. Windows 7 doesn't have the DLL, onnxruntime should support Windows 7.  What I missed?

**Comment by ryanlai2** [comment]
> 1. The OS running the build and test. We are using RS5

DxCore was only available starting from 20H1 builds. This delayload should protect DxCore from loading while DXGI is present in System32. As long as DXGI is available on the system, these model tests should be able to work without loading DxCore DLL. 

> 2. The Windows SDK version (controlled by CMAKE_SYSTEM_VERSION env variable),  could be Windows 10 RS5, 19H1, or something else. Even newer than the first one

Should be fine to use any one of these SDKs and even newer ones. We grab cppwinrt from nuget package now.

> 3. The Windows version we target to. (controlled by WINVER). We set WINVER to 0x0601 to support Windows 7 and newer.
> 
> If the whole system works as expected as the above, then we shouldn't hit the DLL missing error. Windows 7 doesn't have the DLL, onnxruntime should support Windows 7. What I missed?

WinML works only up to Windows 8.1 and not Windows 7 if I understand correctly. @smk2007  can you help explain this for me?

**Comment by smk2007** [comment]
Why not just always delay-load dxcore in winml and require that the SDK reference be Vibranium+?

**Pull request merged**
