### PR TITLE
Add protobuf version constraint

### PR DESCRIPTION
**Pull request by snnn**
To fix a build error:

/home/xxxxxxxxxxxxx/onnxruntime/build/Linux/Debug/tensorboard/compat/proto/cost_graph.pb.cc:17:8: error: ‘PROTOBUF_INTERNAL_EXPORT_tensorboard_2fcompat_2fproto_2ftensor_5fshape_2eproto’ does not name a type
   17 | extern PROTOBUF_INTERNAL_EXPORT_tensorboard_2fcompat_2fproto_2ftensor_5fshape_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_TensorShapeProto_tensorboard_2fcompat_2fproto_2ftensor_5fshape_2eproto;

### CODE REVIEW

**Comment by shaahji** [comment]
There are other places like requirements-*.txt files where a dependency on protobf is called out. Wouldn't it install the latest version conflicting with the version called out here?

**Review by shaahji — APPROVED** [review]
This will fix the issue, but I am not sure if this is the best solution. None of the other listed dependencies in the file call out specific version. Protobuf stands out in the crowd but similar problems can happen with flatbuffers and some of the other libraries as well that auto-generate code. In lack of a common place to force specific version dependency we may not have any other choice but to enforce it here.

**Review by shaahji — APPROVED** [review]

**Comment by snnn** [comment]
Oh, I probably missed a point. The cmake file I'm modifying is part of ORT source code, and it would not be used for building ONNX. So, anything we have here doesn't have any impact on ONNX.  For example, if ORT decided to pickup protobuf 3.6 from Ubuntu operating system instead of 3.18.3 which is listed in cmake/deps.txt, it will not have any impact on ONNX python wheel.

**Review by jchen351 — APPROVED** [review]

**Comment by sl1pkn07** [comment]
oks. thanks. opened a new issue

greetings

**Pull request merged**
