### PR TITLE
static link to mkldnn

### PR DESCRIPTION
**Pull request by snnn**
To get rid of the rpath issue

### CODE REVIEW

**Comment by pranavsharma** [comment]
How do we ensure that these changes work for python packages as well?

**Comment by snnn** [comment]
> How do we ensure that these changes work for python packages as well?

I tested it locally.

**Comment by pranavsharma** [comment]
> > How do we ensure that these changes work for python packages as well?
> 
> I tested it locally.

Mac?

**Comment by snnn** [comment]
> 
> Mac?

Previously, it doesn't work. After this fix, it's unknown.

**Comment by jywu-msft** [comment]
for my understanding, can you provide more details. what is the rpath issue?
is it similar to what we had to do for python shared lib: https://github.com/Microsoft/onnxruntime/blob/master/cmake/onnxruntime_python.cmake#L87 
?

**Comment by snnn** [comment]
> for my understanding, can you provide more details. what is the rpath issue?
> is it similar to what we had to do for python shared lib: https://github.com/Microsoft/onnxruntime/blob/master/cmake/onnxruntime_python.cmake#L87
> ?

Yes.  It's kind of similar.
If you run ldd on the final binaries, sometimes it points to 
```
mklml/src/project_mklml/lib/libmklml_intel.so
```
instead of "libmklml_intel.so" directly.

Therefore, even we added the current folder into LD_LIBRARY_PATH, it will still try to find  "mklml/src/project_mklml/lib/libmklml_intel.so" instead of "libmklml_intel.so" in current folder.

We could try to find the reason why it has such a long name, but I would think a simpler fix is changing it to static link.

**Comment by jywu-msft** [comment]
just to confirm the issue you are reporting.
this is only an issue on Linux and only when building with both --use_mkldnn and --use_mklml  (if we leave off the latter, there is no issue)

I am unable to reproduce the issue of ldd on final binaries pointing to the wrong libmklml_intel.so location. can you run objdump -x on the binary and see if some rpath is being added to header?
when I built from master, I don't see any rpath being set for libmkldnn.so or libmklml_intel.so

Thus, when I properly set LD_LIBRARY_PATH to the mkldnn libs, I don't see any issues.

btw, I built your dev branch snnn/dnn , and I don't think mklml is being statically linked due to the size of the final binaries. i do see mkldnn in there.
also, I ran onnxruntime_perf_test on resnet50 and I do notice that it is noticeably slower than master.
not sure why exactly.

**Comment by snnn** [comment]
> just to confirm the issue you are reporting.
> this is only an issue on Linux and only when building with both --use_mkldnn and --use_mklml (if we leave off the latter, there is no issue)
> 
> I am unable to reproduce the issue of ldd on final binaries pointing to the wrong libmklml_intel.so location. can you run objdump -x on the binary and see if some rpath is being added to header?
> when I built from master, I don't see any rpath being set for libmkldnn.so or libmklml_intel.so
> 
> Thus, when I properly set LD_LIBRARY_PATH to the mkldnn libs, I don't see any issues.
> 
> btw, I built your dev branch snnn/dnn , and I don't think mklml is being statically linked due to the size of the final binaries. i do see mkldnn in there.
> also, I ran onnxruntime_perf_test on resnet50 and I do notice that it is noticeably slower than master.
> not sure why exactly.

Hi @jywu-msft 

The main change in this PR is adding "-DMKLDNN_LIBRARY_TYPE=STATIC" to mkldnn's cmake args. So, mkldnn will be built as a static library, therefore it will not link to any other libraries(including mklml). Then it's onnxruntime's  responsibility to find mklml and link to it. And it still dynamically links to mklml.

Let me close this PR right now, because it needs more investigations.  

Thanks for your finds and suggestions.

**Pull request closed without merging**
