### PR TITLE
Revert NeuralSpeed code for x64 MatMulNBits

### PR DESCRIPTION
**Pull request by luoyu-intel**
### Description

Revert PR#19016 https://github.com/microsoft/onnxruntime/pull/19016
Revert PR#17669 https://github.com/microsoft/onnxruntime/pull/17669

### Motivation and Context
 
The code will be fully tested and reviewed. After that, my colleagues will work on a new PR.

### CODE REVIEW

**Review by snnn — APPROVED** [review]

**Comment by tianleiwu** [comment]
@pranavsharma, @faxu, this PR need onnxruntime-admin approval before merging. Please take a look.

**Review by pranavsharma — APPROVED** [review]

**Comment by leso-kn** [comment]
Hi! Sorry to bump this, but is it possible that this could still affect aarch64 on musl?

Alpine Linux aarch64 build job log: https://gitlab.alpinelinux.org/leso-kn/aports/-/jobs/2031484

**Pull request merged**
