### PR TITLE
[js/web] add sessionOptions.freeDimensionOverrides

### LINKED ISSUE #16707: [Web] SessionOptions::AddFreeDimensionOverride missing
### Describe the issue

SessionOptions in ORTW is missing the ability to set free dimensions. This matters for performance, as models like Stable Diffusion can benefit from all the constant folding and shape inference. Without it, execution providers like WebNN can end up falling back to the CPU provider when operator shapes cannot be computed opportunistically.
https://github.com/microsoft/onnxruntime/blob/b7fd5af48bcad76466b67dcd95dfc78a0bb469b2/js/common/lib/inference-session.ts#L46-L162

### To reproduce

Try to load any model with free dimensions in ORTW, and there is no way to pass the named dimensions. e.g. Presume a `namedFreeDimensionOverrides` attribute existed:

            const sessionOptions =
            {
                executionProviders: [{name: "webnn", deviceType: 'gpu', powerPreference: 'high-performance' }],
                namedFreeDimensionOverrides: {"batch_size": 2, "height": 64, "width": 64 ...},
            };

            options.logSeverityLevel = 0;
            options.logVerbosityLevel = 3;

            const sess = await ort.InferenceSession.create(modelPath, sessionOptions);

### Urgency

Before mid-August ideally (not necessarily in any release, just in master).

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

36b121d8c2badf02eada00d59ab1ade8f761e917

### Execution Provider

WebNN EP

### PR DESCRIPTION
**Pull request by fs-eire**
### Description
Allows to specify fixed size for dynamic input of a model. resolves #16707

Pending test

### CODE REVIEW

**Comment by Honry** [comment]
@fs-eire, many thanks for your effort, I am really exciting to see this feature be ready for Web soon.

I applied your PR and tested on both WebNN EP and CPU EP, unfortunately I didn't see dynamic dimensions been overridden. i.e. this function [`FreeDimensionOverrideTransformer::ApplyImp`](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/optimizer/free_dim_override_transformer.cc#L35) hadn't been called. Looks like it's connection to WebNN EP and CPU EP or other EPs are missing in the underlying.

**Comment by fs-eire** [comment]
updated to use C API `AddFreeDimensionOverrideByName` instead of `AddFreeDimensionOverride`

**Comment by Honry** [comment]
> updated to use C API AddFreeDimensionOverrideByName instead of AddFreeDimensionOverride. please try again!

@fs-eire, :+1: , awesome, it works now!

**Review by guschmue — APPROVED** [review]

**Comment by guschmue** [comment]
test this with webgpu with mobilenet and t5-decoder: batch_size=1.
The option itself works but I did not see gains, depends on model and parameter you make static (for t5 it actually became slower).

**Pull request merged**
