### PR TITLE
Remove CUDNN path from CI build scripts

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

Nvidia's official document says when installing CUDNN, the files should be copied to CUDA's installation dir. Therefore, onnxruntime_CUDA_HOME and onnxruntime_CUDNN_HOME should be the same. As this is the most common case, we should not ask users to specify onnxruntime_CUDNN_HOME every time. 

Also, clean up our build scripts to remove cudnn paths.  One important change is: it also removes CUDA 11.1 paths from our build pipelines. Though all the code were built with CUDA 11.4, we run the binaries with CUDA 11.1. Otherwise some tests would fail. But this is very confusing.  I would rather disable the tests. 

**Motivation and Context**
- Why is this change required? What problem does it solve?

I want to upgrade the CUDA version to 11.6. This PR is a preparation for the work. 

- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by mszhanyi** [comment]
From my understanding, copying cudnn files to CUDA's installation dir can avoid the potential incompatibility issues.
The user should copy the right cudnn files to individual CUDA's installation dir.
If there're multiple cuda toolkits installed in one machine or the user upgrade the cuda, the risk would increase.

**Comment by snnn** [comment]
If there are multiple cuda toolkits installed in one machine, their installation folder would be different. 

For example, this is how we install CUDA to our CI build machines during image building:
```powershell
Write-Output "Installing CUDA 11.1"
choco install cuda --version=11.1.1 -my
Write-Output "Installing CUDA 11.4"
choco install cuda --version=11.4.0.47111 -my
Write-Output "Installing CUDA 11.6"
choco install cuda --version=11.6.2.51165 -my

Write-Output "Copy CUDNN files to CUDA 11.1 dir "
Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\bin\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin" -Recurse

Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\include\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -Recurse

Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\lib\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib\x64" -Recurse
Write-Output "Copy CUDNN files to CUDA 11.4 dir "
Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\bin\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin" -Recurse

Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\include\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -Recurse

Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\lib\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\lib\x64" -Recurse

Write-Output "Copy CUDNN files to CUDA 11.6 dir "
Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\bin\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin" -Recurse

Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\include\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -Recurse

Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\lib\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\lib\x64" -Recurse
```

CUDA 11.1 is under C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
CUDA 11.4 is under C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
CUDA 11.6 is under C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6

**Comment by mszhanyi** [comment]
> If there are multiple cuda toolkits installed in one machine, their installation folder would be different.
> 
> For example, this is how we install CUDA to our CI build machines during image building:
> 
> ```powershell
> Write-Output "Installing CUDA 11.1"
> choco install cuda --version=11.1.1 -my
> Write-Output "Installing CUDA 11.4"
> choco install cuda --version=11.4.0.47111 -my
> Write-Output "Installing CUDA 11.6"
> choco install cuda --version=11.6.2.51165 -my
> 
> Write-Output "Copy CUDNN files to CUDA 11.1 dir "
> Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\bin\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin" -Recurse
> 
> Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\include\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -Recurse
> 
> Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\lib\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\lib\x64" -Recurse
> Write-Output "Copy CUDNN files to CUDA 11.4 dir "
> Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\bin\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin" -Recurse
> 
> Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\include\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -Recurse
> 
> Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\lib\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\lib\x64" -Recurse
> 
> Write-Output "Copy CUDNN files to CUDA 11.6 dir "
> Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\bin\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin" -Recurse
> 
> Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\include\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -Recurse
> 
> Copy-Item -Path "C:\local\cudnn-windows-x86_64-8.5.0.96\lib\*" -Destination "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\lib\x64" -Recurse
> ```
> 
> CUDA 11.1 is under C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1 CUDA 11.4 is under C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4 CUDA 11.6 is under C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6

Does this PR support cudnn files NOT in the dir of CUDA_HOME?
I'm just a little confused why we don't remove the  onnxruntime_cudnn_home since it's same as CUDA_HOME.

**Comment by snnn** [comment]
> Does this PR support cudnn files NOT in the dir of CUDA_HOME?

Yes. It would still work. On Linux we don't have the assumption that CUDA_HOME is the same as CUDNN_HOME.

**Comment by snnn** [comment]
I just find CUDNN's installation doc was changed. 
Before CUDNN 8.4, Nvidia suggests:

1. Navigate to your <installpath> directory containing cuDNN.
2. Unzip the cuDNN package.
cudnn-windows-x86_64-*-archive.zip
3. Copy the following files into the CUDA toolkit directory.
   - Copy <installpath>\cuda\bin\cudnn*.dll to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\vx.x\bin.
   - Copy <installpath>\cuda\include\cudnn*.h to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\vx.x\include.
   - Copy <installpath>\cuda\lib\x64\cudnn*.lib to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\vx.x\lib\x64

Now they suggest creating a separated installation directory for CUDNN. 

See: https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn-850/install-guide/index.html#install-windows

**Comment by mszhanyi** [comment]
> I just find CUDNN's installation doc was changed. Before CUDNN 8.4, Nvidia suggests:
> 
> 1. Navigate to your  directory containing cuDNN.
> 2. Unzip the cuDNN package.
>    cudnn-windows-x86_64-*-archive.zip
> 3. Copy the following files into the CUDA toolkit directory.
>    
>    * Copy \cuda\bin\cudnn*.dll to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\vx.x\bin.
>    * Copy \cuda\include\cudnn*.h to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\vx.x\include.
>    * Copy \cuda\lib\x64\cudnn*.lib to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\vx.x\lib\x64
> 
> Now they suggest creating a separated installation directory for CUDNN.
> 
> See: https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn-850/install-guide/index.html#install-windows

I think the reason is the cudnn packages is changed.
Before 8.4,  each cuda has indivisual cuDNN package.
after 8.4, all cuda 11.x share one cuDNN package.
https://developer.nvidia.com/rdp/cudnn-archive

**Review by jchen351 — APPROVED** [review]

**Comment by snnn** [comment]
As we don't need to have multiple CUDNN versions on our Windows CI build machines, I suggest keeping the old behavior: copy cudnn files to cuda folder to make things simpler. When we need to have multiple CUDNN versions, we can add the build flags back to the yaml files.

**Comment by snnn** [comment]
Prior CUDNN 8.4, Nvidia's official document says when installing CUDNN, the files should be copied to CUDA's installation dir. Therefore, onnxruntime_CUDA_HOME and onnxruntime_CUDNN_HOME should be the same. As this is the most common case, we should not ask users to specify onnxruntime_CUDNN_HOME every time.

Also, this change cleaned up our build scripts to remove cudnn path settings because when we install CUDNN to the machines we have copied the DLLs to CUDA folder. 

Also, it removes CUDA 11.1 paths from the pipelines. Though all our code were built with CUDA 11.4, we run the binaries with CUDA 11.1. Otherwise some tests would fail. But this is very confusing. I think it's better to disable the tests than having these things in inconsistence.

**Pull request merged**
