### PR TITLE
TRT detailed log and strong typed networks

### PR DESCRIPTION
**Pull request by gedoensmax**
### Description
 
@chilo-ms to me it seems sensible to forward the detailed log argument to the TRT logger itself. 
Also when no precision downcast is wanted this will ensure to actually stick to ONNX precision when used with TRT 9+.

### CODE REVIEW

**Comment by jywu-msft** [comment]
you must not be based off main? can you rebase?

**Comment by gedoensmax** [comment]
Yes sure, sorry didn't notice that I was on a different branch.

**Comment by chilo-ms** [comment]
Could you merge main to trigger the CI again?
The builds were too old to be re-run.

**Review by gedoensmax — COMMENTED** [review]
Branch is rebased

**Review by chilo-ms — APPROVED** [review]

**Pull request merged**
