### PR TITLE
Add length checks to fusion_transpose.py

### PR DESCRIPTION
**Pull request by kazssym**
### Description

This change adds list length checks to node's inputs in fusion_transpose.py. It bypasses the optimization if not applicable.

### Motivation and Context

Those nodes have fewer inputs in an older opset and cause runtime exceptions.

### CODE REVIEW

**Comment by tianleiwu** [comment]
@kazssym, one required pipeline of python format failed. Please run `lintrunner -a` according to https://github.com/microsoft/onnxruntime/blob/main/docs/Coding_Conventions_and_Standards.md#linting

**Comment by kazssym** [comment]
I just have synced to main.

**Review by tianleiwu — APPROVED** [review]

**Comment by tianleiwu** [comment]
Looks good to me. Unsqueeze-13 has two inputs, older opset (<13) has only one input.

**Pull request merged**
