### PR TITLE
OVEP 1.21.0 Development Updates

### PR DESCRIPTION
**Pull request by ankitm3k**
### Description
OVEP development changes for ORT 1.21 Release
 
 
### Motivation and Context
- Has Critical Bug Fixes
- Improved Performance optimizations for both memory & inference latency (https://github.com/intel/onnxruntime/pull/513)
- Enabled Model Compilation using NPUW (https://github.com/intel/onnxruntime/pull/508)
- Fixed support for EPContext embed mode 0 for lower memory utilization
- Updated NuGet package name as `Intel.ML.OnnxRuntime.OpenVino`
- Fixed QDQ Stripping logic on NPU

### CODE REVIEW

**Comment by ankitm3k** [comment]
@microsoft-github-policy-service agree company="Intel"

**Review by HectorSVC — APPROVED** [review]

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
