### PR TITLE
[WebNN EP] Remove some constraints for CPU backend

### PR DESCRIPTION
**Pull request by Honry**
Following constraints have been supported by WebNN TFLite backend:
- Concat: supports up to 4 inputs
- Matmul: supports broadcasting
- Resize: supports nearest mode
- Split: supports up to 4 outputs

### CODE REVIEW

**Comment by Honry** [comment]
@guschmue, @fs-eire, @fdwr, PTAL, thanks!

**Review by guschmue — APPROVED** [review]

**Review by fdwr — COMMENTED** [review]
👍 Nice to see these workarounds removed.

**Pull request merged**
