### PR TITLE
Remove training from web ci pipeline

### PR DESCRIPTION
**Pull request by snnn**
### Description
Remove training from web ci pipeline

### CODE REVIEW

**Comment by fs-eire** [comment]
May need also make changes to ort web build script.

**Comment by snnn** [comment]
> May need also make changes to ort web build script.

Will do it separately.

**Review by guschmue — APPROVED** [review]

**Review by jchen351 — APPROVED** [review]
Createa follow up work item to replace 'codecvt_utf8<wchar_t>' ?

**Comment by snnn** [comment]
AB#49053.

**Pull request merged**
