### PR TITLE
[VitisAI] remove wrong error msg, required by Microsoft

### PR DESCRIPTION
**Pull request by BoarQing**
### Description

Remove legacy code and wrong message.

### Motivation and Context

This is required by Microsoft to remove unwanted error message. This is required for 8.15 release.

### CODE REVIEW

**Comment by BoarQing** [comment]
@jywu-msft

**Comment by BoarQing** [comment]
@jywu-msft Can we get this merged when you have time?

**Comment by BoarQing** [comment]
@jywu-msft

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
