### PR TITLE
Cherry pick build pipeline changes from master

### PR DESCRIPTION
**Pull request by jingyanwangms**
**Description**: Cherry picked #3975, #3767 and #4017
Disabled 3 tests because they only fail in 1p

**Motivation and Context**
Add build gate to 1p branch.

### CODE REVIEW

**Comment by edgchen1** [comment]
You may also want #4017. It fixes a workaround introduced by #3767.

**Comment by kit1980** [comment]
I'm verifying with a model I run.

**Comment by jingyanwangms** [comment]
> You may also want #4017. It fixes a workaround introduced by #3767.

Okay I've included #4017 .

**Comment by jingyanwangms** [comment]
Abandon the PR since we're going to do 1p release from master

**Pull request closed without merging**
