### PR TITLE
Enable type reduction for Range, ReverseSequence, ScatterND, Split, and Unique CPU kernels.

### PR DESCRIPTION
**Pull request by edgchen1**
**Description**
Enable type reduction for Range, ReverseSequence, ScatterND, Split, and Unique CPU kernels.

**Motivation and Context**
Enable binary size reduction by excluding implementations for specific types.

### CODE REVIEW

**Comment by skottmckay** [comment]
>     ORT_THROW("Split operator does not support ", input.DataType(), " yet");

nit: we could convert this to being based on the size of the data type (with the exception of std::string) at some point given we're just copying data

---
Refers to: onnxruntime/core/providers/cpu/tensor/split.cc:110 in 9bac678. [](commit_id = 9bac67882e1a025fcfbd49370b71a11ef0c512a7, deletion_comment = False)

**Comment by skottmckay** [comment]
>   else

nit: this could probably also be based on the size of the data types, but no need to yet as there's no overlap. could maybe add a comment as a hint if support for additional types is added

---
Refers to: onnxruntime/core/providers/cpu/tensor/unique.cc:104 in 9bac678. [](commit_id = 9bac67882e1a025fcfbd49370b71a11ef0c512a7, deletion_comment = False)

**Review by skottmckay — APPROVED** [review]
:shipit:

**Comment by edgchen1** [comment]
>     ORT_THROW("Split operator does not support ", input.DataType(), " yet");

good point. added a comment for now.

---
In reply to: [794904729](https://github.com/microsoft/onnxruntime/pull/6963#issuecomment-794904729) [](ancestors = 794904729)

---
Refers to: onnxruntime/core/providers/cpu/tensor/split.cc:110 in 9bac678. [](commit_id = 9bac67882e1a025fcfbd49370b71a11ef0c512a7, deletion_comment = False)

**Review by skottmckay — APPROVED** [review]
:shipit:

**Pull request merged**
