### PR TITLE
Add a comment to onnxruntime_cxx_inline.h

### LINKED ISSUE #1385: Redefinition due to missing guard in onnxruntime_cxx_inline.h
**Describe the bug**

https://github.com/microsoft/onnxruntime/blob/bfda9ca1c1e396411850e335f6c22ab1ffb90fe7/include/onnxruntime/core/session/onnxruntime_cxx_inline.h

This file doesn't work.
There're redefinition everywhere.
image

Where's the `#pragma once`?

**Urgency**

ASAP.
We need to carefully craft our code now to ensure it is included only once.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- GCC/Compiler version (if compiling from source): gcc-8

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 
To resolve #1385

**Motivation and Context**
- Why is this change required? What problem does it solve?
It's not required. But more comment is always better.

- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by pranavsharma** [comment]
May be we should've renamed this file to onnxruntime_cxx_internal.h .

**Comment by xkszltl** [comment]
@snnn Maybe we should add a macro bomb, which is only disarmed by cxx_api.h

For example:
```
#ifndef ORT_CXX_API_INCLUDED
#error "No no no...."
#endif 
```

**Comment by snnn** [comment]
Hi @ryanunderhill, what do you think?

**Comment by RyanUnderhill** [comment]
I like Pranav's idea of renaming the file, if people still try to add the file we can always add the macro bomb to make it even more clear why it fails.

**Pull request merged**
