### PR TITLE
Update protobuf version to 3.18.3 in tools/ci_build/github/linux/docker/scripts/requirements.txt.

### PR DESCRIPTION
**Pull request by edgchen1**
### Description

Update protobuf version to 3.18.3 in tools/ci_build/github/linux/docker/scripts/requirements.txt.

### Motivation and Context

Address component governance alert.

### CODE REVIEW

**Comment by snnn** [comment]
It crashes on Mac. The Mac CI build will fail. And we don't know why. A newer version might work.

**Comment by edgchen1** [comment]
> It crashes on Mac. The Mac CI build will fail. And we don't know why. A newer version might work.

Looks like the Mac CI build is ok. Perhaps it is a different version which causes problems - this is simply upgrading the patch version.

**Comment by snnn** [comment]
Nice!

**Comment by snnn** [comment]
Also, you may see the discussions in  #13078

CC:  @[jcwchen](https://github.com/jcwchen)

**Pull request merged**
