### PR TITLE
[Java] Fixes the Windows build

### PR DESCRIPTION
**Pull request by Craigacp**
**Description**: The gradle build changes stopped the onnxruntime.dll from being included in the jar files, as on Windows the dll is TARGET_FILE_NAME not TARGET_LINKER_FILE_NAME. This patch restores the correct behaviour. It's actually just renaming the file, as currently on Windows the jar contains a file called onnxruntime.lib but the file's contents are those of onnxruntime.dll.

**Motivation and Context**
- Why is this change required? What problem does it solve? Currently the Windows builds do not have the correct filename for the native library.

### CODE REVIEW

**Comment by Craigacp** [comment]
I also have a small patch which makes onnxruntime build correctly with OpenMP on macOS if libomp is installed via Homebrew. I couldn't get it to compile otherwise using the system compilers. I previously had been using gcc 8 to compile it on mac which worked fine with OpenMP, but that produced a binary which caused SIGABRT on Java 8, 9 and 10, though the identical binary worked just fine on Java 11, 12, 13 and 14.

Is there any interest in the patch? I'm not clear how the current mac CI pipeline is building with OpenMP turned on.

**Comment by pranavsharma** [comment]
> I also have a small patch for the cmake scripts which makes onnxruntime build correctly with OpenMP on macOS if libomp is installed via Homebrew. I couldn't get it to compile otherwise using the system compilers. I previously had been using gcc 8 to compile it on mac which worked fine with OpenMP, but that produced a binary which caused SIGABRT on Java 8, 9 and 10, though the identical binary worked just fine on Java 11, 12, 13 and 14.
> 
> Is there any interest in the [patch](https://gist.github.com/Craigacp/66be36737e21df87eee4c0197e76862a)? I'm not clear how the current mac CI pipeline is building with OpenMP turned on.

We compile using AppleClang 10.0.0.10001145. Feel free to send a PR. Thanks!

**Comment by yuslepukhin** [comment]
I have a couple of comments with regards to tests:
1) I can see that when tests run it is not the resultring .jar that is being loaded but the .class files that were being produced by the build. Can we make the test use the build product?
2) In my local build on windows I am getting this error (CI builds pass) but I was wondering what would be a reason:
InferenceTest > testModelSerialization() FAILED
    java.lang.UnsatisfiedLinkError: no onnxruntime in java.library.path:.....

**Comment by yuslepukhin** [comment]
Happy to report that applying this fix my local windows build unit tests started running. However, 1) still applies.

---
In reply to: [623596994](https://github.com/microsoft/onnxruntime/pull/3659#issuecomment-623596994) [](ancestors = 623596994)

**Comment by Craigacp** [comment]
The standalone junit runner we had originally used the prebuilt jar files. I'm not sure if you can make gradle use the jar for the tests, both it and maven usually make the jars after the tests are run. We could revert back to the junit runner but it's fragile to configure (and it needs to download the junit runner and other jars manually rather than having gradle pull them in).

**Comment by yuslepukhin** [comment]
I was tempted to suggest the junit but there appears to be no simple ways. Here is the outcome of my experience, an open question and some needed doc changes.
1) In order to run the build and  the tests on Windows, the gradle binaries as is (run java via  script) do not work. This is bc ctest does not handle .bat files on windows properly. To make it work we have two ways:
  a) as it is addressed currently, installs Chocolatey installer and then install gradle choco package. The package installs a gradle.exe shim that works OK with ctest. If we choose this way, we need to reflect it in the docs.
  b) modify cmake files so it can handle gradle.bat and does not require Chocolatey and its package. I tested it locally and it works.
2) For windows, we MUST disable gradle daemon. set GRADLE_OPTS=-Dorg.gradle.daemon=false. This may also be a part of cmake command. Otherwise, MSBuild hangs waiting for java daemon to complete which never happens. This needs to be reflected in the docs.
3) This fix is a MUSt

---
In reply to: [623616493](https://github.com/microsoft/onnxruntime/pull/3659#issuecomment-623616493) [](ancestors = 623616493)

**Comment by snnn** [comment]
> 2. For windows, we MUST disable gradle daemon. set GRADLE_OPTS=-Dorg.gradle.daemon=false. This may also be a part of cmake command. Otherwise, MSBuild hangs waiting for java daemon to complete which never happens. This needs to be reflected in the docs.
> 3. This fix is a MUST
> 
> In reply to: [623616493](https://github.com/microsoft/onnxruntime/pull/3659#issuecomment-623616493) [](ancestors = 623616493)

See: https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/windows/setup_env.bat

We have done it for the CI.

**Comment by yuslepukhin** [comment]
One more thing. With regards to packaging. NuGet packages usually contain binaries for all supported platforms. I assume we can create a maven package that does the same?
I guess, after each of the platform builds we would need to copy/arrange platform binaries in a way that Java loader loads the correct native libraries.

---
In reply to: [623623167](https://github.com/microsoft/onnxruntime/pull/3659#issuecomment-623623167) [](ancestors = 623623167,623616493)

**Comment by yuslepukhin** [comment]
Yes, I suggest we force merge this change. I just tested it locally.

---
In reply to: [623626651](https://github.com/microsoft/onnxruntime/pull/3659#issuecomment-623626651) [](ancestors = 623626651)

**Comment by pranavsharma** [comment]
> Yes, I suggest we force merge this change. I just tested it locally.
> 
> In reply to: [623626651](https://github.com/microsoft/onnxruntime/pull/3659#issuecomment-623626651) [](ancestors = 623626651)

Since we're having some issues in having github recognize the CI status of external PRs, why don't we create a PR ourselves for this particular fix only and merge it? This way we don't have to force merge. To give appropriate credit, we should mention Adam in the PR and in the commit comment. @Craigacp is that ok? We're working on resolving the CI issues to avoid doing the same for your other PRs.

If it's easy enough to eliminate the dependency on chocolatey, let's do that.

**Comment by Craigacp** [comment]
That's fine by me. I think we'd already discussed making a jar with all the binaries in for CPU, and one for GPU. The CPU version I already use internally, it's about 9MB with Windows 10, OL7 and macOS binaries which doesn't seem too bad. To create it just requires rejaring one of the platforms so it contains the other two binaries, it's straightforward.

**Comment by yuslepukhin** [comment]
See [https://github.com/microsoft/onnxruntime/pull/3811](https://github.com/microsoft/onnxruntime/pull/3811)

---
In reply to: [623679702](https://github.com/microsoft/onnxruntime/pull/3659#issuecomment-623679702) [](ancestors = 623679702)

**Comment by Craigacp** [comment]
Fixed by #3811

**Pull request closed without merging**
