### PR TITLE
fix a segment fault bug in onnxruntime

### PR DESCRIPTION
**Pull request by fuhengwu2021**
### Description
To fix issue: https://github.com/microsoft/onnxruntime/issues/14392

### Motivation and Context
To fix https://github.com/microsoft/onnxruntime/issues/14392

### CODE REVIEW

**Comment by fuhengwu2021** [comment]
@microsoft-github-policy-service agree [company="Oracle"]

**Comment by fuhengwu2021** [comment]
@microsoft-github-policy-service agree company="Oracle"

**Comment by jywu-msft** [comment]
@chenfucn, @yufenglee FYI

**Comment by yufenglee** [comment]
This won't happen in real case as dicussed in https://github.com/microsoft/onnxruntime/issues/14392.

**Pull request closed without merging**
