### PR TITLE
[js/webgpu] Optimize grouped conv

### PR DESCRIPTION
**Pull request by qjia7**
### Description

#21618

This PR optimizes grouped conv by 1) more sequential memory access in gpu 2) reusing input's data to reduce global memory access times.

See `Conv|GroupedConv` op in [Wav2Vec2](https://huggingface.co/facebook/wav2vec2-base-960h) becomes 92 ms from 1058 ms on iGPUs with 32 EU.

For the whole model on my iGPUs with 32 EU,
wav2vec2 model becomes 982ms from 1942 ms.
squeezebert-uncased model becomes 71.86ms from 431.77ms.

### CODE REVIEW

**Comment by qjia7** [comment]
@guschmue @fs-eire @satyajandhyala Please take a look, thanks.

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
