### PR TITLE
[TRT EP] Add missing options initialization.

### PR DESCRIPTION
**Pull request by simonjub**
Add missing initialization for some TensorRT EP options in CreateTensorRTProviderOptions()

### CODE REVIEW

**Comment by simonjub** [comment]
@chilo-ms Hi, just bringing your attention to this. I should have spotted it while doing PR #17567 but it eluded me then.

**Comment by chilo-ms** [comment]
> @chilo-ms Hi, just bringing your attention to this. I should have spotted it while doing PR #17567 but it eluded me then.

@simonjub
Thanks for pointing this out.
Actually i'm refactoring the way TRT EP create/delete OrtTensorRTProviderOptionsV2 as well as when user needs to add additional provider option. I added[ initial value](https://github.com/microsoft/onnxruntime/blob/chi/trt_plugin_python/include/onnxruntime/core/providers/tensorrt/tensorrt_provider_options.h#L13) for each member of the OrtTensorRTProviderOptionsV2, so the code here is not needed will be removed.

      options->device_id = 0;
      options->has_user_compute_stream = 0;
      options->user_compute_stream = nullptr;
      ....

**Comment by simonjub** [comment]
Great, that looks good too. We can close this PR, then.

**Comment by chilo-ms** [comment]
FYI, here is the [PR](https://github.com/microsoft/onnxruntime/pull/17617)

**Comment by simonjub** [comment]
Looks good! I guess we can close this now. Thank you for the update.

**Pull request closed without merging**
