### PR TITLE
Accept success codes other than S_OK in RoInitialize

### PR DESCRIPTION
**Pull request by tiagoshibata**
There are test failures due to `RoInitialize` returning S_FALSE when the apartment was already initialized, if you ran other tests in the same process. This change makes both S_OK and S_FALSE pass.

### CODE REVIEW

**Comment by snnn** [comment]
But what if  the apartment was already initialized with another RO_INIT_TYPE ? Is it ok?

**Review by ryanlai2 — APPROVED** [review]

**Comment by ryanlai2** [comment]
Why is this change needed?

**Comment by tiagoshibata** [comment]
> But what if the apartment was already initialized with another RO_INIT_TYPE ? Is it ok?

It fails. Do we initialize with other types?

**Comment by snnn** [comment]
> > But what if the apartment was already initialized with another RO_INIT_TYPE ? Is it ok?
> 
> It fails. Do we initialize with other types?

Yes. Because when I hit the error, the error message was "Cannot **change** thread mode after it is set".

**Comment by snnn** [comment]
> Just curious, Why is this change needed?

I think it is because the test program also uses some other windows components that will call RoInitialize internally.

**Comment by tiagoshibata** [comment]
Ok, so I'll move the tests to the multithreaded apartment instead.

* Tried using the single-threaded apartment locally, and windows.foundation.h in cppwinrt fails an assertion saying that async methods can deadlock in a single-threaded apartment, so apparently it doesn't run in a single apartment
* I asked the implementer of the test and he said he didn't believe there was a reason to require a single-threaded apartment
* Current test has been running in the multithreaded apartment (because the other tests in the binary already initialized the apartment) in CI and locally (unless it's ran with `--gtest_filter`) and it's been fine

**Review by snnn — APPROVED** [review]

**Comment by smk2007** [comment]
Moving to a multithreaded apartment should be fine.

**Pull request merged**
