### PR TITLE
Detect necessary files inside GPU packages

### PR DESCRIPTION
**Pull request by chilo-ms**
Description: Detect necessary files (including cuda/trt ep runtime libraries and header files) in ORT GPU nuget/tarball/zip before official publish.

Motivation and Context

Why is this change required? What problem does it solve?
During packaging GPU package, we sometimes forget to include necessary files.

This PR is same as #8942, for same reasons old PR didn't show friendly "rename" feature instead showing "add/delete" which makes reviewers hard to review.

### CODE REVIEW

**Comment by chilo-ms** [comment]
For some reasons, even though I use "git mv" to rename files, but the final "files changed" tab still shows add/delete.
But you can still see following commit to have better code difference for review. Thanks
https://github.com/microsoft/onnxruntime/pull/8955/commits/b4f6e84a2d16b74466cfc6e1cab74c42f0144892

**Comment by jywu-msft** [comment]
hmm. sorry I guess git isn't able to do the rename for larger commit changes.
can we do the modifications and rename as separate PR's so it's easier to review?

**Comment by jywu-msft** [comment]
> For some reasons, even though I use "git mv" to rename files, but the final "files changed" tab still shows add/delete.
> But you can still see following commit to have better code difference for review. Thanks
> [b4f6e84](https://github.com/microsoft/onnxruntime/commit/b4f6e84a2d16b74466cfc6e1cab74c42f0144892)

ok, yeah. looks like it doesn't handle it for larger changes. will look at the commit for reviewing. thanks!

**Comment by jywu-msft** [comment]
kick off pipelines to exercise this validation?

**Comment by chilo-ms** [comment]
> kick off pipelines to exercise this validation?

Yes, did it.

**Review by snnn — APPROVED** [review]
You can merge it now if you want.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
