### PR TITLE
Cherry picks for 1.12.1

### PR DESCRIPTION
**Pull request by RandySheriffH**
Cherry picks for 1.12.1 on:
https://github.com/microsoft/onnxruntime/pulls?q=is%3Apr+label%3Arelease%3A1.12.1+

### CODE REVIEW

**Review by fdwr — APPROVED** [review]
Changes look fine.
- Prevent unbounded growth of command allocator memory `GetNextAllocator` #12114
- `generate_nuspec_for_native_nuget.py` changes look good.
- CreateFileMapping2 to valid API partitions #12374

**Review by edgchen1 — APPROVED** [review]
Android build changes look good to me.

**Review by jywu-msft — APPROVED** [review]
looked at the tensorrt ep changes.

**Comment by 15810856129** [comment]
how to get a libonnxruntime.a file?

**Pull request merged**
