### PR TITLE
[js/webgpu] Add HardSigmoid support

### PR DESCRIPTION
**Pull request by qjia7**
### Description
This op is required in mobilenetv3-small-100. With this PR, mobilenetv3-small-100 model becomes less than 10 ms from over 100 ms on ADL.

### CODE REVIEW

**Comment by qjia7** [comment]
run web CI

**Comment by qjia7** [comment]
run web CI

**Comment by qjia7** [comment]
@fs-eire @guschmue @satyajandhyala Please take a look, thanks.

**Review by fs-eire — APPROVED** [review]

**Review by guschmue — APPROVED** [review]

**Pull request merged**
