### PR TITLE
Fix logic error with TensorRT engine cache decryption

### PR DESCRIPTION
**Pull request by simonjub**
The current implementation has logic errors when TRT engine cache and engine cache encryption are both enabled. This commit fixes that issue.

### Description
Change the logic for reading, decryption and deserialization of the Tensor RT engine cache.

### Motivation and Context
This pull request fixes errors in the TensorRT EP when engine cache and engine encryption are both enabled. This problem was reported in issue #12551 but it looks like the issue was not well described/understood. 

Pseudocode of existing implementation:
```
if( engine_cache_enable && engine_file )
   engine_buffer = read(engine_file)
   deserialize(engine_buffer)  <-- If engine_decryption_enable==true, this fails because the content was not decrypted
else if (engine_decryption_enable && engine_cache_enable_ && !engine_file)
   engine_buffer = decrypt(engine_file)  <-- engine cache file does not exist, so this fails
   deserialize(engine_buffer)
else
   //build the engine
...
```
If the engine_file exists and is encrypted, the existing code enters the first if statement, which is not right.

I propose this pseudocode in this pull request:
```
if( engine_cache_enable && engine_file )
   if( engine_decryption_enable )
      engine_buffer = decrypt(engine_file)
   else
      engine_buffer = read(engine_file)
   deserialize(engine_buffer)
else
   //build the engine
...
```
This has the added benefit that the call to deserialize is in one place only and makes for easier maintenance.

### CODE REVIEW

**Comment by simonjub** [comment]
@microsoft-github-policy-service agree

**Comment by jywu-msft** [comment]
thanks for this PR!
can you fix the lint error https://github.com/microsoft/onnxruntime/actions/runs/4766354476/jobs/8598479153?pr=15519  ?

**Comment by simonjub** [comment]
> thanks for this PR! can you fix the lint error https://github.com/microsoft/onnxruntime/actions/runs/4766354476/jobs/8598479153?pr=15519 ?

Yes, will do.

**Comment by simonjub** [comment]
@jywu-msft Fixed the lint error.

**Comment by stevenlix** [comment]
Engine encryption and decryption is an experimental feature developed for specific user. The user was using different name for the encrypted engine, which is not the same name as the unencrypted engine file (engine_file).  User will make sure encrypted engine file is placed in the cache folder and doesn't coexist with unencrypted engine file, otherwise ORT will just deserialize unencrypted engine and ignore encrypted engine (which is the logic in the first branch). If unecrypted engine doesn't exist, ORT will try to decrypt the encrypted engine in the folder (which is the logic in the second branch).

**Comment by jywu-msft** [comment]
sorry i wasn't able to closely look at your PR previously.
this feature is not well documented because it was originally intended for internal usage.  we'll have to revisit some of this logic to see if something else makes more sense.
the code assumes an encrypted engine file has a different filename than a decrypted one. 
that is why the first condition if(engine_cache_enable && engine_file) must be true only if there is no encrypted file
either the encrypted file exists or the engine file exists, not both. 
it also assumes the encrypt/decrypt functions are implemented in a shared lib (supplied by the user)

**Comment by simonjub** [comment]
I see. I had no idea that the intent was the encrypted cache file should have a different name. When an encrypted cache is created, it currently uses the same filename as unencrypted. In this PR I wrongly assumed that a user would likely use the cache exclusively encrypted or non-encrypted modes so it wouldn't an issue.

**Comment by simonjub** [comment]
If you prefer to go the route of a different filename, I'm willing to contribute a new PR that looks for an encrypted engine with a different filename/extension when the option is enabled.

**Comment by simonjub** [comment]
So if I understand correctly, it's the encryption DLL that is currently responsible to modify the provided filename on the fly when it creates or reads the cache. It really wasn't obvious when looking at the implementation.

**Comment by jywu-msft** [comment]
> So if I understand correctly, it's the encryption DLL that is currently responsible to modify the provided filename on the fly when it creates or reads the cache. It really wasn't obvious when looking at the implementation. Edit: If this is true, how do you deal with the case where no cache has been created yet and encryption is enabled?
> 
> ```
> if( engine_cache_enable && engine_file )
>    engine_buffer = read(engine_file)
>    deserialize(engine_buffer)
> else if (engine_decryption_enable && engine_cache_enable_ && !engine_file)
>    // how do we know the encrypted engine file will exist when we get here?
>    engine_buffer = decrypt(engine_file)  
>    deserialize(engine_buffer)
> else
>    //build the engine
> ...
> ```
> 
> I suppose there's still something I don't know.

my understanding is that the library only provides the decrypt function. it doesn't rename the file.
the workflow goes something like this. the user enables engine cache to create an engine.
that engine file is encrypted offline and during that process the file is renamed.
that encrypted engine (with different filename) is what gets deployed.
the user enables the engine decryption option. the decrypt function knows the filename format of the file so it looks for that file and decrypts it.
@stevenlix can confirm this understanding as he is the one who implemented this feature.

**Comment by simonjub** [comment]
From what I can see in the code, the provided library does provide an encrypt function and it gets called when creating the cache if encryption is enabled. But in the use case you describe, this code should never even be reached because there's always a cache being encrypted offline. In my use case it did reach it. I realize the encrypted cache isn't very secure if have to distribute a library that both decrypts and encrypts the cache...

**Comment by jywu-msft** [comment]
> From what I can see in the code, the provided library does provide an encrypt function and it gets called when creating the cache if encryption is enabled. But in the use case you describe, this code should never even be reached because there's always a cache being encrypted offline. In my use case (with PR applied) it did reach it. I realize the encrypted cache isn't very secure if have to distribute a library that both decrypts and encrypts the cache...

i'll discuss with @stevenlix further. maybe i misremembered some of the details from discussions back then. i thought it would make more sense to create engine and encrypt it offline and deploy only encrypted engine (and library which can decrypt it at runtime)
the name of the runtime toggle is also called "engine_decryption_enable" which may lead one to think it can only decrypt and not encrypt at runtime.

**Comment by simonjub** [comment]
> The understanding of @jywu-msft is correct. When we designed the feature with the user, there were a couple of requirements. First the user implemented encryption/decryption functions and exposed it to TRT EP as a library. Second, the user decided the name of the encrypted engine. Third, original TRT engine should never be serialized to file for security reason if the feature is enabled (TRT EP just passed the TRT engine in memory to the user via encryption API). So for encryption, the user encrypted TRT engine in memory, serialized and saved it to the cache folder. For decryption, the user loaded the serialized encrypted TRT engine file in the cache folder and decrypted it. All those processes are done from the user side and are transparent to TRT EP. I agree though it's a bit confusing to use the same flag name engine_decryption_enable for both encryption and decryption.

@stevenlix OK. As I said before, I had no idea that the encryption/decryption library should use a different file name when reading/writing the encrypted engine (The path provided in the library function calls by TRT EP is the unencrypted engine path). 

1. Does the user decide the name within the library based on the path provided to the encrypt and decrypt functions? I can modify my own library to use a different filename for encrypted engine cache, so that's not an issue now that I know this.

2. How do you deal with the first execution with a model when no encrypted cache exists yet? It appears that the code assumes the encrypted engine will always be present. This is the part that I still don't fully understand. @jywu-msft said that the engine cache is encrypted offline, which implies an unencrypted engine cache was written to disk at least once. But that contradicts what you said the user wants.

**Comment by jywu-msft** [comment]
> > The understanding of @jywu-msft is correct. When we designed the feature with the user, there were a couple of requirements. First the user implemented encryption/decryption functions and exposed it to TRT EP as a library. Second, the user decided the name of the encrypted engine. Third, original TRT engine should never be serialized to file for security reason if the feature is enabled (TRT EP just passed the TRT engine in memory to the user via encryption API). So for encryption, the user encrypted TRT engine in memory, serialized and saved it to the cache folder. For decryption, the user loaded the serialized encrypted TRT engine file in the cache folder and decrypted it. All those processes are done from the user side and are transparent to TRT EP. I agree though it's a bit confusing to use the same flag name engine_decryption_enable for both encryption and decryption.
> 
> @stevenlix OK. As I said before, I had no idea that the encryption/decryption library should use a different file name when reading/writing the encrypted engine (The path provided in the library function calls by TRT EP is the unencrypted engine path).
> 
> 1. Does the user decide the name within the library based on the path provided to the encrypt and decrypt functions? I can modify my own library to use a different filename for encrypted engine cache, so that's not an issue now that I know this.
> 2. How do you deal with the first execution with a model when no encrypted cache exists yet? See my earlier comment with the pseudocode snippet. It appears that the code assumes the encrypted engine will always be present. This is the part that I still don't fully understand. @jywu-msft said that the engine cache is encrypted offline, which implies an unencrypted engine cache was written to disk at least once. But that contradicts what you said the user wants.

a few further points of clarification after I had an offline discussion with @stevenlix 

1) like you, i wasn't sure about what the expected behavior of encrypt() should be. does it write out encrypted file with a different naming convention. it's possible. it's also it could be renamed manually.
2) the code assumes the name of encrypted engine is different from standard engine. i.e. that is why there are 2 paths for writing out engine (encrypted and non encrypted) https://github.com/microsoft/onnxruntime/blob/abdd4f518a144035fee3b369996d8416a024bdaa/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L2104 and
https://github.com/microsoft/onnxruntime/blob/abdd4f518a144035fee3b369996d8416a024bdaa/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L2110
and it's expected that the uncrypted engine is never deployed along with encrypted engine (when encryption feature is enabled)
3) there's a bit of confusion with what the 'offline' workflow is. originally I had thought the encryption happens offline using a different toolchain. (and the library only contains the decrypt function)
but as you observed, the library implements both encrypt and decrypt. and the encrypt also happens in onnxruntime tensorrt EP. so offline in this case means ahead-of-time , and still using onnxruntime. so the encrypted engine is generated, renamed ahead of time and deployed.

hopefully this clears up the confusion. I think we can make improvements to this workflow (at least document in more clearly) and expand upon it (and meanwhile not break the existing internal use case)

**Comment by simonjub** [comment]
> 3\. there's a bit of confusion with what the 'offline' workflow is. originally I had thought the encryption happens offline using a different toolchain. (and the library only contains the decrypt function)
>         but as you observed, the library implements both encrypt and decrypt. and the encrypt also happens in onnxruntime tensorrt EP. so offline in this case means ahead-of-time , and still using onnxruntime. so the encrypted engine is generated, renamed ahead of time and deployed.
> 
> 
> hopefully this clears up the confusion. I think we can make improvements to this workflow (at least document in more clearly) and expand upon it (and meanwhile not break the existing internal use case)

I think the only thing missing (other than improved documentation) is a way to handle the case when no encrypted cache exists yet, so that the code that creates the engine cache can be reached.

https://github.com/microsoft/onnxruntime/blob/abdd4f518a144035fee3b369996d8416a024bdaa/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L2035-L2054

When flags engine_decryption_enable_  and engine_cache_enable_ are enabled and the unencrypted engine file does not exist, the execution path always enters here and returns the error "TensorRT EP could not get engine buffer size" when the encrypted engine cache does not exist. There's no way for the execution path to go into the final else statement to build the engine and create the encrypted cache.

**Comment by jywu-msft** [comment]
> > 3. there's a bit of confusion with what the 'offline' workflow is. originally I had thought the encryption happens offline using a different toolchain. (and the library only contains the decrypt function)
> > but as you observed, the library implements both encrypt and decrypt. and the encrypt also happens in onnxruntime tensorrt EP. so offline in this case means ahead-of-time , and still using onnxruntime. so the encrypted engine is generated, renamed ahead of time and deployed.
> > hopefully this clears up the confusion. I think we can make improvements to this workflow (at least document in more clearly) and expand upon it (and meanwhile not break the existing internal use case)
> 
> I think the only thing missing (other than improved documentation) is a way to handle the case when no encrypted cache exists yet, so that the code that creates the engine cache can be reached.
> 
> https://github.com/microsoft/onnxruntime/blob/abdd4f518a144035fee3b369996d8416a024bdaa/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L2022-L2054
> 
> When flags engine_decryption_enable_ and engine_cache_enable_ are enabled and the unencrypted engine file does not exist, the execution path always enters here and returns the error "TensorRT EP could not get engine buffer size" when the encrypted engine cache does not exist. There's no way for the execution path to go into the final else statement to build the engine and create the encrypted cache.

I spent some time analyzing these code paths. I think the only way this implementation works is there are 2 passes done in the ahead-of-time/offline step. in the first pass, engine_cache_enable is set to true.  (so an engine does get serialized to disk, which does seem contrary to the original requirements) for the second pass, both engine_cache_enable and engine_decryption_enable are set to true.  at that point the engine on disk gets encrypted. notice the function signature of encrypt() takes in the path to engine file. so i assume it must exist on disk.
after that, the encrypted engine is manually renamed and deployed. I think the original requirement that the unencrypted engine doesn't exist on disk actually means that it doesn't exist on the filesystem of the deployment target.
this workflow is a bit confusing and inefficient, so i'm not sure we would want to officially document and support it for general usage.

**Comment by simonjub** [comment]
> I spent some time analyzing these code paths. I think the only way this implementation works is there are 2 passes done in the ahead-of-time/offline step. in the first pass, engine_cache_enable is set to true. (so an engine does get serialized to disk, which does seem contrary to the original requirements) for the second pass, both engine_cache_enable and engine_decryption_enable are set to true. at that point the engine on disk gets encrypted. notice the function signature of encrypt() takes in the path to engine file. so i assume it must exist on disk.
> after that, the encrypted engine is manually renamed and deployed. I think the original requirement that the unencrypted engine doesn't exist on disk actually means that it doesn't exist on the filesystem of the deployment target.

In that scenario, with that second pass with engine_cache_enable and engine_decryption_enable set to true, because the unencrypted engine file exists on disk, we will enter the code path that simply deserializes that file and we never reach the part that builds and writes an encrypted engine to disk. To reach the part where the engine is built and saved in cache (encrypted or otherwise), the unencrypted engine file must not exist and engine_decryption_enable be set to false... in which case only an unencrypted engine gets saved to disk. So.. yeah, I'm still confused.

The function signature of encrypt does takes the path to the unencrypted engine file but also a pointer to the engine data to encrypt and its size. I assume the engine file path argument is used to generate the encrypted engine file name (the same way that the decrypt function will)?

One more comment. In the file there I found two locations where either the engine gets built or the cache is read/decrypted. Both have the same code paths/logic regarding cache and encryption flags. I'm not sure when either gets used over the other but that's probably beyond the scope of this discussion.

> this workflow is a bit confusing and inefficient, so i'm not sure we would want to officially document and support it for general usage.

I agree 100%. I'm still not sure I get it completely. But know that there is interest in using encrypted TRT engine caches out there. Issue #12551 and my attempt at "fixing it" here is proof. It would be great to find a solution that works for everyone. 

Thanks a lot for taking the time to discuss this with me by the way, this is much appreciated. I'd like to pursue this but don't know if this PR is the right place anymore.

**Comment by jywu-msft** [comment]
> > I spent some time analyzing these code paths. I think the only way this implementation works is there are 2 passes done in the ahead-of-time/offline step. in the first pass, engine_cache_enable is set to true. (so an engine does get serialized to disk, which does seem contrary to the original requirements) for the second pass, both engine_cache_enable and engine_decryption_enable are set to true. at that point the engine on disk gets encrypted. notice the function signature of encrypt() takes in the path to engine file. so i assume it must exist on disk.
> > after that, the encrypted engine is manually renamed and deployed. I think the original requirement that the unencrypted engine doesn't exist on disk actually means that it doesn't exist on the filesystem of the deployment target.
> 
> In that scenario, with that second pass with engine_cache_enable and engine_decryption_enable set to true, because the unencrypted engine file exists on disk, we will enter the code path that simply deserializes that file and we never reach the part that builds and writes an encrypted engine to disk. To reach the part where the engine is built and saved in cache (encrypted or otherwise), the unencrypted engine file must not exist and engine_decryption_enable be set to false... in which case only an unencrypted engine gets saved to disk. So.. yeah, I'm still confused.
> 
> The function signature of encrypt does takes the path to the unencrypted engine file but also a pointer to the engine data to encrypt and its size. I assume the engine file path argument is used to generate the encrypted engine file name (the same way that the decrypt function will)?
> 
> One more comment. In the file there I found two locations where either the engine gets built or the cache is read/decrypted. Both have the same code paths/logic regarding cache and encryption flags. I'm not sure when either gets used over the other but that's probably beyond the scope of this discussion.
> 
> > this workflow is a bit confusing and inefficient, so i'm not sure we would want to officially document and support it for general usage.
> 
> I agree 100%. I'm still not sure I get it completely. But know that there is interest in using encrypted TRT engine caches out there. Issue #12551 and my attempt at "fixing it" here is proof. It would be great to find a solution that works for everyone.
> 
> Thanks a lot for taking the time to discuss this with me by the way, this is much appreciated. I'd like to pursue this but don't know if this PR is the right place anymore.

yikes. you're right. i think i need to go back to the original commit that enabled this and see if a bug was introduced.
seems like the first if check for deserializing from unencrypted engine should also check that "engine_decryption_enable" should also be false.

**Comment by simonjub** [comment]
Looks like decryption and encryption were added six months apart. Looking at the commits, I would hazard a guess that engine cache encryption within the TRT EP was never used? The code execution paths were the same then than today.

**Comment by simonjub** [comment]
@jywu-msft I made a new attempt and fixing the code execution to be able to reach the encryption. [Here's the commit](https://github.com/simonjub/onnxruntime/commit/00cdbb82078d8bc7afefe2e54856c8d3dd3b9742) I did in a new branch in my forked repo. Care to take a look?

**Comment by jywu-msft** [comment]
> @jywu-msft I made a new attempt at fixing the code execution to be able to reach the encryption. [Here's the commit](https://github.com/simonjub/onnxruntime/commit/00cdbb82078d8bc7afefe2e54856c8d3dd3b9742) I did in a new branch in my forked repo. Care to take a look?

thanks! i took a quick look. looks like you are using successful return of decrypt() call as a proxy for detecting whether an encrypted engine file exists. 
with your current implementation extra decrypt() would be made.  (i.e. you call decrypt() once for the file existence and then the same decrypt() call is made again to fetch the size)
if we go that route, maybe it's better to just store the size of the encrypted file and check size of encrypted file > 0 rather than add a boolean encrypted_engine_exists. we can then use that size in the subsequent decrypt() call.

alternatively, we can continue the existing code's assumptions and add more checks to make the current implementation work.
e.g. add a check that engine decryption isn't enabled before we try to deserialize from an engine file in the 2nd pass.

**Comment by simonjub** [comment]
> thanks! i took a quick look. looks like you are using successful return of decrypt() call as a proxy for detecting whether an encrypted engine file exists. 
Yes, that's the idea, since only the decryption library knows what the encrypted engine filename would be. It assumes the library handles the file not existing gracefully. It would be much easier if the encrypted engine filename was known within onnxruntime.
> with your current implementation extra decrypt() would be made. (i.e. you call decrypt() once for the file existence and then the same decrypt() call is made again to fetch the size) if we go that route, maybe it's better to just store the size of the encrypted file and check size of encrypted file > 0 rather than add a boolean encrypted_engine_exists. we can then use that size in the subsequent decrypt() call.
Fair point! Decrypting the file twice is not optimal. That can be fixed.
> alternatively, we can continue the existing code's assumptions and add more checks to make the current implementation work. e.g. add a check that engine decryption isn't enabled before we try to deserialize from an engine file in the 2nd pass.
I'm not sure if I'm able to help if you prefer that route. It seems like it requires discussion with your internal user.

**Comment by chilo-ms** [comment]
>>>with your current implementation extra decrypt() would be made. (i.e. you call decrypt() once for the file existence and then the same decrypt() call is made again to fetch the size) if we go that route, maybe it's better to just store the size of the encrypted file and check size of encrypted file > 0 rather than add a boolean encrypted_engine_exists. we can then use that size in the subsequent decrypt() call.

>>Fair point! Decrypting the file twice is not optimal. That can be fixed.

> Actually there is a fair point regarding the engine size. The plain engine size may differ from the encrypted one. In order to know it, I had to decrypt twice. As a workaround, I embedded (prefixed) the plain engine size in the encrypted model. The decrypt() reads only size from a file first, without decrypting all the rest.

yea, it needs two decrypt() calls. First call is to get the size of the plain engine in order to create the buffer and the second call is the real decryption to get the plain engine. Current TRT EP has two decrypt() calls so does @simonjub's another [branch](https://github.com/microsoft/onnxruntime/compare/main...simonjub:onnxruntime:fix_12551_attempt2).
How library implements getting the size of the plain engine might differ.

**Comment by chilo-ms** [comment]
I think simonjub's another [branch](https://github.com/microsoft/onnxruntime/compare/main...simonjub:onnxruntime:fix_12551_attempt2) might work. 
It not only keeps the current business logic but also fixes the issue that "there was no code execution path possible so that an encrypted TRT engine cache could be created when flags engine_cache_enable and engine_decryption_enable are true".

@simonjub, just wondering did you test your another branch?

**Comment by simonjub** [comment]
> yea, it needs two decrypt() calls. First call is to get the size of the plain engine in order to create the buffer and the second call is the real decryption to get the plain engine. Current TRT EP has two decrypt() calls so does @simonjub's another [branch](https://github.com/microsoft/onnxruntime/compare/main...simonjub:onnxruntime:fix_12551_attempt2).
> How library implements getting the size of the plain engine might differ.

Yes, my own library added a small header similar to what @AndreyOrb mentioned to avoid having to decrypt the engine just to know it's decrypted size. A call to decrypt() with a nullptr for data can just read the header and return the decrypted size. An unoptimized library might end up doing the full decryption twice.

> I think simonjub's another [branch](https://github.com/microsoft/onnxruntime/compare/main...simonjub:onnxruntime:fix_12551_attempt2) might work. It not only keeps the current business logic but also fixes the issue that "there was no code execution path possible so that an encrypted TRT engine cache could be created when flags engine_cache_enable and engine_decryption_enable are true".
> 
> @simonjub, just wondering did you test your another branch?

@chilo-ms Yes, I've been successfully using this in my own project since I wrote it. I did not write a testcase to prove it however. I know it needs some work to rebase this branch with main. I can work on that if you think it's worth it.

**Comment by chilo-ms** [comment]
> > yea, it needs two decrypt() calls. First call is to get the size of the plain engine in order to create the buffer and the second call is the real decryption to get the plain engine. Current TRT EP has two decrypt() calls so does @simonjub's another [branch](https://github.com/microsoft/onnxruntime/compare/main...simonjub:onnxruntime:fix_12551_attempt2).
> > How library implements getting the size of the plain engine might differ.
> 
> Yes, my own library added a small header similar to what @AndreyOrb mentioned to avoid having to decrypt the engine just to know it's decrypted size. A call to decrypt() with a nullptr for data can just read the header and return the decrypted size. An unoptimized library might end up doing the full decryption twice.
> 
> > I think simonjub's another [branch](https://github.com/microsoft/onnxruntime/compare/main...simonjub:onnxruntime:fix_12551_attempt2) might work. It not only keeps the current business logic but also fixes the issue that "there was no code execution path possible so that an encrypted TRT engine cache could be created when flags engine_cache_enable and engine_decryption_enable are true".
> > @simonjub, just wondering did you test your another branch?
> 
> @chilo-ms Yes, I've been successfully using this in my own project since I wrote it. I did not write a testcase to prove it however. I know it needs some work to rebase this branch with main. I can work on that if you think it's worth it.

Thanks for adding the code and the code looks good to me. I think we want to fix this issue and make it into ORT 1.16 release (branch date is 8/18 and release date is 8/31, so we still have some time). But still let's wait for @jywu-msft review again (It might take several days since he is OOF).

**Comment by chilo-ms** [comment]
> > Thanks for adding the code and the code looks good to me. I think we want to fix this issue and make it into ORT 1.16 release if possible (branch date is 8/18 and release date is 8/31, so we still have some time). But still let's wait for @jywu-msft review again (It might take several days since he is OOF).
> 
> That would be great. My project uses ORT 1.15.1 patched with the change from my second branch but I'm trying to keep up with the releases. Since this PR does not point to the other branch with the better implementation, should I create another PR?

That would be great. And we can have discussion there regarding the implementation.

**Comment by simonjub** [comment]
Closing this PR in favor of #17111

**Pull request closed without merging**
