### PR TITLE
[AIX] Python binding enablement and gcc support

### PR DESCRIPTION
**Pull request by ranjitshs**
### Description
Enabling python binding and gcc support for AIX.

### Motivation and Context
Code changes in this PR contains:
1. python binding enablement
2. gcc building support

Below are list of files and the description.

1. cmake/CMakeLists.txt
[gcc building support] -no-unused-function compiler flag addition for IBMClang
2. cmake/external/eigen.cmake
[gcc building support] AIX check for applying the AIX patch
3. cmake/onnxruntime_python.cmake
[python binding ] putting NOT AIX check for -Xlinker
4. cmake/onnxruntime_unittests.cmake
[gcc building support] Fix for gtest behavior. Check the comment .
[python binding ] using -Wl,-brtl for linking onnxruntime_providers_shared in test_execution_provider
5. cmake/patches/eigen/eigen-aix.patch
[gcc building support] In AIX gcc, we are hitting __builtin_cpu_supports("mma") which is not supported yet. So patching code for this method .  Patched code will check for P10 Processor at run-time and based on that routine will be set.
6. onnxruntime/python/onnxruntime_validation.py
[python binding ] Adding AIX check in check_distro_info()
7. onnxruntime/test/providers/cpu/generator/random_test.cc
[gcc building support] updating previous check for AIX , along with  clang. So in case of gcc, else block will hit.
8. onnxruntime/test/python/onnxruntime_test_python.py
[python binding ] powerpc check on platform.processor()
9. setup.py
[python binding ] Adding AIX check for list of libs.

### CODE REVIEW

**Comment by ranjitshs** [comment]
@tianleiwu @snnn 
Could you please review the changes in this PR ?
Also please trigger relevant CI pipelines.

**Review by snnn — APPROVED** [review]
Thanks

**Comment by ranjitshs** [comment]
@snnn @tianleiwu 
Thanks for review/approval and merging this PR.

**Pull request merged**
