### PR TITLE
[VitisAI] 1. api compatbile 2. dynamic load onnx

### PR DESCRIPTION
**Pull request by BoarQing**
### Description

1. Add a backward-compatible API for compiling model.
2. Run-time load vitisai-ep.dll

### CODE REVIEW

**Comment by BoarQing** [comment]
@jywu-msft Hi, we have made some major changes to Vitis AI. Could you take a look when avaliable?

**Comment by BoarQing** [comment]
@jywu-msft Just a question. I found the cpplint failed. Is there a character limit of 120 for onnxruntime now? I checked the .clang-format there isn't any limit there.

**Comment by jywu-msft** [comment]
> @jywu-msft Just a question. I found the cpplint failed. Is there a character limit of 120 for onnxruntime now? I checked the .clang-format there isn't any limit there.

yes, that's always been there.
see comment at https://github.com/microsoft/onnxruntime/blob/3f0ebd673622d3663011ae33fc6070f1f2ea3af3/.clang-format#L6
and 
https://github.com/microsoft/onnxruntime/blob/main/docs/Coding_Conventions_and_Standards.md

**Comment by BoarQing** [comment]
> > @jywu-msft Just a question. I found the cpplint failed. Is there a character limit of 120 for onnxruntime now? I checked the .clang-format there isn't any limit there.
> 
> yes, that's always been there. see comment at
> 
> https://github.com/microsoft/onnxruntime/blob/3f0ebd673622d3663011ae33fc6070f1f2ea3af3/.clang-format#L6
> 
> 
> and
> https://github.com/microsoft/onnxruntime/blob/main/docs/Coding_Conventions_and_Standards.md

Hi, I l have linted my code. Could you restart the pipeline.

**Comment by BoarQing** [comment]
@jywu-msft Sorry, the last lint wasn't through. Could you start the pipeline again?

**Comment by BoarQing** [comment]
@jywu-msft Sorry, the last lint wasn't through. Could you start the pipeline again?

**Comment by BoarQing** [comment]
@jywu-msft Should the failed CI concerns me? I found the failures are not related to my PR.

**Comment by jywu-msft** [comment]
> @jywu-msft Should the failed CI concerns me? I found the failures are not related to my PR.

looks unrelated to your PR.  there's some transient failure. I am resubmitting the failed jobs.

**Comment by BoarQing** [comment]
> > @jywu-msft Should the failed CI concerns me? I found the failures are not related to my PR.
> 
> looks unrelated to your PR. there's some transient failure. I am resubmitting the failed jobs.

I found the remaining errors also exist in other pull requests. So, feel free to review the code now.

**Comment by BoarQing** [comment]
@jywu-msft Can this PR be merged?

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
