### PR TITLE
Combine Linux build pipelines

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

Combine Linux build pipelines to a single yaml file

**Motivation and Context**
- Why is this change required? What problem does it solve?

To make them easier to schedule/cancel. 

- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by jywu-msft** [comment]
do we really need to combine all of them? 
Would it be safer to keep dnnl and openvino pipelines separate since those would typically be modified by external contributions
and we wouldn't want them to accidentally touch other pipeline configs?

**Comment by snnn** [comment]
> do we really need to combine all of them?


Not really. This is mainly for making 'azp run' easier to use. So, what do you think? If you want to dnnl and openvino separate,  I think there is not much need to combine the others as well.

**Comment by jywu-msft** [comment]
> > do we really need to combine all of them?
> 
> Not really. This is mainly for making 'azp run' easier to use. So, what do you think? If you want to dnnl and openvino separate, I think there is not much need to combine the others as well.

so would it also mean you couldn't run OpenVINO pipeline separately? often times for external contribs, i would kick off a single pipeline first, before running everything (to avoid excessive pipelines being scheduled if the first one doesn't pass)

**Comment by snnn** [comment]
No. Ok. Let's keep it as it is.

**Pull request closed without merging**
