### PR TITLE
[WebNN EP] Enable several ops for WebNN CPU backend

### PR DESCRIPTION
**Pull request by Honry**
WebNN CPU implementation has been migrated from XNNPack to TFLite which supports more ops. Turn on partial `cpu` supported ops which just need the change from `false` to `true` firstly.

### CODE REVIEW

**Review by guschmue — APPROVED** [review]

**Comment by Honry** [comment]
@guschmue, sorry I forget to update the WebNN operators table, PTAL again, thanks!

**Comment by Honry** [comment]
@fdwr, @guschmue, fixed conflict, PTAL again, thanks!

**Review by guschmue — APPROVED** [review]

**Comment by Honry** [comment]
@guschmue, umm, more failure CIs now, do I need to rebase this PR to main?

**Review by fdwr — APPROVED** [review]

**Pull request merged**
