### PR TITLE
Fix typo in quantization howto

### PR DESCRIPTION
**Pull request by TGabor**
**Description**: 
Fix typo in documentation

### CODE REVIEW

**Review by yufenglee — APPROVED** [review]

**Comment by yufenglee** [comment]
You need to create a pull request to master branch.

**Comment by TGabor** [comment]
> You need to create a pull request to master branch.

@yufenglee I just changed the base branch to `master`.

**Comment by faxu** [comment]
Hi @tgabor, it looks like you may have started with an out of date older fork?
It'll probably be cleaner to rebase your fork to the current master branch and remake your edits there.

**Pull request closed without merging**
