### PR TITLE
Merge master into thiagofc/ortmodule-api

### PR DESCRIPTION
**Pull request by thiagocrepaldi**
Merges master into thiagofc/ortmodule-api. 

Many conflicts are detected and a plain copy off all files from mzs/ortmodule-api-rebase-master branch  was used to resolve them

### CODE REVIEW

**Comment by codemzs** [comment]
This sync from master resulted in 200+ conflicts which were resolved by copy-pasting files from [mzs/ortmodule-api-rebase-master](https://github.com/microsoft/onnxruntime/pull/6683)

However resolving conflicts in the above fashion has actually resulted in a change that is not consistent with rebase, for example with rebase of this feature branch on master, [it only touched 73 files](https://github.com/microsoft/onnxruntime/pull/6683) but this sync from master + copying over files from the rebase branch to resolve conflicts is touching [108 files](https://github.com/microsoft/onnxruntime/pull/6723). Below I have highlighted _**some**_ of the new files this change is bringing in and also files this change is modifying which rebase does not modify. This indicates the merge was not proper where it has likely overwritten or deleted existing stuff from master that resulted in us having to add or remove stuff back into this change. Please note we plan to merge back every commit from this branch to master hence it is very important we do not artificially alter the history in master.

image

CC; @SherlockNoMad  @mrry

**Review by codemzs — CHANGES_REQUESTED** [review]
This sync from master resulted in 200+ conflicts which were resolved by copy-pasting files from [mzs/ortmodule-api-rebase-master](https://github.com/microsoft/onnxruntime/pull/6683)

However resolving conflicts in the above fashion has actually resulted in a change that is not consistent with rebase, for example with rebase of this feature branch on master, [it only touched 73 files](https://github.com/microsoft/onnxruntime/pull/6683) but this sync from master + copying over files from the rebase branch to resolve conflicts is touching [108 files](https://github.com/microsoft/onnxruntime/pull/6723) (w.r.t master branch). Moreover with rebase we only added and removed +3,912 −99 lines w.r.t master branch but with this sync we have added and removed +4,537 −1,729 lines w.r.t master branch.

Below I have highlighted _**some**_ of the new files this change is bringing in and also files this change is modifying which rebase does not modify. This indicates the merge was not proper where it has likely overwritten or deleted existing stuff from master that resulted in us having to add or remove stuff back into this change. Please note we plan to merge back every commit from this branch to master hence it is very important we do not artificially alter the history in master.

image

CC; @SherlockNoMad  @mrry

**Review by codemzs — APPROVED** [review]
Didn't review in detail but looks fine overall. Thank you, @thiagocrepaldi

**Review by SherlockNoMad — APPROVED** [review]
Thank you for the merge!

**Pull request merged**
