### PR TITLE
Bug fix for C API

### PR DESCRIPTION
**Pull request by duli2012**
In order to keep the  C API consistent, remove the #if_def USE_CUDA and check whether cuda ep is enabled in function body of OrtSessionOptionsAppendExecutionProvider_CUDA.

### CODE REVIEW

**Review by RyanUnderhill — DISMISSED** [review]
Perfect

**Comment by snnn** [comment]
Why the change is needed?

**Comment by jywu-msft** [comment]
please provide more details? and what about other execution providers?

**Comment by duli2012** [comment]
> Why the change is needed?

added PR description.

**Comment by duli2012** [comment]
> please provide more details? and what about other execution providers?

added pr description. @RyanUnderhill is working on other EPs?

**Review by RyanUnderhill — APPROVED** [review]

**Pull request merged**
