### PR TITLE
[WebNN EP] Support LpPool, GlobalLpPool, and Log ops

### PR DESCRIPTION
**Pull request by Honry**
BTW, reset minimal supported opset to 1, because with minimal supported opset 7 will ignore all ops that have last since version less than 7. e.g. GlobalLpPool, it only has two opset versions: 1, 2.

### CODE REVIEW

**Comment by Honry** [comment]
@fdwr, @guschmue, PTAL, thanks!

**Comment by fdwr** [comment]
The [MacOS CI Pipeline](https://github.com/microsoft/onnxruntime/pull/16954/checks?check_run_id=15539901278) test has failed 2x now with a failure to download some random Python package :/. Will retry again...

**Pull request merged**
