### PR TITLE
[CUDA] Special case for K==0 in CUDA MatMul

### PR DESCRIPTION
**Pull request by yuslepukhin**
### Description
This change addresses a case where we multiply two matrices, and their inner dimension is 0.
numpy and Eigen which is being used in our CPU EP implementation correctly handle this case
and output a [M, N] matrix filled with zeros.

### Motivation and Context
This is required to support GenAI empty input Lora implementation.

Addresses: https://github.com/microsoft/onnxruntime/issues/21483

### CODE REVIEW

**Review by tianleiwu — DISMISSED** [review]

**Review by tianleiwu — APPROVED** [review]

**Review by tianleiwu — APPROVED** [review]

**Comment by ranjitshs** [comment]
@yuslepukhin @tianleiwu 
FYI. Our local AIX CI reported the below newly introduced test case failure. I will try to debug. 
Please let me know if you have any suggestion.

`1: [ RUN      ] MathOpTest.MatMul_ZeroK
1: /home/buildusr/jenkins/workspace/onnxruntime-openxl/onnxruntime/onnxruntime/test/providers/checkers.cc:390: Failure
1: The difference between cur_expected[i] and cur_actual[i] is NaNQ, which exceeds tolerance, where
1: cur_expected[i] evaluates to 0,
1: cur_actual[i] evaluates to -NaNQ, and
1: tolerance evaluates to 9.9999997473787516e-06.
1: i:3
1: Google Test trace:
1: /home/buildusr/jenkins/workspace/onnxruntime-openxl/onnxruntime/onnxruntime/test/providers/checkers.cc:566: provider type: CPUExecutionProvider
1: /home/buildusr/jenkins/workspace/onnxruntime-openxl/onnxruntime/onnxruntime/test/providers/base_tester.cc:827: registered execution providers: CPUExecutionProvider
1: 
1: /home/buildusr/jenkins/workspace/onnxruntime-openxl/onnxruntime/onnxruntime/test/providers/checkers.cc:390: Failure
1: The difference between cur_expected[i] and cur_actual[i] is NaNQ, which exceeds tolerance, where
1: cur_expected[i] evaluates to 0,
1: cur_actual[i] evaluates to -NaNQ, and
1: tolerance evaluates to 9.9999997473787516e-06.
1: i:5
1: Google Test trace:
1: /home/buildusr/jenkins/workspace/onnxruntime-openxl/onnxruntime/onnxruntime/test/providers/checkers.cc:566: provider type: CPUExecutionProvider
1: /home/buildusr/jenkins/workspace/onnxruntime-openxl/onnxruntime/onnxruntime/test/providers/base_tester.cc:827: registered execution providers: CPUExecutionProvider
1: 
1: [  FAILED  ] MathOpTest.MatMul_ZeroK (3 ms)`

**Comment by yuslepukhin** [comment]
We do not have AIX build, however, my hunch is that `std::fill()` with the actual datatype(0) such as float would do better than `memset`. Can you try it locally and let us know? I would provide a fix.

**Comment by ranjitshs** [comment]
Hi @yuslepukhin 
This test failure is intermittent and not happening every time, so it's okay for time being. 
I will try to see the frequency of failure  in local CI  system. 
Thanks for the std::fill suggestion.  I haven't tried because failure is intermittent. 
is it more reliable than memset() for data type other than integers family ?

**Comment by yuslepukhin** [comment]
It depends on the floating-point format used on AIX. I have not worked with AIX for nearly 20 years. `memset()` assumes that all zeros are fine all datatypes. `std::fill()` would rely on explicitly constructing a given data type constant that represents zero on any given platform with any given compiler, and, therefore, is more portable.

**Pull request merged**
