### PR TITLE
[VitisAI]set-data_loaction-as-default-when-load-external-data

### PR DESCRIPTION
**Pull request by zz002**
### Description

set-data_loaction-as-default-when-load-external-data
fix vitis ai ep can not get CutomOps by session_option register

### Motivation and Context

VitisAI bug daily fixes
when use pass: fuse_qdq_GEMM or fuse_qdq_MATMUL, get error like : Error Data of TensorProto ( tensor name: xxx) is stored externally and should not have data field.raw_data

### CODE REVIEW

**Comment by zz002** [comment]
Hi @jywu-msft
When you have some free time, could you please take a moment to review the fixed VitisAI bug? Your feedback would be greatly appreciated. Thank you very much for your attention to this matter!

**Comment by jywu-msft** [comment]
it looks good to me.

**Comment by jywu-msft** [comment]
I see it's still marked as draft.  is it ready for review/merge? I can kick off the CI's if so.

**Comment by jywu-msft** [comment]
fyi lint check failed.


>>> Lint for onnxruntime/core/providers/shared_library/provider_wrappedtypes.h:

  Warning (CLANGFORMAT) format
    See https://clang.llvm.org/docs/ClangFormat.html.
    Run `lintrunner -a` to apply this patch.

    You can run `lintrunner -a` to apply this patch.

    205  205 | 
    206  206 |   bool has_data_location() const { return g_host->TensorProto__has_data_location(this); }
    207  207 |   TensorProto_DataLocation data_location() const { return TensorProto_DataLocation(g_host->TensorProto__data_location(this)); }
    207      |-  
         208 |+
    209  209 |   void set_data_location(TensorProto_DataLocation data_location) { return g_host->TensorProto__set_data_location(this, data_location); }
    210  210 | 
    211  211 |   bool has_raw_data() const { return g_host->TensorProto__has_raw_data(this); }

[2024-02-29T16:32:01Z DEBUG lintrunner::persistent_data] Writing run info to /home/runner/.local/share/lintrunner/8df75c113be62f219293da6d1a6f82a033052b3ca03190b6d03acd3ed6a9691d/runs/2024-02-29T16-27-56.896Z_80015b8980a08df67e03e2596acef487771aed65e28b72d8c60a61[40](https://github.com/microsoft/onnxruntime/actions/runs/8091224200/job/22134736037?pr=19712#step:6:41)007f8e7c

**Comment by zz002** [comment]
@jywu-msft  Now ready to review.

**Comment by jywu-msft** [comment]
hi, can you merge latest main? the test failures are due to some flakey tests which is addressed by https://github.com/microsoft/onnxruntime/pull/19792
I will re-run the CI's afterwards. thanks.

**Comment by zz002** [comment]
> hi, can you merge latest main? the test failures are due to some flakey tests which is addressed by #19792 I will re-run the CI's afterwards. thanks.
done
```
commit 9fc272fbe631247ed5762a68826ed6aff23e0438 (HEAD -> chenduan-set-data_loaction-as-default-when-load-external-data-, zz002/chenduan-set-data_loaction-as-default-when-load-external-data-)
Author: Zhenze Wang <zhenzew@xilinx.com>
Date:   Thu Mar 7 06:32:09 2024 +0000

    fix vitis ai ep can not get CutomOps by session_option register

commit bff4f8bf75562704720624fac63b149d10042ac8 (microsoft/main)
Author: Tianlei Wu <tlwu@microsoft.com>
Date:   Wed Mar 6 17:47:17 2024 -0800
```

**Comment by zz002** [comment]
@jywu-msft Are there any plans to merge this PR?

**Comment by jywu-msft** [comment]
> @jywu-msft Are there any plans to merge this PR?

yes. there was a new CI pipeline I didn't kick off yet. just did so.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
