### PR TITLE
CUDA UpsampleNearest performance improvement

### PR DESCRIPTION
**Pull request by cschreib-ibex**
**Description**: This PR improves the performance of the CUDA kernel for nearest neighbor upsampling. It does so by promoting a function parameter (the rank of the tensor) into a template parameter with explicit instanciations, enabling the compiler to better unroll the loop inside the kernel. It also adds the `__restrict__` keyword to the input and output buffers, telling the compiler that the pointers cannot alias, hence enabling further optimisation.

`nvprof` before the changes (on 1.7.2):
```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   69.28%  69.195ms         5  13.839ms  3.8302ms  30.768ms  void onnxruntime::cuda::_UpampleNearestKernel<float>(__int64, onnxruntime::cuda::TArray<__int64, int=8>, onnxruntime::cuda::_UpampleNearestKernel<float, onnxruntime::cuda::fast_divmod, int=8>, onnxruntime::cuda::fast_divmod, float const *, onnxruntime::cuda::_UpampleNearestKernel<float, onnxruntime::cuda::fast_divmod, int=8>*, __int64)
```
`nvprof` after the changes (still on 1.7.2):
```
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:    4.90%  1.6331ms         5  326.61us  93.118us  722.00us  void onnxruntime::cuda::_UpampleNearestKernel<float, int=4>(onnxruntime::cuda::TArray<__int64, int=8>, onnxruntime::cuda::_UpampleNearestKernel<float, int=4, onnxruntime::cuda::fast_divmod, int=8>, onnxruntime::cuda::fast_divmod, float const *, onnxruntime::cuda::_UpampleNearestKernel<float, int=4, onnxruntime::cuda::fast_divmod, int=8>*, __int64)
```

Speed up: x42!

**Motivation and Context**
- This enables our models, exported from TensorFlow, to run at similar or better speed than when executed from within TensorFlow.
- Closes https://github.com/microsoft/onnxruntime/issues/7578.

### CODE REVIEW

**Comment by cschreib-ibex** [comment]
FYI I noticed other kernels that suffer from this problem. I don't know if you want to port a similar fix to them as well (see `_ResizeNearestMappingKernel` for example; I haven't done an exhaustive search).

**Comment by cschreib-ibex** [comment]
Is there anything I can do to help you review/merge this? I hoped the changes were small enough that they would be a no-brainer to merge... :)

**Comment by jywu-msft** [comment]
@hariharans29 can you help review this change?

**Comment by hariharans29** [comment]
Thanks for the contribution! LGTM.  

@jywu-msft: Are you okay with merging this ?

**Comment by jywu-msft** [comment]
> Thanks for the contribution! LGTM.
> 
> @jywu-msft: Are you okay with merging this ?

yes. looks okay. thanks.

**Review by hariharans29 — APPROVED** [review]

**Comment by cschreib-ibex** [comment]
FYI, I was re-reading the code and found a minor bug on line 182:
```c++
} else if (onnxruntime::UpsampleMode::LINEAR) {
```

Very sorry about this... It should have been `onnxruntime::UpsampleMode::LINEAR == upsample_mode`. Probably not a big deal in practice, as `LINEAR` has value `1` hence the `else if` branch will always be followed. But it does mean that unsupported upsample modes (like `CUBIC`) will silently behave as `LINEAR` instead of doing nothing (previous behavior). I'm not sure that either behavior is correct; but I leave that up to you.

**Comment by hariharans29** [comment]
> FYI, I was re-reading the code and found a minor bug on line 182:
> 
> ```c++
> } else if (onnxruntime::UpsampleMode::LINEAR) {
> ```
> 
> Very sorry about this... It should have been `onnxruntime::UpsampleMode::LINEAR == upsample_mode`. Probably not a big deal in practice, as `LINEAR` has value `1` hence the `else if` branch will always be followed. But it does mean that unsupported upsample modes (like `CUBIC`) will silently behave as `LINEAR` instead of doing nothing (previous behavior). I'm not sure that either behavior is correct; but I leave that up to you.

Thanks for catching that. 

1) Can you please fix the condition ? 

2) `Upsample` got superseded by `Resize` in opset-10 onwards. The code in the file you are modifying can only be hit by the `Upsample` kernel (and not `Resize`). Looking at the spec of [Upsample](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Upsample-9), it doesn't seem to have any other modes other than `nearest` and `linear`. But could you please go ahead and add an ORT_THROW in case we encounter some other mode in that function ? It will help others trying to understand the code in the future.

**Comment by cschreib-ibex** [comment]
I can supply the fix, but probably not until next month, as I have tons of other things on my plate at the moment. Let me know if that's an OK timescale for you.

**Comment by hariharans29** [comment]
> I can supply the fix, but probably not until next month, as I have tons of other things on my plate at the moment. Let me know if that's an OK timescale for you.

That's ok - I will just fix it myself. Thanks.

**Pull request merged**
