### PR TITLE
Tuning GRU performance for batch size > 1

### PR DESCRIPTION
**Pull request by yufenglee**
GRU with batch size >1 is implemented on the assumption that Lotus use single-thread Eigen Gemm. The assumption doesn't hold anymore. MLAS, MKLDNN and MKLML support multi-thread. We don't rely eigen gemm anymore. 
This PR implements batch size > 1 as batch size ==1. With this change, we have about 2x performance gain for GRU.Please refer to the performance test below: 

(ms)
Batch_size | Seq_length | input_size | hiddden_size |       Old |     New
              8 |         30 |        512 |          512 |     19.16 |    10.47
             16 |         30 |        512 |          512 |     28.13 |    15.15
             32 |         30 |        512 |          512 |     36.97 |    26.89
              8 |         30 |       1024 |         1024 |   142.853 |    55.67
             16 |         30 |       1024 |         1024 |   184.397 |    72.32
             32 |         30 |       1024 |         1024     236.364 |   112.78

### CODE REVIEW

**Comment by skottmckay** [comment]
> MLAS, MKLDNN and MKLML support multi-thread. We don't rely eigen gemm anymore.

We don't, but does that mean nobody will? Would it be better to leave the batch parallel option in there, and only set it when we are using Eigen GEMM?

**Comment by skottmckay** [comment]
I assume a similar change will benefit the two LSTM implementations as well given those use the same batch parallel approach.

**Comment by yufenglee** [comment]
I will do the same change for LSTM. I just curious in what kind of scenario user will use eigen. I don't see any benefit from that.

**Comment by skottmckay** [comment]
> I will do the same change for LSTM. I just curious in what kind of scenario user will use eigen. I don't see any benefit from that.

https://github.com/Microsoft/onnxruntime/pull/620 strongly suggests it happens.

**Comment by yufenglee** [comment]
> MLAS, MKLDNN and MKLML support multi-thread. We don't rely eigen gemm anymore.
We don't, but does that mean nobody will? Would it be better to leave the batch parallel option in there, and only set it when we are using Eigen GEMM?

Adding more macros into the code makes it hard to maintain. What's more, if customers build onnxruntime with single-thread eigen explictily, i don't think performance is their concern. Their main interest is to run onnxruntime with single thread? If so, we should not run GRU with multi-thread implicitly. 

> #620 strongly suggests it happens.
The concern for this PR is that ONNXRuntime should be able to run without MLAS. For GRU, removing the batch parallel code doesn't change the ground.

**Pull request closed without merging**
