### PR TITLE
[DmlEp] Avoided warning C4458: declaration of 'X' hides class member

### PR DESCRIPTION
**Pull request by gineshidalgo99**
**Description**: Describe your changes.
Updated MLOperatorAuthorImpl.cpp/h to avoid warning C4458:
```
declaration of 'value' hides class member
d:\build\AutoSDK\Sync\HostWin64\Win64\Windows Kits\10\include\10.0.18362.0\winrt\wrl\implements.h(81): note: see declaration of 'Microsoft::WRL::RuntimeClassFlags<4>::value'
```
More info: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4458?view=msvc-160

Note: This is very similar to the PR already merged in [9541](https://github.com/microsoft/onnxruntime/pull/9541). However, this one is only happening in "some" machines, my guess, because of the Windows Kit 10 version (10.0.18362.0 seems to cause that issue while 10.0.19041.0 does not).

**Motivation and Context**
- Why is this change required? What problem does it solve? In more strict compilers, this warning is triggered when compiling ORT from source.

PS: Happy to change the names to anything else that you might prefer!

### CODE REVIEW

**Review by fdwr — DISMISSED** [review]

**Comment by gineshidalgo99** [comment]
This PR was part of PR #9585 (by @sumitsays, @fdwr) really, so after merging the merge conflicts caused by #9585 there is only 1 line change left. This line is just whether you guys wanna be consistent between the argument name in both the header and cpp file, as the header variable name 

Feel free to either accept and/or directly close this PR, either way is fine for me :)

**Review by fdwr — APPROVED** [review]

**Comment by fdwr** [comment]
>This line is just whether you guys wanna be consistent between the argument name in both the header and cpp file, as the header variable name

Yes, we do : ). (though, this probably could have been folded into another change at this point - oh well :b)

**Pull request merged**
