### PR TITLE
[js/webgpu] Optimize InstanceNormalization

### PR DESCRIPTION
**Pull request by qjia7**
### Description

In previous implementation, there are two loops to iterate H * W elements to calculate the `mean` and `squaredNorm` value in one thread, meanwhile it outputs H * W elements in one thread. That results it's very very slow when H * W is a large value. And usually, H * W does be a large value in a model. For example, in the `candy-8` model, the shapes of [H, W] are [224,224], [112,112], [56,56] for `InstanceNormalization` op. And in my ADL, `[1,224,224,32]` consumes 17 ms. See below:
```
[profiling] kernel "23848328|[InstanceNormalization] 23848328" input[0]: [1,224,224,32] | float32, input[1]: [32] | float32, input[2]: [32] | float32, output[0]: [1,224,224,32] | float32, execution time: 17007914 ns
```

In this PR, it uses workgroup memory to optimize the original algorithm. The advantage is that it can parallelly utilize the 64 (workgroupSize) threads in one workgroup to calculate `mean` and `squaredNorm` value. Meanwhile, it only outputs `H * W / workgroupSize` outputs for one thread, which greatly reduces the overhead for one thread. With this optimization, `[1,224,224,32]` becomes 3 ms and the main overhead is the extra two `transpose`. The `createInstanceNormProgramInfo` only needs `0.64` ms. See below:
```
[profiling] kernel "23003600|[InstanceNormalization] 23003600" input[0]: [1,224,224,32] | float32, output[0]: [1,32,224,224] | float32, execution time: 1543792 ns
program-manager.ts:115 
[profiling] kernel "23003600|[InstanceNormalization] 23003600" input[0]: [1,32,224,224] | float32, input[1]: [32] | float32, input[2]: [32] | float32, output[0]: [1,32,224,224] | float32, execution time: 642652 ns
program-manager.ts:115 
[profiling] kernel "23003600|[InstanceNormalization] 23003600" input[0]: [1,32,224,224] | float32, output[0]: [1,224,224,32] | float32, execution time: 991608 ns
```
This PR currently only applies the new algorithm to NCHW format. For NHWC format, one way is to transpose the input so that it can use the new algorithm. But the disadvantage is that 2 extra transpose are added.  @dakenf also gives another way to optimize NHWC. Details see [here](https://github.com/microsoft/onnxruntime/blob/d45a96616da9843b037210f2d48d6b4e5bdae5c6/js/web/lib/wasm/jsep/webgpu/ops/instance-norm.ts). I checked @dakenf's method. The perf is similar with transpose + optimized NCHW. But on different GPUs, one is a little better than another or vice versa. So I prefer this PR only does the NCHW part. @dakenf can submit his optimization on NHWC.

### CODE REVIEW

**Comment by dakenf** [comment]
My version was optimizing NHWC version and I did not touch the NCWH since it was not used right now, so i guess both changesets can be merged. I've used combined approach and calculated channel scale and channel shift using vec4/vec2 for different channels in a separate compute pass to speed-up applying these values https://github.com/microsoft/onnxruntime/blob/d45a96616da9843b037210f2d48d6b4e5bdae5c6/js/web/lib/wasm/jsep/webgpu/ops/instance-norm.ts

**Comment by qjia7** [comment]
@dakenf, I tried your method. The perf looks pretty well. But I find the results are different between our two methods. So we need some tests to guarantee the correctness (the existed model tests seems go to the cpu path not webgpu path due to opset is too low). For now, I will limit my optimization only on NCHW.

**Comment by dakenf** [comment]
You need to copy instance norm tests from web/test/data/node/opset8 to web/test/data/node/opset17 and then it will work fine. Not sure why in opset17 models are created with opset 6 (or some other low number)

**Comment by fs-eire** [comment]
The reason is because there was a commit in onnx: https://github.com/onnx/onnx/commit/acaa175e7dd48a4dfdc64f0fd3af7d2461f0b304.

This change makes each node test align with the operator's definition opset version. [InstanceNormalization](https://github.com/onnx/onnx/blob/main/docs/Operators.md#InstanceNormalization) has never changed since opset6, so that they make this node test of opset 6.

We don't want to modify onnx test data so I think we can create an op test for InstanceNormalization with the opset version we want.

**Comment by qjia7** [comment]
@fs-eire @guschmue Please take a look. Currently, only optimized the NCHW InstanceNormalization. Will leave NHWC to @dakenf. Thanks.

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
