### PR TITLE
add dependency 'cub' as submodule

### PR DESCRIPTION
**Pull request by fs-eire**
**Description**: Add dependency `cub` as submodule

**Motivation and Context**
- Add `cub` as kernels like `TopK` and `NonMaxSuppression` use it.

### CODE REVIEW

**Comment by pranavsharma** [comment]
Please update cgmanifest.json and third party notices file as well.

**Comment by snnn** [comment]
The third party notices file update can be done after this PR get merged.

**Comment by pranavsharma** [comment]
Also, I thought we're going away from adding additional submodules. @jywu-msft ? (reference https://github.com/microsoft/onnxruntime/issues/1601#issuecomment-520280320)

**Comment by jywu-msft** [comment]
Do we have to add yet another git submodule?
especially as these are all optional build dependencies. It already takes more than 2 minutes to clone the repo already. 
Can we not use cmake external project?

**Comment by pranavsharma** [comment]
> The third party notices file update can be done after this PR get merged.

I would prefer that these are updated as part of this PR itself, it's better to keep track this way.

**Comment by snnn** [comment]
If it's a  cmake external project, I need to download it multiple times every day. And it's very hard to keep the compiler flags consistent across projects. We haven't solve the problem yet.

**Comment by jywu-msft** [comment]
> If it's a cmake external project, I need to download it multiple times every day. And it's very hard to keep the compiler flags consistent across projects. We haven't solved the problem yet.

it wouldn't even include the cmake files (and thus download anything) for optional build dependencies. 
maybe this mostly applies to the submodules DNNlibrary and grpc. Those submodules pull in many other dependent submodules.
Most people aren't building android or onnxruntime server - probably they would be good candidates to be made cmake external projects.

**Comment by snnn** [comment]
> > If it's a cmake external project, I need to download it multiple times every day. And it's very hard to keep the compiler flags consistent across projects. We haven't solved the problem yet.
> 
> it wouldn't even include the cmake files (and thus download anything) for optional build dependencies.
> maybe this mostly applies to the submodules DNNlibrary and grpc. Those submodules pull in many other dependent submodules.
> Most people aren't building android or onnxruntime server - probably they would be good candidates to be made cmake external projects.

Both options have pros and cons,  I'm not against taking grpc away.  For this PR, as long as it works, I feel it is fine.

**Comment by fs-eire** [comment]
> Please update cgmanifest.json and third party notices file as well.

Files updated in latest commit

**Pull request merged**
