### PR TITLE
added miopenGetConvolutionSpatialDim if ROCm5.5

### PR DESCRIPTION
**Pull request by zstreet87**
### Description
MIOpen created a new API to get the spatial dimensions.

### Motivation and Context
Will eventually be able to delete the workaround.

### CODE REVIEW

**Comment by jeffdaily** [comment]
@cloudhan are you able to review or assign a reviewer?

**Review by cloudhan — APPROVED** [review]

**Comment by cloudhan** [comment]
@zstreet87 `black` think it should format a python file. You need to rebase to avoid that file block your merge.

**Comment by zstreet87** [comment]
@cloudhan I don't understand what you mean.  It looks like `psf` tries to issue `black` and says `75 files would be reformatted, 551 files would be left unchanged`.  How am I suppose to handle this?

**Review by cloudhan — APPROVED** [review]

**Pull request merged**
