### PR TITLE
[FIX] register softmaxgrad_13/logsoftmaxgrad_13 for rocm

### PR DESCRIPTION
**Pull request by PeixuanZuo**
**Description**: 
1. register SoftmaxGrad_13 and logSoftmaxGrad_13 for rocm.

**Motivation and Context**
- Why is this change required? What problem does it solve?
when the opset version update to the 14, some kernels used in models not register for rocm and run on CPU, it may bring a lot of memcpy operators and make the ort training slow.
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by pengwa — COMMENTED** [review]
do we have unit test for ROCM LogSoftmaxGrad_13?

**Review by weixingzhang — DISMISSED** [review]

**Comment by weixingzhang** [comment]
AMD CI failed with two UTs below. Can you take a look?

[  FAILED  ] GradientCheckerTest.SoftMaxGrad
[  FAILED  ] GradientCheckerTest.LogSoftMaxGrad

**Comment by PeixuanZuo** [comment]
> do we have unit test for ROCM LogSoftmaxGrad_13?

1.orttraining/orttraining/test/gradient/gradient_ops_test.cc has unit test for gradient ops include SoftmaxGrad(13) and LogSoftmaxGrad(13).
2.orttraining/orttraining/test/training_ops/cuda/softmax_test.cc has unit test for Softmax ops, i add SoftmaxGrad_13 and LogSoftmaxGrad_13 unit test in this file.

**Comment by weixingzhang** [comment]
> > do we have unit test for ROCM LogSoftmaxGrad_13?
> 
> 1.orttraining/orttraining/test/gradient/gradient_ops_test.cc has unit test for gradient ops include SoftmaxGrad(13) and LogSoftmaxGrad(13). 2.orttraining/orttraining/test/training_ops/cuda/softmax_test.cc has unit test for Softmax ops, i add SoftmaxGrad_13 and LogSoftmaxGrad_13 unit test in this file.

Usually, CUDA UTs can be leveraged for ROCm.

**Review by weixingzhang — APPROVED** [review]

**Review by pengwa — APPROVED** [review]

**Pull request merged**
