### PR TITLE
DNNL 1.1

### PR DESCRIPTION
**Pull request by sreekanth-yalachigere**
Removed unused DNNL CMAKE parameters.
Deleted unused MKL-DNN patch

### CODE REVIEW

**Comment by snnn** [comment]
BTW, I'm seeing crashes in the onnx_test_runner model tests, in master branch.

**Comment by sreekanth-yalachigere** [comment]
> BTW, I'm seeing crashes in the onnx_test_runner model tests, in master branch.

`build.py: error: unrecognized arguments: --use_mkldnn --build_java
`

I don't see --use_mkldnn and --build_java in file https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py

I searched the entire repo. Couldn't find these arguments 
I

**Comment by snnn** [comment]
Please ignore the java build. It doesn't work yet.

**Pull request merged**
