### PR TITLE
[js/web] JSEP Gemm for opset 13

### PR DESCRIPTION
**Pull request by dakenf**
### Description
Added JSEP Gemm registration for opset 13. It was falling back to CPU provider as CPU has it for 13

### CODE REVIEW

**Review by guschmue — APPROVED** [review]

**Comment by guschmue** [comment]
can you run ```npm run build:doc``` to make the ci pipeline happy ?

**Comment by guschmue** [comment]
CI pipeline is nagging about doc update. ```npm run build:doc``` should fix it.

**Comment by dakenf** [comment]
> CI pipeline is nagging about doc update. `npm run build:doc` should fix it.

Done. However it did some unrelated changes but that could be because of some previous merge conflicts.
Do you have a doc with a checklist before contributing so I won't forget to do stuff like that?

**Comment by guschmue** [comment]
we can come up with a checklist and we are also changing the CI to run these kinds of checks much earlier.

**Review by satyajandhyala — APPROVED** [review]

**Pull request merged**
