### PR TITLE
[Java] Tidying up the sample MNIST code

### PR DESCRIPTION
**Pull request by Craigacp**
**Description**:
This changes the sample `ScoreMNIST` code so it loads MNIST from a libsvm format file, rather than a preprocessed Java serialized object which was hard to create. It also adds a couple of small onnx models, a CNN trained in pytorch and a logistic regression trained in scikit-learn for use with the sample code. This is mainly to show how to unpack the different output formats on the Java side.

### CODE REVIEW

**Comment by Craigacp** [comment]
Ooops, the spotless check failed. I've fixed it.

**Comment by Craigacp** [comment]
Looks like the CI got hit by this - https://github.com/microsoft/onnxruntime/pull/3761, do I need to rebase on master to get around it or is there some other way?

**Comment by yuslepukhin** [comment]
Currently, the build process symlinks native libraries from under build\Windows\<config>\java. The target of the link is a *.dll file but the link name is *.lib. Can you, please, fix it?

**Comment by Craigacp** [comment]
Way ahead of you, that's in this PR - https://github.com/microsoft/onnxruntime/pull/3659

**Comment by yuslepukhin** [comment]
Thanks, Adam! I spent all this time debugging gradle. It would not work unless I install gradle.exe shim from Chocolatey. It would be greate to get rid of it. Gradle daemon also creates megabytes of logs both in the build directory and in the home folder.

---
In reply to: [622550264](https://github.com/microsoft/onnxruntime/pull/3598#issuecomment-622550264) [](ancestors = 622550264)

**Comment by yuslepukhin** [comment]
I think I know why the builds are hanging. I just reproed it locally. After gradle build portion comlpetes, the java process never termnates so MSBuild from Cmake is waiting on it indefinitely.

---
In reply to: [622605488](https://github.com/microsoft/onnxruntime/pull/3598#issuecomment-622605488) [](ancestors = 622605488,622550264)

**Comment by yuslepukhin** [comment]
Build hangs.

image

Bc java gradle process never terminates:

image

**Comment by yuslepukhin** [comment]
After I kill Gradle daemon (java.exe) the build continues until it runs the tests, then it hangs again for the same reason. In other words, MSBuild is waiting on it to complete but it is a daemon and never terminates.

---
In reply to: [622607698](https://github.com/microsoft/onnxruntime/pull/3598#issuecomment-622607698) [](ancestors = 622607698,622605488,622550264)

**Comment by yuslepukhin** [comment]
It actually happens 3 times. By the time tests are about to run it displays this message:
 Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be reused, use --status for details
Then runs the tests (all of which fail locally to load the OrtEnvironment class) and then it hangs again.

---
In reply to: [622613168](https://github.com/microsoft/onnxruntime/pull/3598#issuecomment-622613168) [](ancestors = 622613168,622607698,622605488,622550264)

**Comment by yuslepukhin** [comment]
Disabling gradle daemon helps.

---
In reply to: [622616091](https://github.com/microsoft/onnxruntime/pull/3598#issuecomment-622616091) [](ancestors = 622616091,622613168,622607698,622605488,622550264)

**Comment by Craigacp** [comment]
Ok, so it's purely a CI issue? PR #3761 builds fine for me on Windows 10 using the Visual Studio 16 2019 generator, bar an issue with the tests calling the wrong gradle (which I think is a misconfiguration on my machine). The tests execute just fine if you run gradle from the command line, and the main cmake build manages to execute gradle multiple times while building the jar files.

**Comment by yuslepukhin** [comment]
Faith, I have created a rebased version of this PR: https://github.com/microsoft/onnxruntime/pull/3824

> 
> 
> /azp run Linux CPU CI Pipeline,Linux GPU CI Pipeline,Linux GPU TensorRT CI Pipeline,MacOS CI Pipeline,Windows GPU CI Pipeline,Windows GPU TensorRT CI Pipeline,MacOS NoContribops CI Pipeline,Linux CPU x64 NoContribops CI Pipeline,Windows CPU CI Pipeline

**Comment by Craigacp** [comment]
Fixed by #3824

**Pull request closed without merging**
