### PR TITLE
Revert "[java] Changes OrtEnvironment so it can't be closed by users"

### PR DESCRIPTION
**Pull request by pranavsharma**
Reverts microsoft/onnxruntime#10670 as this is causing the pipelines to slow down significantly blocking upcoming release.

### CODE REVIEW

**Comment by yuslepukhin** [comment]
Cc: @Craigacp

**Comment by Craigacp** [comment]
Ok, I changed how the tests run in that PR, I can unpick just that today.

**Comment by Craigacp** [comment]
If you revert this I think you'll need to revert #10200 as well, because it's a necessary fix for the Java tests to pass after #10200.

**Comment by faxu** [comment]
@craigacp any estimate when this will be ready? We're in the process of cutting the release branch and need to address this issue to validate release pipelines.

**Comment by Craigacp** [comment]
See #10811.

**Comment by pranavsharma** [comment]
Adam has provided a fix so this is not needed any more.

**Pull request closed without merging**
