### PR TITLE
Bump up onnx version

### PR DESCRIPTION
**Pull request by raymondxyang**
Bump up onnx version to take fix for OCR model

### CODE REVIEW

**Comment by raymondxyang** [comment]
my bad.. forgot to update other script..

**Comment by pranavsharma** [comment]
Since this fix is important for the OCR team, let's do this for the 0.4 rel branch as well.

**Comment by pranavsharma** [comment]
A bunch of other scripts need to be updated as well. See [this](https://github.com/Microsoft/onnxruntime/commit/1f066d4dc4d35658433bdd7ad0c8f04c79e5a4e6) as example.

**Comment by pranavsharma** [comment]
> A bunch of other scripts need to be updated as well. See [this](https://github.com/Microsoft/onnxruntime/commit/1f066d4dc4d35658433bdd7ad0c8f04c79e5a4e6) as example.

@snn @raymondxyang are other files not required any more to bump up onnx version?

**Comment by pranavsharma** [comment]
> > A bunch of other scripts need to be updated as well. See [this](https://github.com/Microsoft/onnxruntime/commit/1f066d4dc4d35658433bdd7ad0c8f04c79e5a4e6) as example.
> 
> @snn @raymondxyang are other files not required any more to bump up onnx version?

Ah, I see a follow up PR for this.

**Pull request merged**
