### PR TITLE
Add missing Python dependencies for ORT training

### PR DESCRIPTION
**Pull request by KeDengMS**
cerberus - option parsing
h5py - checkpoint
onnx - model proto
packaging/sympy - symbolic shape inference

### CODE REVIEW

**Comment by snnn** [comment]
There was a debate whether onnxruntime python package should depend on onnx python package.  From the changelog you can see it was added then removed. cerberus is similar.

**Comment by KeDengMS** [comment]
> There was a debate whether onnxruntime python package should depend on onnx python package. From the changelog you can see it was added then removed. cerberus is similar.

The problem is that after installing the nightly build, the package is not usable and all these dependencies are needed to get it working. For a first time user, this is a bad first impression IMO.

**Comment by thiagocrepaldi** [comment]
> There was a debate whether onnxruntime python package should depend on onnx python package. From the changelog you can see it was added then removed. cerberus is similar.

cerberus is needed by ORTTrainer (onnxruntime training) in runtime

Are we going to have a single wheel package for training and inferencing or they will be different packages? In the latter case, we need to split requirements.txt to dont mix dependencies

**Review by thiagocrepaldi — COMMENTED** [review]
Are we going to have a single wheel package for training and inferencing or they will be different packages? In the latter case, we need to split requirements.txt to dont mix dependencies

**Comment by snnn** [comment]
> Are we going to have a single wheel package for training and inferencing or they will be different packages? In the latter case, we need to split requirements.txt to dont mix dependencies

There is no plan to merge them yet, at least not for the next release.

**Comment by snnn** [comment]
> However, that does not address the dependency on onnx.

George and Pranav had concerns on this. Please see the discussions in #4073.  I had added onnx there, then Prabhat Roy removed it. But things are changing. So I'd to know what they think now.

**Comment by thiagocrepaldi** [comment]
> > However, that does not address the dependency on onnx.
> 
> George and Pranav had concerns on this. Please see the discussions in #4073. I had added onnx there, then Prabhat Roy removed it. But things are changing. So I'd to know what they think now.

This discussion is about doing *Inference* without ONNX, but *Training* frontend did take this dependency

**Comment by jywu-msft** [comment]
> > > However, that does not address the dependency on onnx.
> > 
> > 
> > George and Pranav had concerns on this. Please see the discussions in #4073. I had added onnx there, then Prabhat Roy removed it. But things are changing. So I'd to know what they think now.
> 
> This discussion is about doing _Inference_ without ONNX, but _Training_ frontend did take this dependency

yes, it's not needed for inference, so ideally we don't have it as a dependency per discussions from 4073.
can we have separate requirements files for training and inference since the packages are separate?

**Comment by KeDengMS** [comment]
> > > > However, that does not address the dependency on onnx.
> > > 
> > > 
> > > George and Pranav had concerns on this. Please see the discussions in #4073. I had added onnx there, then Prabhat Roy removed it. But things are changing. So I'd to know what they think now.
> > 
> > 
> > This discussion is about doing _Inference_ without ONNX, but _Training_ frontend did take this dependency
> 
> yes, it's not needed for inference, so ideally we don't have it as a dependency per discussions from 4073.
> can we have separate requirements files for training and inference since the packages are separate?

Sure, separated the requirements.txt and requirements-training.txt

**Review by thiagocrepaldi — APPROVED** [review]
LGTM.
@snnn what do you think?

**Review by snnn — APPROVED** [review]
Thank you

**Pull request merged**
