### PR TITLE
Use CUDA libraries found by CMake.

### PR DESCRIPTION
**Pull request by xkszltl**
Resolve undefined symbols on CentOS due to missing cudart.

Question:
For CUDNN, why using shared lib on Win but .a on Linux?

### CODE REVIEW

**Comment by xkszltl** [comment]
Hi ort team!

The CI build error might be related to a compatibility issue between early version of cmake and CUDA 10.
If that's the case, could you update cmake in build agent?

**Comment by HectorSVC** [comment]
> Hi ort team!
> 
> The CI build error might be related to a compatibility issue between early version of cmake and CUDA 10.
> If that's the case, could you update cmake in build agent?

We are using docker for the build on Linux.  For Linux GPU build, the cmake is specified https://github.com/Microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/scripts/install_deps.sh

**Comment by xkszltl** [comment]
@HectorSVC Thanks for the docker script, that's really helpful.
There's a bug in cmake 3.12.1, could you update the cmake in this script to latest?

Here's the fix: [https://blog.kitware.com/cmake-3-12-2-available-for-download/](https://blog.kitware.com/cmake-3-12-2-available-for-download/)
```
FindCUDA: Do not find cublas_device on CUDA >= 9.2
```

**Comment by xkszltl** [comment]
BTW the current latest is `3.13.2`

**Comment by snnn** [comment]
> Question:
> For CUDNN, why using shared lib on Win but .a on Linux?

We are fixing this mismatch.  #239

**Comment by xkszltl** [comment]
Added fix for dll delay loading

**Comment by xkszltl** [comment]
Conflict resolved.

**Pull request merged**
