### PR TITLE
[CANN] Multi-stream execution support for CANN EP.

### PR DESCRIPTION
**Pull request by FFFrog**
### Description
**Multi-stream** execution support for **CANN EP**.

### Motivation and Context
**CANN EP** is currently **unavailable** due to the introduction of a new mechanism for multi-stream execution [#13495](https://github.com/microsoft/onnxruntime/pull/13495), the deletion of the Fence-based synchronization mechanism, and the failure to update the relevant logic of **CANN EP** synchronously.

This PR is to fix it.

### CODE REVIEW

**Comment by FFFrog** [comment]
@jywu-msft Hi, sorry to @ you again. could you please take a look at this PR？Thanks a lot.

**Comment by jywu-msft** [comment]
+@jslhcl, @souptc can you help review the stream api usage?

**Comment by FFFrog** [comment]
@jslhcl, @souptc, Could you please review this PR?
Thank you.

**Comment by FFFrog** [comment]
@jywu-msft, @jslhcl, @souptc could you please help review this PR? we also have some other features ready and wait to submit.

Thanks a lot.

**Comment by jywu-msft** [comment]
sorry for the delay. looks good to me.

**Pull request merged**
