### PR TITLE
Add Gemm op to DNNL Exectution provider

### PR DESCRIPTION
**Pull request by georgen117**
**Description**:
This adds the Gemm op to the DNNL Execution provider

With the addition of the Gemm op that uses the DNNL endpoint the KernelRegistry was deleted. The only Op that was in the KernelRegistry was Gemm and the implementation was not using DNNL.

With Gemm now implemented the old Gemm code was deleted. The act of deleting the KernelRegistry exposed a bug in the Training unit tests for execution providers without a KernelRegistry.  We added a fix for this that mirrors the same way it is handled in the non-training unit tests.

Now the Training ops run without needing to manually specify the DnnlExecutionProvider.  We were able to remove several instances `#ifdef USE_DNNL` from the graident_op_test.cc code. The one exception being the ConvGrad unit test.

Added two new tests one that only modifies the `alpha` attribute of Gemm another that only modified the `beta` attribute of Gemm.  This enabled figuring out which of the two attributes caused an issue.

Fix a few other bugs discovered while working on the Gemm op. 
- In some situations the DNNL subgraph code could produce a subgraph with two outputs with the same name generating an invalid graph. (Discovered when running the GlobalAveragePoolGrad unit test) **fixed**
- For dynamic shaped graphs the DNNL implementation GlobalAveragePool and GlobalMaxPool could crash. (Discovered when running the GlobalAveragePoolGrad unit test) **fixed**

**Motivation and Context**
- Why is this change required?
This adds Gemm op to the DNNL execution provider
-  What problem does it solve?
Expands the number of operations supported by DNNL execution provider

### CODE REVIEW

**Comment by georgen117** [comment]
@snnn can you please also run `/azp run Linux DNNL CI Pipeline` since this is the only pipeline to my knowledge that enables the dnnl ep.

**Comment by snnn** [comment]
Next week, George's team will help review this.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
