### PR TITLE
[WebNN EP] Support subgraph of the control flow nodes

### PR DESCRIPTION
**Pull request by Honry**
This PR also makes some processing on the subgraph's initializers. The subgraph doesn't contain all its required initializers, some common initializers are stored in its ancestor graphs. We need to collect all required initializers and re-map to the subgraph.

### CODE REVIEW

**Comment by Honry** [comment]
@fdwr, @guschmue, merry Christmas! PTAL when you are back. :)  Thanks!

**Review by guschmue — APPROVED** [review]

**Review by fdwr — APPROVED** [review]

**Comment by fdwr** [comment]
I'm guessing this is for the merged models with encoder/decoder and an `if` node.

**Pull request merged**
