### PR TITLE
remove option --enable_lto

### PR DESCRIPTION
**Pull request by HectorSVC**
remove build option --enable_lto which could cause python GPU build failed randomly

### CODE REVIEW

**Comment by jywu-msft** [comment]
thanks for debugging this!

**Comment by snnn** [comment]
Could you please provide more information? If you disable it, binary size will increase a lot.

**Comment by jywu-msft** [comment]
> Could you please provide more information? If you disable it, binary size will increase a lot.

seems like the CI is still failing with similar type of CUDA/CUDNN error even with it disabled.

**Comment by HectorSVC** [comment]
> Could you please provide more information? If you disable it, binary size will increase a lot.

I didn't see the binary size increase, the whl is 34MB, but I do find some clue on the box.

**Comment by snnn** [comment]
Please remove it from CI as well. (If you're sure it is the culprit)

**Comment by HectorSVC** [comment]
> Please remove it from CI as well. (If you're sure it is the culprit)

Let's monitor it several days to get more confidence.

**Comment by snnn** [comment]
But Linux build has the similar issue

**Pull request merged**
