### PR TITLE
build wasm with linux

### PR DESCRIPTION
**Pull request by mszhanyi**
### Description
Make all build_wasm tasks (NPM packaging and post merge)run on Linux.
Enable web gpu test in npm package pipeline too.

### Motivation and Context
Even on Windows, build_wasm is running in cygwin.
So, it could save a lot of time to run it on Linux.

### CODE REVIEW

**Comment by fs-eire** [comment]
will we remove the file win-wasm-ci.yml as the next step?

**Comment by mszhanyi** [comment]
> will we remove the file win-wasm-ci.yml as the next step?

Yes. Do you want to keep it?

**Comment by mszhanyi** [comment]
@snnn @fs-eire

**Comment by fs-eire** [comment]
> > will we remove the file win-wasm-ci.yml as the next step?
> 
> Yes. Do you want to keep it?

I think I have one reason for keeping it and another one reason for not keeping it.
To keep it and use it in CI - helps to make sure ORT web can build from windows (otherwise a PR may brake ort-web build on windows and the CI will not know it
To remove it - helps to reduce the maintenance cost as well as the risk of inconsistency of the build steps between win/linux 

@snnn what do you think?

**Comment by snnn** [comment]
If the file is not used anywhere, we need to remove it from our source tree. Because we often refactor the build pipelines, an unused yaml file could quick be broken.  I suggest having this change first. Then the next time when the Windows build has any trouble we sit down together and discuss what's the best way to prevent such.  We may still need a win-wasm-ci.yml but it doesn't need to have so many steps as what is now.

**Review by snnn — APPROVED** [review]

**Pull request merged**
