### PR TITLE
Replaced spaces on tabs

### PR DESCRIPTION
**Pull request by kuznetsov-m**
Just fix document formatting.

### CODE REVIEW

**Comment by snnn** [comment]
HI @kuznetsov-m , could you please merge your branch with the latest master?

**Comment by kuznetsov-m** [comment]
@snnn, done. Check it out please.

**Comment by kuznetsov-m** [comment]
@snnn, could I help you with something else to accept this pull-quest?

**Comment by snnn** [comment]
Thank you!

**Pull request merged**
