### PR TITLE
[VitisAI] Vitis ai ep support dynamic options

### PR DESCRIPTION
**Pull request by danyue333**
### Description
relate to #22282. Let Vitis ai ep handles dynamic_options

### CODE REVIEW

**Comment by danyue333** [comment]
@microsoft-github-policy-service agree [company="AMD"]

**Comment by danyue333** [comment]
@microsoft-github-policy-service agree company="AMD"

**Comment by danyue333** [comment]
Hi @jywu-msft , Can you please review this PR?

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
