### PR TITLE
[JS/Web]Adding support for WebGL v1

### PR DESCRIPTION
**Pull request by duli2012**
**Description**: Describe your changes.
Adding support for WebGL v1

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by fs-eire** [comment]
https://github.com/microsoft/onnxruntime/blob/e668d3490ae1243555d071d91700d446657e05af/js/web/test/test-runner.ts#L437
should remove

**Comment by duli2012** [comment]
> https://github.com/microsoft/onnxruntime/blob/e668d3490ae1243555d071d91700d446657e05af/js/web/test/test-runner.ts#L437
> 
> 
> should remove
Good catch. removed and tested with Safari 14.

**Comment by fs-eire** [comment]
realized just now: we need also modify the section "Compatibility" in README.md

**Comment by duli2012** [comment]
> realized just now: we need also modify the section "Compatibility" in README.md
> 
> add 'webgl' for macOS

Updated.

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
