### PR TITLE
[WebNN] Add ScatterElements and GatherElements

### PR DESCRIPTION
**Pull request by shiyi9801**

### CODE REVIEW

**Comment by shiyi9801** [comment]
This PR is based on the gatherND/scatterND PR, will rebase after its merged. @Honry Please take a look, thanks!

**Review by Honry — APPROVED** [review]
LGTM, thanks!

**Comment by shiyi9801** [comment]
@fdwr @guschmue PTAL, thanks!

**Review by fdwr — APPROVED** [review]
👍

**Pull request merged**
