### PR TITLE
[js/webgpu] Add activation for conv3d naive

### PR DESCRIPTION
**Pull request by axinging**

### CODE REVIEW

**Comment by axinging** [comment]
@fs-eire @guschmue, PTAL

@qjia7 @xhcao @hujiajie @jzm-intel @gyagp

**Comment by guschmue** [comment]
it wants you to run ```npm run format```

**Comment by axinging** [comment]
> it wants you to run `npm run format`
Thanks @guschmue. When I first upload this file, it failed even after I run npm run format.

npm run format is done, not sure if this will pass the bots.
```
-            isChannelsLast ? getElementAt('uniforms.x_shape', 1, x.rank) : getElementAt('uniforms.x_shape', 2, x.rank)};
+            isChannelsLast ? getElementAt('uniforms.x_shape', 1, x.rank) :
+                             getElementAt('uniforms.x_shape', 2, x.rank)};
               let xShapeZ = ${
-            isChannelsLast ? getElementAt('uniforms.x_shape', 2, x.rank) : getElementAt('uniforms.x_shape', 3, x.rank)};
+            isChannelsLast ? getElementAt('uniforms.x_shape', 2, x.rank) :
+                             getElementAt('uniforms.x_shape', 3, x.rank)};
               let xShapeW = ${
-            isChannelsLast ? getElementAt('uniforms.x_shape', 3, x.rank) : getElementAt('uniforms.x_shape', 4, x.rank)};
+            isChannelsLast ? getElementAt('uniforms.x_shape', 3, x.rank) :
+                             getElementAt('uniforms.x_shape', 4, x.rank)};
               let xShapeU = ${
-            isChannelsLast ? getElementAt('uniforms.x_shape', 4, x.rank) : getElementAt('uniforms.x_shape', 1, x.rank)};
+            isChannelsLast ? getElementAt('uniforms.x_shape', 4, x.rank) :
+                             getElementAt('uniforms.x_shape', 1, x.rank)};
               let inputDepthNearestVec4 = (xShapeU / 4) * 4;
               let inputDepthVec4Remainder = xShapeU % 4;

```

**Review by guschmue — APPROVED** [review]

**Pull request merged**
