### PR TITLE
Support ORT WASM compilation with the training flag

### PR DESCRIPTION
**Pull request by baijumeswani**
Building ort wasm with the training flag errors out because of two problems:
1. Eigen includes were not wrapped around https://github.com/microsoft/onnxruntime/issues/10852
2. `tensorboard` linker errors.

This pull request solves the above two problems.

### CODE REVIEW

**Review by hanbitmyths — COMMENTED** [review]
Just wondering if there are any any scenarios where for wasm with training. I remember there was one request to enable training ops in wasm.

Do you have unit tests to validate whether wasm with a training flag is working correctly or not? Do you think that adding 'build wasm with training flag' into web ci pipeline is good to have?

**Comment by baijumeswani** [comment]
We are trying to support some teams that would like to perform training through javascript for different on-device training scenarios. This is the first step into supporting this exploratory work.

> Do you have unit tests to validate whether wasm with a training flag is working correctly or not? Do you think that adding 'build wasm with training flag' into web ci pipeline is good to have?

I think we should definitely have a pipeline validating the training flag with wasm config for compilation. But I feel that we could introduce this once we have a concrete training solution for wasm. For now, we just want to explore building training ops with wasm for experimentation. Let me know what your thoughts are.

**Comment by askhade** [comment]
@hanbitmyths : This request came from @juharris . He is working on a tutorial on how to train pytorch model in javascript : [juharris/train-pytorch-in-js: Convert a PyTorch model to train it in JavaScript using ONNX Runtime Web (github.com)](https://github.com/juharris/train-pytorch-in-js) and was running into build issues. I don't think this warrants a whole new CI pipeline.

**Comment by juharris** [comment]
Building with training operations enable for WASM used to work. So a CI pipeline or at least tests to make sure this keeps working would be great. Ideally, I'd love to get a build published to npm but I understand if that's too much to ask right now.

**Review by hanbitmyths — APPROVED** [review]

**Pull request merged**
