### PR TITLE
Remove nGraph Execution Provider

### PR DESCRIPTION
**Pull request by smkarlap**
**Description**: Remove all code and documentation for nGraph Execution Provider

**Motivation and Context**
- Pursuant to nGraph deprecation notice: https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/nGraph-ExecutionProvider.md#deprecation-notice

**Deprecation Notice**

| | |
| --- | --- |
| Deprecation Begins	| June 1, 2020 |
| Removal Date |	December 1, 2020 |

Starting with the OpenVINO™ toolkit 2020.2 release, all of the features
previously available through nGraph have been merged into the OpenVINO™
toolkit. As a result, all the features previously available through
ONNX RT Execution Provider for nGraph have been merged with ONNX RT
Execution Provider for OpenVINO™ toolkit.

Therefore, ONNX RT Execution Provider for **nGraph** will be deprecated
starting June 1, 2020 and will be completely removed on December 1,
2020. Users are recommended to migrate to the ONNX RT Execution Provider
for OpenVINO™ toolkit as the unified solution for all AI inferencing on
Intel® hardware.

### CODE REVIEW

**Comment by Craigacp** [comment]
You need to remove some methods from the Java code as well.

- https://github.com/microsoft/onnxruntime/blob/master/java/src/main/java/ai/onnxruntime/OrtSession.java#L759
- https://github.com/microsoft/onnxruntime/blob/master/java/src/main/java/ai/onnxruntime/OrtSession.java#L898

**Comment by smkarlap** [comment]
Removed methods from Java code

**Comment by smkarlap** [comment]
resolved merge conflicts

**Review by HectorSVC — APPROVED** [review]

**Pull request merged**
