### PR TITLE
[VitisAI] optimize model clone

### PR DESCRIPTION
**Pull request by BoarQing**
### Description

Optimize the memory consumption for model_clone which is a crucial part of our model preparation

### Motivation and Context

This is curcial for meeting the requirement for Microsoft's 8.15 release.

### CODE REVIEW

**Comment by BoarQing** [comment]
> /azp run Windows ARM64 QNN CI Pipeline,Windows CPU CI Pipeline,Windows GPU CI Pipeline,Windows GPU TensorRT CI Pipeline,Windows x64 QNN CI Pipeline,onnxruntime-binary-size-checks-ci-pipeline,orttraining-linux-ci-pipeline,orttraining-linux-gpu-ci-pipeline,orttraining-ortmodule-distributed

Sorry, there is a bug we are still debugging. We will remove the draft state after we fix it.

**Comment by BoarQing** [comment]
@HectorSVC @jywu-msft  This is required for next release.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
