### PR TITLE
[MIGraphX EP] Add GroupNormalization and LayerNormalization Support

### PR DESCRIPTION
**Pull request by TedThemistokleous**
### Description

Need this to ensure we use GroupNormalization and LayerNormalization operators in MIGraphX

### Motivation and Context

Needed to add proper support and not reject models with these onnx operators.

### CODE REVIEW

**Comment by TedThemistokleous** [comment]
ping @tianleiwu need this to help with operator support. This already exists in MIGraphX but missing in the EP

**Review by tianleiwu — APPROVED** [review]

**Pull request merged**
