### PR TITLE
Add Python checks pipeline

### PR DESCRIPTION
**Pull request by edgchen1**
**Description**
This change adds a new pipeline for checking Python code. Currently this pipeline only runs flake8.
flake8 is also run as part of the CMake project builds, but if this proposed change is accepted we can remove that later.
The .flake8 config file was also updated to make it easier to run standalone (flake8 --config ./.flake8) and some Python formatting issues were addressed in files that were not previously scanned.

Build: https://dev.azure.com/onnxruntime/onnxruntime/_build?definitionId=164&_a=summary

**Motivation and Context**
Make it easier to run flake8 manually.
Reorganize and decouple flake8 run from C++ builds. In the future if we want to add more Python checks, e.g., type annotation checking, we can add to this pipeline.

### CODE REVIEW

**Comment by snnn** [comment]
I just found we forgot to review this PR and I deleted your pipeline because I thought it was not needed.

@edgchen1 Do you still want this change? I can help you review it. But please resolve the conflict.

**Review by snnn — APPROVED** [review]

**Review by thiagocrepaldi — APPROVED** [review]

**Comment by thiagocrepaldi** [comment]
do we have a plan for when will orttraining python frontend will be added to the pipeline?

**Comment by edgchen1** [comment]
> do we have a plan for when will orttraining python frontend will be added to the pipeline?

It would be great to do that. No plan that I'm aware of, but perhaps we can create a work item.

**Pull request merged**
