### PR TITLE
[OpenVINO-EP] UEP v3.1 Release with OpenVINO 2021.4.1

### PR DESCRIPTION
**Pull request by MaajidKhan**
**Description**: Making UEP compatible with the latest OpenVINO Update Version Release (OpenVINO 2021.4.1)

**Motivation and Context**
- Makes UEP compatible with latest OpenVINO 2021.4.1 Version
- Dockerfiles and Internal_CI pipelines files updated to latest package and have been validated.

### CODE REVIEW

**Comment by MaajidKhan** [comment]
The corresponding documentation PR:
https://github.com/microsoft/onnxruntime/pull/9084

**Review by oliviajain — APPROVED** [review]

**Pull request merged**
