### PR TITLE
[ORT 1.18.0 Release] Cherry pick 1st round

### PR DESCRIPTION
**Pull request by yihonglyu**
Kindly request the authors of the PRs to review the changes. If you have any questions, please let me know. If everything looks good, please approve the changes.

### CODE REVIEW

**Review by adrianlizarraga — APPROVED** [review]

**Review by edgchen1 — APPROVED** [review]
signing off on #20360 and #20509

**Review by skottmckay — DISMISSED** [review]

**Review by yf711 — APPROVED** [review]

**Comment by HectorSVC** [comment]
https://github.com/microsoft/onnxruntime/pull/20560 is missed?

**Review by jywu-msft — APPROVED** [review]

**Comment by Honry** [comment]
@yihonglyu, could you help revert this https://github.com/microsoft/onnxruntime/pull/20585/commits/804945e352e4accdd33bbba906fa70a46254d6f4 from your cherry pick list? We do not expect to have this commit in the ORT 1.18.0 release, thanks!

**Review by fs-eire — DISMISSED** [review]
Approved for js/web/README.md

**Comment by yihonglyu** [comment]
> #20560 is missed?

@HectorSVC  It would be in Cherry pick 2nd round

**Comment by yihonglyu** [comment]
> @yihonglyu, could you help revert this [804945e](https://github.com/microsoft/onnxruntime/commit/804945e352e4accdd33bbba906fa70a46254d6f4) from your cherry pick list? We do not expect to have this commit in the ORT 1.18.0 release, thanks!

@Honry Revert it and remove the label rel:1.18.0

**Comment by Honry** [comment]
> > @yihonglyu, could you help revert this [804945e](https://github.com/microsoft/onnxruntime/commit/804945e352e4accdd33bbba906fa70a46254d6f4) from your cherry pick list? We do not expect to have this commit in the ORT 1.18.0 release, thanks!
> 
> @Honry Revert it and remove the label rel:1.18.0

Thank you so much!

**Comment by chilo-ms** [comment]
@yihonglyu 
will this https://github.com/microsoft/onnxruntime/pull/20550 be in the 2nd round cherry pick?

**Review by jywu-msft — APPROVED** [review]

**Comment by yihonglyu** [comment]
> @yihonglyu will this #20550 be in the 2nd round cherry pick?

@chilo-ms , indeed. The PR will be included in the 2nd round of cherry-picking, unless it causes a failure in the validation or package pipeline.

**Review by guschmue — APPROVED** [review]

**Review by YUNQIUGUO — APPROVED** [review]
Approved for #20424

**Review by liqunfu — APPROVED** [review]

**Comment by liqunfu** [comment]
also need to cherry-pick this: https://github.com/microsoft/onnxruntime/pull/20482
maybe in next round?

**Review by yufenglee — APPROVED** [review]

**Pull request merged**
