### PR TITLE
[js/rn] Support create boolean tensor

### PR DESCRIPTION
**Pull request by hans00**
### Description

For some use case need to create boolean tensor.

I've tested on [this project](https://github.com/hans00/react-native-transformers-example)

### Motivation and Context

Add handle `ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL`

And it required #15556 (It seems not include in latest release (v1.15.1))

### CODE REVIEW

**Comment by YUNQIUGUO** [comment]
> And it required https://github.com/microsoft/onnxruntime/pull/15556 (It seems not include in latest release (v1.15.1))

Hi, fyi, if the change is not included in the latest released react native npm package, you can always try the dev version package.

**Comment by YUNQIUGUO** [comment]
Also, mind adding the test case for this newly added bool type here?

https://github.com/microsoft/onnxruntime/blob/c424e42594d92daba54f264c1c7409e53529d933/js/react_native/android/src/androidTest/java/ai/onnxruntime/reactnative/TensorHelperTest.java#L89-L115

**Comment by hans00** [comment]
> Hi, fyi, if the change is not included in the latest released react native npm package, you can always try the dev version package.

Umm.. the main problem is 
https://github.com/microsoft/onnxruntime/blob/0471f6fbb3aa1602cfc3d90e2daa8c190970869b/js/react_native/android/build.gradle#L234
here, it always use latest release on maven, so that I need manually build AAR like [this](https://github.com/hans00/react-native-transformers-example/tree/main/onnxruntime-patched).

And the derivative problem is when I downgrade version, it still use the latest Java library.

**Comment by hans00** [comment]
@microsoft-github-policy-service agree company="BRICKS"

**Comment by hans00** [comment]
@YUNQIUGUO @skottmckay @jchen351  
Can someone review this PR?

**Review by YUNQIUGUO — APPROVED** [review]

**Review by skottmckay — APPROVED** [review]

**Pull request merged**
