### PR TITLE
[Bug Fix] Missing CustomOp SchemaRegister when generator EPContext ONNX model

### PR DESCRIPTION
**Pull request by mingyueliuh**
### Description
Enhancements to EPContext Operations:
1.  Introduced support for the bfloat16 data type in EPContext operations.
2.  Bug Fix: Missing Custom OP Schema Registration when generator EPContext ONNX model

### CODE REVIEW

**Comment by mingyueliuh** [comment]
@jywu-msft please take a look when you are available. Thanks.

**Comment by mingyueliuh** [comment]
@jywu-msft Could you help review this PR . Thanks.

**Review by HectorSVC — DISMISSED** [review]

**Comment by jywu-msft** [comment]
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1574765&view=logs&j=7f366e99-16b2-52cc-e1ff-653af284e397&t=5c9cf234-f957-5fdc-9c37-89899bf73c0c
i think ContribOperators.md needs to be updated too

**Comment by HectorSVC** [comment]
> https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1574765&view=logs&j=7f366e99-16b2-52cc-e1ff-653af284e397&t=5c9cf234-f957-5fdc-9c37-89899bf73c0c i think ContribOperators.md needs to be updated too +@HectorSVC

good catch. I pushed a commit to fix that.

**Review by HectorSVC — APPROVED** [review]

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
