### PR TITLE
Make argmin/armax support identical data types and add int64 support

### PR DESCRIPTION
**Pull request by cbourjau**
### Description
This PR adds further `int64` kernels for `ArgMin` and `ArgMax`. Furthermore, this PR adds `int8` and `uint8` kernels to `ArgMin` to keep the coverage between the two equivalent.

### Motivation and Context
We ran into the missing kernels in [ndonnx](https://github.com/Quantco/ndonnx). Especially the int64 data type support is important for us since int64 is a common default when working with NumPy/array API code.

### CODE REVIEW

**Comment by cbourjau** [comment]
@baijumeswani might you be in a position to review this?

**Comment by cbourjau** [comment]
@pranavsharma Could you maybe give this a review and/or trigger the CI?

**Comment by cbourjau** [comment]
@xadupre Since you are also close by in the git-blame: Might you have time take a look at this PR, please?

**Comment by cbourjau** [comment]
@skottmckay might you be in a position to give this a review or to recommend a reviewer?

**Review by xadupre — DISMISSED** [review]

**Comment by cbourjau** [comment]
Thanks for the approval @xadupre ! Could you also trigger the CI or do you not have the permissions to do so?

**Comment by cbourjau** [comment]
@baijumeswani I'm not quite sure what the issue with the CI was. It passes locally for me on MacOS. Could you maybe trigger it again, please? I just merged in the latest `main`.

**Comment by baijumeswani** [comment]
[cbourjau](https://github.com/cbourjau) some unit tests are failing. Example failure:

```
1: [ RUN      ] ReductionOpTest.ArgMin_uint8
1: 2024-09-16 20:44:31.5490080 [W:onnxruntime:Default, tensorrt_execution_provider.cc:2586 onnxruntime::TensorrtExecutionProvider::GetCapability] [TensorRT EP] No graph will run on TensorRT execution provider
1: D:\a\_work\1\s\onnxruntime\test\providers\base_tester.cc(317): error: Expected equality of these values:
1:   expect_result
1:     Which is: 4-byte object <00-00 00-00>
1:   ExpectResult::kExpectFailure
1:     Which is: 4-byte object <01-00 00-00>
1: Initialize failed but expected success: Could not find an implementation for ArgMin(1) node with name 'node1'
1: Google Test trace:
1: D:\a\_work\1\s\onnxruntime\test\providers\base_tester.cc(827): registered execution providers: TensorrtExecutionProvider
1: Stack trace:
1:   00007FF7B29C80E9: (unknown)
1:   00007FF7B29CA3F4: (unknown)
1:   00007FF7B29C8FAE: (unknown)
1:   00007FF7B29C90E8: (unknown)
1:   00007FF7B2C3D449: (unknown)
1:   00007FF7B38D7992: (unknown)
1:   00007FF7B38D7856: (unknown)
1:   00007FF7B38FCED2: (unknown)
1:   00007FF7B38FCFF8: (unknown)
1:   00007FF7B38FD1A1: (unknown)
1: ... Google Test internal frames ...
1: 
1: [  FAILED  ] ReductionOpTest.ArgMin_uint8 (9 ms)
```

Could you please address the failures?

**Comment by cbourjau** [comment]
Apologies for the extra friction, @baijumeswani ! I didn't register the new kernels with the older opsets. Things should be fixed now. The tests correctly run through locally on osx-arm64.

**Review by baijumeswani — DISMISSED** [review]

**Comment by cbourjau** [comment]
I am now skipping the tests for int8 inputs on TensorRT. Unfortunately, I don't have the hardware to test it. Apologies for the additional iterations!

**Comment by baijumeswani** [comment]
> I am now skipping the tests for int8 inputs on TensorRT. Unfortunately, I don't have the hardware to test it. Apologies for the additional iterations!


@jywu-msft is it ok to skip these tests on tensorrt?

**Comment by jywu-msft** [comment]
> > I am now skipping the tests for int8 inputs on TensorRT. Unfortunately, I don't have the hardware to test it. Apologies for the additional iterations!
> 
> @jywu-msft is it ok to skip these tests on tensorrt?

OK. we will revisit the int8 test.

**Review by baijumeswani — APPROVED** [review]

**Comment by baijumeswani** [comment]
@cbourjau thank you for the contribution. Apologies for the delay in reviewing and merging. :)

**Pull request merged**
