### PR TITLE
Update nsync submodule

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

Update nsync submodule

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by pranavsharma** [comment]
What's the reason to upgrade? More stable version? More performant?

**Comment by snnn** [comment]
> What's the reason to upgrade? More stable version? More performant?

He fixed a few tiny compile warnings.

**Comment by pranavsharma** [comment]
> > What's the reason to upgrade? More stable version? More performant?
> 
> He fixed a few tiny compile warnings.

Hopefully it didn't have any effect on perf.

**Comment by snnn** [comment]
> Hopefully it didn't have any effect on perf.

It shouldn't. I'll monitor the daily perf report closely.

**Pull request merged**
