### PR TITLE
Update pybind11

### PR DESCRIPTION
**Pull request by snnn**
### Description
Upgrade pybind11 to the latest as suggested by @gnought in #21063

### Motivation and Context
Recently numpy released a new version, which caused compatibility issue between the latest numpy version and the latest ONNX Runtime version.

### CODE REVIEW

**Comment by jywu-msft** [comment]
this just adds the ability to build against numpy 2.0 right? 
but do we want to move to 2.0 ?  what about current users who are mostly on 1.x  , is there another PR to pin ORT deps to numpy < 2 ?

**Comment by snnn** [comment]
I think we can address the issues one by one. At least this change this safe and harmless.

**Comment by jywu-msft** [comment]
the windows cuda 12 pipeline is failing? : https://github.com/microsoft/onnxruntime/actions/runs/9555478951/job/26338802814?pr=21072#logs

it's complaining about using an unsupported host compiler
"C:\vss-agent\2.317.0\_work\onnxruntime\onnxruntime\cuda_sdk\v12.2\include\crt/host_config.h(164): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk. [D:\b\Debug\CMakeFiles\CMakeScratch\TryCompile-yv7iwa\cmTC_5ef87.vcxproj]"

is this related to the vc compiler upgrade that was mentioned previously?

**Comment by snnn** [comment]
Yes, Jian has a PR for that #21070

**Review by jchen351 — APPROVED** [review]

**Comment by pranavsharma** [comment]
Is this change backward compatible for ppl still on numpy < 2?

**Review by pranavsharma — APPROVED** [review]

**Comment by snnn** [comment]
This change only upgrades the pybind11 version. It does not change the numpy version or python version. So I think it should not cause any ABI level change, as we still use the same numpy ABI version.

**Comment by snnn** [comment]
I merged this PR, then I will build new packages and test how they would work. If it is not enough, we need to consider to upgrade numpy as well.

**Pull request merged**
