### PR TITLE
Add a flag to allow for linking against shared system protobuf

### PR DESCRIPTION
**Pull request by xhochy**
**Description**: 

In some environments you would like to link to the shared libprotobuf from the system. This is fine to use if you have full control over all protobuf users in your environment.

This need for the existence of this option is already mentioned as a comment in CMakeLists.txt, this adds it now.

Describe your changes.

**Motivation and Context**

We have packaged `onnxruntime` for conda-forge. There we prefer shared linkage and have a good control (and automation) to link everything to the same protobuf library and also rebuild everything on a protobuf update. This adds an option to `CMakeLists.txt` to allow us to use the shared library without us patching the source.

### CODE REVIEW

**Comment by snnn** [comment]
You can use the option: onnxruntime_PREFER_SYSTEM_LIB .

**Comment by xhochy** [comment]
I'm using `onnxruntime_PREFER_SYSTEM_LIB`, that's why I mainly run into this code path. Currently, this enforces static protobuf linkage but in certain situations.

**Comment by snnn** [comment]
Got it. How about this: instead of introducing a new build option, can you help me change:
```
      message(FATAL_ERROR "Please enable Protobuf_USE_STATIC_LIBS")
```
to a normal warning.  Then please adjust the text message accordingly.

**Review by snnn — APPROVED** [review]

**Comment by snnn** [comment]
Thank you! The change will be in our next release, which will be published in a few weeks. Then you can update your conda package to take it.

**Pull request merged**
