### PR TITLE
Adds int32_t and uint32_t clip kernels

### PR DESCRIPTION
**Pull request by adityagoel4512**
### Description
This adds support for int32_t and uint32_t clip operator, introduced in Opset 12. It also closes https://github.com/microsoft/onnxruntime/issues/15304.

### Motivation and Context
Closes https://github.com/microsoft/onnxruntime/issues/15304

### CODE REVIEW

**Comment by adityagoel4512** [comment]
> @adityagoel4512 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="QuantCo"

**Review by hariharans29 — DISMISSED** [review]

**Comment by hariharans29** [comment]
[docs_update.zip](https://github.com/microsoft/onnxruntime/files/11142744/docs_update.zip)

Can you please re-base with main and update the attached files in the docs/ folder. This is to reflect the newly added types. Once you do these, the failing pipelines should be fixed and we can merge this. Thanks!

**Comment by adityagoel4512** [comment]
> [docs_update.zip](https://github.com/microsoft/onnxruntime/files/11142744/docs_update.zip)
> 
> 
> 
> Can you please re-base with main and update the attached files in the `docs/` folder. This is to reflect the newly added types. Once you do these, the failing pipelines should be fixed and we can merge this. Thanks!

Should be done - thanks for the tip!

**Comment by adityagoel4512** [comment]
> [docs_update.zip](https://github.com/microsoft/onnxruntime/files/11142744/docs_update.zip)
> 
> Can you please re-base with main and update the attached files in the `docs/` folder. This is to reflect the newly added types. Once you do these, the failing pipelines should be fixed and we can merge this. Thanks!

Thanks for the tip about the docs! It looks likes the CI failures are identical to those on the main branch unfortunately.

**Pull request merged**
