### PR TITLE
GCC11/Libstdc++11 Compilation fixes 

### PR DESCRIPTION
**Pull request by ankurverma85**
Fixes bug # 7583

### CODE REVIEW

**Review by snnn — DISMISSED** [review]
LGTM.

**Comment by snnn** [comment]
How about this: you exclude the changes on cmake/CMakeLists.txt and let us merge the other changes first.  Then we handle the gtest issue separately.

**Comment by ankurverma85** [comment]
> For example, if we update our gtest version to the latest ,probably the warning will be gone. But I know there will be other issues.

Sounds good i'll revert back the cmake changes.
Also , Yes i can confirm . It goes away
I just wasnt sure how open you'll be to the prospect of moving to a non-release floating commit from a release commit of gtest

**Comment by snnn** [comment]
> I just wasnt sure how open you'll be to the prospect of moving to a non-release floating commit from a release commit of gtest

I think it's fine. We don't ship gtest.

**Pull request merged**
