### PR TITLE
Updated ORT Web API documentation

### PR DESCRIPTION
**Pull request by shalvamist**
### Description
Updated the documentation generated from the source code.

### CODE REVIEW

**Review by natke — COMMENTED** [review]
Is it possible to stage the docs?

**Comment by shalvamist** [comment]
Sure, I just issued a site rendering request. I will update as soon as it's ready.

**Comment by shalvamist** [comment]
Hey, the site is ready - please review - 
https://shalvamist.github.io/onnxruntime/

**Review by natke — COMMENTED** [review]
Looks good to me., although I have not used the API extensively

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
