### PR TITLE
Improving Runtime Error Messages for Operators

### PR DESCRIPTION
**Pull request by jeffsaremi**
This is a change to provide additional context such as Node type and Node name to Status messages generated during validation checks in Operator implementations.
The change will add type and name to the error messages already provided in the code.

### CODE REVIEW

**Comment by hariharans29** [comment]
LGTM - but overall this seems to expose node name and node type *when the status is getting created*. Why not just ad op type here - https://github.com/Microsoft/onnxruntime/blob/0bf12e9dbf7d5ba434dcaa8254a9495b9d3d7bd7/onnxruntime/core/framework/sequential_executor.cc#L121 ?

**Comment by jeffsaremi** [comment]
@hariharans29 
that's even a better suggestion. I might as well do that instead.
I'm going to close this PR, create a branch instead and resubmit subsequent to the inputs.

**Pull request closed without merging**
