### PR TITLE
Enable LTO for Android build

### PR DESCRIPTION
**Pull request by snnn**
### Description
Enable LTO for Android build, which can reduce binary size by 6%.

### CODE REVIEW

**Comment by edgchen1** [comment]
should we also enable this in a build that gets tested more? e.g., the actual package builds that will be published and CI builds.

**Comment by snnn** [comment]
> should we also enable this in a build that gets tested more? e.g., the actual package builds that will be published and CI builds.

Where should I modify?

**Comment by edgchen1** [comment]
> > should we also enable this in a build that gets tested more? e.g., the actual package builds that will be published and CI builds.
> 
> Where should I modify?

package build settings are here:

https://github.com/microsoft/onnxruntime/blob/f39ee14b46f7977e43c6cae3b8e8c56b968a7d98/tools/ci_build/github/android/default_full_aar_build_settings.json#L10-L19

https://github.com/microsoft/onnxruntime/blob/f39ee14b46f7977e43c6cae3b8e8c56b968a7d98/tools/ci_build/github/android/training_full_aar_build_settings.json#L10-L20

CI build is here:
https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/azure-pipelines/android-x86_64-crosscompile-ci-pipeline.yml

**Comment by snnn** [comment]
Updated.

**Comment by edgchen1** [comment]
one more place to update:
https://github.com/microsoft/onnxruntime/blob/b1a5afba6c535319a5c7ed002a7743c17965bf62/tools/ci_build/github/azure-pipelines/android-x86_64-crosscompile-ci-pipeline.yml#L87-L98

**Review by edgchen1 — APPROVED** [review]

**Review by mszhanyi — APPROVED** [review]

**Pull request merged**
