### PR TITLE
Update python 3.11 and remove 3.7 for Linux

### PR DESCRIPTION
**Pull request by jchen351**
### Description
Update python 3.11 and remove 3.7

### Motivation and Context
Update python 3.11 and remove 3.7

### CODE REVIEW

**Comment by snnn** [comment]
Update this line: https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/linux/docker/scripts/manylinux/install_deps.sh#L17

**Comment by justinchuby** [comment]
After all platforms are updated I would also update this line: https://github.com/microsoft/onnxruntime/blob/750747d8c9f1a96bda182b9a8810f3f6a75d6bdc/pyproject.toml#L46

**Comment by mszhanyi** [comment]
cloud you please check 
`error: unknown target CPU 'armv8.2-a+fp16'`
https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=293166&view=logs&jobId=fa93fdec-c840-5943-722c-a717417f20ee&j=fa93fdec-c840-5943-722c-a717417f20ee&t=11a65d75-7438-5119-82b1-557c5cc57554

**Comment by snnn** [comment]
> cloud you please check `error: unknown target CPU 'armv8.2-a+fp16'` https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=293166&view=logs&jobId=fa93fdec-c840-5943-722c-a717417f20ee&j=fa93fdec-c840-5943-722c-a717417f20ee&t=11a65d75-7438-5119-82b1-557c5cc57554

It is because:

When we build a universal2 lib on MacOS, we split onnxruntime_mlas into 3 parts: onnxruntime_mlas(the common part), onnxruntime_mlas_arm64, onnxruntime_mlas_x86_64. The later two only contains platform specific code. The common part cannot have platform specific code since we build it only once for two platforms. 

For example, if a file in the common part has ARM64 specific asm, then the compiler does not know how to process it for x86_64, then it fails.  Such a file cannot be in the common part of onnxruntime_mlas.

**Comment by mszhanyi** [comment]
> > cloud you please check `error: unknown target CPU 'armv8.2-a+fp16'` https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=293166&view=logs&jobId=fa93fdec-c840-5943-722c-a717417f20ee&j=fa93fdec-c840-5943-722c-a717417f20ee&t=11a65d75-7438-5119-82b1-557c5cc57554
> 
> Not due to this change. The failure is because:
> 
> When we build a universal2 lib on MacOS, we split onnxruntime_mlas into 3 parts: onnxruntime_mlas(the common part), onnxruntime_mlas_arm64, onnxruntime_mlas_x86_64. The later two only contains platform specific code. The common part cannot have platform specific code since we build it only once for two platforms. 
> 
> For example, if a file in the common part has ARM64 specific asm, then the compiler does not know how to process it for x86_64, then it fails.  Such a file cannot be in the common part of onnxruntime_mlas.

who's taking care of it?
The last successful time on main branch is Mar 19th.

**Review by pranavsharma — APPROVED** [review]

**Pull request merged**
