### PR TITLE
[ROCm] Fix attention softmax memory access fault error 

### PR DESCRIPTION
**Pull request by PeixuanZuo**
use int64 instaed of int32 to avoid memory access fault.

### CODE REVIEW

**Comment by tianleiwu** [comment]
Please update the cuda one as well. 
Is it possible to use hipify this file?

**Comment by PeixuanZuo** [comment]
> It could be rare for integer overflow. Since the index is up to BxNxSxS*. To reach overflow, you need prompt length S=4096, S*=4096, N=128, B>=1. Instead of changing this kernel, you can also check integer overflow (BxNxSxS* < MAX_INT) during allocating buffers before calling the kernel. It is because such long prompt shall use flash attention so we do not need to support it in unfused kernel, which is too slow for long prompt.
> 
> Please also add a test case to ensure that other part of attention code is good to handle integer overflow.
> 
> Please update the cuda code as well. Is it possible to hipify this file to avoid duplication work?

Thanks for your suggestion. It's rare for integer overflow, we encountered this problem when testing the maximum batch size that whisper model can use. ROCm EP use TunableOp to select best kernel and need to make sure a default implementation can handle every shape.

**Review by tianleiwu — APPROVED** [review]

**Comment by tianleiwu** [comment]
@PeixuanZuo, is this still needed? If so, please merge main to kick off new pipeline runs.

**Comment by PeixuanZuo** [comment]
> @PeixuanZuo, is this still needed? If so, please merge main to kick off new pipeline runs.

Thanks for your reminder, this PR is not necesarry.

**Pull request closed without merging**
