### PR TITLE
Change the OrtCustomOp invocation as a constant.

### PR DESCRIPTION
**Pull request by wenbingl**
**Description**: Change the OrtCustomOp invocation as a constant.

**Motivation and Context**
The existing OrtCustomOp object was passed as non-const in the ORT custom-op API, so it makes the object being stateful between ORT and the user custom op which bring some unclear prototype in MT and some other complication.

However, the runtime doesn't need to change any state of OrtCustomOp, so adding the const constraint to make the API and its protocol being clear and simple.

### CODE REVIEW

**Comment by wenbingl** [comment]
/azp orttraining-linux-gpu-ci-pipeline, Linux Nuphar CI Pipeline, orttraining-linux-gpu-ci-pipeline (Onnxruntime_Linux_GPU_Training Debug), orttraining-linux-gpu-ci-pipeline (Onnxruntime_Linux_GPU_Training Release)

**Review by snnn — CHANGES_REQUESTED** [review]
Isn't this an ABI breaking change?

**Comment by wenbingl** [comment]
> Isn't this an ABI breaking change?

Adding a const constraint doesn't affect any precompiled binaries so it is fine.

But this flaw in API needs to be fixed, and there is a small chance the user needs to update their code if they want to compile their code with a newer ORT, which seems to be fair as well.

**Comment by snnn** [comment]
> > Isn't this an ABI breaking change?
> 
> Adding a const constraint doesn't affect any precompiled binaries so it is fine.
> 

I think it is part of the ABI. 

See:  https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B

**Comment by wenbingl** [comment]
> > > Isn't this an ABI breaking change?
> > 
> > 
> > Adding a const constraint doesn't affect any precompiled binaries so it is fine.
> 
> I think it is part of the ABI.
> 
> See: https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B

I search const and didn't find any related info, which text line are you referring to?

Technically, there is no difference w/ or w/o const in lower level code. And I already changed the header file used into another projects and it work fine with ORT precompiled binary.

@pranavsharma, any suggestion on how to fix the issue?

**Review by snnn — APPROVED** [review]

**Pull request merged**
