### PR TITLE
[VitisAI] add registered custom op for perf test

### PR DESCRIPTION
**Pull request by BoarQing**
### Description

Register for custom op when testing the performance

### Motivation and Context

This is needed for providers to test their implementation

### CODE REVIEW

**Comment by BoarQing** [comment]
@jywu-msft This would be helpful for providers to test the performance.

**Comment by jywu-msft** [comment]
can you help resolve merge conflict? thanks!

**Comment by BoarQing** [comment]
> can you help resolve merge conflict? thanks!

Hi, I have solve the confliect.

**Comment by BoarQing** [comment]
> > can you help resolve merge conflict? thanks!
> 
> Hi, I have solve the confliect. @jywu-msft

@jywu-msft

**Comment by BoarQing** [comment]
> /azp run Big Models, Linux Android Emulator QNN CI Pipeline

Hi, could you review it?

**Comment by BoarQing** [comment]
@HectorSVC  @jywu-msft  Could we get this review and merged?

**Comment by BoarQing** [comment]
@jywu-msft This is quite useful for the performance test. Could you review this?

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
