### PR TITLE
Fix scalar tensors and add test

### LINKED ISSUE #4369: ArgumentException: Dimensions must contain elements
**Describe the bug**
While debugging a network and splitting it into separate parts I reduced one part down to simply returning the first dimension of the shape. This exception occurs while running the model using the C# InferenceSample project. Exception occurs in Tensor.cs:309.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Build 18363
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: b41fcf1
- Python version: N/A
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): cl.exe 19.26.28806 for x64
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
- Use the Microsoft.ML.OnnxRuntime.InferenceSample project
- Modify the sample to use the attached .onnx file (see below) and skip using the inputData from "bench.in" (i.e. initialize the input tensors without inputData)
- Run and notice the exception that occurs.

**Expected behavior**
Since the output is a scalar I'd still expect the dimensions to correctly show as 1.

**Screenshots**
image

**Additional context**
[siamese_test_opt.zip](https://github.com/microsoft/onnxruntime/files/4848364/siamese_test_opt.zip)

### PR DESCRIPTION
**Pull request by amirebrahimi**
**Description**:
Allow construction of scalar DenseTensors

**Motivation and Context**
Fixes #4369

### CODE REVIEW

**Comment by amirebrahimi** [comment]
Do I need to fix these other tests since there is inconsistencies among platforms or is this related to some other known issue?

**Comment by hariharans29** [comment]
Looks like the Windows tests are failing - Is it okay if I just patch your branch - amirebrahimi:contrib/scalar-fix and just take the commit in ? You don't have to waste time with incremental fixes.

**Comment by hariharans29** [comment]
Looks like a few tests need to be updated to **not** expect exceptions to be thrown . This is because we don't throw exceptions when the dimensions are empty anymore. 

image

I can take care of these in due course.

**Comment by amirebrahimi** [comment]
> Looks like the Windows tests are failing - Is it okay if I just patch your branch - amirebrahimi:contrib/scalar-fix and just take the commit in ? You don't have to waste time with incremental fixes.

Of course. Thank you.

**Comment by hariharans29** [comment]
> > Looks like the Windows tests are failing - Is it okay if I just patch your branch - amirebrahimi:contrib/scalar-fix and just take the commit in ? You don't have to waste time with incremental fixes.
> 
> Of course. Thank you.

Thanks. I ll make sure this makes the next release (if everyone else is okay with this change).

**Comment by hariharans29** [comment]
Closing in favor of https://github.com/microsoft/onnxruntime/pull/4849 to allow for faster iteration. Thanks for the contribution.

**Pull request closed without merging**
