### PR TITLE
Fix for the MKLDNN v1 segfaults

### PR DESCRIPTION
**Pull request by tomdol**
Fix for the segfaults observed on the test models file used in CI. The patch now contains fixes for both the segfauls and constexpr build error on windows.

### CODE REVIEW

**Comment by jywu-msft** [comment]
@sreekanth-yalachigere , does mkl-dnn ep need this too?

**Comment by sreekanth-yalachigere** [comment]
> @sreekanth-yalachigere , does mkl-dnn ep need this too?

We don't need this patch for MKL-DNN EP.

Squeeze (tf_inception) reshape is causing this segment default and we don't have this operator implemented in MKL-DNN EP.

**Comment by jywu-msft** [comment]
GPU CI failure isn't related to your changes. Can you merge latest onnxruntime master ? That would fix the failure.

**Pull request merged**
