### PR TITLE
[js/webgpu] Optimize transpose

### PR DESCRIPTION
**Pull request by qjia7**
### Description

Fix bugs in previous implementation and add more situations to go the optimized path.

Below situations will go to the optimized path.
1. 2d inputs or squeezed 2d inputs
2. channels last or channels first transpose. For example, channel last transpose: [1, 256, 512, 512] -> [1, 512, 512, 256]
    For this case, the transpose becomes [256, 512x512] -> [512x512, 256]

### Motivation and Context

For SD Turbo demo, the total transpose time becomes 39.98ms from 122.09ms. And the correspnding percents becomes 3.89% from 11.05% in this demo.

This PR will also help #21618, the total transpose time in that demo becomes 17.32 ms from 70.25 ms on my iGPUs.

### CODE REVIEW

**Comment by qjia7** [comment]
@guschmue @fs-eire @satyajandhyala Please take a look, thanks.

**Comment by satyajandhyala** [comment]
Can we add testcases that exercise the newly added code if not already exists?

**Review by guschmue — APPROVED** [review]

**Comment by qjia7** [comment]
> Can we add testcases that exercise the newly added code if not already exists?

Done. Please take another look, thanks.

**Review by satyajandhyala — APPROVED** [review]

**Pull request merged**
