### PR TITLE
Add Resize and Upsample to ROCm EP

### PR DESCRIPTION
**Pull request by jeffdaily**
Hipify and register Resize and Upsample for ROCm EP.

Some CUDA EP files could hipify cleanly.  Unfortunately, resize_impl.cu needed to be largely rewritten for the ROCm EP.  The support for device function pointers is not yet available.  Instead, the device function pointers were converted to device functors.  Case statements, lambdas, and macros are used for dispatch; as a result, all combinations of kernels are compiled with inlined functors.  This basis of this approach can be found in PyTorch.

### CODE REVIEW

**Comment by jeffdaily** [comment]
> @jeffdaily for any newly registered operators, can you confirm the associated unit tests ran on ROCm?

https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=515399&view=logs&j=48b14a85-ff1a-5ca4-53fa-8ea420d27feb&t=e882c4fa-e626-5790-579a-99f25f8389cd&l=3513

These are 11 tests that use the newly registered op.

DequantizeLinearOpTest.Uint8
DequantizeLinearOpTest.Int8
DequantizeLinearOpTest.2D
DequantizeLinearOpTest.Scalar
DequantizeLinearOpTest.Without_Zero_Point
QuantizeLinearOpTest.Uint8
QuantizeLinearOpTest.Int8
QuantizeLinearOpTest.Int8_NegativeZeroPoint
QuantizeLinearOpTest.Int8_PositiveZeroPoint
QuantizeLinearOpTest.2D
QuantizeLinearOpTest.Scalar

**Comment by jeffdaily** [comment]
> @jeffdaily for any newly registered operators, can you confirm the associated unit tests ran on ROCm?

https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=515466&view=logs&j=48b14a85-ff1a-5ca4-53fa-8ea420d27feb&t=e882c4fa-e626-5790-579a-99f25f8389cd&l=6770

ResizeOpTest.ResizeOpLinearDownSampleTest_tf_crop_and_resize
ResizeOpTest.ResizeOpLinearDownSampleTest_tf_crop_and_resize_with_extrapolation
ResizeOpTest.ResizeOpLinearDownSampleTest_4DBilinear
ResizeOpTest.ResizeOpLinearDownSampleTest_4DBilinear1
ResizeOpTest.ResizeOpLinearDownSampleTest_4DBilinear1_WithSizes
ResizeOpTest.ResizeOpLinearDownSampleTest_4DBilinear_align_corners
ResizeOpTest.ResizeOpLinearDownSampleTest_2DBilinear_pytorch_half_pixel
ResizeOpTest.ResizeOpLinearUpSampleTest_4DBilinear_asymmetric
ResizeOpTest.ResizeOpLinearUpSampleTest_2DBilinear_align_corners
ResizeOpTest.ResizeOpLinearDownSampleTest_3DTrilinear_pytorch_half_pixel
ResizeOpTest.ResizeOpLinearUpSampleTest_5DTrilinear_pytorch_half_pixel
ResizeOpTest.ResizeOpLinearScalesNoOpTest
ResizeOpTest.ResizeOpNearestDownSampleTest
ResizeOpTest.ResizeOpNearestDownSampleTest_Opset12
ResizeOpTest.ResizeOpNearestDownSampleTest_WithSizes
ResizeOpTest.ResizeOpNearestDownSampleTest_tf_half_pixel
ResizeOpTest.ResizeOpNearestDownSampleTest_tf_crop_and_resize_with_extrapolation
ResizeOpTest.ResizeOpNearestDownSample5dTest_tf_crop_and_resize_with_extrapolation
ResizeOpTest.ResizeOpNearestUpSampleTest
ResizeOpTest.ResizeOpNearestUpSampleTest_WithSizes_CeilMode
ResizeOpTest.ResizeOpNearestUpSample5dTest_WithSizes_CeilMode
ResizeOpTest.ResizeOpNearestUpSample_Floor_Align_Corners
ResizeOpTest.ResizeOpNearest_OneToOneMappingBetweenInputAndOutputDataDims
ResizeOpTest.ResizeOpNearestUpSample_Nearest2xOptimization_Scales
ResizeOpTest.ResizeOpNearestUpSample_Nearest2xOptimization_Sizes
ResizeOpTest.ResizeOpCubicDownSampleTest
ResizeOpTest.ResizeOpCubicDownSampleTest_exclude_outside
ResizeOpTest.ResizeOpCubicDownSampleTest_coeff
ResizeOpTest.ResizeOpCubicDownSampleTest_with_roi
ResizeOpTest.ResizeOpCubicDownSampleTest_asymmetric
ResizeOpTest.ResizeOpCubicUpSampleTest
ResizeOpTest.ResizeOpCubicUpSampleTest_MultiChannel
ResizeOpTest.ResizeOpCubicUpSampleTest_tf_half_pixel_for_nn
ResizeOpTest.ResizeOpLinearDownSampleTest_4DBilinear_Ver10
ResizeOpTest.ResizeOpLinearDownSampleTest_2DBilinear_Ver10
ResizeOpTest.ResizeOpLinearUpSampleTest_4DBilinear_Ver10
ResizeOpTest.ResizeOpLinearUpSampleTest_2DBilinear_Ver10
ResizeOpTest.ResizeOpLinearScalesNoOpTest_Ver10
ResizeOpTest.ResizeOpNearestDownSampleTest_Ver10
ResizeOpTest.ResizeOpNearestUpSampleTest_Ver10
ResizeOpTest.ResizeOp_MissingRoiAndMissingScalesOptionalInputs
UpsampleOpTest.ResizeOpNearestNoScaleTest_Ver10

**Comment by suffiank** [comment]
> Hipify and register Resize and Upsample for ROCm EP.
> 
> Some CUDA EP files could hipify cleanly. Unfortunately, resize_impl.cu needed to be largely rewritten for the ROCm EP. The support for device function pointers is not yet available. Instead, the device function pointers were converted to device functors. Case statements, lambdas, and macros are used for dispatch; as a result, all combinations of kernels are compiled with inlined functors. This basis of this approach can be found in PyTorch.

@jeffdaily  Since this pattern is recognizable in PyTorch, can we just use it for both CUDA and ROCm? I don't see any negative performance implication.

**Comment by jeffdaily** [comment]
> @jeffdaily Since this pattern is recognizable in PyTorch, can we just use it for both CUDA and ROCm? I don't see any negative performance implication.

Yes, of course we can do that.  I will submit a new PR that changes the CUDA EP's implementation of these ops and let the review continue there, but I will leave this PR open just in case.

**Pull request closed without merging**
