### PR TITLE
Call `lazy_reset_grad` in on-device training docs

### PR DESCRIPTION
**Pull request by dannyfriar**

### CODE REVIEW

**Review by baijumeswani — APPROVED** [review]

**Comment by baijumeswani** [comment]
Need to close the PR and reopen to trigger CI pipelines.

**Comment by dannyfriar** [comment]
No problem. Out of curiosity are there any details you can share regarding future of development of the on-device training features? Is there are roadmap available anywhere?

It seems like a very useful feature and I've been experimenting with it but have found the docs a little sparse and I'm not clear how well it is supported or how widely it's used.

**Comment by baijumeswani** [comment]
What we currently support:

- Android packages (allows for easy training on Android devices with Java, C, C++ language bindings)
- Desktop packages (Windows and Linux with language bindings available in C, C++, C#, Java, Python)

Work in progress right now:

- iOS package (with Objective-C and Swift language bindings)
- Web packages (allows for on-device training on web browsers with Typescript language bindings)
- Minimal build support (to be able to create a custom build with as small a binary size as possible)
- Custom operators support (so onnx models with pre and post processing operators defined in an external custom library (such as [onnxruntime-extensions](https://github.com/microsoft/onnxruntime-extensions)) can be executed)
- Extending the list of supported ops and their gradients in ort.

Work planned for the near future:

- Ability to train a partially quantized model on a device.

Sorry, I don't have a more detailed roadmap than this at the moment. If you have feature requests, do share with us through GitHub issues.

**Comment by dannyfriar** [comment]
That's great, thanks @baijumeswani

**Pull request merged**
