### PR TITLE
[VSINPU]Update vsinpu patches

### PR DESCRIPTION
**Pull request by chenfeiyue-cfy**
### Description
- update patches for accuracy modification && local result recording

### CODE REVIEW

**Comment by chenfeiyue-cfy** [comment]
Could anyone please help merge this code?These patch files are crucial for our weekly software integration testing.

**Comment by chenfeiyue-cfy** [comment]
Hi, I see the "ONNX Runtime Web CI Pipeline (Test_web_MultiBrowsers build_onnxruntime_web_windows)"check failed but I don't know why, is this matter related to whether my PR can be merged?

**Review by tianleiwu — APPROVED** [review]
If some change (like IsResultExactlyMatch<Int4x2> etc) is generic for other provider, you can submit change to original source file instead of using patch.

**Pull request merged**
