### PR TITLE
[js/webgpu] Add input/output shapes information to profiling

### PR DESCRIPTION
**Pull request by qjia7**
### Description
This PR is to enhance the profiling information.
With the PR, the profiling result is like below:
```
[profiling] kernel "[Split] 51288384" input[0]: 1,256,64,64, output[0]: 1,256,64,64, execution time: 37135 ns
program-manager.ts:114 
[profiling] kernel "[Concat] 52361040" input[0]: 1,256,64,64, output[0]: 1,256,64,64, execution time: 50833 ns
program-manager.ts:114 
[profiling] kernel "[Transpose] 52375264" input[0]: 1,256,64,64, output[0]: 1,64,64,256, execution time: 99791 ns
program-manager.ts:114 
[profiling] kernel "[Sub] 51098472" input[0]: , input[1]: 1, output[0]: 1, execution time: 7448 ns
program-manager.ts:114 
[profiling] kernel "[Mul] 51344440" input[0]: 1, input[1]: 1,256,1,1, output[0]: 1,256,1,1, execution time: 8334 ns
```
Without this PR, the profiling result is like below:
```
[profiling] kernel "52097928|[Split] 52097928" execution time: 37760 ns
program-manager.ts:105 
[profiling] kernel "41898328|[Concat] 41898328" execution time: 51666 ns
program-manager.ts:105 
[profiling] kernel "41915648|[Transpose] 41915648" execution time: 95416 ns
program-manager.ts:105 
[profiling] kernel "49757856|[Sub] 49757856" execution time: 7969 ns
program-manager.ts:105 
[profiling] kernel "51680504|[Mul] 51680504" execution time: 8906 ns
```
With the new information, we can easily know what kind of shape ops have poor performance. Also it can help us to check whether too small shape ops run on gpu.

### CODE REVIEW

**Comment by qjia7** [comment]
@fs-eire @guschmue Please take a look, thanks.

**Comment by fs-eire** [comment]
can we put tensor data type as well? they are in TensorView.dataType. It's a number and can be used with tensorDataTypeEnumToString() to convert to string representation.

**Comment by qjia7** [comment]
> can we put tensor data type as well? they are in TensorView.dataType. It's a number and can be used with tensorDataTypeEnumToString() to convert to string representation.

Done.
```
[profiling] kernel "[Split] 51288384" input[0]: 1,256,64,64 | float32, output[0]: 1,256,64,64 | float32, execution time: 31406 ns
program-manager.ts:115 
[profiling] kernel "[Concat] 52361040" input[0]: 1,256,64,64 | float32, output[0]: 1,256,64,64 | float32, execution time: 42968 ns
program-manager.ts:115 
[profiling] kernel "[Transpose] 52375264" input[0]: 1,256,64,64 | float32, output[0]: 1,64,64,256 | float32, execution time: 84167 ns
program-manager.ts:115 
[profiling] kernel "[Sub] 51098472" input[0]:  | float32, input[1]: 1 | float32, output[0]: 1 | float32, execution time: 6511 ns
program-manager.ts:115 
[profiling] kernel "[Mul] 51344440" input[0]: 1 | float32, input[1]: 1,256,1,1 | float32, output[0]: 1,256,1,1 | float32, execution time: 6771 ns

**Comment by qjia7** [comment]
I just notices that @guschmue 's profiling result is like 
```
[profiling] kernel "44184248|[Split] /Split_1" execution time: 1436672 ns
```
But my original result is like
```
[profiling] kernel "52097928|[Split] 52097928" execution time: 37760 ns
```
Not sure why the op name becomes kernel id. Anyway, I just keep the original profiling info unchanged and add the additional input shapes and output shapes.

**Comment by guschmue** [comment]
I think @fs-eire added the name recently. I remember I had to change my scripts a few days ago.

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
