### PR TITLE
Add overflow protection for quantization bias to reduce quantization precision loss

### PR DESCRIPTION
**Pull request by duanshengliu**
### Description

When the scale of the bias is too small, the quantized bias may exceed the range of `int32`, leading to significant loss of precision. Therefore, before converting quantized bias to `int32`, it needs to be clipped within the range of `int32` to reduce the loss of quantization precision.

### Motivation and Context

Fix the issue https://github.com/microsoft/onnxruntime/issues/21000

### CODE REVIEW

**Comment by duanshengliu** [comment]
@yihonglyu @adrianlizarraga, could you take a look and start the CI pipelines?

**Comment by duanshengliu** [comment]
@adrianlizarraga, could you please start CI again?

**Comment by duanshengliu** [comment]
@yufenglee @adrianlizarraga, could you please review and start the CI Pipeline?

**Review by yufenglee — APPROVED** [review]

**Comment by duanshengliu** [comment]
@yufenglee @adrianlizarraga, could you please start the CI Pipeline?

**Comment by duanshengliu** [comment]
@adrianlizarraga, @yufenglee,  could you please start the CI again?

**Comment by duanshengliu** [comment]
@adrianlizarraga, @yufenglee, sync with the main branch again, could you please start the CI?

**Comment by duanshengliu** [comment]
@adrianlizarraga, @yufenglee, could you start the CI pipeline when you are free?

**Comment by duanshengliu** [comment]
@fajin-corp, the `orttraining-ortmodule-distributed` was canceled.

**Comment by duanshengliu** [comment]
@yufenglee, @fajin-corp, @adrianlizarraga, the `orttraining-ortmodule-distributed` pipeline was canceled. Could you help to restart it?

**Comment by duanshengliu** [comment]
@yufenglee, @fajin-corp, @adrianlizarraga, all the checks have passed. Could you help to merge?

**Comment by yihonglyu** [comment]
@duanshengliu What's the difference between clip + cast and cast only? Could you add a test for it?

**Comment by duanshengliu** [comment]
> @duanshengliu What's the difference between clip + cast and cast only? Could you add a test for it?

For the values within the `int32` range, there is no difference between `clip + cast` and `cast only`. However, for the values outside the `int32` range, `cast only` will `wrap around` into the representable range of `int32` (resulting in significant loss of precision), for example:
```
>>> import numpy as np
>>> bias = np.array(2147483648, dtype=np.float32)
>>> bias.astype(np.int32)
<stdin>:1: RuntimeWarning: invalid value encountered in cast
array(-2147483648, dtype=int32)
```
If we do `clip + cast` ：
```
>>> import numpy as np
>>> bias = np.array(2147483648, dtype=np.float32)
>>> bias = np.clip(bias, np.iinfo(np.int32).min, np.iinfo(np.int32).max)
>>> bias.astype(np.int32)
2147483647
```
Obviously, `cast only` carries the risk of causing significant precision loss, whereas `clip + cast` does not, and it can reduce quantization precision loss

**Pull request merged**
