### PR TITLE
Add the missing status for beam search

### PR DESCRIPTION
**Pull request by feihugis**
**Description**: Describe your changes.
Fix the minor issue of missing the returned status.

**Motivation and Context**
- Why is this change required? What problem does it solve?
Without this change, the build will fail.

### CODE REVIEW

**Review by snnn — APPROVED** [review]
Should we get a compile warning for this? How it gets ignored?

**Comment by feihugis** [comment]
> Should we get a compile warning for this? How it gets ignored?

@snnn I got the below error. Not sure why the CI did not catch it.

```
/datadrive/fhu/github/onnxruntime/onnxruntime/contrib_ops/cuda/transformers/beam_search_device_helper.cc: In function ‘onnxruntime::common::Status onnxruntime::contrib::BeamSearchCudaDeviceHelper::UpdateFeeds(onnxruntime::AllocatorPtr, void*, const std::vector<OrtValue>&, std::vector<OrtValue>&, int, OrtValue&, gsl::span<const int>, gsl::span<const int>, int, const onnxruntime::contrib::transformers::IConsoleDumper*) [with T = onnxruntime::MLFloat16]’:
/datadrive/fhu/github/onnxruntime/onnxruntime/contrib_ops/cuda/transformers/beam_search_device_helper.cc:467:1: error: control reaches end of non-void function [-Werror=return-type]
  467 | }
      | ^
cc1plus: all warnings being treated as errors
```

**Pull request merged**
