### PR TITLE
Cherry picks for release - 1.8.1 Round 2

### PR DESCRIPTION
**Pull request by harshithapv**
This PR has all the cherry picks for round two for release 1.8.1. Following are the list of 14 PRs:
Fix mac shared_provider warning (#8153) - Had conflicts
• Approved

Fix Python Cuda loading issues (#7939) - Had conflicts with #7873
• Approved

Ortmodule override torch.manual_seed() (#8131) - Had a conflict with #7513
• Approved

Update logic in props.xml to account for shared provider library changes  release:1.8.1 triage:approved
#8138 by hariharans29 was merged 17 hours ago
• Approved

Add int64 as a required type to ConstantOfShape 
 release:1.8.1
#8128 by skottmckay was merged 13 hours ago• Approved 

[Mobile package] Update required operator config with additional ops for newer version of Wav2Vec 2. 
 release:1.8.1 triage:approved
#8123 by edgchen1 was merged 15 hours ago• Approved

 Fix 32bit Android java API crash 
 release:1.8.1 triage:approved
#8122 by gwang-msft was merged 17 hours ago• Approved

 Fix input schema extraction for ORTModule 
 component:ortmodule component:training-frontend release:1.8.1 triage:approved
#8098 by thiagocrepaldi was merged 5 days ago• Approved

 Add module attribute to ORTModule to support HuggingFace Trainer save_model – Had conflicts with #7819
 component:ortmodule component:training-frontend release:1.8.1 triage:approved
#8088 by baijumeswani was merged 5 days ago• Approved

 [Mobile package] Update required operator config with additional ops for wav2vec2. 
 release:1.8.1 triage:approved
#8079 by edgchen1 was merged 6 days ago• Approved

 Linux GPU Nuget package missing shared provider files 
 release:1.8.1 triage:approved
#8066 by RyanUnderhill was merged 7 days ago• Approved

 Add shape inference to custom symbolic functions – Had conflicts
 component:ortmodule component:training-frontend release:1.8.1 triage:approved
#7937 by BowenBao was merged 15 days ago• Approved
 
 Topo sort the model before saving 
 release:1.8.1 triage:approved
#7913 by wangyems was merged 21 days ago• Approved

 Fix boost download url 
 release:1.8.1 triage:approved
#7843 by gwang-msft was merged 28 days ago• Approved

### CODE REVIEW

**Comment by skottmckay** [comment]
Can this be added please? https://github.com/microsoft/onnxruntime/pull/8128

**Comment by harshithapv** [comment]
> Can this be added please? #8128

done :)

**Comment by hariharans29** [comment]
Could you take this in as well please ? https://github.com/microsoft/onnxruntime/pull/8138

**Comment by gwang-msft** [comment]
Could you take this #8153 as well?

**Review by baijumeswani — DISMISSED** [review]

**Review by natke — APPROVED** [review]

**Review by baijumeswani — APPROVED** [review]

**Pull request merged**
