### PR TITLE
using OffscreenCanvas when DOM is not available

### PR DESCRIPTION
**Pull request by jiangzhuo**
### Description
when DOM API is not avaiable, using OffscreenCanvas

### Motivation and Context
In some environment like service worker or web worker, the DOM API is not avaiable, we can use OffscreenCanvas API to replace `document.createElement('canvas')`.
Most of the APIs of OffscreenCanvas and HTMLCanvasElement are the same, except that `toDataUrl` is missing.

It fix this issues #19032

### CODE REVIEW

**Comment by jiangzhuo** [comment]
> @jiangzhuo please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by jiangzhuo** [comment]
sorry for unformatted file, I formatt the changed file with `npm run format` in new commit

**Comment by jiangzhuo** [comment]
@fs-eire  
Do you think the failure in the `ONNX Runtime React Native CI Pipeline` is a flaky failure in CI, not related to the changes made in this PR? If you believe it's an issue caused by my code modifications, please let me know, and I will investigate and address it.

**Comment by fs-eire** [comment]
I think it should be fine. The React Native failure is not related to this change.

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
