### PR TITLE
Pylint fix after #11647

### PR DESCRIPTION
**Pull request by vvchernov**
All post-CI for master commits and other CI for further PRs cannot pass pylint after #11647 (see activities). There is simple fix of pylint

### CODE REVIEW

**Review by justinchuby — DISMISSED** [review]
Thanks! As long as "Python format" passes we should be good. I can look into what happens with pyright

**Comment by vvchernov** [comment]
Hello @justinchuby! Looks like I've fixed pyright issues

**Review by justinchuby — APPROVED** [review]
Thanks for the fix!

**Review by garymm — COMMENTED** [review]
Please merge this ASAP as the `Lint / Python format` check is blocking all other PRs

**Review by yufenglee — APPROVED** [review]

**Comment by yufenglee** [comment]
> Thanks! As long as "Python format" passes we should be good. I can look into what happens with pyright

@justinchuby and @garymm, the style checking is good. Could you please make them required? Or it may be merged if don't check all the pipeline.

**Comment by justinchuby** [comment]
> > Thanks! As long as "Python format" passes we should be good. I can look into what happens with pyright
> 
> @justinchuby and @garymm, the style checking is good. Could you please make them required? Or it may be merged if don't check all the pipeline.

I think Pranav can help. I just asked

**Comment by justinchuby** [comment]
It's now required

**Comment by vvchernov** [comment]
Hello @xadupre @garymm! Could you rerun canceled CI tests. They failed due to long connection

**Comment by vvchernov** [comment]
Any ideas about "##[error]The agent did not connect within the alloted time of 45 minute(s)."?

**Comment by vvchernov** [comment]
Hello @xadupre @garymm! Do you know how to workaround problem with bad connection in CI or somebody who can help us? I think this PR should be merge ASAP to skip pylint issue blocking other ones, but connection absence blocks it.

**Comment by justinchuby** [comment]
@snnn could you help?

**Comment by vvchernov** [comment]
@yufenglee we did it three times with the same effect, may be problem is with servers or in CI system. The PR fixes cannot influence on this tests

**Comment by yufenglee** [comment]
> @yufenglee we did it three times with the same effect, may be problem is with servers or in CI system. The PR fixes cannot influence on this tests

yes, there is no up server in the agent pool.

**Comment by justinchuby** [comment]
```
/usr/bin/bash --noprofile --norc /mnt/vss/_work/_temp/813a6f3d-fddd-4c90-8ff4-26d175d2af0a.sh
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Invalid: lock file's acorn@8.2.4 does not satisfy acorn@8.7.1
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [--no-audit] [--foreground-scripts] [--ignore-scripts]
npm ERR! [--script-shell <script-shell>]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cloudtest/.npm/_logs/2022-06-02T22_45_44_276Z-debug-0.log
##[error]Bash exited with code '1'.
Finishing: npm ci /js/web/
```

**Comment by snnn** [comment]
This time it will be good.

**Pull request merged**
