### PR TITLE
Remove CentOS CI pipeline

### PR DESCRIPTION
**Pull request by snnn**
**Description**:

The pipeline is for testing if our code is compatible with the GCC 4.8 on CentOS 7. We will stop supporting this feature, thus this pipeline needs be removed. 

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by Craigacp** [comment]
Are you stopping supporting CentOS 7 entirely? Or just requiring that CentOS builds use a more recent `devtoolset`?

**Comment by snnn** [comment]
> requiring that CentOS builds use a more recent `devtoolset`?

The later.

**Review by thiagocrepaldi — APPROVED** [review]
Are we going to support CentOS 8 instead?

**Comment by snnn** [comment]
> Are we going to support CentOS 8 instead?

I think we won't make the change in the near future.

**Pull request merged**
