### PR TITLE
Fix build break in migraphx ep

### PR DESCRIPTION
**Pull request by souptc**
**Description**: Fix build break in migraphx ep. 

issue: #11473

### CODE REVIEW

**Comment by causten** [comment]
There is a lot of whitespace changes in this pull request.  Hard to see the actual functional differences.  I'll test it though

**Comment by causten** [comment]
I have tested this PR using migraphx as the provider.  This PR fixes the problem.  Thank you!

**Comment by souptc** [comment]
> There is a lot of whitespace changes in this pull request. Hard to see the actual functional differences. I'll test it though

Let me check the formatter.

**Comment by souptc** [comment]
fixed the format issue.

**Review by snnn — APPROVED** [review]

**Pull request merged**
