### PR TITLE
Normalizing kernel launching format.

### PR DESCRIPTION
**Pull request by ghostplant**
Changes to normalize the standard CUDA kernel launching format, which is important to port onnxruntime-cuda to amd devices.

### CODE REVIEW

**Comment by ghostplant** [comment]
@raymondxyang Seems like Windows CI failure for pipeline access error, not related to the PR changes.

**Comment by raymondxyang** [comment]
@snnn could u take a look into the permission issue? not remembering seeing the error message before

**Comment by ghostplant** [comment]
`Packages failed to download`

**Comment by raymondxyang** [comment]
The auto CI kick-off has some problems right now, we are following this problem with the devops team. Meanwhile I manually queued your change.

**Comment by yuslepukhin** [comment]
Please, supply a good description for your PR so people do not need to look into source in the future.

**Pull request closed without merging**
