### PR TITLE
[WIP] Expose opset_version when instantiating ORTModule

### PR DESCRIPTION
**Pull request by xadupre**
**Description**:
ORTModule converts an torch model into ONNX using a fixed version. This parameter allows to change that.

### CODE REVIEW

**Comment by SherlockNoMad** [comment]
I agree with @thiagocrepaldi that it shouldn't be a parameter to the constructor, as the list of parameter could grow. 
And I also agree with @xadupre that "onnxruntime.traiing.ortmodule.ONNX_OPSET_VERSION=13" is too intrusive and not very intuitive. 

It's very common for model owners to pick an opset that's different from the default, and for different models, it might need different opset support. 

I would prefer to set this in the experimental user config, a central json file where model owner changes ORTModule configs.

**Comment by baijumeswani** [comment]
@thiagocrepaldi the solution to set `ONNX_OPSET_VERSION` through torch_ort by using `torch_ort.ONNX_OPSET_VERSION=13` might not be feasible without any explicit setter because that would mean that the variable is defined inside `torch_ort` as opposed to `onnxruntime.training.ortmodule` and it also means that ortmodule somehow would need to pull that variable from `torch_ort`.

Since setting the opset version is an advanced feature which we don't expect users to play around much with, how about we make it controllable using env variables? User can do `export ORTMODULE_ONNX_OPSET_VERSION=13` to set the opset version?
That could be a way that requires minimal change and also provides a way for us to set the opset version through the json config loader. It also does not have the problem with two repos trying to set the same variable (`torch_ort` and `onnxruntime.training.ortmodule`).

**Comment by thiagocrepaldi** [comment]
> @thiagocrepaldi the solution to set `ONNX_OPSET_VERSION` through torch_ort by using `torch_ort.ONNX_OPSET_VERSION=13` might not be feasible without any explicit setter because that would mean that the variable is defined inside `torch_ort` as opposed to `onnxruntime.training.ortmodule` and it also means that ortmodule somehow would need to pull that variable from `torch_ort`.
> 
> Since setting the opset version is an advanced feature which we don't expect users to play around much with, how about we make it controllable using env variables? User can do `export ORTMODULE_ONNX_OPSET_VERSION=13` to set the opset version? That could be a way that requires minimal change and also provides a way for us to set the opset version through the json config loader. It also does not have the problem with two repos trying to set the same variable (`torch_ort` and `onnxruntime.training.ortmodule`).

You are right, env var is cleaner

**Comment by xadupre** [comment]
Reading the environment variable at importing time means the constant stored in the package overwrites the environment variable if changed during execution. Reading the environment variable at exporting time means it overwrites the constant stored in the package. Which one do you prefer?

**Comment by thiagocrepaldi** [comment]
> Reading the environment variable at importing time means the constant stored in the package overwrites the environment variable if changed during execution. Reading the environment variable at exporting time means it overwrites the constant stored in the package. Which one do you prefer?

I believe the former is more adequate and in line with all the other flags thar already uses environment variables. Environment variables are not changed during training, but flags are. Capturing internal variable changes are important, especially for testing purposes.

Think of the testing point of view. The initial value is what the environment, we run tests to make sure env vars are handled. Next we change the variable during training and check whether the new variable takes place

Although the design is different, the code changes does the same thing: exposes opset_version to user as the pr title proposes. But it is ok to close this one and open another

**Comment by thiagocrepaldi** [comment]
> Ok... I'm not sure which one I should implement then. I suggest created another PR because I'll have to remove all my changes. The new PR will link to this one so the discussion won't be lost. Environment variables are not easy to test. That's one of the reason I usually avoid them. However, reading it at exporting time is easy to test in a new unit test. Reading it at importing time impacts all unit tests.

Feel free to create a new PR and link this one for tracking purposes.

https://github.com/microsoft/onnxruntime/blob/master/orttraining/orttraining/test/python/orttraining_test_ortmodule_fallback.py#L134-L187 has a full example on how to test env var. UT can set or delete them as needed.

Making the behavior of features consistent is important for usability. Users that know the behavior for one feature with env var will know what to expect from another feature using env var

**Comment by baijumeswani** [comment]
@xadupre After discussing with @thiagocrepaldi we've come to a consensus that the default should continue to live in `__init__.py` and the opset version from the env should be read inside `GraphExecutionManager` constructor. If the env var is defined, the env var opset version used should override the default one. If not defined, we use the default defined in the `__init__.py`.

**Pull request closed without merging**
