### PR TITLE
Adjust the nGraph EP to the newest CI test data

### PR DESCRIPTION
**Pull request by tomdol**
4 models from the newest zip file fail with nGraph EP. We can discuss what to do about them during the next meeting.

I'm not sure if this PR should be included in the upcoming 1.0 release, it's just something that had to be done anyway.

### CODE REVIEW

**Comment by tomdol** [comment]
BTW, `mask_rcnn_keras` and `candy` fail on BDW, on CLX they both pass.

**Comment by jywu-msft** [comment]
Looks like it's timing out executing the model tests.
Previously the execution could be completed in ~35 min and now it's exceeding the default 60 min timeout.
Can you double check whether there are models executing too slowly?
We can increase the test timeout, but I wanted to be sure that's the proper course of action (and not unintentionally hide a perf issue)

**Pull request merged**
