### PR TITLE
Create      SECURITY.md

### PR DESCRIPTION
**Pull request by EiendomAS**
**Description**: Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by pranavsharma** [comment]
Mentioned here https://github.com/microsoft/onnxruntime/blob/master/CONTRIBUTING.md#reporting-security-issues

**Comment by tianleiwu** [comment]
@pranavsharma, how about adding supported version?

**Comment by snnn** [comment]
Is it still needed?

**Comment by thiagocrepaldi** [comment]
@pranavsharma do we still need this?

**Comment by pranavsharma** [comment]
We've not made a decision about how far back we want to support security updates. As such, it's in the best interest of users to upgrade to the latest release since all releases post 1.0 are binary compatible. If there's any issue in the latest release, please file an issue as mentioned here https://github.com/microsoft/onnxruntime/blob/master/CONTRIBUTING.md#reporting-security-issues.

**Pull request closed without merging**
