### PR TITLE
[VitisAI] Int4 support

### PR DESCRIPTION
**Pull request by BoarQing**
### Description

1. Add support for throwing error when hardware is not supported for VitisAI.
2. Add support for unloading VitisAI EP.
3. Add API for Win25.

### Motivation and Context

This is requirement for Win25

### CODE REVIEW

**Comment by BoarQing** [comment]
@jywu-msft I have accumulated a few things due to the slow progress of VitisAI open source. Could you review this? This is required for **Win25 Release**.

**Comment by BoarQing** [comment]
> /azp run Big Models, Linux Android Emulator QNN CI Pipeline, Windows GPU CUDA CI Pipeline, Windows GPU DML CI Pipeline, Windows GPU Doc Gen CI Pipeline

Hi, I have resolved the conflect.

**Comment by jywu-msft** [comment]
@BoarQing please fix lint error https://github.com/microsoft/onnxruntime/actions/runs/12369885814/job/34542672292?pr=22850

**Comment by BoarQing** [comment]
> @BoarQing please fix lint error https://github.com/microsoft/onnxruntime/actions/runs/12369885814/job/34542672292?pr=22850

Hi, I wasn't aware of the lint update that caused the lint error. I am sorry about it. The lint issue is resolved now.

**Comment by BoarQing** [comment]
> /azp run Big Models, Linux Android Emulator QNN CI Pipeline, Windows GPU CUDA CI Pipeline, Windows GPU DML CI Pipeline, Windows GPU Doc Gen CI Pipeline

Hi, the pipeline is finished. Could you review it when you have the time?

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
