### PR TITLE
[MIGraphX EP] Add support for Mod OP

### PR DESCRIPTION
**Pull request by TedThemistokleous**
This has been available since July 25th 2022 in MIGraphX. Appared to be missing from support list of ops

https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1302

### Description

Add in node name for Mod Operator to be supported by MIGraphX

### Motivation and Context

Expand available functionality to Onnxruntime for the MIGraphX EP

### CODE REVIEW

**Comment by TedThemistokleous** [comment]
ping @PeixuanZuo @ytaous

**Review by PeixuanZuo — APPROVED** [review]

**Pull request merged**
