### PR TITLE
Try ngraph with explicitly exported API

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
**Description**: To test that https://github.com/NervanaSystems/ngraph/pull/3767 does not break integration with onnx runtime.

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
For testing purposed. Don't merge

**Comment by ilya-lavrenov** [comment]
Hi,

Can someone help to resolve issues with
```
HEAD is now at 054254b Merge remote-tracking branch 'origin/master' into il/export-symbols
error: patch failed: cmake/external_protobuf.cmake:84
error: cmake/external_protobuf.cmake: patch does not apply
error: patch failed: src/ngraph/frontend/onnx_import/CMakeLists.txt:194
error: src/ngraph/frontend/onnx_import/CMakeLists.txt: patch does not apply
CMakeFiles/project_ngraph.dir/build.make:98: recipe for target 'ngraph/src/project_ngraph-stamp/project_ngraph-patch' failed
make[2]: *** [ngraph/src/project_ngraph-stamp/project_ngraph-patch] Error 1
make[2]: *** Waiting for unfinished jobs....

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'onnxruntimedev@cus-cpu-25lc.(none)')
Cannot save the current index state
CMake Error at /build/Debug/ngraph/tmp/project_ngraph-gitupdate.cmake:83 (message):
  Failed to stash changes

```
I wonder why git cannot apply patch.

**Comment by ilya-lavrenov** [comment]
can we also restart ngraph CI pipeline for both Windows and Linux?

**Comment by jywu-msft** [comment]
> Hi,
> 
> Can someone help to resolve issues with
> 
> ```
> HEAD is now at 054254b Merge remote-tracking branch 'origin/master' into il/export-symbols
> error: patch failed: cmake/external_protobuf.cmake:84
> error: cmake/external_protobuf.cmake: patch does not apply
> error: patch failed: src/ngraph/frontend/onnx_import/CMakeLists.txt:194
> error: src/ngraph/frontend/onnx_import/CMakeLists.txt: patch does not apply
> CMakeFiles/project_ngraph.dir/build.make:98: recipe for target 'ngraph/src/project_ngraph-stamp/project_ngraph-patch' failed
> make[2]: *** [ngraph/src/project_ngraph-stamp/project_ngraph-patch] Error 1
> make[2]: *** Waiting for unfinished jobs....
> 
> *** Please tell me who you are.
> 
> Run
> 
>   git config --global user.email "you@example.com"
>   git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
> 
> fatal: unable to auto-detect email address (got 'onnxruntimedev@cus-cpu-25lc.(none)')
> Cannot save the current index state
> CMake Error at /build/Debug/ngraph/tmp/project_ngraph-gitupdate.cmake:83 (message):
>   Failed to stash changes
> ```
> 
> I wonder why git cannot apply patch.

It's a cmake/external project issue.
You modified ngraph.cmake to point to your branch which will run into that issue.
Try using a tag or commitid instead.

**Comment by ilya-lavrenov** [comment]
@jywu-msft, thanks! used commitid instead of branch. Could you please re-start the builds?

**Comment by ilya-lavrenov** [comment]
@jywu-msft, I have another issue:

```
Cloning into 'project_ngraph'...
fatal: reference is not a tree: f150595a2cea0ff5c6c046b8122c77a602aeddf6
CMake Error at /build/Release/ngraph/tmp/project_ngraph-gitclone.cmake:75 (message):
  Failed to checkout tag: 'f150595a2cea0ff5c6c046b8122c77a602aeddf6'


CMakeFiles/project_ngraph.dir/build.make:89: recipe for target 'ngraph/src/project_ngraph-stamp/project_ngraph-download' failed
make[2]: *** [ngraph/src/project_ngraph-stamp/project_ngraph-download] Error 1
CMakeFiles/Makefile2:1009: recipe for target 'CMakeFiles/project_ngraph.dir/all' failed
make[1]: *** [CMakeFiles/project_ngraph.dir/all] Error 2
```

But https://github.com/NervanaSystems/ngraph/tree/f150595a2cea0ff5c6c046b8122c77a602aeddf6 is in ngraph tree. Could you please advice?

**Comment by jywu-msft** [comment]
> @jywu-msft, I have another issue:
> 
> ```
> Cloning into 'project_ngraph'...
> fatal: reference is not a tree: f150595a2cea0ff5c6c046b8122c77a602aeddf6
> CMake Error at /build/Release/ngraph/tmp/project_ngraph-gitclone.cmake:75 (message):
>   Failed to checkout tag: 'f150595a2cea0ff5c6c046b8122c77a602aeddf6'
> 
> 
> CMakeFiles/project_ngraph.dir/build.make:89: recipe for target 'ngraph/src/project_ngraph-stamp/project_ngraph-download' failed
> make[2]: *** [ngraph/src/project_ngraph-stamp/project_ngraph-download] Error 1
> CMakeFiles/Makefile2:1009: recipe for target 'CMakeFiles/project_ngraph.dir/all' failed
> make[1]: *** [CMakeFiles/project_ngraph.dir/all] Error 2
> ```
> 
> But https://github.com/NervanaSystems/ngraph/tree/f150595a2cea0ff5c6c046b8122c77a602aeddf6 is in ngraph tree. Could you please advice?

The commitid might exist but maybe not reachable from a clone for whatever reason. Can you try to reproduce locally? Or try using a tag?

**Comment by ilya-lavrenov** [comment]
used tag, let's re-start CI.

**Comment by ilya-lavrenov** [comment]
It seems the issue is not with touching of `ngraph.cmake`. Even with tags I have the same issue with patch applying. 

Re-done changes and removed patch applying to protobuf. Please, re-start.

**Comment by ilya-lavrenov** [comment]
Can someone fix credential on build server?

```
warning: squelched 2 whitespace errors
warning: 7 lines add whitespace errors.

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'onnxruntimedev@cus-cpu-22lc.(none)')
Cannot save the current index state
CMake Error at /build/Release/ngraph/tmp/project_ngraph-gitupdate.cmake:83 (message):
  Failed to stash changes
```

**Comment by jywu-msft** [comment]
> Can someone fix credential on build server?
> 
> ```
> warning: squelched 2 whitespace errors
> warning: 7 lines add whitespace errors.
> 
> *** Please tell me who you are.
> 
> Run
> 
>   git config --global user.email "you@example.com"
>   git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
> 
> fatal: unable to auto-detect email address (got 'onnxruntimedev@cus-cpu-22lc.(none)')
> Cannot save the current index state
> CMake Error at /build/Release/ngraph/tmp/project_ngraph-gitupdate.cmake:83 (message):
>   Failed to stash changes
> ```

It's not a build server change. It's due to your changes. @tomdol can you help? I recall you ran into same thing but I forget the reason exactly.

**Comment by ilya-lavrenov** [comment]
does anybody know how to test custom branch? Azure CI fails in most of cases.

**Comment by jywu-msft** [comment]
> does anybody know how to test custom branch? Azure CI fails in most of cases.

@postrational, @tomdol can you guys help? I'm currently out of office.

**Comment by tomdol** [comment]
Sorry for a late reply, I was out of the office too. AFAIK this won't work when you specify a branch name in the .cmake file because git tries stashing any changes before switching to that branch. Usually git is not configured with any credentials in CI and stashing requires those (because it's in fact a commit).

My solution was to use a commit id instead of a branch name (top commit in the branch that you wanted to test) and that always worked. Unfortunately I don't know why you're getting errors in this PR.

You can run the full CI locally on your machine using build.sh or build.bat from the root directory of this repo or using the tools/ci_build/build.py script.

**Comment by jywu-msft** [comment]
> does anybody know how to test custom branch? Azure CI fails in most of cases.

currently it looks like you are still not pointing to a tag or commitid. please use commitid. i suspect you aren't able to add a tag for https://github.com/NervanaSystems/ngraph (the tags all look official)
I think your previous attempt to use commitd was failing for a different reason (protobuf patch)
which probably should be resolved after you removed the patch file?
can you please test the build locally as @tomdol mentioned? 
we should only trigger the CI after changes are tested and working.

**Comment by tomdol** [comment]
I've just realized something. You've created this PR from your own fork of `microsoft/onnxruntime` repository. If you only set the commit id in `ngraph.cmake` and try running the CI it won't work, because you're pointing to your fork, not to `NervanaSystems/onnxruntime`. If you want to test it in CI you need to set 2 variables in `ngraph.cmake`:
```
set(ngraph_URL "https://github.com/ilya-lavrenov/onnxruntime")
set(ngraph_TAG "<top commit id from il/export-symbols>")
```

I would recommend you moving your changes to our fork (`NervanaSystems/onnxruntime`) though because we have set up a similar CI there.

**Comment by ilya-lavrenov** [comment]
@tomdol, `ngraph_URL` is used to point to `ngraph` branch and I used ngraph branch which is in `NervanaSystems` group.

**Comment by jywu-msft** [comment]
> I've just realized something. You've created this PR from your own fork of `microsoft/onnxruntime` repository. If you only set the commit id in `ngraph.cmake` and try running the CI it won't work, because you're using a commit id from your fork, not from `NervanaSystems/onnxruntime`. If you want to test it in CI you need to set 2 variables in `ngraph.cmake`:
> 
> ```
> set(ngraph_URL "https://github.com/ilya-lavrenov/onnxruntime")
> set(ngraph_TAG "<top commit id from il/export-symbols>")
> ```
> 
> I would recommend you moving your changes to our fork (`NervanaSystems/onnxruntime`) though because we have set up a similar CI there.

Thanks @tomdol
I didn't realize it was a forked repo
@ilya-lavrenov  , I believe you should follow @tomdol 's suggestion. (set the URL to your forked repo and use the commitID of latest commit in your branch)
You can test the build locally first.

**Comment by jywu-msft** [comment]
> > I've just realized something. You've created this PR from your own fork of `microsoft/onnxruntime` repository. If you only set the commit id in `ngraph.cmake` and try running the CI it won't work, because you're using a commit id from your fork, not from `NervanaSystems/onnxruntime`. If you want to test it in CI you need to set 2 variables in `ngraph.cmake`:
> > ```
> > set(ngraph_URL "https://github.com/ilya-lavrenov/onnxruntime")
> > set(ngraph_TAG "<top commit id from il/export-symbols>")
> > ```
> > 
> > 
> > I would recommend you moving your changes to our fork (`NervanaSystems/onnxruntime`) though because we have set up a similar CI there.
> 
> Thanks @tomdol
> I didn't realize it was a forked repo
> @ilya-lavrenov , I believe you should follow @tomdol 's suggestion. (set the URL to your forked repo and use the commitID of latest commit in your branch)
> You can test the build locally first.

small correction.
the url should point to ilya's forked ngraph repo, not onnxruntime

https://github.com/ilya-lavrenov/ngraph
that is where il/export-symbols branch resides.

**Pull request closed without merging**
