### PR TITLE
Make Java API available on Android

### PR DESCRIPTION
**Pull request by daquexian**
**Description**:

Java API is introduced by the great work of @Craigacp. This PR makes it available on Android and builds an Android Archive (AAR) file for Android developers

**Motivation and Context**
- Why is this change required? What problem does it solve?
It solves the problem that Java API cannot be built correctly for Android

### CODE REVIEW

**Comment by daquexian** [comment]
@maintainers I just found the Java build system is being overhauled in #2866. I will update this PR after #2866 is merged

**Comment by snnn** [comment]
#2866 is merged. Please rebase your work on that.

**Comment by daquexian** [comment]
@snnn I have updated it.

**Comment by Craigacp** [comment]
Looks like it's not possible to build both the Android package and the Java package in the same build process? As far as I can tell it's possible to build all the other language bindings in the same build, so is it worth trying to fix this?

**Comment by snnn** [comment]
@daquexian Please fix the build errors.

**Comment by daquexian** [comment]
> Looks like it's not possible to build both the Android package and the Java package in the same build process? As far as I can tell it's possible to build all the other language bindings in the same build, so is it worth trying to fix this?

I have made some updates. Now it is possible to build Android package and Java package in the same process

**Comment by daquexian** [comment]
@snnn Could you please trigger the CI once more? Thanks!

**Comment by daquexian** [comment]
@snnn I have fixed the error. Could you please trigger the CI again? Thanks!

**Comment by tim-jagenberg-ws** [comment]
I'm successfully building on Ubuntu 18.04 for Android, but I do not get the *.aar:

`./build.sh --android --android_sdk_path ~/Android/Sdk/ --android_ndk_path ~/Android/android-ndk-r21b/ --android_abi arm64-v8a --android_api 28 --build_shared_lib --use_dnnlibrary`

Any tips on how to get the build to produce the *.aar file?

**Comment by fran6co** [comment]
@tim-jagenberg-ws you'll find it in `build/Linux/Debug/java/build/android/outputs/aar/`

> I'm successfully building on Ubuntu 18.04 for Android, but I do not get the *.aar:
> 
> `./build.sh --android --android_sdk_path ~/Android/Sdk/ --android_ndk_path ~/Android/android-ndk-r21b/ --android_abi arm64-v8a --android_api 28 --build_shared_lib --use_dnnlibrary`
> 
> Any tips on how to get the build to produce the *.aar file?

**Pull request merged**
