### PR TITLE
Make incremental builds more robust with CONFIGURE_DEPENDS

### LINKED ISSUE #906: Use CONFIGURE_DEPENDS in file(GLOB*
ONNX RT makes heavy use of globbing to collect source files in the CMake scripts. This can lead to breaks when doing incremental builds where files are removed/added without otherwise touching the CMake files. This issue can be avoided either by explicitly listing all source files, or by using [`CONFIGURE_DEPENDS`](https://cmake.org/cmake/help/v3.13/command/file.html#glob-recurse) which re-runs glob during build to check whether CMake has to be re-configured.

Note that this is only an issue when not using the `tools/ci_build/build.py` script (which by default would do an `--update` that re-configures CMake each time) and instead running CMake directly. Using CMake directly is useful when consuming onnxruntime via `add_subdirectory` from another project.

### PR DESCRIPTION
**Pull request by letmaik**
Closes #906.

### CODE REVIEW

**Comment by snnn** [comment]
Does it work on Windows?

**Comment by letmaik** [comment]
Sure, why not?

**Comment by letmaik** [comment]
I haven't compared build times. By definition they will be longer, but I doubt it's noticeable since this is only for ONNX RT's source files, not of dependencies, and there aren't that many to be honest.

**Pull request merged**
