### PR TITLE
Fix ARMv7 build

### PR DESCRIPTION
**Pull request by lukasberbuer**
Fix ARMv7 build error on Linux.

### Description

`cpuinfo_*` functions are only available if `CPUINFO_SUPPORTED` set and therefore `"cpuinfo.h"` included.
Fixed with extended conditional code.

### Motivation and Context
Compilation with ARMv7 on Linux system fails.

### CODE REVIEW

**Comment by ytaous** [comment]
@chenfucn

**Review by chenfucn — DISMISSED** [review]

**Review by chenfucn — APPROVED** [review]

**Comment by lukasberbuer** [comment]
@chenfucn, the failed builds seem to be build configuration errors `Python bindings use typeid so you can't disable RTTI`. How to proceed?

**Pull request merged**
