### PR TITLE
[CANN] add more operators

### PR DESCRIPTION
**Pull request by FFFrog**
### Description
Adding new operators and  enhances operators, also.

### Motivation and Context
The operators of CANN EP is modified as follows:

The list of enhanced operators is as follows:

- Add
- Sub
- Mul
- Div
- Gemm
- MatMul
- AveragePool
- GlobalAveragePool
- MaxPool
- GlobalMaxPool
- Dropout

The new operators are as follows:

- Abs
- Neg
- Floor
- Ceil
- Reciprocal
- Sqrt
- Log
- Exp
- Erf
- Round
- Sin
- Cos
- Cast
- Reshape
- Transpose

The remaining operators will be supported in the next PRs.

### CODE REVIEW

**Comment by FFFrog** [comment]
@jywu-msft Hi, sorry to @ you again. The new pr is ready for review. Big thanks for your help.

**Comment by jywu-msft** [comment]
> @jywu-msft Hi, sorry to @ you again. The new pr is ready for review. Big thanks for your help.

Thanks! We will take a look. It will take some time to review.

**Comment by FFFrog** [comment]
> Windows GPU CI Pipeline

Thanks for your review :)

There are two error messages here:

1. The first error (LGTM analysis: C/C++) is due to the lower version of cmake in the CI environment
2. The second error (Windows GPU CI Pipeline) is due to the missing builder module in google.protobuf.internal

These two errors may be caused by the CI environment.

**Comment by FFFrog** [comment]
@jywu-msft Hi, sorry to @ you again. The problem of the cmake version should have been fixed, can you please help to re-trigger the ci? Big thanks for your help.

**Comment by jywu-msft** [comment]
> @jywu-msft Hi, sorry to @ you again. The problem of the cmake version should have been fixed, can you please help to re-trigger the ci? Big thanks for your help.

thanks. sorry for the delay, it was thankgiving holidays in the U.S. so I was out of the office. Will take a look this upcoming week.

**Comment by FFFrog** [comment]
> > @jywu-msft Hi, sorry to @ you again. The problem of the cmake version should have been fixed, can you please help to re-trigger the ci? Big thanks for your help.
> 
> thanks. sorry for the delay, it was thankgiving holidays in the U.S. so I was out of the office. Will take a look this upcoming week.

Sorry to interrupt your thanksgiving break, I will ask for your help during your working hours in the future, sorry again for that.

**Comment by jywu-msft** [comment]
> > > @jywu-msft Hi, sorry to @ you again. The problem of the cmake version should have been fixed, can you please help to re-trigger the ci? Big thanks for your help.
> > 
> > 
> > thanks. sorry for the delay, it was thankgiving holidays in the U.S. so I was out of the office. Will take a look this upcoming week.
> 
> Sorry to interrupt your thanksgiving break, I will ask for your help during your working hours in the future, sorry again for that.

no worries. i've looked through the code and also kicked off CI's.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
