### PR TITLE
[WebNN EP] Fall back resize nearest mode for WebNN CPU backend

### PR DESCRIPTION
**Pull request by zesongw**
WebNN CPU backend only supports linear mode. Fall back for this case.

### CODE REVIEW

**Comment by zesongw** [comment]
@fdwr, @guschmue, PTAL, thanks!

**Review by guschmue — APPROVED** [review]

**Review by fdwr — COMMENTED** [review]
LGTM. It would be nice if we had some way to more generically query these from the WebNN implementation, but I wager this won't be a real problem once the backends are more mature with the spec.

**Pull request merged**
