### PR TITLE
Revert "[WebNN] Fallback the node when its output doesn't have shape info"

### PR DESCRIPTION
**Pull request by shiyi9801**
Reverts microsoft/onnxruntime#22556 since it causes incorrect fallback.

### CODE REVIEW

**Comment by shiyi9801** [comment]
This PR reverts "[WebNN] Fallback the node when its output doesn't have shape info" since it mistakenly fallbacks the entire model if this model has outputs that don't have shape info.
@Honry @fdwr @guschmue Please help approve, thanks!

**Review by Honry — APPROVED** [review]
👍

**Review by fdwr — APPROVED** [review]
> if this model has outputs that don't have shape info

Darn, I actually wondered that possibility while reviewing but then dismissed it because I figured shape inference would have propagated all the way to the end given WebNN need static graphs anyway and that the free dimensions should be specified.

**Comment by fdwr** [comment]
> @github-actions Lint / Python format (pull_request)

> /mnt/vss/_work/_temp/f52fee79-71e9-4c38-bfdf-69bddd952f12.sh: line 3: lintrunner: command not found
> Error: Invalid value for 'INPUT': 'lint.json': No such file or directory

This looks completely unrelated to your C++ change :/.

**Pull request merged**
