### PR TITLE
ppc64le: optimizing the MlasRequantizeOutput() with VSX

### PR DESCRIPTION
**Pull request by maxiwell**
This VSX code is compatible with Power8, Power9, and Power10

### CODE REVIEW

**Comment by maxiwell** [comment]
@yufenglee Requesting review.

**Comment by maxiwell** [comment]
I updated my code using the last `quantize.cpp` version

**Review by yufenglee — APPROVED** [review]

**Comment by yufenglee** [comment]
@maxiwell, the fix of Web CI pipeline break was just merged into master. You need to sync up to master to pass it.

**Review by yufenglee — APPROVED** [review]

**Pull request merged**
