### PR TITLE
Fixed compilation with ngraph

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
**Description**: 

Solves linker errors with https://github.com/NervanaSystems/ngraph/pull/3767

**Motivation and Context**
- We are trying to enable proper ngraph API export in https://github.com/NervanaSystems/ngraph/pull/3767. When we import `ngraph` as a static library, we experience linker errors. So, I have imported as a `SHARED` one, but with additional import library (.lib) file.

### CODE REVIEW

**Comment by snnn** [comment]
If I understand correctly, the ngraph lib doesn't have a C interface, and it uses google protobuf. 
So, if you build it as a shared library, it will "provide" some of the google protobuf symbols, and they will duplicate with the symbols in onnxruntime. And when you pass a protobuf object between the shared lib boundaries, bad things can happen.

**Comment by ilya-lavrenov** [comment]
Ngraph is always built as a dynamic library, I'm just properly importing it.

**Comment by jywu-msft** [comment]
Yes, ngraph has always been shared lib.
Re: the protobuf issue, that is why ngraph has to be patched to use the same protobuf version as ORT (v3.6.1).
see https://github.com/microsoft/onnxruntime/blob/master/cmake/patches/ngraph/ngraph_protobuf.patch#L14

so if ORT ever uses a different version of protobuf, that patch should be updated.

**Pull request merged**
