### PR TITLE
Add Ort::Session constructor overload to load from std::istream

### PR DESCRIPTION
**Pull request by chausner-audeering**
**Description**: This adds a constructor overload to `Ort::Session` for loading a model from a `std::istream` object. A corresponding function `CreateSessionFromStream` is also added to the C API using a language-agnostic abstraction `OrtInputStream` which is basically a wrapper around a function callback for reading from a stream.

I also added a basic unit test for loading a model from an `std::ifstream`.

**Motivation and Context**
- Currently, it is only possible to load models from disk via a file path or from a memory buffer. In the latter case, the full model needs to be loaded in memory. This a limitation when models need to be pre-processed/transformed, loaded from the network or similar. For example, model files may be stored in compressed form on disk. Currently, the file needs to be decompressed fully to memory before it can be loaded with onnxruntime.
- `InferenceSession` already has a constructor that accepts a `std::istream` object but it appears nowhere to be used at the moment. Also, that class is not part of the public headers as far as I know, thus not intended to be used by library consumers.

This PR is currently just a draft. I would like to get some initial feedback on whether such functionality would be welcomed and if this is the way to implement it or if there is a better way.

### CODE REVIEW

**Comment by chausner-audeering** [comment]
> InferenceSession already has a constructor that accepts a std::istream object but it appears nowhere to be used at the moment. Also, that class is not part of the public headers as far as I know, thus not intended to be used by library consumers.

In theory, though, for C++ users statically linking to onnxruntime, is there anything speaking against simply calling these internal APIs directly?

**Comment by chausner-audeering** [comment]
@snnn Could you or somebody else of the maintainer team have a look at this MR and let me know if you would be open to accept these additions in this or a similar form? I am happy to make changes if desired. Thanks! :)

**Comment by chausner-audeering** [comment]
> As long as protobuf is in use, it's very hard to avoid the double copy. 

Hmm okay. I thought `ParseFromZeroCopyStream` would enable exactly that, i.e. avoid a copy of the data during the protobuf parsing. I have not done any measurements myself, however, so am I understanding you right that you say, even with my implementation proposal, peak memory usage would not be reduced over loading the ONNX model from a memory buffer?

> If peak memory usage is your concern, try onnx's external file format.

This is very interesting indeed and something we have not looked at so far. I understand that the idea is to memory-map the external weights file and pass that via `AddInitializer` to ONNX Runtime. We'll probably have a look at this.

I'll close this MR for now.

**Comment by Linux13524** [comment]
Hi. We used this patch here together with an `std::ifstream` to improve our peak memory usage by quiet a bit. In one case from ~650MB to ~450MB peak memory during model loading. We were also able to implement a stream based decryption to decrypt the models on the file. Before we needed to decrypt the whole file into memory before it could be loaded in ORT which was leading to high overhead in peak memory consumption of course.
Having this implemented in ORT and not needing to apply this patch manually (and updating on every ORT update) would help us a lot. Is there any chance this could be pulled into ORT @snnn? I could also help adapting this patch to the latest ORT version if needed.

**Pull request closed without merging**
