### PR TITLE
fix import in transformer optimizer python script

### PR DESCRIPTION
**Pull request by xiaoyu-work**
### Description

Fix import.

### Motivation and Context
Fix error.

### CODE REVIEW

**Comment by tianleiwu** [comment]
Both are fine, though it is more consistent after the change.

**Review by tianleiwu — APPROVED** [review]

**Comment by xiaoyu-work** [comment]
> Both are fine, though it is more consistent after the change.

There was an import bug for this so I sent out this PR to fix that:
```
from onnxruntime.transformers.onnx_utils import extract_raw_data_from_model, has_external_data
ModuleNotFoundError: No module named 'onnxruntime.transformers.onnx_utils'
```

**Pull request merged**
