### PR TITLE
Add default C++ initialization to OrtCUDAProviderOptions

### PR DESCRIPTION
**Pull request by RyanUnderhill**
**Description**: Adds a C++ default initializer to prevent accidental uninitialized fields. Especially for new fields added between versions.

This will prevent this issue from this user from happening again:
https://github.com/microsoft/onnxruntime/issues/9038

### CODE REVIEW

**Comment by pranavsharma** [comment]
Are there other structs that could benefit from this?

**Comment by RyanUnderhill** [comment]
> Are there other structs that could benefit from this?

Yes, ROCM could also use it, OrtTensorRTProviderOptions is deprecated. I was going to make some more fixes in separate changes.

**Comment by askhade** [comment]
@RyanUnderhill : What do you mean by OrtTensorRTProviderOptions is deprecated?

**Comment by pranavsharma** [comment]
> @RyanUnderhill : What do you mean by OrtTensorRTProviderOptions is deprecated?

We won't be extending OrtTensorRTProviderOptions any more since extending it makes our API ABI incompatible. Hence we introduced [this](https://github.com/microsoft/onnxruntime/blob/0034ad72e6c6da0a343565fb3d5364a7cec53137/include/onnxruntime/core/session/onnxruntime_c_api.h#L1450-L1487).

**Comment by RyanUnderhill** [comment]
> @RyanUnderhill : What do you mean by OrtTensorRTProviderOptions is deprecated?

There is OrtTensorRTProviderOptionsV2 that should be used instead going forward.

**Review by askhade — APPROVED** [review]

**Pull request merged**
