### PR TITLE
Add /Qspectre compiler flags

### PR DESCRIPTION
**Pull request by jignparm**
Adding compiler options to guard against security vulnerabilities  (/Qspectre and /guard:cf). Part of SDL compliance activity.

### CODE REVIEW

**Comment by pranavsharma** [comment]
Should this option be enabled by default? Is there any reason we wouldn't want to enable this? Trying to see if we can eliminate this additional build option.

**Comment by jignparm** [comment]
> Should this option be enabled by default? Is there any reason we wouldn't want to enable this? Trying to see if we can eliminate this additional build option.

Only consideration is that users building on Windows will require Visual Studio with  KB 4338871 installed to enable the /Qspectre option (see https://aka.ms/Ofhn4c). This is not installed by default on community editions of VS or Azure VMs. So compiling OnnxRuntime out of the box would require most users to install the toolset.

We can set as the default option however, if we're looking to reduce number of build configurations.

**Comment by RyanUnderhill** [comment]
Is it known how Spectre could affect inference? Since we don't have any timing functions I'm not sure how someone could read protected memory by running a model.

**Comment by jignparm** [comment]
Regarding performance, the quote from the /Qspectre page mentions there should be negligible impact. It seems that loading a model could potentially be considered crossing a trust boundary, since it falls under "parses untrusted input or files" category. 

>**"The performance impact of /Qspectre has been seen to be negligible in several very large code bases, but there are no guarantees that performance of your code under /Qspectre remains unaffected"**

**Comment by pranavsharma** [comment]
Since this flag is going to be part of the officially released binaries, let's verify it doesn't affect the performance of most important 1P models.

**Comment by jignparm** [comment]
A brief summary of performance numbers for ResNet and TinyYolo.  The code base is exactly the same, one DLL is built using **--enable_qspectre**, another without it.

**/Qspectre** is not seem to be negatively impacting performance. It seems to result in slightly more efficient scoring code (at least for these two models).

with /Qspectre flag
-------------------

D:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo>onnxruntime_perf_test.exe -s -r 1000 d:\models\test_resnet50\model.onnx perf.resnet.withspectre.txt
Setting thread pool size to 6
Total time cost:35.8138
Total iterations:1000
Average time cost:35.8138 ms


D:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo>onnxruntime_perf_test.exe -s -r 1000 d:\models\test_tiny_yolov2\model.onnx perf.yolo.withspectre.txt
Setting thread pool size to 6
Total time cost:30.2484
Total iterations:1000
Average time cost:30.2484 ms


Without /Qspectre flag
----------------------

D:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo>onnxruntime_perf_test.exe -s -r 1000 d:\models\test_resnet50\model.onnx perf.resnet.withoutspectre.txt
Setting thread pool size to 6
Total time cost:39.4769
Total iterations:1000
Average time cost:39.4769 ms

D:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo>onnxruntime_perf_test.exe -s -r 1000 d:\models\test_tiny_yolov2\model.onnx perf.yolo.withoutspectre.txt
Setting thread pool size to 6
Total time cost:35.7952
Total iterations:1000
Average time cost:35.7952 ms

**Comment by pranavsharma** [comment]
Thanks Jignesh for the performance numbers. Given the numbers, should be enable it by default? If it's the default there's one less thing to worry about in build configs.

**Comment by jignparm** [comment]
> Thanks Jignesh for the performance numbers. Given the numbers, should be enable it by default? If it's the default there's one less thing to worry about in build configs.

Only consideration is that users building on Windows will require Visual Studio with KB 4338871 installed to enable the /Qspectre option (see https://aka.ms/Ofhn4c). This is not installed by default on community editions of VS or Azure VMs. So compiling OnnxRuntime out of the box would require most users to install the toolset.

If these are made mandatory, the installation steps Build.md can be updated (small change), but the primary issue is requiring users to install the spectre libraries even though they are not required. Preference is to keep it optional (for ease of compilation for users). If there are any strong thoughts otherwise, we can make these flags mandatory.

**Comment by pranavsharma** [comment]
Also, can you find out how much additional binary size does this add?

**Comment by jignparm** [comment]
The binary dll size is 4,855,808 bytes without spectre, and 4,882,944 bytes with spectre. So about 0.5% diff (27KB).

**Comment by snnn** [comment]
Hi
Why do you add /Zi there?

**Comment by jignparm** [comment]
If /Qspectre is specified without /Zi, BinSkim cannot analyze the binary file. Therefore need to set /Zi whenever /Qspectre is set. /Zi is usually set by default in Debug build and RelWithDebInfo, but not for Release build.

**Comment by snnn** [comment]
The why don't use the Release build?

**Pull request merged**
