### PR TITLE
Update Git submodule cgmanifest.json.

### PR DESCRIPTION
**Pull request by edgchen1**
**Description**
Sync submodule cgmanifest.json.

**Motivation and Context**
Keep the submodule cgmanifest.json file up to date.

### CODE REVIEW

**Comment by pranavsharma** [comment]
Is there any value in separating cgmanifest.json into 2 separate dirs? I would rather have one file where I can look for all external deps.

**Comment by edgchen1** [comment]
> Is there any value in separating cgmanifest.json into 2 separate dirs? I would rather have one file where I can look for all external deps.

@pranavsharma The value is being able to run a script to generate one for submodules at the correct versions. In fact, it might be better to not check in the submodules one at all and have it be generated by the CI build, so we don't need to remember (or know) to update it.

**Comment by pranavsharma** [comment]
> > Is there any value in separating cgmanifest.json into 2 separate dirs? I would rather have one file where I can look for all external deps.
> 
> @pranavsharma The value is being able to run a script to generate one for submodules at the correct versions. In fact, it might be better to not check in the submodules one at all and have it be generated by the CI build, so we don't need to remember (or know) to update it.

Yeah, having a script generate the file is fine, but if the output of that script is just one single file with all deps, it'll be much better. I don't see a value of separating the deps between submodule vs otherwise. If we want to do this you can easily add metadata to the json file in the comment key to distinguish these things.

**Comment by edgchen1** [comment]
> > > Is there any value in separating cgmanifest.json into 2 separate dirs? I would rather have one file where I can look for all external deps.
> > 
> > 
> > @pranavsharma The value is being able to run a script to generate one for submodules at the correct versions. In fact, it might be better to not check in the submodules one at all and have it be generated by the CI build, so we don't need to remember (or know) to update it.
> 
> Yeah, having a script generate the file is fine, but if the output of that script is just one single file with all deps, it'll be much better. I don't see any value of categorizing and separating the deps between submodule vs otherwise. If we want to do this you can easily add metadata to the json file in the comment key to distinguish these things.

Ok. Currently they are split into two files. We can consolidate them, but then the script needs to be smart enough not to overwrite non-submodule entries. That can be done in another PR.

**Pull request merged**
