### PR TITLE
Add Pow-15 for LayerNorm Fusion and FastGelu Fusion

### PR DESCRIPTION
**Pull request by iK1D**
When working on some models that require OpSet15, the LayerNorm fusion will fail because the Pow Op with SinceVersion 15 cannot pass the supported version check. This PR is to add Pow-15 support for LayerNorm fusion and FastGelu fusion.

### CODE REVIEW

**Comment by askhade** [comment]
I don't think this is a good idea. We bump the opset version for an OP only when the change is NOT backward compatible. This PR assumes the change will be backward compatible and that seems wrong. 
ONNX rules for BC breaking are a bit strict meaning a new data type addition is considered BC breaking whereas in ORT we can deal with that change in a non BC breaking manner. However, I do not think it is safe enable fusions for new versions by default as it may introduce bugs.

**Comment by skottmckay** [comment]
> I don't think this is a good idea.

I 100% agree. You would be creating a scenario where you'd automatically enable fusion between things that may not be compatible, that may not be covered by existing unit tests, that may not be noticed until post-release. 

An alternative approach may be to update the tests to automatically find the latest opset and test the fusion still occurs with that. I would expect that is fairly expensive to implement though as there are various ways the tests can be done (load saved model with fixed opset, generate model dynamically, test just the optimizer directly, etc).

Or we could just run https://github.com/microsoft/onnxruntime/blob/master/tools/python/FindOptimizerOpsetVersionUpdatesRequired.py whenever we take an ONNX update and determine what needs changing. Looks like that's a little out of date. Will add a quick PR to make it mainly work but needs to be expanded to consider the CUDA fusions. That would have found the issue:

```
[WARNING] - Newer opset found for kOnnxDomain.Pow. Latest:15 Optimizer support ends at 13. File:.\onnxruntime/core/optimizer\fast_gelu_fusion.cc
[WARNING] - Newer opset found for kOnnxDomain.Pow. Latest:15 Optimizer support ends at 13. File:.\onnxruntime/core/optimizer\layer_norm_fusion.cc
[WARNING] - Newer opset found for kOnnxDomain.Pow. Latest:15 Optimizer support ends at 13. File:.\onnxruntime/core/optimizer\layer_norm_fusion.cc
[WARNING] - Newer opset found for kOnnxDomain.BatchNormalization. Latest:15 Optimizer support ends at 14. File:.\onnxruntime/core/optimizer\nchwc_transformer.c
```

**Comment by skottmckay** [comment]
PR for fix to script: https://github.com/microsoft/onnxruntime/pull/12330

**Comment by iK1D** [comment]
Thanks @askhade and @skottmckay . Just reverted the change and add the Pow-15 version to the fusion code.

**Review by skottmckay — APPROVED** [review]

**Pull request merged**
