### PR TITLE
[OpenVINO-EP R3.1] Disabled failed maxpool test on GPU

### PR DESCRIPTION
**Pull request by suryasidd**
**Description**: Disabled an unit test that was added recently, as it's not supported on GPU.

**Motivation and Context**
- This change is required to pass all the C++ unit tests for GPU configuration.
- One of intel's internal team is using onnxruntime with OpenVINO 3.1 and need this to be fixed.

### CODE REVIEW

**Comment by jywu-msft** [comment]
would this PR be rendered obsolete by the upcoming OpenVINO 2020.2 EP PR?

**Comment by suryasidd** [comment]
It would be, but one of our internal team has done all of their validation with R3.1 and wont be moving for a month or so to the new release. Also the upcoming PR would take some time to get merged to master right. So i thought this could be merged so that they are unblocked. Also, we discussed about a tagged release for OV3.1 right? I don't know if we are doing this but if so we can merge this in and create one.

**Comment by jywu-msft** [comment]
your branch seems pretty out of date from master. can you refresh?
it may be causing some of the CI failures.

**Comment by jywu-msft** [comment]
sorry please merge one more time. we're changing the way we're fetching test data in the CI.

**Pull request merged**
