### PR TITLE
Add unique identifier in function subgraph node

### PR DESCRIPTION
**Pull request by raymondxyang**
To fix the problem mentioned in email thread

### CODE REVIEW

**Comment by pranavsharma** [comment]
>   }

Don't we need to add the node index here too?

---
Refers to: onnxruntime/core/graph/function.cc:119 in f3b8eb6. [](commit_id = f3b8eb6b40e8888382fda314d2130e8beb46e183, deletion_comment = False)

**Comment by pranavsharma** [comment]
> > }
> 
> Don't we need to add the node index here too?
> 
> Refers to: onnxruntime/core/graph/function.cc:119 in [f3b8eb6](https://github.com/Microsoft/onnxruntime/commit/f3b8eb6b40e8888382fda314d2130e8beb46e183). [](commit_id = [f3b8eb6](https://github.com/Microsoft/onnxruntime/commit/f3b8eb6b40e8888382fda314d2130e8beb46e183), deletion_comment = False)

This didn't come out too well (had written it using CodeFlow). I was referring to another instance of AddNode invoked in the same file.

**Comment by raymondxyang** [comment]
That one is used in fusing original nodes, where all the nodes has already passed the checker and suppose to be a unique node.

**Pull request merged**
