### PR TITLE
Update googletest to latest commit to fix build issues with GCC11 

### PR DESCRIPTION
**Pull request by ankurverma85**
**Description**: Update googletest to latest commit to fix build issues with GCC11 
#7918

**Motivation and Context**

- Why is this change required? What problem does it solve?
Build issues with newer compilers

- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by snnn** [comment]
I guess it requires code changes too. Welcome to change it!

**Comment by ankurverma85** [comment]
@snnn 
 i'm not sure what you mean by that. 
 When i tried locally updating to a newer googletest commit simply worked with no further changes being requied.

**Comment by snnn** [comment]
We can try it first.

**Comment by snnn** [comment]
> @snnn
> i'm not sure what you mean by that.


Now you can see it. :-)

**Comment by ankurverma85** [comment]
> > @snnn
> > i'm not sure what you mean by that.
> 
> Now you can see it. :-)

I see . I'll abandon the PR. 

Could i perhaps ask you then to suppress all warnings from googletests cpp file compilations. 

I remember you saying it should have been there already but evidently thats not the case

**Pull request closed without merging**
