### PR TITLE
Add string attribute interface for C API.

### LINKED ISSUE #755: Support retrieving more attributes types in C API
As of writing this issue, the [`OrtCustomOpApi` interface](https://github.com/Microsoft/onnxruntime/blob/06888437dd4270b07531253673460bb26e9630ee/include/onnxruntime/core/session/onnxruntime_c_api.h#L544) can only get the float and int64 argument for the custom op. This forbids user from defining operator arguments of strings and lists. Eventually we should be able to support all ONNX attribute types listed [here](https://github.com/onnx/onnx/blob/a8b45d62de57ab9b25d7764e38e44f5e9e9c027a/onnx/onnx.proto#L95).

### PR DESCRIPTION
**Pull request by harrysummer**
This PR aims to add string attribute interface in C API. This serves as an initial attempt to ultimately resolve #755 . The string length is handled in WinAPI fashion -- need two API calls to get the string. The first one is used to get the length of the string, and the second call get the actual string.

### CODE REVIEW

**Comment by pranavsharma** [comment]
@harrysummer Can you resolve the conflict?

**Comment by harrysummer** [comment]
> @harrysummer Can you resolve the conflict?

Sorry I didn't get a chance to do this. Hopefully I will check this within this week.

**Comment by harrysummer** [comment]
Merged master to resolve conflicts.

The previous CI errors look like not related to this PR. Let's build again.

**Comment by harrysummer** [comment]
Looks like the two failed CI checks are not caused by this PR.

**Comment by RyanUnderhill** [comment]
Ok, I was able to merge these changes in another PR: https://github.com/microsoft/onnxruntime/pull/1436

Closing this one as now it's in!

**Pull request closed without merging**
