### PR TITLE
[Java] Initial Apple Silicon support

### PR DESCRIPTION
**Pull request by Craigacp**
**Description**:
The Java library loader needed support adding for aarch64 binaries, and the cmake update to put those binaries in the right place.

I also rearranged the CPU architecture detection in `cmake/onnxruntime_mlas.cmake`, as Apple Silicon Macs report their architecture as `arm64` which was previously caught by the 32-bit ARM regex.

For reference the `clang -dumpmachine` test produces this output:
```shell
$ clang -dumpmachine
arm64-apple-darwin20.1.0
```

Note this PR makes the Java tests pass on Apple Silicon, however there are test failures in the core library:

```
1: [==========] 2265 tests from 189 test suites ran. (30822 ms total)
1: [  PASSED  ] 2245 tests.
1: [  FAILED  ] 20 tests, listed below:
1: [  FAILED  ] DynamicQuantizeMatMul.Int8_test
1: [  FAILED  ] DynamicQuantizeMatMul.Int8_test_bias
1: [  FAILED  ] DynamicQuantizeMatMul.UInt8_test
1: [  FAILED  ] DynamicQuantizeMatMul.UInt8_test_bias
1: [  FAILED  ] MatMulIntegerToFloat.Int8_test
1: [  FAILED  ] MatMulIntegerToFloat.Int8_bias_test
1: [  FAILED  ] MatMulIntegerToFloat.UInt8_test
1: [  FAILED  ] MatMulIntegerToFloat.UInt8_bias_test
1: [  FAILED  ] QAttentionTest.QAttentionBatch2
1: [  FAILED  ] QAttentionTest.QAttentionPastState_u8u8
1: [  FAILED  ] QAttentionTest.QAttentionPastState_u8s8
1: [  FAILED  ] DynamicQuantLSTMTest.SmallSize
1: [  FAILED  ] DynamicQuantLSTMTest.LargeSize
1: [  FAILED  ] MatmulIntegerOpTest.MatMulInteger_WithZero_ZeroPoint
1: [  FAILED  ] MatmulIntegerOpTest.MatMulInteger_Uint8_Int8_Scalar
1: [  FAILED  ] MatmulIntegerOpTest.MatMulInteger_Uint8_Int8_GEMV
1: [  FAILED  ] ConvIntegerTest.WithGroup_2D
1: [  FAILED  ] ConvIntegerTest.WithPadding_3D
1: [  FAILED  ] ConvIntegerTest.WithStride2_2D
1: [  FAILED  ] ConvIntegerTest.WithStride3_2D
```

I've not looked into these yet, and I suspect it's because of some issues in the asm which I'll need some help to figure out.

**Motivation and Context**
- Why is this change required? What problem does it solve? Makes ONNX Runtime work on my M1 Macbook Pro.

### CODE REVIEW

**Comment by wenbingl** [comment]
@tracysh , can you share some thought about the MLAS cmake change, I personally prefer adding a MacOS  ARM64 in the cmake file, instead of detecting from the dumpout.

Also, The failures in Unit test is caused the incorrect build script, or the arch difference?

**Comment by tracysh** [comment]
The build change looks okay, but Apple has tweaked the calling convention from the standard. @Craigacp, can you try modifying onnxruntime\core\mlas\lib\aarch64\QgemmU8X8KernelNeon.S to change line 26 to the below? This packs the parameters per Apple's changes.

#if defined(__APPLE__)
        .equ    .LGemmU8X8KernelFrame_ZeroMode, 12
#else
        .equ    .LGemmU8X8KernelFrame_ZeroMode, 16
#endif

https://developer.apple.com/documentation/xcode/writing_arm64_code_for_apple_platforms

**Comment by Craigacp** [comment]
@tracysh nope, that didn't work, the same tests fail.

**Comment by Craigacp** [comment]
There's a lot of output from the errors, the start of it looks like this:
```
1: [----------] 5 tests from DynamicQuantizeMatMul
1: [ RUN      ] DynamicQuantizeMatMul.Int8_test
1: /Users/craigacp/Development/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:156: Failure
1: The difference between expected[i] and output[i] is 339801.45132279396, which exceeds threshold, where
1: expected[i] evaluates to -339800,
1: output[i] evaluates to 1.4513227939605713, and
1: threshold evaluates to 9.9999997473787516e-05.
1: i:64, provider_type: CPUExecutionProvider
1: Google Test trace:
1: /Users/craigacp/Development/onnxruntime/onnxruntime/test/common/tensor_op_test_utils.cc:14: ORT test random seed: 1017963480
1: /Users/craigacp/Development/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:156: Failure
1: The difference between expected[i] and output[i] is 358001.86117720604, which exceeds threshold, where
1: expected[i] evaluates to 358003.3125,
1: output[i] evaluates to 1.4513227939605713, and
1: threshold evaluates to 9.9999997473787516e-05.
1: i:64, provider_type: CPUExecutionProvider
1: Google Test trace:
1: /Users/craigacp/Development/onnxruntime/onnxruntime/test/common/tensor_op_test_utils.cc:14: ORT test random seed: 1017963480
1: [  FAILED  ] DynamicQuantizeMatMul.Int8_test (12 ms)
1: [ RUN      ] DynamicQuantizeMatMul.Int8_test_bias
1: /Users/craigacp/Development/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:156: Failure
1: The difference between expected[i] and output[i] is 394420.71676766872, which exceeds threshold, where
1: expected[i] evaluates to -394419.40625,
1: output[i] evaluates to 1.3105176687240601, and
1: threshold evaluates to 9.9999997473787516e-05.
1: i:64, provider_type: CPUExecutionProvider
1: Google Test trace:
1: /Users/craigacp/Development/onnxruntime/onnxruntime/test/common/tensor_op_test_utils.cc:14: ORT test random seed: 1017963480
1: /Users/craigacp/Development/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:156: Failure
1: The difference between expected[i] and output[i] is 299807.25198233128, which exceeds threshold, where
1: expected[i] evaluates to 299808.5625,
1: output[i] evaluates to 1.3105176687240601, and
1: threshold evaluates to 9.9999997473787516e-05.
1: i:64, provider_type: CPUExecutionProvider
1: Google Test trace:
1: /Users/craigacp/Development/onnxruntime/onnxruntime/test/common/tensor_op_test_utils.cc:14: ORT test random seed: 1017963480
1: [  FAILED  ] DynamicQuantizeMatMul.Int8_test_bias (13 ms)
```

**Comment by tracysh** [comment]
@Craigacp, just to double-check: if you have just the below line:

.equ .LGemmU8X8KernelFrame_ZeroMode, 12

The code I pasted above lost the underscores from the `"__APPLE__".`

**Comment by Craigacp** [comment]
Yep I just finished running it myself without the ifdef and it works fine, give me a min to recheck it with the underscores.

**Comment by Craigacp** [comment]
All tests pass with that fix. I formatted your fix so it fits in with the rest of the .S file.

**Review by wenbingl — DISMISSED** [review]

**Comment by wenbingl** [comment]
@Craigacp , did you build your project with --use_xcode, or not?

**Comment by Craigacp** [comment]
My build command line is `./build.sh --update --parallel --build --test --build_java`. I can rerun with the `--use_xcode` option.

**Comment by Craigacp** [comment]
With `--use_xcode` I get this error:
```
CMake Error in external/onnx/CMakeLists.txt:
  The custom command generating

    /Users/craigacp/Development/onnxruntime/build/MacOS/Debug/external/onnx/onnx/onnx-operators-ml.proto

  is attached to multiple targets:

    gen_onnx_operators_proto
    onnx_proto

  but none of these is a common dependency of the other(s).  This is not
  allowed by the Xcode "new build system".
```

**Comment by wenbingl** [comment]
> With `--use_xcode` I get this error:
> 
> ```
> CMake Error in external/onnx/CMakeLists.txt:
>   The custom command generating
> 
>     /Users/craigacp/Development/onnxruntime/build/MacOS/Debug/external/onnx/onnx/onnx-operators-ml.proto
> 
>   is attached to multiple targets:
> 
>     gen_onnx_operators_proto
>     onnx_proto
> 
>   but none of these is a common dependency of the other(s).  This is not
>   allowed by the Xcode "new build system".
> ```


This specific issue could be solved by buildsytem=1, but there will be more other issues.
So please merge PR after validation, and xcode issue will be addressed in the another PR.

**Comment by Craigacp** [comment]
Looks like the Mac test was cancelled? Windows doesn't seem to be setting `X86_64` like I expected, so I'll check the logic.

**Comment by Craigacp** [comment]
I've updated the Java architecture logic. To be honest it would be nice if something in CMake would consistently set the platform and architecture so I didn't have to borrow the logic from `cmake/onnxruntime_mlas.cmake`, especially given the MSVC code path doesn't set the same environment variables as the non-MSVC path, but that can be tidied up later.

**Review by wenbingl — APPROVED** [review]

**Pull request merged**
