### PR TITLE
Add  DnnlOpManager

### PR DESCRIPTION
**Pull request by georgen117**
The DnnlOpManager is able to more accurately check if a node is
supported by the DNNLExecutionProvider.

The DNNLExecutionProvider::GetCapability function has been updated
to use the DnnlOpManager.

This commit adds the ability to check if data type, attributes,
and tensor dimensions of the node are supported.

The IsDimensionSupported function is no longer needed since the checks
it was doing have been moved into the individual implementations of
the virtual class DnnlNodeCapability.

Signed-off-by: George Nash <george.nash@intel.com>

**Description**: Describe your changes.

**Motivation and Context**
- Why is this change required? What problem does it solve?
In the process of adding additional Operators to the DnnlExecutionProvider I discovered it was not checking the data type of the Operator. The EP always assumes it is working with Float32 data types. When the "Add" operator was added we discovered that an int64 "Add" was being sent to the float32 version Dnnl "Add" operator.  This will fix all the operators in the DnnlExecutionProvider so they no longer just assume the data type but actually check it.

- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Comment by jywu-msft** [comment]
there are several test failures. please take a look

/onnxruntime_src/onnxruntime/test/providers/cpu/model_tests.cc:564
Value of: _tmp_status.IsOK()
  Actual: false
Expected: true
[ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running DnnlCustomOp_11921673657945258441_0 node. Name:'DnnlExecutionProvider_DnnlCustomOp_11921673657945258441_0_0' Status Message: Status: 2, message: could not construct a memory descriptor using a format tag

**Comment by georgen117** [comment]
> there are several test failures. please take a look

Thanks @jywu-msft I had missed that there were build failures I am looking into them now.

**Comment by georgen117** [comment]
@jywu-msft can you run `Linux DNNL CI Pipeline` again to verify that the tests now pass.  Thanks.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
