### PR TITLE
Enable metadata and signature changes in graph transformers

### PR DESCRIPTION
**Pull request by Dudeldu**
After applying all the graph transformations the metadata and signature could have changes
(e.g.: new outputs got added, or the outputs/inputs got renamed). Therefore the local
copies of metadata and signature, that InferenceSession administrated for faster lookup, has to be updated, what isn't done so far. This leads to inconsistencies between the InferenceSession and the *actual* graph. And results in problems like (#4689).

As the metadata/signature orignially are stored  using `SaveModelMetadata`, this should be called after resolving the transformed graph in `Initialize` as well. Therefore I made the `SaveModelMetadata` execution idempotent by clearing the vectors/maps before refilling them. (There might maybe a better solution for this, especially for my concrete implementation). 

**Motivation and Context**
As described in issue #4689, i had a problem with not being able to set new outputs inside a graph transformer. While further investigating my issue, i thought about generally enabeling metadata/signature changes for graph transformers (mainly adding/removing/renaming in- or output)

### CODE REVIEW

**Comment by faxu** [comment]
@Dudeldu could you please resolve conflicts?

**Comment by Dudeldu** [comment]
> @Dudeldu could you please resolve conflicts?

Done

**Comment by pranavsharma** [comment]
What's the use case for changing the inputs/outputs of the graph during transformations? Do you've a concrete scenario in mind?

**Comment by Dudeldu** [comment]
I have the two conrete issues, i wanted to adress:
 - To get my graph outputs always a uniforme way (that's required in my enviroment), i wanted to insert cast nodes at each of the *original* outputs. (This was possbile before with a hacky workaround, but at least renaming the output node to something like *OUTPUT*_string wasn't)
- In some cases I wanted to drop some of the outputs, less for optimization purposes (although this could be also the case) but more for the simplicity of the model. Therefore I not only had  to *unplug* the unused output, but also remove it from the ouputs list.

**Pull request merged**
