### PR TITLE
Upgrade tf 2.4.1 to 2.4.2 for component governance

### PR DESCRIPTION
**Pull request by oliviajain**
**Description**: Upgrade tf version for component governance

**Motivation and Context**
- necessary for compliance of MacOS CI, MacOS NoContribops CI

### CODE REVIEW

**Comment by jywu-msft** [comment]
You mentioned it's needed for Linux GPU TensorRT GPU CI? Why is that? 
this is only for python api documentation right? 
also, it's not clear to me why tensorflow package is needed for our python documentation.

**Comment by oliviajain** [comment]
> You mentioned it's needed for Linux GPU TensorRT GPU CI? Why is that?
> this is only for python api documentation right?
> also, it's not clear to me why tensorflow package is needed for our python documentation.

I was following this reference [here](https://dev.azure.com/onnxruntime/onnxruntime/_componentGovernance/112016/alert/5191655?typeId=588176), but you're right in that Component Detection succeeds on the [Linux GPU TensorRT CI](https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=417104&view=logs&j=e3c0c568-7de3-59a2-10fc-6735e4b33109&t=f74b7a2f-f405-5fed-255f-94a2b7d97dbb&l=1)

**Comment by oliviajain** [comment]
- [Mac OS](https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=417151&view=results)
- [Mac OS Contribops](https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=417157&view=results)

**Comment by snnn** [comment]
Let me try if all the packaging pipelines also work.

**Comment by oliviajain** [comment]
**Tf Options**

- Original Master: tensorflow>=2.2.0,<2.5.0. 
- Azure pipeline:  2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0
- Component Gov: TensorFlow 2.5.0, TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4

So no version satisfies all 3 - @thiagocrepaldi any suggestions? Is the original master tf range adjustable?

**Comment by thiagocrepaldi** [comment]
> Python Packaging Pipelines are failing with this change.
> 
> **Tf Options**
> 
> * Original Master: tensorflow>=2.2.0,<2.5.0.
> * [Azure pipeline](https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=158909&view=logs&j=25a0b15b-27e3-58da-824e-95bfbec57ddf&t=62f44121-1cd3-593b-6988-ba82a34680cd&l=43):  2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, **2.5.0**
> * Component Gov: TensorFlow **2.5.0**, TensorFlow 2.4.2, TensorFlow 2.3.3, TensorFlow 2.2.3 and TensorFlow 2.1.4
> 
> So no version satisfies all 3 - @thiagocrepaldi any suggestions? Is the original master tf range adjustable to include 2.5.0?

In the past 2.5.0 was causing conflicts with existing python modules, so I had to restrict it. Not sure if that is the case yet, I think it will be a trial and error fix.

**Review by snnn — APPROVED** [review]

**Pull request merged**
