### PR TITLE
Fix TensorRT memory leaks

### PR DESCRIPTION
**Pull request by alkoumpa**
**Description**: Describe your changes.

Instead of passing a raw pointer inside `struct TensorrtFuncState`, I'm passing a pointer to a unique_pointer class. This concerns variables `context` and `engine`. This way we can call `destroy` method inside `compute_func` in case there's a change update and the engine needs to be recreated. The call to `destroy` is made indirectly using `reset` method of unique_pointer. The order in which `reset` is being called is important, if violated TensorRT explodes. 

**Motivation and Context**

This change is required in order to resolve the memory leak issues that arise when the TensorRT provider re-creates an engine due to input size change. 
I'm not aware of an open issue for this.

### CODE REVIEW

**Comment by jywu-msft** [comment]
@stevenlix FYI

**Comment by jywu-msft** [comment]
@alkoumpa There's an intermittent failure that causes some pipelines to fail (not related to your change). Can you merge to the latest master to pick up the fix?

**Comment by alkoumpa** [comment]
@jywu-msft done!

**Pull request merged**
