### PR TITLE
[js/webgpu] fix conv1d error

### PR DESCRIPTION
**Pull request by xhcao**

### CODE REVIEW

**Comment by xhcao** [comment]
@guschmue Please take a look, thanks. The patch addresses the issue https://github.com/microsoft/onnxruntime/issues/21108

**Comment by xhcao** [comment]
@satyajandhyala @axinging PTAL

**Review by guschmue — APPROVED** [review]

**Comment by guschmue** [comment]
main you merge with main? CI pipeline setup changed,

**Comment by xhcao** [comment]
@guschmue I can't merge it

**Comment by guschmue** [comment]
wired. Maybe the easiest would be to create a new PR with the 1 file on main.

**Comment by xhcao** [comment]
> wired. Maybe the easiest would be to create a new PR with the 1 file on main.

@guschmue , we are conflicted why should create a new PR, we think it is OK to update the code to the latest main, so I only rebase the code.
Do I misunderstand your comments?

**Review by fs-eire — APPROVED** [review]

**Comment by fs-eire** [comment]
> > wired. Maybe the easiest would be to create a new PR with the 1 file on main.
> 
> @guschmue , we are conflicted why should create a new PR, we think it is OK to update the code to the latest main, so I only rebase the code. Do I misunderstand your comments?

You are right. we usually do what you said. the problem is sometimes the build pipeline was not working as expected and we didn't know the reason. and when this happens, creating a new PR may fix it.

I triggered the pipeline again and let's see if it works this time.

**Pull request merged**
