### PR TITLE
[webgpu] Optimize matmulnbits with M > 1

### PR DESCRIPTION
**Pull request by qjia7**
This is the webgpu native ep implementation of #23092.

I used https://github.com/fs-eire/ort-webgpu-nodejs-chatapp-prototype to test. Meanwhile, applied https://github.com/fs-eire/ort-webgpu-nodejs-chatapp-prototype/pull/2 to print the first token time.

The result is like below:
The latest main branch:
Intel Arc Graphics
```
659 tokens in 24.8sec, 26.57 tokens/sec
    Decoding first token with input 449 tokens: 13.0 sec
    Decoding remaining 210 tokens:
        11.8 sec
        17.79 tokens/sec
```
NV RTX 2000
```
659 tokens in 14.4sec, 45.85 tokens/sec
    Decoding first token with input 449 tokens: 7.3 sec
    Decoding remaining 210 tokens:
        7.0 sec
        29.81 tokens/sec
```
-------------------------------------------------------------------------
With this PR:
Intel Arc Graphics
```
657 tokens in 20.6sec, 31.92 tokens/sec
    Decoding first token with input 449 tokens: 8.5 sec
    Decoding remaining 208 tokens:
        12.1 sec
        17.23 tokens/sec
```
NV RTX 2000
```
659 tokens in 11.4sec, 57.93 tokens/sec
    Decoding first token with input 449 tokens: 4.1 sec
    Decoding remaining 210 tokens:
        7.2 sec
        28.98 tokens/sec
```

From above data, you can see that with this PR, both intel (13s -> 8.5s) and NV (7.3s -> 4.1s) GPUs for the first token time are performing better.

### CODE REVIEW

**Comment by qjia7** [comment]
@sushraja-msft @sushanthr Currently, I only test it on my laptop with dual GPUs. You can find the data in above description message. Please help verify it in your side to see if we can see similar result since our gpus and benchmarks are not same. 

cc @guschmue @fs-eire This PR still needs to be further refactored to reduce some duplicated codes. Now it's just for verification.

**Comment by sushraja-msft** [comment]
> @sushraja-msft @sushanthr Currently, I only test it on my laptop with dual GPUs. You can find the data in above description message. Please help verify it in your side to see if we can see similar result since our gpus and benchmarks are not same.
> 
> cc @guschmue @fs-eire This PR still needs to be further refactored to reduce some duplicated codes. Now it's just for verification.

Ran your change on my intel Xe laptop, this is faster than mine 👏. 55tk's vs 44tk's in mine. 
We should land yours and its okay to remove my implementation @guschmue @qjia7 

```
C:\model_benchmark>model_benchmark.exe -i C:\Phi-3.5-mini-instruct-onnx-web\Phi-3.5-mini-instruct-onnx-web -l 500
Batch size: 1, prompt tokens: 501, tokens to generate: 128
Prompt processing (time to first token):
        avg (us):       9.10299e+06
        avg (tokens/s): 55.0369                                <<<<
        p50 (us):       9.09658e+06
        stddev (us):    13042.6
        n:              5 * 501 token(s)
Token generation:
        avg (us):       79482.3
        avg (tokens/s): 12.5814
        p50 (us):       79505.4
        stddev (us):    2280.06
        n:              635 * 1 token(s)
Token sampling:
        avg (us):       18.0841
        avg (tokens/s): 55297.3
        p50 (us):       14.4
        stddev (us):    24.9088
        n:              640 * 1 token(s)
E2E generation (entire generation loop):
        avg (ms):       19199.6
        p50 (ms):       19200.1
        stddev (ms):    20.0724
        n:              5
Peak working set size (bytes): 5470642176
WebGPU device lost (2): Device was destroyed.```

**Comment by guschmue** [comment]
very cool JiaJia, I can run it on a bunch of machines

**Comment by qjia7** [comment]
@guschmue @fs-eire This is ready for review. Please take a look, thanks.

**Review by guschmue — APPROVED** [review]

**Pull request merged**
