### PR TITLE
[WebNN EP] Fixed a minor bug in ConvTranspose

### PR DESCRIPTION
**Pull request by Honry**
For ConvTranspose, the filter should be transposed from iohw -> ohwi if it is NHWC preferred layout.

### CODE REVIEW

**Comment by Honry** [comment]
@fdwr, @guschmue, PTAL, thanks!

**Review by guschmue — APPROVED** [review]

**Comment by Honry** [comment]
@guschmue, this one also rebased. Pls. help retrigger the CI.

**Review by fdwr — APPROVED** [review]
👍

**Comment by fdwr** [comment]
> help retrigger the CI.

I don't know why this happens: `Azure Pipelines could not run because the pipeline triggers exclude this branch/path`.

**Pull request merged**
