### PR TITLE
Update MCR image table

### PR DESCRIPTION
**Pull request by qiaodalei**
Update MCR image table with tag v1.5.1

### CODE REVIEW

**Review by thiagocrepaldi — APPROVED** [review]

**Comment by qiaodalei** [comment]
I don't have write access to merge this PR. Should I apply for the write access to this repository?

**Comment by manashgoswami** [comment]
@faxu mark nuphar, ngraph and tensorRT images as deprecated.

**Comment by snnn** [comment]
Hi @qiaodalei , would you please update your branch with the latest master? Then I will help you merge this PR.

For permission issues, please write to Faith and Pranav.

**Comment by qiaodalei** [comment]
https://github.com/microsoft/onnxruntime/pull/5509.   PR to update table to version 1.5.2 has been merged. This PR will be closed.

**Pull request closed without merging**
