### PR TITLE
[VitisAI] Cache node subgraph when necessary

### PR DESCRIPTION
**Pull request by zz002**
### Description

[VitisAI] Cache node subgraph when necessary

### CODE REVIEW

**Comment by zz002** [comment]
Hi @jywu-msft 
A new feature in VitisAI. If you have a moment, could you please take a look at the code?

**Comment by zz002** [comment]
hi @jywu-msft

**Comment by jywu-msft** [comment]
change causes build breaks in several CI Pipelines

2024-09-24T05:31:02.5670130Z /mnt/vss/_work/1/s/onnxruntime/core/session/provider_bridge_ort.cc:1206:37: error: 'GraphViewer__GetSchemaRegistry' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
2024-09-24T05:31:02.5671904Z  1206 |   IOnnxRuntimeOpSchemaCollectionPtr GraphViewer__GetSchemaRegistry(const GraphViewer* p) const { return p->GetSchemaRegistry(); }
2024-09-24T05:31:02.5672437Z       |                                     ^
2024-09-24T05:31:02.5736271Z /mnt/vss/_work/1/s/onnxruntime/core/providers/shared_library/provider_interfaces.h:996:45: note: overridden virtual function is here
2024-09-24T05:31:02.5737325Z   996 |   virtual IOnnxRuntimeOpSchemaCollectionPtr GraphViewer__GetSchemaRegistry(const GraphViewer* p) const = 0;
2024-09-24T05:31:02.5737829Z       |

**Comment by zz002** [comment]
hi @jywu-msft

**Comment by zz002** [comment]
hi @jywu-msft 
Can this PR be considered for merging?

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
