### PR TITLE
Disable ccache for WinML build

### PR DESCRIPTION
**Pull request by snnn**
### Description
It seems would resolve the timeout issue.

### CODE REVIEW

**Comment by snnn** [comment]
I'm not sure if it will actually solve the problem.

**Comment by mszhanyi** [comment]
To avoid the inflation of cache size, it will only read cache generated today.
That is, there isn't cache for some runs.
Cache will accelerate most runs, but it could not solve timeout issue of some runs.

**Review by mszhanyi — APPROVED** [review]

**Comment by mszhanyi** [comment]
It looks the compilation isn't stable suddenly. 
I agree to disable it to narrow download the scope.

**Pull request merged**
