### PR TITLE
[js/webgpu] Make sure only storage buffers are reused

### PR DESCRIPTION
**Pull request by qjia7**
### Description

This PR makes sure that only storage buffers are reused. Previously, the query buffer might also get from the freeBuffers list if there is a matching size in it. But they are different usage, which results errors.

### CODE REVIEW

**Comment by qjia7** [comment]
@fs-eire @guschmue Please take a look, thanks.

**Comment by guschmue** [comment]
lint is nagging:
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1080720&view=logs&j=96bb6f8b-177f-5c87-f240-68050a28686f&t=5f53931c-9b29-5372-7076-43dd32f36bb8

to repro local run ```npm run lint``` in the js/ directory.

**Comment by qjia7** [comment]
> lint is nagging: https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1080720&view=logs&j=96bb6f8b-177f-5c87-f240-68050a28686f&t=5f53931c-9b29-5372-7076-43dd32f36bb8
> 
> to repro local run `npm run lint` in the js/ directory.

Done. Please take another look, thanks!.

**Review by guschmue — APPROVED** [review]

**Pull request merged**
