### PR TITLE
Fail tests gracefully for the minimal cuda build

### PR DESCRIPTION
**Pull request by poweiw**
### Description
Several tests result in segfaults during the minimal cuda build. Although test failures are expected due to the limitation of the minimal cuda EP, failing gracefully would be much preferred. 

### Motivation and Context
To reproduce:
1. Build ORT with:
```bash
./build.sh --build_shared_lib --use_full_protobuf --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --tensorrt_home /TensorRT-10.0.1.6 --parallel --skip_tests --skip_submodule_sync --allow_running_as_root --use_tensorrt --cmake_extra_defines onnxruntime_CUDA_MINIMAL=1
```
2. Run `onnxruntime_test_all`
```bash
...
[----------] 1 test from AllocationPlannerTest
[ RUN      ] AllocationPlannerTest.ReusedInputCrossDifferentStreams
Segmentation fault (core dumped)
```

### CODE REVIEW

**Comment by poweiw** [comment]
@microsoft-github-policy-service agree [company="nvidia"]

**Comment by poweiw** [comment]
@microsoft-github-policy-service agree company="nvidia"

**Comment by poweiw** [comment]
@chilo-ms @yf711 for review. Thanks!

**Review by tianleiwu — APPROVED** [review]

**Comment by tianleiwu** [comment]
BTW, I did see many test failures for minimal cuda build:
[  FAILED  ] 177 tests, listed below:
[  FAILED  ] PlannerTest.LocationPlanningForPassThroughExplicitAndImplicitSubgraphInputs
[  FAILED  ] PlannerTest.LocationPlanningForInitializersOnlyUsedInANestedSubgraph
[  FAILED  ] PlannerTest.LocationPlanningForImplicitInputsWithoutExplicitConsumersInMainGraph
[  FAILED  ] AllocationPlannerTest.ReusedInputCrossDifferentStreams
[  FAILED  ] InferenceSessionTests.TestArenaShrinkageAfterRun
[  FAILED  ] TransformerTest.MemcpyTransformerTest
[  FAILED  ] TransformerTest.MemcpyTransformerTestCudaFirst
[  FAILED  ] TransformerTest.TestInitializerDuplicationInSubgraph
[  FAILED  ] TransformerTest.MemcpyTransformerTestGraphInputConsumedOnMultipleDevices
[  FAILED  ] TransformerTest.MemcpyTransformerTestImplicitInputConsumedOnMultipleDevices
[  FAILED  ] ActivationOpTest.Sigmoid_bfloat16
[  FAILED  ] ActivationOpTest.Tanh_bfloat16
[  FAILED  ] ActivationOpTest.Relu_bfloat16
[  FAILED  ] AttentionTest.AttentionEmptyPastState_SharedPastPresent
[  FAILED  ] AttentionTest.AttentionPastStateBatch1_SharedPastPresent
[  FAILED  ] AttentionTest.AttentionPastStateBatch2_SharedPastPresent
[  FAILED  ] AttentionTest.AttentionPastStateBatch2WithPadding_SharedPastPresent
[  FAILED  ] AttentionTest.AttentionWithNeoXRotaryEmbedding
[  FAILED  ] AttentionTest.Attention4DMask
[  FAILED  ] BeamSearchTest.GptBeamSearchFp16
[  FAILED  ] BeamSearchTest.GptBeamSearchWithInitDecoderFp16
[  FAILED  ] BeamSearchTest.GptBeamSearchFp16_VocabPadded
[  FAILED  ] BiasAddTest.BiasAddTest_HiddenSize_320
[  FAILED  ] BiasAddTest.BiasAddTest_HiddenSize_640
[  FAILED  ] BiasAddTest.BiasAddTest_HiddenSize_1280
[  FAILED  ] BiasAddTest.BiasAddTest_HiddenSize_768
[  FAILED  ] BiasAddTest.BiasAddTest_HiddenSize_1536
[  FAILED  ] BiasSoftmaxTest.InnerBroadcast
[  FAILED  ] BiasSoftmaxTest.InnerBroadcastNegativeAxis
[  FAILED  ] BiasSoftmaxTest.InnerBroadcastEmptyBiasBatch
[  FAILED  ] BiasSoftmaxTest.InnerBroadcastFullBiasBatch
[  FAILED  ] BiasSoftmaxTest.OuterBroadcast
[  FAILED  ] BiasSoftmaxTest.OuterBroadcastNegativeAxis
[  FAILED  ] BiasSoftmaxTest.OuterBroadcastEmptyBiasBatch
[  FAILED  ] BiasSoftmaxTest.OuterBroadcastFullBiasBatch
[  FAILED  ] BiasSoftmaxTest.InnerBroadcastMediumBatch
[  FAILED  ] BiasSoftmaxTest.OuterBroadcastMediumBatch
[  FAILED  ] BiasSoftmaxTest.InnerBroadcastLargeBatch
[  FAILED  ] BiasSoftmaxTest.OuterBroadcastLargeBatch
[  FAILED  ] BiasSplitGeluTest.BiasSplitGeluTest_HiddenSize_2560
[  FAILED  ] BiasSplitGeluTest.BiasSplitGeluTest_HiddenSize_5120
[  FAILED  ] BiasSplitGeluTest.BiasSplitGeluTest_HiddenSize_10240
[  FAILED  ] BiasSplitGeluTest.BiasSplitGeluTest_HiddenSize_6144
[  FAILED  ] BiasSplitGeluTest.BiasSplitGeluTest_HiddenSize_12288
[  FAILED  ] BitmaskDropoutTest.InferenceFloatType
[  FAILED  ] BitmaskDropoutTest.InferenceDoubleType
[  FAILED  ] BitmaskDropoutTest.InferenceHalfType
[  FAILED  ] BitmaskDropoutTest.TrainingFloatType
[  FAILED  ] BitmaskDropoutTest.TrainingDoubleType
[  FAILED  ] BitmaskDropoutTest.TrainingHalfType
[  FAILED  ] ContribOpTest.Rfft
[  FAILED  ] ContribOpTest.Irfft
[  FAILED  ] DecoderAttentionTest.SelfAttentionNoStateNoCache
[  FAILED  ] DecoderAttentionTest.CrossAttentionNoStateNoCache
[  FAILED  ] DecoderAttentionTest.SelfAttentionNoStateOutputCache
[  FAILED  ] DecoderAttentionTest.CrossAttentionNoStateOutputCache
[  FAILED  ] DecoderAttentionTest.SelfAttentionWithCache
[  FAILED  ] DecoderAttentionTest.CrossAttentionWithCache
[  FAILED  ] DecoderAttentionTest.SelfAttentionNoStateNoCachePaddingMask
[  FAILED  ] DecoderMaskedSelfAttentionTest.Test_fp32
[  FAILED  ] DecoderMaskedSelfAttentionTest.Test_fp16
[  FAILED  ] DynamicTimeWarp.simple
[  FAILED  ] MathOpTest.ComplexMul
[  FAILED  ] MathOpTest.ComplexMulConj
[  FAILED  ] MathOpTest.ComplexMul_fp16
[  FAILED  ] MathOpTest.ComplexMulConj_fp16
[  FAILED  ] MathOpTest.Add_float
[  FAILED  ] MathOpTest.Add_Broadcast_Axis
[  FAILED  ] MathOpTest.Add_Broadcast_MultidirectionalAB
[  FAILED  ] MathOpTest.Add_Broadcast_MultidirectionalBA
[  FAILED  ] MathOpTest.Sub
[  FAILED  ] MathOpTest.Mul
[  FAILED  ] MathOpTest.Div
[  FAILED  ] MathOpTest.Sqrt_bfloat16
[  FAILED  ] MathOpTest.MatMul_bfloat16
[  FAILED  ] BiasGeluTest.BFloat16
[  FAILED  ] FastGeluTest.FastGeluWithBias_BFloat16
[  FAILED  ] FusedMatMulOpTest.BFloat16_NoTranspose
[  FAILED  ] GemmaRotaryEmbeddingTest.GemmaRotaryEmbedding_Small
[  FAILED  ] GreedySearchTest.GptGreedySearchFp16_VocabPadded
[  FAILED  ] GroupNormTest.GroupNorm_128
[  FAILED  ] LongformerAttentionTest.LongformerAttention_Format0_NoGlobal
[  FAILED  ] LongformerAttentionTest.LongformerAttention_Format0_GlobalStart
[  FAILED  ] LongformerAttentionTest.LongformerAttention_Format0_UseCompactMemory
[  FAILED  ] LongformerAttentionTest.LongformerAttention_Format0_Float16
[  FAILED  ] LongformerAttentionTest.LongformerAttention_Format0_FullWindow
[  FAILED  ] LongformerAttentionTest.LongformerAttention_Format1_NoGlobal
[  FAILED  ] LongformerAttentionTest.LongformerAttention_Format1_GlobalStart
[  FAILED  ] LongformerAttentionTest.LongformerAttention_Format1_NoCompactMemory
[  FAILED  ] LongformerAttentionTest.LongformerAttention_Format1_Float16
[  FAILED  ] LongformerAttentionTest.LongformerAttention_Format1_FullWindow
[  FAILED  ] MatMulNBits.Float16
[  FAILED  ] MoETest.MoETest_Gelu
[  FAILED  ] MoETest.MoETest_Relu
[  FAILED  ] MoETest.MoETest_Mixtral
[  FAILED  ] MoETest.QMoETest_Mixtral_Int4
[  FAILED  ] MultiHeadAttentionTest.CrossAttention_Batch2_HeadSize32_RightSidePadding_Mask1D
[  FAILED  ] MultiHeadAttentionTest.CrossAttention_Batch2_HeadSize32_RightSidePadding_Mask2D
[  FAILED  ] MultiHeadAttentionTest.CrossAttention_Batch1_HeadSize32_LeftSidePadding_Mask2D
[  FAILED  ] MultiHeadAttentionTest.CrossAttention_Batch2_HeadSize32_NoBias_NoMask_PackedKV
[  FAILED  ] MultiHeadAttentionTest.SelfAttention_Batch2_HeadSize32_NoBias_NoMask_PackedQKV
[  FAILED  ] NhwcConvTest.Conv2D_2
[  FAILED  ] NhwcConvTest.Conv2D_Bias_1
[  FAILED  ] NhwcConvTest.Conv2D_AutoPad1
[  FAILED  ] NhwcConvTest.Conv2D_AutoPad2
[  FAILED  ] NhwcConvTest.Conv2D_asymmetric_padding1
[  FAILED  ] NhwcConvTest.Conv2D_asymmetric_padding2
[  FAILED  ] PackedAttentionTest.NoPack
[  FAILED  ] PackedAttentionTest.NoPackWithRelativePositionBias
[  FAILED  ] PackedAttentionTest.PackedWithRelativePositionBias
[  FAILED  ] PackedAttentionTest.PackedBatch
[  FAILED  ] PackedAttentionTest.PackedBatchWithQKV
[  FAILED  ] PackedAttentionTest.TestWithRandomData
[  FAILED  ] PackedAttentionTest.TestWithRandomDataWithRBP
[  FAILED  ] PackedAttentionTest.TestWithRandomDataLargeSeq
[  FAILED  ] PackedMultiHeadAttentionTest.PackedQKV_NoPadding_NoBias_trt
[  FAILED  ] PackedMultiHeadAttentionTest.PackedQKV_NoPadding_NoBias_cutlass
[  FAILED  ] PackedMultiHeadAttentionTest.PackedQKV_NoPadding_NoBias_unfused
[  FAILED  ] PackedMultiHeadAttentionTest.Q_K_V_NoPadding_NoBias_trt
[  FAILED  ] PackedMultiHeadAttentionTest.Q_K_V_NoPadding_Bias_RelPosBias_cutlass
[  FAILED  ] PackedMultiHeadAttentionTest.Q_K_V_NoPadding_Bias_RelPosBias_unfused
[  FAILED  ] PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_trt
[  FAILED  ] PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_cutlass
[  FAILED  ] PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_FlashAttention
[  FAILED  ] PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_unfused
[  FAILED  ] PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_RelPosBias
[  FAILED  ] PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_BroadcastRelPosBias_cutlass
[  FAILED  ] PackedMultiHeadAttentionTest.PackedQKV_Padding_NoBias_BroadcastRelPosBias_unfused
[  FAILED  ] QOrderedTest.Gelu_3x11x12
[  FAILED  ] QOrderedTest.LayerNormalization_RowMajor
[  FAILED  ] QOrderedTest.FP32_Quantize_COL
[  FAILED  ] QOrderedTest.FP32_Quantize_ROW
[  FAILED  ] QOrderedTest.FP32_Quantize_COL32
[  FAILED  ] QOrderedTest.FP32_Quantize_COL4_4R2_8C
[  FAILED  ] QOrderedTest.FP16_Quantize_COL
[  FAILED  ] QOrderedTest.FP16_Quantize_ROW
[  FAILED  ] QOrderedTest.FP16_Quantize_COL32
[  FAILED  ] QOrderedTest.FP16_Quantize_COL4_4R2_8C
[  FAILED  ] QOrderedTest.FP32_Dequantize_COL32
[  FAILED  ] QOrderedTest.FP32_Dequantize_ROW
[  FAILED  ] QOrderedTest.FP16_Dequantize_COL32
[  FAILED  ] QOrderedTest.FP16_Dequantize_ROW
[  FAILED  ] QAttentionTest.QAttentionBatch1
[  FAILED  ] QAttentionTest.QAttentionBatch1_Float16
[  FAILED  ] QAttentionTest.QAttentionBatch2
[  FAILED  ] QAttentionTest.QAttentionMaskPartialSequence
[  FAILED  ] QAttentionTest.QAttentionMaskExceedSequence
[  FAILED  ] QAttentionTest.QAttentionNoMaskIndex
[  FAILED  ] QAttentionTest.QAttentionUnidirectional_CUDA
[  FAILED  ] QAttentionTest.QAttentionPrunedModel
[  FAILED  ] RelativePositionBiasTest.RelativePositionBiasTest_FP32
[  FAILED  ] RelativePositionBiasTest.RelativePositionBiasTest_FP16
[  FAILED  ] RelativePositionBiasTest.RelativePositionBiasTest2_FP16
[  FAILED  ] RelativePositionBiasTest.RelativePositionBiasTest_FP16_No_Bidirectional
[  FAILED  ] GatedRelativePositionBiasTest.FP16_BSNHD_1x3x2x4x8
[  FAILED  ] GatedRelativePositionBiasTest.FP32_BSNHD_2x3x2x4x8
[  FAILED  ] GatedRelativePositionBiasTest.FP32_LongSeq_BSNHD_2x5x2x4x4
[  FAILED  ] GatedRelativePositionBiasTest.FP16_BSNHD_2x8x2x4x8_NoPadding
[  FAILED  ] RemovePaddingTest.RemovePaddingBatch1_NoPadding
[  FAILED  ] RemovePaddingTest.RemovePaddingBatch3_TwoWithPadding
[  FAILED  ] RemovePaddingTest.RemovePaddingBatch3_AllWithPadding
[  FAILED  ] RestorePaddingTest.RestorePaddingBatch1_NoPadding
[  FAILED  ] RestorePaddingTest.RestorePaddingBatch3_TwoWithPadding
[  FAILED  ] RestorePaddingTest.RestorePaddingBatch3_AllWithPadding
[  FAILED  ] SamplingTest.Gpt2Sampling_GPU
[  FAILED  ] SkipGroupNormTest.SkipGroupNorm_with_bias
[  FAILED  ] SkipGroupNormTest.SkipGroupNorm_no_bias_broadcast_skip
[  FAILED  ] UnfoldTensorOpTest.LastDim
[  FAILED  ] UnfoldTensorOpTest.NormalDim
[  FAILED  ] ModOpTest.Fmod_bfloat16_mixed_sign
[  FAILED  ] GemmOpTest.GemmNoTrans_bfloat16
[  FAILED  ] SoftmaxOperator.Simple_bfloat16
[  FAILED  ] ReductionOpTest.ReduceSum_bfloat16
[  FAILED  ] ReductionOpTest.ReduceSumBFloat16_2
[  FAILED  ] GatherOpTest.Gather_invalid_index_gpu
[  FAILED  ] IsInfTest.test_isinf_bfloat16
[  FAILED  ] IsInfTest.test_Float8E4M3FN

**Comment by poweiw** [comment]
> BTW, I did see many test failures for minimal cuda build

Yeah these are expected as even though testing CUDA EP was [disabled when USE_TENSORRT](https://github.com/microsoft/onnxruntime/blob/88c811b6382cec6cce5edb83f61f1ce7fbd987ec/onnxruntime/test/providers/base_tester.cc#L634), CUDA EP seems to be checked in the TRT EP tests. As discussed [here](https://github.com/microsoft/onnxruntime/issues/21394), maintain all of them to be negative tests will require unworthy huge effort.

**Pull request merged**
