### PR TITLE
Fix an init order bug in onnxruntime_test_all.exe

### PR DESCRIPTION
**Pull request by snnn**
### Description
C++ has a famous "static initialization order problem". This PR is a partial fix for one such problem.  
The problem I'm fixing is: in onnxruntime/test/providers/cpu/model_tests.cc, we call the core framework's LoopDir function, however, this is before "main" function is started. So, for sure at this moment the default logger in onnxruntime::common is not initialized yet. However, if any ORT function threw any exception, it would trigger the logging framework to get a stacktrace and print them out through the DefaultLogger.  In other words, do not use exceptions if the function could be used before "main".

I say this PR is only a partial fix because similarly before "main" we should not call any protobuf functions neither.   So probably the best fix is to not implement model tests in such a way. GTest's "testing::ValuesIn" function should only be used with constexpr!

But, at least, this fix could still avoid some crashes and hangs.

### CODE REVIEW

**Comment by snnn** [comment]
> Would this be required if the default logger were available via a function scoped static instance?

It is hard to answer.  Another problem is: before "main", we should not use any third-party libraries, because they might haven't initialized too. So, even if we could provide a default instance for the default logger, we still need to rework the logger library so that it won't use any 3rd-party library. That would be too much work. 

Usually we do not need to call into any filesystem APIs before "main". There is no such needs except there we use this information to setup model tests with the google test framework.

**Comment by snnn** [comment]
More precisely, the problem is: if we threw an exception before the "main" is started, the "ORT_THROW" macro will call GetStackTrace() to get a stacktrace first(before constructing an exception). Then GetStackTrace will call CaptureStackTrace::Trace(). At the beginning of "CaptureStackTrace::Trace()", it will try to initialize SymbolHelper if the helper hasn't initialized.  However, the constructor of "SymbolHelper" could fail. When it fails, it calls "LOGS_DEFAULT". At this moment, the default logger doesn't exist yet. So LOGS_DEFAULT throws an exception. But we are processing a throwing exception! So it goes back to initialize SymbolHelper again. It doesn't work. 

So the root cause is: throwing an exception shouldn't result creating another exception.

**Review by pranavsharma — APPROVED** [review]

**Comment by snnn** [comment]
Sorry I was wrong. The LoopDir function was not called before "main". Actually, it was from onnxruntime\test\unittest_main\test_main.cc's  "::testing::InitGoogleTest" function call. But that one is invoked before     ortenv_setup(); This is why when SymbolHelper's constructor failed, there was no DefaultLogger can be used.

**Comment by snnn** [comment]
No longer needed. Another fixe has been merged in.

**Pull request closed without merging**
