### PR TITLE
Refactor deprecated gradle syntax 

### PR DESCRIPTION
**Pull request by jchen351**
To replaced deprecated API. 
Should verify with the `Gradle cmakeCheck` step from `Windows_Packaging_CPU_x64_default` stage from the Zip-Nuge-... pipeline.

### CODE REVIEW

**Comment by skottmckay** [comment]
@Craigacp in case there are any concerns

**Comment by Craigacp** [comment]
I also needed to do this to make this deprecation warning (https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#test_framework_implementation_dependencies) go away:

```
diff --git a/java/build.gradle b/java/build.gradle
index e09fd01e93..96a8d43a3b 100644
--- a/java/build.gradle
+++ b/java/build.gradle
@@ -174,6 +174,7 @@ if (cmakeBuildDir != null) {
 dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.2'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.2'
+       testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
        testImplementation 'com.google.protobuf:protobuf-java:3.21.7'
 }
```

It looks like that PR broke header file generation for the JNI binding, not had chance to look deeper in to it yet.

**Comment by jchen351** [comment]
> I also needed to do this to make this deprecation warning (https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#test_framework_implementation_dependencies) go away:
> 
> ```
> diff --git a/java/build.gradle b/java/build.gradle
> index e09fd01e93..96a8d43a3b 100644
> --- a/java/build.gradle
> +++ b/java/build.gradle
> @@ -174,6 +174,7 @@ if (cmakeBuildDir != null) {
>  dependencies {
>         testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.2'
>         testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.2'
> +       testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
>         testImplementation 'com.google.protobuf:protobuf-java:3.21.7'
>  }
> ```
> 
> It looks like that PR broke header file generation for the JNI binding, not had chance to look deeper in to it yet.

It should have been fixed.

**Comment by snnn** [comment]
@Craigacp , could you please help review it?

**Comment by snnn** [comment]
Right now the Gradle cmakeCheck step fails in "Nuget-CUDA-Packaging-Pipeline" because it tries to run GPU tests on a CPU-only machine. This PR would not address the issue, right? But we need to get it right before the next patch release.

**Comment by Craigacp** [comment]
> Right now the Gradle cmakeCheck step fails in "Nuget-CUDA-Packaging-Pipeline" because it tries to run GPU tests on a CPU-only machine. This PR would not address the issue, right? But we need to get it right before the next patch release.

I think fixing that would involve modifying the gradle command invoked by that pipeline. The CUDA GPU tests are automatically enabled if Java tests are run when CUDA is enabled in the build. What things is that pipeline supposed to test (e.g. is it ok if all the Java tests are disabled)?

**Review by snnn — APPROVED** [review]

**Pull request merged**
