### PR TITLE
MNIST Sample Fix

### PR DESCRIPTION
**Pull request by RyanUnderhill**
**Description**: Change global variable initialization order and add error messages on failure

### CODE REVIEW

**Comment by skottmckay** [comment]
>   hdc_dib_ = CreateCompatibleDC(nullptr);

Should there be an error message here and if CreateWindow fails?

---
Refers to: samples/c_cxx/MNIST/MNIST.cpp:131 in 22939e1. [](commit_id = 22939e1a5d45599b6f88433fb62214a814ba29bd, deletion_comment = False)

**Comment by fdwr** [comment]
> > hdc_dib_ = CreateCompatibleDC(nullptr);
> 
> Should there be an error message here and if CreateWindow fails?
> 
> Refers to: samples/c_cxx/MNIST/MNIST.cpp:131 in [22939e1](https://github.com/microsoft/onnxruntime/commit/22939e1a5d45599b6f88433fb62214a814ba29bd). [](commit_id = [22939e1](https://github.com/microsoft/onnxruntime/commit/22939e1a5d45599b6f88433fb62214a814ba29bd), deletion_comment = False)

Assuming the basics are right (such as using the correct window class name), CreateWindow will realistically only fail under exceptional circumstances, such as the global system not having enough memory, in which case even showing an error message would also fail (because MessageBox calls CreateWindow too).

**Comment by skottmckay** [comment]
> > > hdc_dib_ = CreateCompatibleDC(nullptr);
> > 
> > 
> > Should there be an error message here and if CreateWindow fails?
> > Refers to: samples/c_cxx/MNIST/MNIST.cpp:131 in [22939e1](https://github.com/microsoft/onnxruntime/commit/22939e1a5d45599b6f88433fb62214a814ba29bd). [](commit_id = [22939e1](https://github.com/microsoft/onnxruntime/commit/22939e1a5d45599b6f88433fb62214a814ba29bd), deletion_comment = False)
> 
> Assuming the basics are right (such as using the correct window class name), CreateWindow will realistically only fail under exceptional circumstances, such as the global system not having enough memory, in which case even showing an error message would also fail (because MessageBox calls CreateWindow too).

I don't expect it to fail, but when a program exits unsuccessfully and provides no output to the user as to why that isn't the greatest experience (especially if this is your first time trying to use ORT).

**Comment by snnn** [comment]
#2297

**Pull request merged**
