### PR TITLE
Fix compile warnings (as errors) for functions which miss returning required return value

### PR DESCRIPTION
**Pull request by mtavenrath**
Added dummy return values to functions which specify a return value, but do not return an value value.

### Motivation and Context
Fix compiler errors with 'warnings as errors' enabled.

### CODE REVIEW

**Comment by mtavenrath** [comment]
@gedoensmax I guess it'd be better to change the signature to return void instead of returning a dummy float? What is your opinion?

**Comment by gedoensmax** [comment]
Yes for sure 🤔 It does not make sense to have a return value for a function that does not return an actual result.

**Comment by mtavenrath** [comment]
I changes the return signatures to void for a more clean interface.

**Comment by mtavenrath** [comment]
@jeffbloo @PatriceVignola This is a minor issue which should be fast to review.

**Review by PatriceVignola — APPROVED** [review]

**Comment by mtavenrath** [comment]
@skottmckay I am pretty sure the android failures / python failures are not caused by my change. Do I have to rebase it for another CI run?

**Comment by skottmckay** [comment]
Unrelated and can be ignored. Couple of new required CI needs to run - kicked those off.

**Pull request merged**
