### PR TITLE
Update OpenVINO MCR container build docs with dynamic device selection info

### PR DESCRIPTION
**Pull request by smkarlap**
**Description**: Update MCR Docker container build instructions with Dynamic device selection API info.

**Motivation and Context**
- This addition highlights the feature of OpenVINO based containers built for one default hardware accelerator target to be dynamically repurposed for another hardware accelerator at run time.

### CODE REVIEW

**Comment by HectorSVC** [comment]
@smkarlap, could you merge the latest master, there's a fix for the MacOS CI pipeline. Thanks

**Comment by smkarlap** [comment]
> @smkarlap, could you merge the latest master, there's a fix for the MacOS CI pipeline. Thanks

Done

**Pull request merged**
