### PR TITLE
[mlas] add loongarch lsx and lasx optimize code

### PR DESCRIPTION
**Pull request by junchao-loongson**
### Description
Hello we(@lixing-star) are the developers of loongson team.

We add 128 (lsx), 256 (lasx) vector optimization code for the loongarch architecture

[100% tests passed, 0 tests failed out of 7](https://cloud.a-boat.cn:2021/api/public/dl/6831z1Bi?inline=true)

### Development Environments1
```
CPU: 
    Loongson-3C5000L
uname -a:  
    Linux localhost.localdomain 4.19.190-6.4.lns8.loongarch64 #1 SMP Thu Jul 14 12:08:04 CST 2022 loongarch64 loongarch64 loongarch64 GNU/Linux

```
### LonngArch Documents
- [LoongArch Reference Manual - Volume 1: Basic Architecture: This manual describes the basic part of the LoongArch architecture.](https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html)
- [LoongArch ELF psABI: This manual describes the LoongArch ELF psABI.](https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html)
- [more](https://loongson.github.io/LoongArch-Documentation/README-EN.html)

### CODE REVIEW

**Comment by junchao-loongson** [comment]
@microsoft-github-policy-service agree [company="{Loongson Technology Corporation Limited}"]

**Comment by junchao-loongson** [comment]
@microsoft-github-policy-service agree company="Loongson Technology Corporation Limited"

**Comment by junchao-loongson** [comment]
@snnn hello~
How to trigger the ci test?

**Comment by snnn** [comment]
@faxu , please help review

**Comment by snnn** [comment]
Is it possible to build the code and run the tests in QEMU, like https://wiki.debian.org/LoongArch/sbuildQEMU？
Is there a way to get a cross-compiler for this arch? Like for ARM we can get one from https://www.linaro.org/downloads/.

**Comment by junchao-loongson** [comment]
hello~ 
Here is some information about qemu and cross-compile
## qemu
```
git clone https://gitlab.com/qemu-project/qemu.git
cd qemu
./configure --target-list=loongarch64-linux-user

```

## download cross-compile tool
```
 wget https://mirrors.wsyu.edu.cn/fedora/linux/Yongbao/cross-toolchain/x86_64-cross-tools-loongarch64-gcc-libc.tar.xz
```

## cfg

tool.cmake
```
 SET(CMAKE_SYSTEM_NAME Linux)
 SET(CMAKE_SYSTEM_VERSION 1)
 SET(CMAKE_C_COMPILER loongarch64-unknown-linux-gnu-gcc)
 SET(CMAKE_CXX_COMPILER loongarch64-unknown-linux-gnu-g++)
 SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
 SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
 SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
 SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```

```
wget https://github.com/protocolbuffers/protobuf/releases/download/v3.18.1/protoc-3.18.1-linux-x86_64.zip
unzip protoc-3.18.1-linux-x86_64.zip -d protoc
```

```
cmake -DONNX_CUSTOM_PROTOC_EXECUTABLE=`pwd`/../protoc/bin/protoc  -DCMAKE_TOOLCHAIN_FILE=`pwd`/../tool.cmake ../cmake
```
## issues

When I run make cmd, I get the following error message.
I don't get this error when I compile locally using build.sh
```
[ 18%] Building CXX object CMakeFiles/onnxruntime_mlas.dir/home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib/threading.cpp.o
In file included from /home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib/threading.cpp:17:
/home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib/mlasi.h:1277:9: error: ?__m128? does not name a type; did you mean ?__int128??
 1277 | typedef __m128 MLAS_FLOAT32X4;
      |         ^~~~~~
      |         __int128
/home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib/mlasi.h:1278:9: error: ?__m128i? does not name a type
 1278 | typedef __m128i MLAS_INT32X4;
      |         ^~~~~~~
/home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib/mlasi.h:1285:1: error: ?MLAS_INT32X4? does not name a type
 1285 | MLAS_INT32X4
      | ^~~~~~~~~~~~
/home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib/mlasi.h:1300:1: error: ?MLAS_INT32X4? does not name a type
 1300 | MLAS_INT32X4
      | ^~~~~~~~~~~~
```
I realized that the -mlsx (loongarch SIMD) compilation parameter is missing when compiling platform.cpp.
I'm not quite sure if my cmake command parameters are correct or not
```
/home/yala/work/plugins/la-cross-tools/bin/loongarch64-unknown-linux-gnu-g++ -DCPUINFO_SUPPORTED_PLATFORM=0 -DEIGEN_MPL2_ONLY -DEIGEN_USE_THREADS -DNSYNC_ATOMIC_CPP11 -DORT_ENABLE_STREAM -DORT_NO_RTTI -DPLATFORM_POSIX -D_GNU_SOURCE -I/home/yala/work/plugins/onnxruntime/build-cross/_deps/utf8_range-src -I/home/yala/work/plugins/onnxruntime/include/onnxruntime -I/home/yala/work/plugins/onnxruntime/include/onnxruntime/core/session -I/home/yala/work/plugins/onnxruntime/build-cross/_deps/pytorch_cpuinfo-src/include -I/home/yala/work/plugins/onnxruntime/build-cross/_deps/google_nsync-src/public -I/home/yala/work/plugins/onnxruntime/build-cross -I/home/yala/work/plugins/onnxruntime/onnxruntime -I/home/yala/work/plugins/onnxruntime/build-cross/_deps/abseil_cpp-src -I/home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/inc -I/home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib -I/home/yala/work/plugins/onnxruntime/build-cross/_deps/gsl-src/include -ffunction-sections -fdata-sections -Wno-restrict -DCPUINFO_SUPPORTED -fPIC -fno-rtti -Wall -Wextra -Wno-deprecated-copy -Wno-nonnull-compare -Werror -MD -MT CMakeFiles/onnxruntime_mlas.dir/home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib/platform.cpp.o -MF CMakeFiles/onnxruntime_mlas.dir/home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib/platform.cpp.o.d -o CMakeFiles/onnxruntime_mlas.dir/home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib/platform.cpp.o -c /home/yala/work/plugins/onnxruntime/onnxruntime/core/mlas/lib/platform.cpp
```

**Comment by snnn** [comment]
Nice! Would you please confirm that the cross-compile tool you showed to me is publicly available?  Is it an official package from Fedora project?

**Comment by junchao-loongson** [comment]
cross-compile tool source code come form gcc repository(commit id is cead92b7fc4d7a545dcf2f02397120e3c9afe1a3)
I just compiled it to binary and provided this temporary link

**Comment by junchao-loongson** [comment]
We've put this toolchain into loongson's official repository

https://github.com/loongson/build-tools/releases/download/2023.08.08/x86_64-cross-tools-loongarch64-gcc-libc.tar.xz

**Comment by snnn** [comment]
I will go ahead and merge this PR.

**Comment by junchao-loongson** [comment]
We fixed this issue. Also fixed some issues caused by clang-fomat

**Review by snnn — APPROVED** [review]

**Comment by junchao-loongson** [comment]
hello~
what else do we need to do to merge this patch

**Comment by snnn** [comment]
No. Thanks.  I've sent this PR to @yufenglee to review.

**Comment by lixing-star** [comment]
@snnn , how about the code review progress? thanks.

**Review by yufenglee — APPROVED** [review]

**Comment by snnn** [comment]
I will setup a CI build pipeline for this.

**Comment by lixing-star** [comment]
thanks. We will also rebuild the main code for checking our code.

**Pull request merged**
