### PR TITLE
[Technical docs] Fixed a couple of old links in `FAQ.md`

### PR DESCRIPTION
**Pull request by NickLucche**
### Description
Updated a couple of old links in the technical documentation that where pointing to files present prior to the migration to https://onnxruntime.ai/docs.

### CODE REVIEW

**Review by snnn — APPROVED** [review]

**Comment by hariharans29** [comment]
Hi @natke/@snnn - Any idea on how to go about merging this PR ? It seems like it is waiting on some pipelines which we are unable to trigger because of exclusion rules ?

**Review by natke — APPROVED** [review]

**Pull request merged**
