### PR TITLE
Cancel EP check in python for 1.16.1

### PR DESCRIPTION
**Pull request by RandySheriffH**
Remove the condition to allow an empty provide list.

### CODE REVIEW

**Comment by pranavsharma** [comment]
This should be cherry picked by @snnn. We shouldn't have to check this in directly in the branch.

**Comment by RandySheriffH** [comment]
> This should be cherry picked by @snnn. We shouldn't have to check this in directly in the branch.

@snnn, blocked by some conflict you said?

**Comment by snnn** [comment]
> @snnn, blocked by some conflict you said?

Right. That's why I was seeking help from you.  Thanks for making it happen.

**Review by pranavsharma — APPROVED** [review]

**Comment by snnn** [comment]
> This should be cherry picked by @snnn. We shouldn't have to check this in directly in the branch.

There was some conflicts that I didn't know how to resolve. So about half an hour ago I asked him if he can directly create a PR that targets the release branch.  Thanks for the immediate response.

**Review by snnn — APPROVED** [review]

**Pull request merged**
