### PR TITLE
Cherry pick for 1.17.2 source code release

### PR DESCRIPTION
**Pull request by YUNQIUGUO**
### Description

As title.

### CODE REVIEW

**Comment by tianleiwu** [comment]
Does the title mean there is no binary built for this release?

**Comment by YUNQIUGUO** [comment]
> Does the title mean there is no binary built for this release?

i I just got the update yesterday that we will be doing a 1.17.2 source code only release. no packages to be published. @pranavsharma for confirming

**Comment by pranavsharma** [comment]
> Does the title mean there is no binary built for this release?

Yes, this is to support cudnn 9.0. No binary. This is specifically for Triton.

**Review by pranavsharma — APPROVED** [review]

**Comment by snnn** [comment]
Should we increase the "VERSION_NUMBER" to avoid confusion? @pranavsharma ?

**Comment by pranavsharma** [comment]
> Should we increase the "VERSION_NUMBER" to avoid confusion? @pranavsharma ?

Good point. Let's do that.

**Review by snnn — APPROVED** [review]

**Comment by snnn** [comment]
This PR has been included in the `rel-1.17.2` branch. Removing the `release:1.17.2` label.

**Pull request merged**
