### PR TITLE
[WebNN EP] Fix compilation with newer flatbuffers

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
@fdwr, @guschmue, PTAL, thanks!

**Review by guschmue — APPROVED** [review]

**Comment by cdeepali** [comment]
Does this support flatbuffers 23.5.26?

**Comment by cdeepali** [comment]
Thanks @Honry. Yes that is correct. 

In my environment, I am able to build onnxruntime with flatbuffers v23.1.21 but not with versions higher than 23.1.21. So was curious to know if this change adds fix for newer versions of flatbuffers.

**Pull request merged**
