### PR TITLE
Turn on debug node inputs outputs in one nuget pipeline to catch breaks

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: Can be checked periodically (every day's nuget run) and doesn't need to be done with every PR

**Motivation and Context**
https://github.com/microsoft/onnxruntime/issues/6459

### CODE REVIEW

**Comment by edgchen1** [comment]
Good idea, thanks for enabling this in a CI build.
I'd expect this to make the tests run significantly slower though, does it impact the particular build it got added to?

**Comment by hariharans29** [comment]
> Good idea, thanks for enabling this in a CI build.
> I'd expect this to make the tests run significantly slower though, does it impact the particular build it got added to?

It does make tests slower on my machine by a small factor. That is why I added this to a Nuget pipeline (not CI). I think the nuget pipelines are only run once daily. Given that this feature has been fairly stable, I'd expect adding it to the Nuget pipeline (and having it tested once daily) is sufficient.

**Comment by edgchen1** [comment]
> > Good idea, thanks for enabling this in a CI build.
> > I'd expect this to make the tests run significantly slower though, does it impact the particular build it got added to?
> 
> It does make tests slower on my machine by a small factor. That is why I added this to a Nuget pipeline (not CI). I think the nuget pipelines are only run once daily. Given that this feature has been fairly stable, I'd expect adding it to the Nuget pipeline (and having it tested once daily) is sufficient.

Is this Nuget pipeline used to create the release packages? I think we probably do not want to compile this feature in if that's the case, right? It is good to test that these debugging features still build though. Is it worth creating a separate nightly build to test them? There are a few others like those controlled by ENABLE_NVTX_PROFILE and CONCURRENCY_VISUALIZER, but we can start with debug node IO first.

**Comment by hariharans29** [comment]
> > > Good idea, thanks for enabling this in a CI build.
> > > I'd expect this to make the tests run significantly slower though, does it impact the particular build it got added to?
> > 
> > 
> > It does make tests slower on my machine by a small factor. That is why I added this to a Nuget pipeline (not CI). I think the nuget pipelines are only run once daily. Given that this feature has been fairly stable, I'd expect adding it to the Nuget pipeline (and having it tested once daily) is sufficient.
> 
> Is this Nuget pipeline used to create the release packages? I think we probably do not want to compile this feature in if that's the case, right? It is good to test that these debugging features still build though. Is it worth creating a separate nightly build to test them? There are a few others like those controlled by ENABLE_NVTX_PROFILE and CONCURRENCY_VISUALIZER, but we can start with debug node IO first.

Yes, this is the nuget pipeline used to create the release packages. 

I don't see much of a difference between the run times of the manual run I kicked-off on my branch and the triggered master runs - 

image

Thanks for the suggestions but should we just hold off on creating a separate nightly build if the run time is drastically slower ?

**Comment by hariharans29** [comment]
> > > Good idea, thanks for enabling this in a CI build.
> > > I'd expect this to make the tests run significantly slower though, does it impact the particular build it got added to?
> > 
> > 
> > It does make tests slower on my machine by a small factor. That is why I added this to a Nuget pipeline (not CI). I think the nuget pipelines are only run once daily. Given that this feature has been fairly stable, I'd expect adding it to the Nuget pipeline (and having it tested once daily) is sufficient.
> 
> Is this Nuget pipeline used to create the release packages? I think we probably do not want to compile this feature in if that's the case, right? It is good to test that these debugging features still build though. Is it worth creating a separate nightly build to test them? There are a few others like those controlled by ENABLE_NVTX_PROFILE and CONCURRENCY_VISUALIZER, but we can start with debug node IO first.

Sorry - I totally missed the point about not wanting to compile this feature in the binary that is going to be shipped. You're right - it shouldn't be. included. We could turn it on if the nuget pipeline is being run in "Debug" mode and schedule 2 runs each night - one Debug and one RelWithDebInfo (this already exists). Does that sound better than creating a new pipeline altogether ?

**Comment by edgchen1** [comment]
> > > > Good idea, thanks for enabling this in a CI build.
> > > > I'd expect this to make the tests run significantly slower though, does it impact the particular build it got added to?
> > > 
> > > 
> > > It does make tests slower on my machine by a small factor. That is why I added this to a Nuget pipeline (not CI). I think the nuget pipelines are only run once daily. Given that this feature has been fairly stable, I'd expect adding it to the Nuget pipeline (and having it tested once daily) is sufficient.
> > 
> > 
> > Is this Nuget pipeline used to create the release packages? I think we probably do not want to compile this feature in if that's the case, right? It is good to test that these debugging features still build though. Is it worth creating a separate nightly build to test them? There are a few others like those controlled by ENABLE_NVTX_PROFILE and CONCURRENCY_VISUALIZER, but we can start with debug node IO first.
> 
> Sorry - I totally missed the point about not wanting to compile this feature in the binary that is going to be shipped. You're right - it shouldn't be. included. We could turn it on if the nuget pipeline is being run in "Debug" mode and schedule 2 runs each night - one Debug and one RelWithDebInfo (this already exists). Does that sound better than creating a new pipeline altogether ? Or it will have to go into a CI check and every PR will incur the cost.

I agree that we don't need to run this for every PR change. I think it's fine to do another Nuget pipeline "Debug" run which compiles this feature in.

**Pull request closed without merging**
