### PR TITLE
Introduce parameterized as a dev dependency

### PR DESCRIPTION
**Pull request by justinchuby**
Introduce parameterized as a dev dependency to allow for parameterized test cases.

E.g.
https://github.com/pytorch/text/blob/fae8e8cabf7adcbbc2f09c0520216288fd53f33b/test/datasets/test_sst2.py#L71-L86

### CODE REVIEW

**Review by garymm — APPROVED** [review]

**Comment by snnn** [comment]
But is the file used at anywhere?

**Comment by justinchuby** [comment]
> But is the file used at anywhere?

The package will be used to create parameterized tests, e.g. https://github.com/microsoft/onnxruntime/pull/11318/files#diff-00958b8075591649f87960fe11551f3f734141735d1823dab4ddd41b07292f41R126

**Comment by snnn** [comment]
Is the requirements-dev.txt file used in any our pipeline?  Just curious.

**Comment by justinchuby** [comment]
> Is the requirements-dev.txt file used in any our pipeline? Just curious.

It seems so:

https://github.com/microsoft/onnxruntime-extensions/blob/cb8134439291515b587a6efb970454805cce80b1/ci_build/azure-pipelines/mshost.yaml#L69-L70

**Pull request merged**
