### PR TITLE
[VitisAI] Translate all session configs into provider options with prefix

### PR DESCRIPTION
**Pull request by chenduan-amd**
### Description
We need to translate all session configs into provider options, prefix with ort_session_config, so that we can pass ORT session options to VAIP 

### Motivation and Context
Based on this PR(https://github.com/microsoft/onnxruntime/pull/21781), we need to provide a comprehensive interface to handle both session_configs and provider_options together. To achieve this, we use prefixes on the onnxruntime side to differentiate between the two.

### CODE REVIEW

**Comment by chenduan-amd** [comment]
@microsoft-github-policy-service agree company="Advanced Micro Devices, Inc."

**Comment by jywu-msft** [comment]
https://github.com/microsoft/onnxruntime/actions/runs/10698900556/job/29678983177?pr=21907 
can you address clang-format lint error?
also please merge latest main branch

**Comment by tianleiwu** [comment]
@chenduan-amd, Please fix python format using lintrunner:
```
pip install -r requirements-lintrunner.txt
pip install intrunner
lintrunner init
lintrunner -a
```

**Comment by jywu-msft** [comment]
> @chenduan-amd, Please fix python format using lintrunner:
> 
> ```
> pip install -r requirements-lintrunner.txt
> pip install intrunner
> lintrunner init
> lintrunner -a
> ```

          2837 |-  for(const auto &option: options->value.config_options.configurations) {
          2838 |+  for (const auto& option : options->value.config_options.configurations) {

**Comment by jywu-msft** [comment]
https://github.com/microsoft/onnxruntime/pull/22096 replaces this PR, correct?

**Pull request closed without merging**
