### PR TITLE
[OpenVINO-EP] 2021.4 Release

### PR DESCRIPTION
**Pull request by MaajidKhan**
**Description:** OpenVINO EP 2021.4 Release

**Motivation and Context:**
Making changes in UEP to align it with the latest OpenVINO 2021.4 Official Release

### CODE REVIEW

**Comment by MaajidKhan** [comment]
Are the other pipelines already triggered?

**Comment by oliviajain** [comment]
/azp run orttraining-linux-ci-pipeline,orttraining-mac-ci-pipeline,orttraining-linux-gpu-ci-pipeline,centos7_cpu,Linux CPU Minimal Build E2E CI Pipeline,Linux Nuphar CI Pipeline,MacOS NoContribops CI Pipeline,Linux OpenVINO CI Pipeline,orttraining-distributed, orttraining-amd-gpu-ci-pipeline Linux CPU CI Pipeline,Linux CPU x64 NoContribops CI Pipeline,Linux GPU CI Pipeline,Linux GPU TensorRT CI Pipeline,MacOS CI Pipeline,MacOS NoContribops CI Pipeline,Windows CPU CI Pipeline,Windows GPU CI Pipeline,Windows GPU TensorRT CI Pipeline,  orttraining-ortmodule, orttraining-ortmodule-distributed

**Comment by MaajidKhan** [comment]
2 Training pipelines failed which has nothing to do with OV-EP. I just merged our branch with latest onnxrt master.
can all of these pipelines be re-triggered.

**Comment by oliviajain** [comment]
Verified on CPU/GPU

**Comment by oliviajain** [comment]
Building Openvino 2021.4 from source to test VPU

**Review by oliviajain — APPROVED** [review]

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
