### PR TITLE
Move and rename nuget pipeline file

### PR DESCRIPTION
**Pull request by RandySheriffH**
Move the nuget pipeline file to parent directory and rename it.

### CODE REVIEW

**Review by snnn — DISMISSED** [review]
I scheduled a build for you. You may merge the pr when it passed.

Thank you!

**Comment by snnn** [comment]
No. Looks like you discarded my recent change.

**Comment by RandySheriffH** [comment]
> No. Looks like you discarded my recent change.

Just merged the latest master.

**Comment by jywu-msft** [comment]
how can we reflect that this is a packaging pipeline?

**Comment by jywu-msft** [comment]
I think you can't just move this file up to parent directory and not change some of the steps inside (they reference some relative directory paths)
e.g. anything referencing files in the templates directory

**Pull request closed without merging**
