### PR TITLE
Ort openvino 4.3 cli

### PR DESCRIPTION
**Pull request by sfatimar**
### Description
Introduce cache_dir CLI for graph serialisation.
Replace existing use_compile_network and blob_dump_path cli options for openvino with a single command line option "cache_dir" specifying the path that needs to be passed for blob dump/load improving the developer experience.

### Motivation and Context?
We were having two values to set cache dir which was unnecessary

### CODE REVIEW

**Comment by sfatimar** [comment]
@jywu-msft Can we please pull this PR in ORT 1.14 Release as it is critical for us.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
