### PR TITLE
[js/webgpu] Simplify the Resize shader when noScale is true

### LINKED ISSUE #18311: [Web] WebGPU incorrect output for Segment Anything Model (SAM)
### Describe the issue

Attempting to run the original [Segment Anything Models (SAM)](https://huggingface.co/Xenova/sam-vit-base) results in warnings and incorrect output. cc @guschmue @fs-eire

#### Output

- Incorrect (WebGPU) output:
  image

- Correct (WASM) output:
  image

#### Warnings
```
An uncaught WebGPU validation error was raised: Tint WGSL reader failure: :47:20 error: index 3 out of bounds [0..2]
      inputIndices[3] = max(0, min(col, undefined - 1));
                   ^

 - While validating [ShaderModuleDescriptor]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).
 ```

```
An uncaught WebGPU validation error was raised: [Invalid ShaderModule] is invalid.
 - While validating compute stage ([Invalid ShaderModule], entryPoint: main).
 - While calling [Device].CreateComputePipeline([ComputePipelineDescriptor]).
```

```
[Invalid ComputePipeline] is invalid.
 - While Validating GetBindGroupLayout (0) on [Invalid ComputePipeline]
```

### To reproduce

Run the following code in a browser that supports WebGPU:

```js
import 'https://cdn.jsdelivr.net/npm/onnxruntime-web@1.16.1/dist/ort.webgpu.min.js'

ort.env.wasm.wasmPaths='https://cdn.jsdelivr.net/npm/onnxruntime-web@1.16.1/dist/'

const options = {
    executionProviders: ['webgpu'],
    graphOptimizationLevel: 'disabled',
}


const path = './sam-vit-base/onnx/vision_encoder.onnx';
const session = await ort.InferenceSession.create(path, options);
console.log(session);

// Dummy inputs
const inputs = {
    pixel_values: new ort.Tensor('float32', new Float32Array(1 * 3 * 1024 * 1024).fill(2.248908281326294), [1, 3, 1024, 1024])
}

const output = await session.run(inputs);
console.log(output);
```

### Urgency

high - Blocks WebGPU support in Transformers.js

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.1

### Execution Provider

'webgpu' (WebGPU)

### PR DESCRIPTION
**Pull request by qjia7**
### Description
For Resize, when `noScale` is true, the shader can become very simple, which is not related with `attributes.mode` anymore. So we should remove those parts of shader code for simplification.

This PR can also fix #18311 since the `noScale` are all true in that model.

However, #18311 also exposes that the Resize implementation for `linear` mode has bug. It seems that the currently implementation always treat the input as either 2d or 4d tensor, however, the actual input is 3d tensor, that's why the shader compilation is failed. We may need to fix it in a separate PR.

### CODE REVIEW

**Comment by qjia7** [comment]
@guschmue @fs-eire Please take a look, thanks!

**Review by satyajandhyala — APPROVED** [review]

**Review by guschmue — APPROVED** [review]

**Pull request merged**
