### PR TITLE
[js/webgpu] Fix reshape int32 test case

### PR DESCRIPTION
**Pull request by xhcao**
Co-authored-by: Xing Xu <xing.xu@intel.com>

### CODE REVIEW

**Comment by fs-eire** [comment]
reshape-int32.jsonc is a special test only for webgl, which uses the non-standard int32 instead of int64 as shape (input[1]). It's not for a Reshape with input[0] as int32 type. This is a workaround for webgl only, because for some historical reason we decided not to support int64 at that time.

maybe we can rename this test filename to make it less confusing.

**Comment by axinging** [comment]
> reshape-int32.jsonc is a special test only for webgl, which uses the non-standard int32 instead of int64 as shape (input[1]). It's not for a Reshape with input[0] as int32 type. This is a workaround for webgl only, because for some historical reason we decided not to support int64 at that time.
> 
> maybe we can rename this test filename to make it less confusing.

I merged the int32 case into float32 case,   and keep the reshape-int32.json file unchanged. PTAL @fs-eire

**Comment by axinging** [comment]
@qjia7 @gyagp, PTAL

**Review by fs-eire — APPROVED** [review]

**Pull request merged**
