### PR TITLE
Liqun/roberta

### PR DESCRIPTION
**Pull request by liqunfu**
**Description**: Describe your changes.
add GLUE Roberta example, fix unused initializer issue at backend. Bert GLUE expected out updated due to graph changes between June29 to July1st

**Motivation and Context**
add mode examples, fix bugs

### CODE REVIEW

**Comment by ytaous** [comment]
there are 19 commits in this PR, and first vs last commit looks totally different
perhaps start with clean PR?

**Comment by ytaous** [comment]
is it only the 3 files for review (since there are 19 commits)?

**Comment by liqunfu** [comment]
@ytaous, Yes there are only 3 files in this PR. I accidentally included a few other changes need more time to complete and are unrelated to this PR. They were moved to another branch.

**Comment by ytaous** [comment]
add mode examples, fix bugs   <--- typo ? "more"

**Comment by suffiank** [comment]
As it is now, if weights to train are explicitly set by user, they will be honored as is and not auto discovery of weights to train is made. For the changes to Roberta model, can we try to turn on the auto discovery to see if it works? I made a previous change to discover all trainable weights from the loss node. This seems the preferred mode.

Otherwise, when the user explicitly sets the weights to train, would it not be better to error out when no consumer node is found? It seems the user setting the weights to train is a special circumstances, and in such case they should expect which weights exist and are trainable. But if our built-in discovery process is not robust enough, maybe just ignoring unused weights with warnings makes sense.

**Pull request merged**
