### PR TITLE
[TRT EP] Fix ProviderOptions functions

### PR DESCRIPTION
**Pull request by simonjub**
### Description
When trying to use the TRT EP option trt_extra_plugin_lib_paths I noticed that my custom op library was not being loaded by the EP. After some digging I found that code was missing to update this option when UpdateTensorRTProviderOptions() is used to set it. 

At the same time I noticed that char arrays were allocated in that function and wondered where they are de-allocated. When I found it was done in ReleaseTensorRTProviderOptions(), I noticed that a few de-allocations were missing.

### Motivation and Context
This PR fixes the problems described above.

### CODE REVIEW

**Comment by chilo-ms** [comment]
Linux Nuphar CI Pipeline, Linux OpenVINO CI Pipeline, MacOS CI Pipeline, ONNX Runtime Web CI Pipeline, Windows CPU CI Pipeline, Windows GPU CI Pipeline

**Comment by chilo-ms** [comment]
Thanks for finding this issue. 
It tells us again that we need to refactor the way to add new provider options, people usually forget to add necessary code that may cause no effect or lead to memory leak.

**Comment by simonjub** [comment]
@chilo-ms Quick question regarding the delete statements in [ReleaseTensorRTProviderOptions()](https://github.com/simonjub/onnxruntime/blob/0d880a806a753653cdb828dd483a9e238f8d4507/onnxruntime/core/session/provider_bridge_ort.cc#L1930). If this is meant to release the char arrays allocated in [TRT EP's UpdateProviderOptions()](https://github.com/simonjub/onnxruntime/blob/0d880a806a753653cdb828dd483a9e238f8d4507/onnxruntime/core/providers/tensorrt/tensorrt_provider_factory.cc#L113), shouldn't they be _delete[]_ statements as they were allocated as _new char[str_size +1]_? I don't know the code enough to tell if the pointers could be allocated elsewhere.

**Comment by chilo-ms** [comment]
> @chilo-ms Quick question regarding the delete statements in [ReleaseTensorRTProviderOptions()](https://github.com/simonjub/onnxruntime/blob/0d880a806a753653cdb828dd483a9e238f8d4507/onnxruntime/core/session/provider_bridge_ort.cc#L1930). If this is meant to release the char arrays allocated in [TRT EP's UpdateProviderOptions()](https://github.com/simonjub/onnxruntime/blob/0d880a806a753653cdb828dd483a9e238f8d4507/onnxruntime/core/providers/tensorrt/tensorrt_provider_factory.cc#L113), shouldn't they be _delete[]_ statements as they were allocated as _new char[str_size +1]_? I don't know the code enough to tell if the pointers could be allocated elsewhere.

That's a really good catch! I think you are right. Could you help replace with delete[] in this PR? 
We did use valgrind to test memroy leak but seems we overlook the case where those char array are really being allocated. 
I will test to see.

**Comment by chilo-ms** [comment]
> @chilo-ms Quick question regarding the delete statements in [ReleaseTensorRTProviderOptions()](https://github.com/simonjub/onnxruntime/blob/0d880a806a753653cdb828dd483a9e238f8d4507/onnxruntime/core/session/provider_bridge_ort.cc#L1930). If this is meant to release the char arrays allocated in [TRT EP's UpdateProviderOptions()](https://github.com/simonjub/onnxruntime/blob/0d880a806a753653cdb828dd483a9e238f8d4507/onnxruntime/core/providers/tensorrt/tensorrt_provider_factory.cc#L113), shouldn't they be _delete[]_ statements as they were allocated as _new char[str_size +1]_? I don't know the code enough to tell if the pointers could be allocated elsewhere.

That's a good catch! I think you are right. Even though the OrtTensorRTProviderOptionsV2 instance will be automatically deallocated by smart pointer, but yes, those char array allocated with `new []` should be deallocated with `delete []`.
Could you help fix this in this PR?
We did run valgrind to test memory leak, but it seems we overlook the case where those char array are being allocated.
I will use valgrind to test again.

**Comment by simonjub** [comment]
Done.

**Review by chilo-ms — APPROVED** [review]

**Pull request merged**
