### PR TITLE
#19921 [Dup] LLC Core count calculations updated 

### PR DESCRIPTION
**Pull request by YUNQIUGUO**
### Description

See #19921 Just to address one comment: https://github.com/microsoft/onnxruntime/pull/19921#discussion_r1543398640

since this is an external branch. need to open another pull request for this.

### CODE REVIEW

**Review by jchen351 — APPROVED** [review]

**Review by jchen351 — DISMISSED** [review]

**Comment by YUNQIUGUO** [comment]
thanks for reformatting @jchen351 !

**Review by sophies927 — APPROVED** [review]
LGTM

**Review by jchen351 — APPROVED** [review]

**Review by sophies927 — APPROVED** [review]
LGTM

**Comment by A-Satti** [comment]
@jchen351  The flag was added back, considering its position in the code this wont have an affect without the additional conditionals. To avoid confusion and cleanliness I suggest removing the flag, in the build file.

 We don't expect those building ORT to need additional knowledge of the platform to get the best performance.

**Pull request merged**
