### PR TITLE
[oneDNN ep] matmulinteger postop fusion

### PR DESCRIPTION
**Pull request by georgen117**
**Description**:
This adds fusion code to the oneDNN execution provider to fuse MatMulInteger and upto 32 post ops.

This enables running MatMulInteger and converting directly to f32 instead of needing to run the extra cast from i32 to f32

In addition if the MatMulInteger + cast is followed by an binary or elementwise operator and it can be fuse with the MatMulInteger operation in oneDNN this will add the binary and/or elementwise operators as post op operations.

This creates a performance increase for models that this MatMulInteger + postop fusion is possible.

**Motivation and Context**
- Why is this change required? What problem does it solve?
This change is to increase the performance of int8 models when running on the oneDNN execution provider.

### CODE REVIEW

**Comment by georgen117** [comment]
@jywu-msft maintainer please run /azp run Linux DNNL CI Pipeline since this is the primary pipeline for testing the OneDNN execution provider.

**Comment by georgen117** [comment]
@jywu-msft could you kick off the other CI builds. As well as re-run `run /azp run Linux DNNL CI Pipeline`.  I did a cleanup commit based on the Lint C++ results so that pipeline will need to be re-run. 😊

**Comment by jywu-msft** [comment]
> @jywu-msft could you kick off the other CI builds. As well as re-run `run /azp run Linux DNNL CI Pipeline`. I did a cleanup commit based on the Lint C++ results so that pipeline will need to be re-run. 😊

i noticed yesterday there was a build failure as well. did you address that as well?

**Comment by jywu-msft** [comment]
[ 66%] Building CXX object CMakeFiles/onnxruntime_providers_dnnl.dir/onnxruntime_src/onnxruntime/core/providers/dnnl/subgraph/dnnl_sum.cc.o
/onnxruntime_src/onnxruntime/core/providers/dnnl/subgraph/dnnl_subgraph_transformer.cc: In member function ‘void onnxruntime::ort_dnnl::DnnlGraphTransformer::MatMulBinaryEltwise(onnxruntime::ort_dnnl::DnnlSubgraph&)’:
/onnxruntime_src/onnxruntime/core/providers/dnnl/subgraph/dnnl_subgraph_transformer.cc:697:10: error: unused variable ‘attribute_flag’ [-Werror=unused-variable]
  697 |     bool attribute_flag = false;
      |          ^~~~~~~~~~~~~~
/onnxruntime_src/onnxruntime/core/providers/dnnl/subgraph/dnnl_subgraph_transformer.cc: In member function ‘void onnxruntime::ort_dnnl::DnnlGraphTransformer::MatMulIntegerBinaryEltwise(onnxruntime::ort_dnnl::DnnlSubgraph&)’:
/onnxruntime_src/onnxruntime/core/providers/dnnl/subgraph/dnnl_subgraph_transformer.cc:809:10: error: unused variable ‘attribute_flag’ [-Werror=unused-variable]
  809 |     bool attribute_flag = false;

**Comment by georgen117** [comment]
> bool attribute_flag = false



> i noticed yesterday there was a build failure as well. did you address that as well?

No I missed that build failure.  Odd I thought it passed.  I will check it out.  Thanks @jywu-msft

**Comment by georgen117** [comment]
@jywu-msft I addressed the 3 unused-variable error/warnings.  Sorry that I missed those in the last build.  Thanks for pointing it out. If would not mind kicking off the `/azp run Linux DNNL CI Pipeline` build.

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
