### PR TITLE
Clarify usage of kOnnxDomainAlias.

### PR DESCRIPTION
**Pull request by skottmckay**
**Description**: 
There are limited places where kOnnxDomainAlias could/should be used. Cleanup the code to remove unnecessary checks for kOnnxDomainAlias in places where it's not possible.

**Motivation and Context**
Clarify code to avoid unnecessary checks for Node::Domain() returning kOnnxDomainAlias.

### CODE REVIEW

**Comment by edgchen1** [comment]
maybe it would be safer to only update direct comparisons with Node::Domain() instead of functions with string domain parameters. otherwise callers need to know that kOnnxDomainAlias doesn't automatically map to kOnnxDomain anymore - could also explicitly say that in the documentation.

**Comment by edgchen1** [comment]
apart from this:
https://github.com/microsoft/onnxruntime/blob/1cc2cfb7b807632a5ec5f5ff8fa8cfe34584326c/onnxruntime/core/graph/graph.cc#L821-L825

looks like there's one more write to Node::domain_:
https://github.com/microsoft/onnxruntime/blob/1cc2cfb7b807632a5ec5f5ff8fa8cfe34584326c/onnxruntime/core/graph/graph.cc#L738

should we also ensure that domain_ is not set to kOnnxDomainAlias when loading the ORT format model?

**Comment by skottmckay** [comment]
> should we also ensure that domain_ is not set to kOnnxDomainAlias when loading the ORT format model?

I did consider that, but given the ORT format model is created from the Node instance, how would it have a domain value of kOnnxDomainAlias?

**Review by edgchen1 — APPROVED** [review]
:shipit:

**Pull request merged**
