### PR TITLE
Add attrProto.release_s interface

### PR DESCRIPTION
**Pull request by danyue333**
### Description
Add AttributeProto.release_s interface, which is used to obtain the string in the attribute using move semantics instead of copying it

### Motivation and Context
The ep_context node stores a lot of information in attributes, which may cause the memory usage to increase. Use this interface to avoid memory waste

### CODE REVIEW

**Comment by danyue333** [comment]
Hi @jywu-msft , Can you please review this PR?

**Comment by jywu-msft** [comment]
it's failing lint checks.

Warning (CLANGFORMAT) format
    See https://clang.llvm.org/docs/ClangFormat.html.
    Run `lintrunner -a` to apply this patch.

    You can run `lintrunner -a` to apply this patch.

    234  234 |   ModelProto* (*model_to_proto)(Model& model);                                                                                                        // [95]
    235  235 |   DllSafe<std::string> (*model_proto_serialize_as_string)(ModelProto& model_proto);                                                                   // [96]
    236  236 |   void (*model_proto_delete)(ModelProto* p);                                                                                                          // [97]
    236      |-  DllSafe<std::string> (*attr_proto_release_string)(AttributeProto* attr);// [98]
         237 |+  DllSafe<std::string> (*attr_proto_release_string)(AttributeProto* attr);// [98]
    238  238 | };
    239  239 | 
    240  240 | #ifndef USE_VITISAI

[2024-12-05T17:58:49Z DEBUG lintrunner::persistent_data] Writing run info to /home/cloudtest/.local/share/lintrunner/90a885e688310be9e42a[55](https://github.com/microsoft/onnxruntime/actions/runs/12173123972/job/33991131381?pr=22977#step:7:56)0e10042c91e89bfa0b1be8a7cf0128dbb937830178/runs/2024-12-05T17-[57](https://github.com/microsoft/onnxruntime/actions/runs/12173123972/job/33991131381?pr=22977#step:7:58)-19.950Z_80015b8980a08df67e03e2596acef487771aed65e28b72d8c[60](https://github.com/microsoft/onnxruntime/actions/runs/12173123972/job/33991131381?pr=22977#step:7:61)a6140007f8e7c

You can reproduce these results locally by using `lintrunner`. To set up lintrunner locally, see https://github.com/microsoft/onnxruntime/blob/main/docs/Coding_Conventions_and_Standards.md#linting .
Error: Process completed with exit code 1.

**Comment by danyue333** [comment]
`lintrunner -a` has been executed

**Review by jywu-msft — APPROVED** [review]

**Pull request merged**
